// The tables of the game data as db/schema.sql describes them: their columns in order (the order of the keys in
// office/data/db.js), the primary key, what kind of value each column holds and its default.
import fs from 'node:fs';
import path from 'node:path';

export const ROOT = path.join(path.dirname(new URL(import.meta.url).pathname), '..', '..');

export function readSchema(file = path.join(ROOT, 'db', 'schema.sql')) {
  const text = fs.readFileSync(file, 'utf8').split('\n').map(l => l.replace(/\s--.*$/, '')).join('\n');
  const tables = {};
  for (const m of text.matchAll(/CREATE TABLE IF NOT EXISTS (\w+) \(([\s\S]*?)\n\);/g)) {
    const cols = [];
    let pk = [];
    for (const raw of m[2].split('\n')) {
      const l = raw.trim().replace(/,$/, '');
      const key = /^PRIMARY KEY \(([^)]*)\)/i.exec(l);
      if (key) { pk = key[1].split(',').map(s => s.trim()); continue; }
      const c = /^(\w+)\s+(\w+)(\([^)]*\))?(.*)$/.exec(l);
      if (!c) continue;
      const type = c[2].toLowerCase(), rest = c[4];
      const def = /DEFAULT\s+('(?:[^']|'')*'|-?[\d.]+|NULL)/i.exec(rest);
      const col = {
        name: c[1],
        kind: type === 'json' ? 'json' : /int|decimal|float|double/.test(type) ? 'num' : 'str',
        notNull: /NOT NULL|PRIMARY KEY/i.test(rest),
        def: !def || /^NULL$/i.test(def[1]) ? null : def[1][0] === "'" ? def[1].slice(1, -1).replace(/''/g, "'") : Number(def[1])
      };
      if (/PRIMARY KEY/i.test(rest)) pk = [col.name];
      cols.push(col);
    }
    tables[m[1]] = { name: m[1], cols, pk, col: Object.fromEntries(cols.map(c => [c.name, c])) };
  }
  return tables;
}

// A row in the shape of office/data/db.js: every column in schema order, numbers as numbers, JSON parsed, a missing
// value as its default (or null). Works on rows from DoltHub (strings) and from db/ (already typed).
export function normalizeRow(table, row) {
  const out = {};
  for (const c of table.cols) {
    let v = row[c.name];
    if (v === undefined) v = c.def;
    if (v != null) {
      if (c.kind === 'json' && typeof v === 'string') v = JSON.parse(v);
      else if (c.kind === 'num') v = Number(v);
      else if (c.kind === 'str') v = String(v);
    }
    out[c.name] = v === undefined ? null : v;
  }
  return out;
}

const cmp = (a, b) => typeof a === 'number' && typeof b === 'number' ? a - b : String(a) < String(b) ? -1 : String(a) > String(b) ? 1 : 0;
export const keyOf = (table, row) => table.pk.map(k => String(row[k])).join('\u0001');
export function sortRows(table, rows) {        // the order DoltHub returns them in: by the primary key
  return rows.slice().sort((a, b) => { for (const k of table.pk) { const d = cmp(a[k], b[k]); if (d) return d; } return 0; });
}

// The whole database as the game reads it (window.SO_DB): config as { k: value } (a number when it reads as one),
// every other table as its rows.
export function gameData(schema, tables) {
  const db = {};
  for (const name of Object.keys(schema)) {
    const rows = sortRows(schema[name], (tables[name] || []).map(r => normalizeRow(schema[name], r)));
    db[name] = name === 'config' ? Object.fromEntries(rows.map(r => [r.k, isNaN(r.v) ? r.v : Number(r.v)])) : rows;
  }
  return db;
}

export function writeGameData(db, from, file = path.join(ROOT, 'office', 'data', 'db.js')) {
  fs.writeFileSync(file, `/* Generated by tools/db.mjs ${from}. Do not edit: change db/ and build again (see db/README.md). */\nwindow.SO_DB = ${JSON.stringify(db, null, 1)};\n`);
  return file;
}

export function readGameData(file = path.join(ROOT, 'office', 'data', 'db.js')) {
  const text = fs.readFileSync(file, 'utf8');
  const window = {};
  new Function('window', text)(window);
  return window.SO_DB;
}
