-- Places (office/PLAN.md section 3). Positions live in office/zones/<zone>.js, keyed by id.
-- Written by agent C. Push: node tools/dolt.mjs push <this file>
REPLACE INTO places (id, name, name_ko, zone, kind, note) VALUES
  ('home_bed', 'Your bed', '내 침대', 'home', 'sleep', 'Sleep here to end the day (next day 07:00, energy 100).'),
  ('home_desk', 'Desk by the window', '창가 책상', 'home', 'desk', 'Check the calendar and plan the week.'),
  ('home_kitchen', 'Kitchen', '부엌', 'home', 'eat', 'Eat groceries from your inventory.'),
  ('home_door', 'Apartment door', '아파트 현관', 'home', 'door', 'Leads to city apartment_door.'),
  ('apartment_door', 'Maple Street Apartments', '메이플 스트리트 아파트', 'city', 'door', 'Your building. Leads to home home_door.'),
  ('bus_stop', 'Bus stop on Maple Street', '메이플 스트리트 버스 정류장', 'city', 'transit', 'The Number 12 bus downtown, $2.50 a ride.'),
  ('coffee_cart', 'Coffee cart on Lake Avenue', '레이크 애비뉴 커피 카트', 'city', 'shop', 'Nina''s cart: coffee and pastries.'),
                                                                                                                      ('park_bench', 'Bench in Seaside Park', '시사이드 공원 벤치', 'city', 'seat', 'Farmers market on Saturday mornings.'),
  ('office_door', 'Lakeside Labs entrance', '레이크사이드 랩스 입구', 'city', 'door', 'Same id on both sides: the street entrance in city, the way out in the office zone.'),
  ('diner_door', 'Sunny Side Diner', '서니 사이드 다이너', 'city', 'door', 'Same id on both sides: the street door in city, the way out in the diner zone.'),
  ('market_door', 'Fairview Market', '페어뷰 마켓', 'city', 'door', 'Same id on both sides: the street door in city, the way out in the market zone.'),
  ('parking', 'Parking lot', '주차장', 'city', 'transit', 'Downtown parking, $18 a day.'),
  ('airport_shuttle', 'Airport shuttle stop', '공항 셔틀 정류장', 'city', 'transit', 'Leads to the airport, only on days with a business trip.'),
  ('office_lobby', 'Lakeside Labs lobby', '레이크사이드 랩스 로비', 'office', 'desk', 'Front desk (Tom).'),
  ('office_desk', 'Your desk', '내 자리', 'office', 'desk', 'Sit and work.'),
  ('office_desk_team', 'Team desks', '팀 자리', 'office', 'desk', 'Derek sits by the window.'),
  ('office_kitchen', 'Office kitchen', '사무실 탕비실', 'office', 'eat', 'Free coffee and snacks.'),
  ('office_meeting', 'Meeting room', '회의실', 'office', 'meeting', 'Standups, planning and demos.'),
  ('office_manager', 'Maya''s office', '마야의 사무실', 'office', 'desk', 'Your manager''s office.'),
  ('office_hr', 'HR office', '인사팀 사무실', 'office', 'desk', 'Linda: paperwork, benefits and payroll.'),
  ('office_it', 'IT help desk', 'IT 헬프데스크', 'office', 'desk', 'Sam: laptops, accounts and badges.'),
  ('diner_counter', 'Diner counter', '다이너 카운터', 'diner', 'shop', 'Order and pay here (Rosa).'),
  ('diner_table', 'Booth by the window', '창가 부스 자리', 'diner', 'eat', NULL),
  ('market_shelves', 'Grocery aisles', '식료품 진열대', 'market', 'shop', 'Fruit, vegetables, bread, dairy, frozen food and snacks.'),
  ('market_checkout', 'Checkout lane', '계산대', 'market', 'shop', 'Pay here (Mike).'),
  ('airport_checkin', 'Airline check-in counter', '항공사 체크인 카운터', 'airport', 'desk', NULL),
  ('airport_security', 'Security checkpoint', '보안 검색대', 'airport', 'desk', NULL),
  ('airport_gate', 'Gate B12', 'B12 탑승구', 'airport', 'seat', NULL),
  ('airport_door', 'Airport entrance', '공항 입구', 'airport', 'door', 'Leads back to the city.'),
  ('airport_arrive', 'Arrivals', '도착 층', 'airport', 'door', 'After the flight: leads to the hotel.'),
  ('hotel_desk', 'Hotel front desk', '호텔 프런트', 'hotel', 'desk', NULL),
  ('hotel_room', 'Your hotel room', '호텔 방', 'hotel', 'sleep', NULL),
  ('hotel_restaurant', 'Hotel restaurant', '호텔 식당', 'hotel', 'eat', NULL),
  ('hotel_door', 'Hotel entrance', '호텔 입구', 'hotel', 'door', 'Leads to the client office.'),
  ('hotel_shuttle', 'Hotel airport shuttle', '호텔 공항 셔틀', 'hotel', 'transit', 'Leads to the airport.'),
  ('client_lobby', 'Summit Retail lobby', '서밋 리테일 로비', 'client', 'desk', NULL),
  ('client_meeting', 'Summit Retail conference room', '서밋 리테일 회의실', 'client', 'meeting', NULL),
  ('client_door', 'Summit Retail entrance', '서밋 리테일 입구', 'client', 'door', 'Leads back to the hotel.');
