-- People and their idle small talk (chatter cycles by seq).
-- Written by agent C. Push: node tools/dolt.mjs push <this file>
REPLACE INTO npcs (id, name, role, role_ko, model, place, voice_pitch, voice_rate, voice_like, bio, bio_ko) VALUES
  ('maya', 'Maya Chen', 'Engineering manager', '엔지니어링 매니저', 'woman-suit', 'office_manager', 1.05, 0.94, NULL, 'Calm and organized, with a checklist for everything. She ends almost every talk with "Let me know if you have any questions."', '차분하고 꼼꼼해서 모든 일에 체크리스트가 있습니다. 대화 끝에는 거의 늘 "Let me know if you have any questions."라고 합니다.'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ('derek', 'Derek Alvarez', 'Senior developer, your onboarding buddy', '시니어 개발자, 온보딩 버디', 'man-hoodie', 'office_desk_team', 0.9, 0.98, NULL, 'Laid-back senior developer who reviews code carefully but kindly. Says "No rush" and "Just ping me" a lot.', '느긋한 시니어 개발자로, 코드 리뷰는 꼼꼼하지만 친절합니다. "No rush", "Just ping me"를 입에 달고 삽니다.'),
  ('priya', 'Priya Nair', 'Product manager', '프로덕트 매니저', 'woman-casual-2', 'office_meeting', 1.12, 1, NULL, 'Upbeat product manager who keeps every meeting on time. Her favorite question is "Any blockers?"', '회의를 늘 제시간에 끝내는 밝은 프로덕트 매니저입니다. 제일 좋아하는 질문은 "Any blockers?"입니다.'),
  ('tom', 'Tom Becker', 'Office manager at the front desk', '프런트 데스크의 사무 관리자', 'man-casual', 'office_lobby', 0.95, 0.95, NULL, 'Knows everyone in the building and where the good coffee is. Greets people by name and never forgets a birthday.', '건물 사람들을 다 알고, 맛있는 커피가 어디 있는지도 압니다. 사람들 이름을 불러 인사하고 생일을 잊는 법이 없습니다.'),
  ('sam', 'Sam Reyes', 'IT help desk', 'IT 헬프데스크 담당', 'man-casual-2', 'office_it', 0.86, 0.97, NULL, 'Unflappable IT guy with three monitors and a cold brew. His first question is always "Have you tried restarting it?"', '모니터 세 대와 콜드브루를 곁에 둔 느긋한 IT 담당입니다. 첫 질문은 언제나 "Have you tried restarting it?"입니다.'),
  ('linda', 'Linda Park', 'HR and payroll', '인사·급여 담당', 'woman-formal-2', 'office_hr', 1, 0.92, NULL, 'Patient HR specialist who explains forms slowly and clearly. She loves a good acronym: W-4, PTO, FICA, 401(k).', '서류를 천천히, 알기 쉽게 설명해 주는 인사 담당자입니다. W-4, PTO, FICA, 401(k) 같은 약어를 좋아합니다.'),
  ('rosa', 'Rosa', 'Server at the Sunny Side Diner', '서니 사이드 다이너 종업원', 'woman-casual-3', 'diner_counter', 1.15, 1, NULL, 'Has worked the diner counter for twenty years. Calls everyone "hon" and remembers how you like your eggs.', '20년째 다이너 카운터를 지키고 있습니다. 누구에게나 "hon"이라고 부르고, 손님이 계란을 어떻게 먹는지 기억합니다.'),
  ('mike', 'Mike', 'Cashier at Fairview Market', '페어뷰 마켓 계산원', 'man-worker', 'market_checkout', 0.97, 0.98, NULL, 'College student working the evening shift. Knows every sale in the store and talks about them whether you ask or not.', '저녁 교대로 일하는 대학생입니다. 가게의 할인 상품을 전부 꿰고 있어서, 묻지 않아도 알려 줍니다.'),
  ('nina', 'Nina', 'Barista at the coffee cart', '커피 카트 바리스타', 'woman-adventurer-2', 'coffee_cart', 1.2, 1, NULL, 'Cheerful early bird who runs the coffee cart on Lake Avenue. Remembers regulars'' orders after two visits.', '레이크 애비뉴에서 커피 카트를 하는 명랑한 아침형 인간입니다. 두 번만 오면 단골의 주문을 기억합니다.'),
  ('carl', 'Carl', 'Your neighbor and landlord', '이웃이자 집주인', 'man-farmer', 'bus_stop', 0.8, 0.9, NULL, 'Retired bus mechanic who owns your building and lives on the first floor. Calls you "kid" and has an opinion about everything.', '은퇴한 버스 정비사로, 당신이 사는 건물의 주인이고 1층에 삽니다. 당신을 "kid"라고 부르고, 모든 일에 한마디씩 합니다.'),
  ('greg', 'Greg Whitfield', 'VP at Summit Retail (client)', '서밋 리테일 부사장(고객사)', 'man-suit', 'client_meeting', 0.85, 0.93, NULL, 'Busy, direct client who wants the bottom line first. Friendly once he trusts you, and he likes people who say "I don''t know, but I''ll find out."', '결론부터 듣고 싶어 하는 바쁘고 직설적인 고객입니다. 믿음이 생기면 다정해지고, "모르지만 알아보겠습니다"라고 말하는 사람을 좋아합니다.');

REPLACE INTO npcs (id, name, role, role_ko, model, place, voice_pitch, voice_rate, voice_like, bio, bio_ko) VALUES
  ('amy', 'Amy', 'Airline check-in agent', '항공사 체크인 직원', 'woman-formal-3', 'airport_checkin', 1.1, 0.98, NULL, 'Quick, polite airline agent who has heard every excuse for an overweight bag.', '빠르고 공손한 항공사 직원으로, 무게 초과 가방에 대한 온갖 변명을 다 들어 봤습니다.'),
  ('kelly', 'Kelly', 'Hotel front desk', '호텔 프런트 직원', 'woman-suit-2', 'hotel_desk', 1.05, 0.96, NULL, 'Warm hotel receptionist who always knows a good place to eat nearby.', '근처 맛집을 늘 알고 있는 친절한 호텔 프런트 직원입니다.'),
                                                                                                                                                                                                                                                                                                                                  ('lee', 'Lee', 'TSA officer at airport security', '공항 보안 검색 요원', 'man-worker-2', 'airport_security', 0.92, 0.92, NULL, 'Calm, firm security officer. Short sentences, clear instructions, and the occasional dry joke.', '침착하고 단호한 보안 요원입니다. 짧은 문장과 분명한 지시, 가끔 건조한 농담을 합니다.');

REPLACE INTO chatter (npc, seq, line, line_ko) VALUES
  ('maya', 1, 'Morning! Did you get everything you need?', '좋은 아침! 필요한 건 다 받았어요?'),
  ('maya', 2, 'I''m in back-to-back meetings until two, but ping me if it''s urgent.', '두 시까지 회의가 줄줄이 있지만, 급하면 메시지 줘요.'),
  ('maya', 3, 'Remember, nobody expects you to know everything in week one.', '기억해요, 첫 주에 다 알 거라고 기대하는 사람은 없어요.'),
  ('maya', 4, 'Let me know if you have any questions, okay?', '궁금한 거 있으면 말해 줘요, 알았죠?'),
  ('derek', 1, 'Hey! How''s it going?', '안녕! 어떻게 돼 가요?'),
  ('derek', 2, 'If the build breaks, it wasn''t you. Probably.', '빌드가 깨져도 당신 탓은 아니에요. 아마도요.'),
                                                                                                                                                                                                                                               ('derek', 3, 'I need more coffee before I look at that pull request.', '그 풀 리퀘스트 보기 전에 커피가 더 필요해요.'),
  ('derek', 4, 'No rush on anything today. Just ping me if you get stuck.', '오늘은 급한 거 없어요. 막히면 메시지 줘요.'),
  ('derek', 5, 'Did you catch the game last night? Total nail-biter.', '어젯밤 경기 봤어요? 완전 손에 땀을 쥐게 했어요.'),
  ('priya', 1, 'Standup''s at ten sharp! Don''t be late.', '스탠드업은 열 시 정각이에요! 늦지 마요.'),
  ('priya', 2, 'I''m updating the roadmap. Wish me luck.', '로드맵 고치는 중이에요. 행운을 빌어 줘요.'),
  ('priya', 3, 'Any blockers? No? Great!', '막히는 거 있어요? 없어요? 좋아요!'),
  ('priya', 4, 'This room is booked all afternoon, as usual.', '이 방은 늘 그렇듯 오후 내내 예약돼 있어요.'),
  ('tom', 1, 'Morning! Badge working okay?', '좋은 아침! 출입증은 잘 돼요?'),
  ('tom', 2, 'If you need anything, I''m right here.', '필요한 게 있으면 여기 있을게요.'),
  ('tom', 3, 'There''s cake in the kitchen. Somebody''s birthday, I think.', '탕비실에 케이크 있어요. 누구 생일인가 봐요.'),
  ('tom', 4, 'Heads-up: the elevator on the right is acting up again.', '참고로, 오른쪽 엘리베이터가 또 말썽이에요.'),
  ('sam', 1, 'Have you tried turning it off and on again?', '껐다가 다시 켜 봤어요?'),
  ('sam', 2, 'Don''t click on any links from the "CEO" asking for gift cards.', '기프트 카드 달라는 "CEO"의 링크는 누르지 마요.'),
  ('sam', 3, 'Remember to lock your screen when you step away.', '자리 비울 때는 화면 잠그는 거 잊지 마요.'),
  ('sam', 4, 'Password expires every ninety days. Sorry, not my rule.', '비밀번호는 90일마다 만료돼요. 미안, 제가 정한 규칙은 아니에요.'),
  ('linda', 1, 'Hi there! Door''s open if you need anything.', '안녕하세요! 필요하면 언제든 들러요.'),
  ('linda', 2, 'Don''t forget: open enrollment closes in thirty days.', '잊지 마요, 복리후생 가입은 30일 뒤에 마감이에요.'),
  ('linda', 3, 'Payday is every other Friday, by direct deposit.', '급여일은 격주 금요일, 계좌 입금이에요.'),
  ('linda', 4, 'Make sure your address is up to date in the HR portal.', 'HR 포털에 주소가 최신인지 확인해요.'),
  ('rosa', 1, 'Hi, hon! Sit anywhere you like.', '어서 와요! 아무 데나 앉아요.'),
  ('rosa', 2, 'Pie of the day is apple. Just saying.', '오늘의 파이는 사과예요. 그냥 말하는 거예요.'),
  ('rosa', 3, 'More coffee, hon? Refills are free.', '커피 더 줄까요? 리필은 무료예요.'),
  ('rosa', 4, 'Lunch rush starts at noon, so come early.', '점심 손님은 정오부터 몰려요, 일찍 와요.'),
  ('mike', 1, 'Hey! Strawberries are buy one, get one free this week.', '안녕하세요! 이번 주 딸기는 하나 사면 하나 더예요.'),
  ('mike', 2, 'Don''t forget your rewards number. You save a ton.', '적립 번호 잊지 마요. 꽤 아껴요.'),
  ('mike', 3, 'We close at ten tonight.', '오늘 밤 열 시에 문 닫아요.'),
  ('mike', 4, 'Paper or plastic? Just kidding, I''ll ask at checkout.', '종이? 비닐? 농담이에요, 계산할 때 물어볼게요.'),
  ('nina', 1, 'Morning! The usual?', '좋은 아침! 늘 먹던 걸로?'),
  ('nina', 2, 'Cold brew''s extra strong today. You''ve been warned.', '오늘 콜드브루 엄청 진해요. 경고했어요.'),
  ('nina', 3, 'Blueberry muffins just came in. Still warm!', '블루베리 머핀 막 들어왔어요. 아직 따뜻해요!'),
  ('nina', 4, 'Have a good one! Don''t work too hard.', '좋은 하루 보내요! 너무 무리하지 말고요.'),
  ('carl', 1, 'Morning, kid. Bus is running late again.', '좋은 아침. 버스가 또 늦네.');

REPLACE INTO chatter (npc, seq, line, line_ko) VALUES
  ('carl', 2, 'Looks like rain later. Better grab an umbrella.', '이따 비 오겠어. 우산 챙기는 게 좋겠네.'),
  ('carl', 3, 'Trash goes out Monday night. Don''t forget.', '쓰레기는 월요일 밤에 내놔. 잊지 말고.'),
  ('carl', 4, 'Back in my day, the fare was a quarter.', '내가 젊을 땐 버스비가 25센트였지.'),
  ('greg', 1, 'Let''s keep this quick. I''ve got a call at the top of the hour.', '짧게 합시다. 정각에 통화가 있어요.'),
  ('greg', 2, 'Bottom line: will it be ready for the holidays?', '결론만요: 연말 시즌 전에 준비됩니까?'),
  ('greg', 3, 'Good to see you in person for once.', '이번엔 직접 보니 좋네요.'),
  ('amy', 1, 'Next in line, please!', '다음 분 오세요!'),
  ('amy', 2, 'Any bags to check today?', '오늘 부칠 짐 있으세요?'),
                                                                                                                                                           ('amy', 3, 'Boarding starts forty minutes before departure.', '탑승은 출발 40분 전에 시작합니다.'),
  ('kelly', 1, 'Welcome! Checking in?', '어서 오세요! 체크인하세요?'),
  ('kelly', 2, 'Breakfast is from six-thirty to ten in the restaurant.', '아침은 식당에서 여섯 시 반부터 열 시까지예요.'),
  ('kelly', 3, 'The Wi-Fi password is on the back of your key card sleeve.', '와이파이 비밀번호는 카드키 봉투 뒷면에 있어요.'),
  ('kelly', 4, 'Need a dinner recommendation? Just ask!', '저녁 추천 필요하면 물어보세요!'),
  ('lee', 1, 'Laptops out of the bag, please.', '노트북은 가방에서 꺼내 주세요.'),
  ('lee', 2, 'Liquids in a quart-size bag. Three point four ounces or less.', '액체는 1쿼트 봉투에. 3.4온스 이하로요.'),
  ('lee', 3, 'Shoes stay on today. Lucky you.', '오늘은 신발 안 벗어도 돼요. 운 좋네요.'),
  ('lee', 4, 'Step forward, please. Arms up.', '앞으로 오세요. 팔 올리세요.');
