-- Things money buys: coffee cart, diner, market, fares. model = Kenney food pack node. US prices.
-- Written by agent C. Push: node tools/dolt.mjs push <this file>
REPLACE INTO items (id, name, name_ko, kind, price, model, energy, place, note) VALUES
  ('coffee', 'Drip coffee, medium', '드립 커피(미디엄)', 'drink', 2.75, 'cup-coffee', 8, 'coffee_cart', 'house blend'),
  ('latte', 'Latte, medium', '라테(미디엄)', 'drink', 4.75, 'cup-coffee', 9, 'coffee_cart', 'whole, skim, oat or almond milk'),
  ('cold_brew', 'Cold brew', '콜드브루', 'drink', 4.5, 'frappe', 10, 'coffee_cart', 'extra strong'),
  ('hot_tea', 'Hot tea', '따뜻한 차', 'drink', 2.5, 'cup-tea', 5, 'coffee_cart', NULL),
  ('muffin', 'Blueberry muffin', '블루베리 머핀', 'meal', 3.25, 'muffin', 12, 'coffee_cart', 'a snack'),
  ('croissant', 'Butter croissant', '버터 크루아상', 'meal', 3.5, 'croissant', 12, 'coffee_cart', 'a snack'),
  ('diner_cheeseburger', 'Cheeseburger with fries', '치즈버거와 감자튀김', 'meal', 13.95, 'burger-cheese', 42, 'diner_counter', 'comes with fries or a side salad'),
                                                                                                      ('diner_fries', 'Side of fries', '감자튀김(사이드)', 'meal', 4.5, 'fries', 12, 'diner_counter', 'a snack'),
  ('diner_pancakes', 'Short stack of pancakes', '팬케이크(세 장)', 'meal', 10.95, 'pancakes', 35, 'diner_counter', 'breakfast served all day'),
  ('diner_club', 'Club sandwich', '클럽 샌드위치', 'meal', 12.5, 'sandwich', 38, 'diner_counter', 'turkey, bacon, lettuce and tomato'),
  ('diner_soup', 'Soup of the day', '오늘의 수프', 'meal', 6.95, 'bowl-soup', 30, 'diner_counter', 'with crackers'),
  ('diner_salad', 'Garden salad', '가든 샐러드', 'meal', 9.5, 'salad', 30, 'diner_counter', 'ranch, Italian or balsamic'),
  ('diner_pie', 'Slice of apple pie', '사과 파이 한 조각', 'meal', 5.25, 'cake-slicer', 14, 'diner_counter', 'a la mode for $1.50 more'),
  ('diner_coffee', 'Diner coffee (free refills)', '다이너 커피(리필 무료)', 'drink', 2.25, 'mug', 7, 'diner_counter', 'bottomless'),
  ('apple', 'Apple', '사과', 'grocery', 0.89, 'apple', 8, 'market_shelves', 'sold by the piece'),
  ('bananas', 'Bananas (bunch of 5)', '바나나(5개 한 송이)', 'grocery', 1.45, 'banana', 10, 'market_shelves', NULL),
  ('oranges', 'Navel oranges (3)', '네이블 오렌지(3개)', 'grocery', 2.99, 'orange', 9, 'market_shelves', NULL),
  ('grapes', 'Red grapes (2 lb)', '적포도(2파운드)', 'grocery', 4.98, 'grapes', 10, 'market_shelves', NULL),
  ('strawberries', 'Strawberries (1 lb box)', '딸기(1파운드 상자)', 'grocery', 3.99, 'strawberry', 9, 'market_shelves', 'buy one, get one free this week'),
  ('avocado', 'Avocado', '아보카도', 'grocery', 1.5, 'avocado', 10, 'market_shelves', NULL),
  ('tomatoes', 'Tomatoes (1 lb)', '토마토(1파운드)', 'grocery', 2.49, 'tomato', 5, 'market_shelves', NULL),
  ('onion', 'Yellow onion', '양파', 'grocery', 0.99, 'onion', 3, 'market_shelves', 'for cooking'),
  ('carrots', 'Baby carrots (1 lb bag)', '베이비 당근(1파운드 봉지)', 'grocery', 1.79, 'carrot', 8, 'market_shelves', NULL),
  ('broccoli', 'Broccoli crown', '브로콜리', 'grocery', 2.29, 'broccoli', 6, 'market_shelves', NULL),
  ('bread', 'Sandwich bread (loaf)', '식빵(한 봉지)', 'grocery', 3.49, 'loaf', 12, 'market_shelves', NULL),
  ('baguette', 'French baguette', '바게트', 'grocery', 2.99, 'loaf-baguette', 12, 'market_shelves', NULL),
  ('eggs', 'Eggs (dozen)', '달걀(12개)', 'grocery', 3.79, 'egg', 15, 'market_shelves', 'large, grade A'),
  ('milk', 'Milk (half gallon carton)', '우유(반 갤런 팩)', 'grocery', 3.29, 'carton', 8, 'market_shelves', '2%'),
  ('cheese', 'Cheddar cheese (8 oz)', '체다 치즈(8온스)', 'grocery', 4.49, 'cheese', 12, 'market_shelves', NULL),
  ('bacon', 'Bacon (12 oz)', '베이컨(12온스)', 'grocery', 6.99, 'bacon', 15, 'market_shelves', NULL),
  ('ground_beef', 'Ground beef (1 lb)', '다진 소고기(1파운드)', 'grocery', 5.99, 'meat-patty', 15, 'market_shelves', 'for burgers at home'),
  ('deli_turkey', 'Sliced deli turkey (8 oz)', '칠면조 슬라이스(8온스)', 'grocery', 5.49, 'turkey', 14, 'market_shelves', NULL),
  ('cereal', 'Box of cereal', '시리얼 한 상자', 'grocery', 4.99, 'bowl-cereal', 15, 'market_shelves', NULL),
  ('peanut_butter', 'Peanut butter (jar)', '땅콩버터(병)', 'grocery', 3.49, 'peanut-butter', 12, 'market_shelves', NULL),
  ('canned_soup', 'Canned chicken noodle soup', '치킨 누들 수프 통조림', 'grocery', 2.19, 'can', 30, 'market_shelves', 'a quick meal'),
  ('frozen_pizza', 'Frozen pepperoni pizza', '냉동 페퍼로니 피자', 'grocery', 6.49, 'pizza-box', 40, 'market_shelves', 'a meal'),
  ('ice_cream', 'Ice cream (pint)', '아이스크림(파인트)', 'grocery', 5.49, 'ice-cream', 12, 'market_shelves', NULL),
  ('soda_12pk', 'Soda (12-pack of cans)', '탄산음료(12캔 묶음)', 'grocery', 7.99, 'soda-can', 7, 'market_shelves', NULL),
  ('soda_bottle', 'Soda (2-liter bottle)', '탄산음료(2리터 병)', 'grocery', 2.29, 'soda-bottle', 6, 'market_shelves', NULL),
  ('chips', 'Potato chips (family size)', '감자칩(대용량)', 'grocery', 4.29, 'bag', 12, 'market_shelves', NULL),
  ('cookies', 'Chocolate chip cookies', '초콜릿 칩 쿠키', 'grocery', 3.99, 'cookie', 11, 'market_shelves', NULL),
  ('candy_bar', 'Candy bar', '초코바', 'grocery', 1.79, 'candy-bar', 10, 'market_shelves', NULL),
  ('bus_ride', 'Bus fare', '버스 요금', 'fare', 2.5, NULL, 0, 'bus_stop', 'one ride, tap a card or pay exact change'),
  ('bus_day_pass', 'Bus day pass', '버스 1일권', 'fare', 5, NULL, 0, 'bus_stop', 'unlimited rides until midnight'),
  ('parking_day', 'Parking, all day', '주차(종일)', 'fare', 18, NULL, 0, 'parking', 'downtown lot'),
  ('laundry_load', 'Laundry, one load', '세탁 1회', 'other', 2.75, NULL, 0, 'apartment_door', 'basement laundry room; quarters or the app');
