-- Work calendar, days 1-7 (day 1 = the first Monday). Days 8+ are in a later seed.
-- Written by agent C. Push: node tools/dolt.mjs push <this file>
REPLACE INTO calendar (day, time, title, title_ko, place, episode) VALUES
  (1, '08:30', 'Pick up your badge at the front desk', '프런트에서 출입증 받기', 'office_lobby', 'd1_badge'),
  (1, '09:00', 'Onboarding with Maya', '마야와 온보딩', 'office_manager', 'd1_onboarding'),
  (1, '10:00', 'Daily standup', '데일리 스탠드업', 'office_meeting', 'd1_standup'),
  (1, '11:00', 'Desk and dev setup with Derek', '데릭과 자리·개발 환경 세팅', 'office_desk_team', 'd1_desk'),
  (1, '12:00', 'Lunch break', '점심시간', 'diner_counter', 'd1_lunch'),
  (2, '10:00', 'Daily standup', '데일리 스탠드업', 'office_meeting', NULL),
  (2, '11:00', 'Code review follow-up with Derek', '데릭과 코드 리뷰 후속 논의', 'office_desk_team', 'd2_code_review'),
  (2, '13:00', 'IT appointment: laptop', 'IT 예약: 노트북', 'office_it', 'd2_it_laptop'),
                                                                                                                                                             (2, '14:00', 'Checkout design review with Priya', '프리야와 결제 화면 디자인 리뷰', 'office_meeting', NULL),
  (3, '10:00', 'Daily standup', '데일리 스탠드업', 'office_meeting', NULL),
  (3, '11:00', '1:1 with Maya', '마야와 1:1', 'office_manager', 'd3_one_on_one'),
  (3, '12:00', 'Taco lunch with the team', '팀과 타코 점심', 'office_desk_team', 'd3_lunch'),
  (3, '14:00', 'Sprint planning', '스프린트 플래닝', 'office_meeting', 'd3_planning'),
  (4, '10:00', 'Daily standup', '데일리 스탠드업', 'office_meeting', NULL),
  (4, '11:00', 'Refund bug check-in with Priya', '프리야와 환불 버그 점검', 'office_meeting', 'd4_deadline'),
  (4, '14:00', 'Benefits enrollment with HR', '인사팀과 복리후생 가입', 'office_hr', 'd4_benefits'),
  (4, '16:00', 'Ask Maya about time off', '마야에게 휴가 문의', 'office_manager', 'd4_pto'),
  (5, '07:00', 'Payday: paycheck by direct deposit', '급여일: 급여 계좌 입금', NULL, NULL),
  (5, '10:00', 'Daily standup', '데일리 스탠드업', 'office_meeting', NULL),
  (5, '11:00', 'Sprint demo and retro', '스프린트 데모와 회고', 'office_meeting', 'd5_demo'),
  (5, '14:00', 'Pay stub questions with Linda', '린다에게 급여명세서 문의', 'office_hr', 'd5_paystub'),
  (5, '17:30', 'Team happy hour (optional)', '팀 해피아워(선택)', 'office_desk_team', 'd5_happy_hour'),
  (6, '10:00', 'Farmers market in Riverside Park', '리버사이드 공원 파머스 마켓', 'park_bench', 'w_park'),
  (6, '15:00', 'Grocery run', '장보기', 'market_checkout', 'w_market'),
  (7, '10:00', 'Ask Carl about the leaky faucet', '칼에게 새는 수도꼭지 이야기하기', 'apartment_door', 'w_faucet'),
  (7, '20:00', 'Plan the week ahead', '다음 주 계획 세우기', 'home_desk', NULL);
