-- First weekend (days 6-7, repeatable w_ episodes): episodes, turns, phrases. Written by agent C.
-- Push: node tools/dolt.mjs push db/seed/15-weekend.sql
REPLACE INTO episodes (id, title, title_ko, place, npc, day_from, day_to, time_from, time_to, requires, summary, summary_ko, reward, energy, sort, tags) VALUES
  ('w_park', 'Saturday in the park', '공원의 토요일', 'park_bench', 'carl', 6, 7, '08:00', '18:00', NULL,
   'Run into Carl in Riverside Park. Talk about your first week, the farmers market, and trash day.', '리버사이드 공원에서 칼을 만납니다. 첫 주 이야기, 파머스 마켓, 쓰레기 버리는 날에 대해 이야기하세요.',
   0, 0, 10, 'small-talk,neighbor,home'),
  ('w_market', 'Weekend grocery run', '주말 장보기', 'market_checkout', 'mike', 6, 7, '09:00', '21:00', NULL,
   'Stock up for the week. Get the buy-one-get-one deal, use your rewards number, and skip the cash back.', '한 주 먹을 것을 사 두세요. 1+1 할인을 챙기고, 적립 번호를 쓰고, 캐시백은 사양하세요.',
   0, 0, 20, 'shopping,market,money'),
                                                                                                         ('w_faucet', 'The leaky faucet', '물 새는 수도꼭지', 'apartment_door', 'carl', 6, 7, '09:00', '20:00', NULL,
   'Your kitchen faucet drips all night. Ask Carl, your landlord, to fix it, and find out where the laundry room is.', '부엌 수도꼭지가 밤새 똑똑 샙니다. 집주인 칼에게 수리를 부탁하고, 세탁실이 어디 있는지도 알아보세요.',
   0, 0, 30, 'home,landlord,repair');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('w_park', 1, 'carl',
   'It is a sunny weekend morning. Carl is on a park bench with a newspaper and a paper cup of coffee.', '화창한 주말 아침입니다. 칼이 공원 벤치에서 신문과 종이컵 커피를 들고 있습니다.',
   'Hey, neighbor! You survived your first week?', 'Say you did, barely, and that it was busy but good.', '겨우 버텼다고, 바빴지만 좋았다고 하세요.',
   '[{"any":["busy","survived","barely","good","great","long","crazy","intense"]}]',
   'Barely! It was busy, but good.',
   '["No, I''d like it to go.","Yes, paper is fine.","Yes, the deadline is Tuesday."]',
                                                                                                                                                                                                                                                    '["Answer with one word, then add how the week was.","Key words: barely, busy but good"]', '["한 단어로 답한 뒤 한 주가 어땠는지 덧붙이세요.","핵심 단어: barely, busy but good"]',
   'carl', 'Ha! That''s how it goes. The first week''s always a blur.', '하! 원래 그래. 첫 주는 늘 정신없이 지나가지.'),
  ('w_park', 2, 'carl',
   'You can hear music and smell kettle corn from the other side of the park.', '공원 건너편에서 음악 소리와 캐틀콘 냄새가 납니다.',
   'So, what brings you to the park?', 'Say you heard about the farmers market and came to check it out.', '파머스 마켓 얘기를 듣고 구경하러 왔다고 하세요.',
   '[{"any":["farmers market","market","farmers"]}]',
   'I heard about the farmers market, so I came to check it out.',
   '["I missed the bus, so I walked to work.","I forgot my badge, so I went to the front desk.","I needed a loaner, so I went to IT."]',
   '["Use \\"I heard about …, so …\\".","Key words: farmers market, check it out"]', '["\\"I heard about …, so …\\"를 쓰세요.","핵심 단어: farmers market, check it out"]',
   'carl', 'Good call. Get the peaches from the stand by the fountain. Best in town.', '잘 왔네. 분수대 옆 가판에서 복숭아를 사. 이 동네 최고야.'),
  ('w_park', 3, 'carl',
   'Carl folds his newspaper.', '칼이 신문을 접습니다.',
   'Oh, one more thing. Trash and recycling go out Monday night. Bins go out to the curb.', 'Thank him for the heads-up and ask which bin is for recycling.', '알려 줘서 고맙다고 하고, 어느 통이 재활용인지 물어보세요.',
   '[{"all":["which"],"any":["bin","recycling","one","color"]},{"all":["recycling"]}]',
   'Thanks for the heads-up. Which bin is for recycling?',
   '["Thanks for the heads-up. Which bus goes downtown?","Thanks for the heads-up. Which floor is HR on?","Thanks for the heads-up. Which plan is cheaper?"]',
   '["Ask \\"Which bin is for …?\\"","Key words: which bin, recycling"]', '["\\"Which bin is for …?\\"로 물어보세요.","핵심 단어: which bin, recycling"]',
   'carl', 'Blue one''s recycling, green''s yard waste, and the black one''s regular trash.', '파란 건 재활용, 초록은 정원 쓰레기, 검은 건 일반 쓰레기야.'),
  ('w_park', 4, 'carl',
   'He holds up a finger.', '그가 손가락 하나를 들어 보입니다.',
   'Just rinse out the cans and bottles first, or the city won''t take ''em.', 'Say okay, you will remember that.', '알겠다고, 기억하겠다고 하세요.',
   '[{"any":["remember","got it","will do","okay","ok","sounds good","noted","good to know"]}]',
   'Got it. I''ll remember that.',
   '["Sure, I''ll have the pancakes.","Sorry, I have a meeting at two.","Can I pay in cash?"]',
   '["Say you understand and will remember.","Key words: got it, I''ll remember"]', '["알겠다고, 기억하겠다고 하세요.","핵심 단어: got it, I''ll remember"]',
   'carl', 'Enjoy the market, kid.', '마켓 구경 잘 해.'),
  ('w_market', 1, 'mike',
   'Mike recognizes you from your first visit.', '마이크가 처음 왔을 때의 당신을 알아봅니다.',
   'Hey, welcome back! Stocking up for the week?', 'Say yes, and ask if the strawberries are still buy one, get one free.', '그렇다고 하고, 딸기가 아직 1+1인지 물어보세요.',
   '[{"any":["sale","bogo","buy one","deal","discount","free"]}]',
   'Yeah. Are the strawberries still buy one, get one free?',
   '["Yeah. Is the diner open on Sundays?","Yeah. Does the bus run on weekends?","Yeah. Is Derek coming to the park?"]',
   '["Ask about the deal on strawberries.","Key words: buy one, get one free"]', '["딸기 할인에 대해 물어보세요.","핵심 단어: buy one, get one free"]',
   'mike', 'They sure are. Looks like you only grabbed one box, though.', '네, 맞아요. 그런데 한 상자만 가져오셨네요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('w_market', 2, 'mike',
   'There is nobody behind you in line.', '당신 뒤에 줄 선 사람이 없습니다.',
   'Want to go grab another one? I can wait.', 'Thank him and say you will be right back.', '고맙다고 하고 금방 오겠다고 하세요.',
   '[{"all":["right back"]},{"all":["be quick"]},{"all":["one sec"]},{"all":["one second"]},{"all":["be back"]}]',
   'Oh, thanks! I''ll be right back.',
   '["Oh, thanks! I''ll have the soup.","Oh, thanks! I''ll push the deadline.","Oh, thanks! I''ll take the PPO."]',
   '["Say you will come back very soon.","Key words: right back"]', '["금방 돌아오겠다고 하세요.","핵심 단어: right back"]',
   'mike', 'Take your time.', '천천히 다녀와요.'),
  ('w_market', 3, 'mike',
                                                                                                            'You come back with a second box of strawberries.', '딸기 한 상자를 더 들고 돌아옵니다.',
   'Alright. Did you want to use your rewards number today?', 'Say yes, and that you will punch in your phone number.', '네, 전화번호를 누르겠다고 하세요.',
   '[{"any":["phone","number","type","enter","punch"]}]',
   'Yes, please. I''ll punch in my phone number.',
   '["Yes, please. For here.","Yes, please. Medium rare.","Yes, please. Oat milk."]',
   '["Remember \\"punch in\\" from the checkout last time.","Key words: punch in, phone number"]', '["지난번 계산대에서 배운 punch in을 떠올리세요.","핵심 단어: punch in, phone number"]',
   'mike', 'You saved four dollars and twelve cents today. Nice!', '오늘 4달러 12센트 아끼셨어요. 좋네요!'),
  ('w_market', 4, 'mike',
   'The card reader shows a question.', '카드 단말기에 질문이 뜹니다.',
   'Would you like any cash back?', 'Say no, thanks.', '괜찮다고 거절하세요.',
   '[{"all":["no"],"any":["thanks","thank","good","fine","okay"]},{"all":["i am good"]},{"all":["all set"]}]',
   'No, thanks. I''m good.',
   '["I''d like a rain check.","Can I get the check?","Two works for me."]',
   '["A polite no: \\"No, thanks. I''m good.\\"","Key words: no thanks, I''m good"]', '["정중한 거절: \\"No, thanks. I''m good.\\"","핵심 단어: no thanks, I''m good"]',
   'mike', 'You got it. Here''s your receipt. Have a good weekend!', '알겠어요. 영수증 여기요. 좋은 주말 보내요!'),
  ('w_faucet', 1, 'carl',
   'Your kitchen faucet dripped all night. You find Carl watering the plants in front of the building.', '부엌 수도꼭지가 밤새 똑똑 샜습니다. 건물 앞에서 화초에 물을 주는 칼을 만납니다.',
   'Morning, kid! Everything okay up there?', 'Tell him your kitchen faucet is leaking.', '부엌 수도꼭지가 샌다고 말하세요.',
   '[{"any":["leaking","leaky","leaks","dripping","drips","faucet"]}]',
   'Not really. My kitchen faucet is leaking. It dripped all night.',
   '["Not really. My laptop keeps freezing.","Not really. My bus was late again.","Not really. My latte was cold."]',
   '["Say what is wrong in your kitchen.","Key words: faucet, leaking"]', '["부엌에 무엇이 문제인지 말하세요.","핵심 단어: faucet, leaking"]',
   'carl', 'Ah, shoot. Probably the washer. Happens in these old buildings.', '아이고. 아마 고무 패킹일 거야. 이런 오래된 건물에선 흔해.'),
  ('w_faucet', 2, 'carl',
   'Carl puts down the watering can.', '칼이 물뿌리개를 내려놓습니다.',
   'I can come take a look. When''s a good time?', 'Ask if he could come by this afternoon.', '오늘 오후에 와 줄 수 있는지 물어보세요.',
   '[{"any":["afternoon","today","now","this morning","tonight","anytime","any time"]}]',
   'Could you come by this afternoon? I''ll be home all day.',
   '["Could you move it to two? I have a meeting.","Could you ring me up? I''m in a hurry.","Could you add a unit test? It''s failing."]',
   '["Use \\"Could you come by …?\\"","Key words: come by, this afternoon"]', '["\\"Could you come by …?\\"를 쓰세요.","핵심 단어: come by, this afternoon"]',
   'carl', 'Sure thing.', '그러지.'),
  ('w_faucet', 3, 'carl',
   'He checks his watch.', '그가 시계를 봅니다.',
   'How''s three o''clock? I''ll bring my toolbox.', 'Say three works and thank him.', '세 시 좋다고 하고 고맙다고 하세요.',
   '[{"any":["three","3","works","perfect","great","sounds good"]}]',
   'Three works. Thanks a lot.',
   '["Paper, please.","No, I''ll take the stairs.","I''d like a refund, please."]',
   '["Say the time is okay.","Key words: three works"]', '["그 시간이 괜찮다고 하세요.","핵심 단어: three works"]',
   'carl', 'No problem.', '별말을.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('w_faucet', 4, 'carl',
   'You also have a pile of laundry and no idea where to wash it.', '빨래도 잔뜩 쌓였는데 어디서 빨아야 할지 모릅니다.',
   'Anything else while I''m at it?', 'Ask where the laundry room is and how much a load costs.', '세탁실이 어디 있고 한 번 돌리는 데 얼마인지 물어보세요.',
   '[{"all":["laundry"]},{"all":["washer"]},{"all":["washing"]},{"all":["dryer"]}]',
   'Actually, yes. Where''s the laundry room, and how much is a load?',
   '["Actually, yes. Where''s the farmers market, and when does it open?","Actually, yes. Where''s the IT desk, and when does it close?","Actually, yes. Where''s the diner, and is it open late?"]',
                                                                                                                                                                  '["Ask \\"Where''s the …, and how much is …?\\"","Key words: laundry room, a load"]', '["\\"Where''s the …, and how much is …?\\"로 물어보세요.","핵심 단어: laundry room, a load"]',
   'carl', 'Basement, next to the storage lockers. Two seventy-five a load. It takes quarters or the app.', '지하실, 창고 사물함 옆이야. 한 번에 2달러 75센트. 25센트 동전이나 앱으로 돼.');

REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('w_park.survived', 'w_park', 'You survived your first week?', '첫 주 잘 버텼어?', 'A joking way to ask how a hard week went.', '힘든 한 주가 어땠는지 농담처럼 묻는 말입니다.', 'small-talk'),
  ('w_park.a_blur', 'w_park', 'The first week''s always a blur.', '첫 주는 늘 정신없이 지나가.', '"A blur" = so busy you hardly remember it.', 'a blur는 너무 바빠서 기억도 잘 안 나는 것입니다.', 'small-talk'),
  ('w_park.what_brings_you', 'w_park', 'What brings you here?', '여긴 어쩐 일이에요?', 'A friendly way to ask why someone came.', '왜 왔는지 친근하게 묻는 표현입니다.', 'small-talk'),
  ('w_park.good_call', 'w_park', 'Good call.', '잘 생각했어요.', 'Says someone made a good decision.', '좋은 결정을 했다는 뜻입니다.', 'small-talk'),
                                                                                                                                  ('w_park.heads_up', 'w_park', 'Thanks for the heads-up.', '미리 알려 줘서 고마워요.', 'A "heads-up" is a warning or useful tip in advance.', 'heads-up은 미리 주는 경고나 유용한 정보입니다.', 'home'),
  ('w_park.to_the_curb', 'w_park', 'Bins go out to the curb.', '쓰레기통은 길가에 내놔요.', 'In the US, trash bins are put by the street on pickup day.', '미국에서는 수거일에 쓰레기통을 길가에 내놓습니다.', 'home'),
  ('w_park.rinse_out', 'w_park', 'Rinse out the cans and bottles.', '캔과 병은 헹궈서 내놔요.', '"Rinse out" = wash quickly with water.', 'rinse out은 물로 간단히 헹구는 것입니다.', 'home'),
  ('w_market.stocking_up', 'w_market', 'Stocking up for the week?', '한 주 먹을 거 사 두시는 거예요?', '"Stock up" = buy a lot to keep at home.', 'stock up은 집에 두려고 많이 사는 것입니다.', 'shopping'),
  ('w_market.bogo', 'w_market', 'Buy one, get one free', '하나 사면 하나 더(1+1)', 'Often written BOGO on sale signs.', '할인 안내판에는 흔히 BOGO라고 씁니다.', 'shopping'),
  ('w_market.right_back', 'w_market', 'I''ll be right back.', '금방 올게요.', 'Say this when you leave for a moment.', '잠깐 자리를 비울 때 하는 말입니다.', 'shopping'),
  ('w_market.take_your_time', 'w_market', 'Take your time.', '천천히 하세요.', 'Tells someone not to hurry.', '서두르지 말라는 말입니다.', 'small-talk'),
  ('w_market.you_saved', 'w_market', 'You saved four dollars and twelve cents.', '4달러 12센트 아끼셨어요.', 'Receipts often show your savings from the rewards card.', '영수증에 적립 카드로 아낀 금액이 나오는 경우가 많습니다.', 'shopping'),
  ('w_market.cash_back', 'w_market', 'Would you like any cash back?', '현금 인출하시겠어요?', 'With a debit card, you can take cash from your account at the register.', '직불카드로 계산대에서 계좌의 현금을 받을 수 있습니다.', 'shopping'),
  ('w_market.im_good', 'w_market', 'No, thanks. I''m good.', '괜찮아요.', '"I''m good" is a casual way to decline an offer.', '"I''m good"은 제안을 편하게 거절하는 말입니다.', 'small-talk'),
  ('w_faucet.everything_okay', 'w_faucet', 'Everything okay up there?', '위층은 별일 없지?', 'A landlord or neighbor checking on you.', '집주인이나 이웃이 안부를 확인하는 말입니다.', 'home'),
  ('w_faucet.faucet_leaking', 'w_faucet', 'My kitchen faucet is leaking.', '부엌 수도꼭지가 새요.', 'Americans say "faucet"; the British say "tap".', '미국에서는 faucet, 영국에서는 tap이라고 합니다.', 'home'),
  ('w_faucet.shoot', 'w_faucet', 'Ah, shoot.', '아이고, 저런.', 'A mild word for small bad news.', '작은 나쁜 소식에 쓰는 순한 말입니다.', 'home'),
  ('w_faucet.take_a_look', 'w_faucet', 'I can come take a look.', '가서 한번 볼게.', '"Take a look" = check or inspect.', 'take a look은 확인하거나 살펴보는 것입니다.', 'home'),
  ('w_faucet.come_by', 'w_faucet', 'Could you come by this afternoon?', '오늘 오후에 들러 주실 수 있어요?', '"Come by" = visit briefly.', 'come by는 잠깐 들르는 것입니다.', 'home'),
  ('w_faucet.while_im_at_it', 'w_faucet', 'Anything else while I''m at it?', '온 김에 다른 건 없어?', '"While I''m at it" = since I''m already doing this.', 'while I''m at it은 하는 김에라는 뜻입니다.', 'home'),
  ('w_faucet.laundry_room', 'w_faucet', 'Where''s the laundry room?', '세탁실이 어디예요?', 'Many US apartment buildings have shared coin laundry.', '미국 아파트 건물에는 공용 동전 세탁실이 많습니다.', 'home'),
  ('w_faucet.a_load', 'w_faucet', 'How much is a load?', '한 번 돌리는 데 얼마예요?', 'A "load" of laundry = one machine full.', 'a load of laundry는 세탁기 한 번 분량입니다.', 'home');
