-- Sim Office seed (agent D): week 2, days 8-10: client kickoff, scope and contract negotiation, trip prep
-- Generated from structured data; push with: node tools/dolt.mjs push <this file>
-- Statements are split at a semicolon at the end of a line. Each statement is kept under ~11k URL-encoded characters (DoltHub limit).
/* part 1/1: d8_standup d8_kickoff d8_trip_approval d9_scope d9_travel_booking d9_code_review d10_contract_terms d10_approval d10_handoff ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO episodes (id, title, title_ko, place, npc, day_from, day_to, time_from, time_to, requires, summary, summary_ko, reward, energy, sort, tags) VALUES
  ('d8_standup', 'Flagging a blocker at standup', '스탠드업에서 블로커 알리기', 'office_desk_team', 'derek', 8, 8, '09:00', '10:30', NULL, 'At the Monday standup, share what you finished, what you are doing today, and what is blocking you.', '월요일 스탠드업에서 끝낸 일, 오늘 할 일, 막혀 있는 일을 공유합니다.', 0, 0, 810, 'meeting,standup,week2'),
  ('d8_kickoff', 'Kickoff call with Summit Retail', '서밋 리테일 킥오프 콜', 'office_meeting', 'priya', 8, 8, '10:30', '12:30', NULL, 'Priya puts Greg Whitfield from Summit Retail on the big screen. Confirm his requirements and ask the right questions.', '프리야가 서밋 리테일의 그렉 휫필드를 큰 화면에 띄웁니다. 요구사항을 확인하고 필요한 질문을 하세요.', 0, 0, 820, 'client,meeting,requirements,video-call,week2'),
  ('d8_trip_approval', 'Asking to visit the client', '고객사 출장 승인 받기', 'office_manager', 'maya', 8, 8, '13:00', '17:30', 'd8_kickoff', 'Greg wants to review the contract in person on Thursday and Friday. Ask Maya for approval and learn the travel policy.', '그렉이 목요일과 금요일에 직접 만나 계약을 검토하자고 합니다. 마야에게 승인을 받고 출장 규정을 알아보세요.', 0, 0, 830, 'travel,hr,request,week2'),
  ('d9_scope', 'Negotiating scope and timeline', '범위·일정 협상', 'office_meeting', 'priya', 9, 9, '10:00', '12:30', 'd8_kickoff', 'Greg wants the dashboard and the mobile app by November 1. Push back politely and offer a phased plan.', '그렉은 대시보드와 모바일 앱을 11월 1일까지 원합니다. 정중히 반대하고 단계별 계획을 제안하세요.', 0, 0, 910, 'client,negotiation,video-call,week2'),
  ('d9_travel_booking', 'Booking the trip with Tom', '톰과 출장 예약하기', 'office_lobby', 'tom', 9, 10, '09:00', '17:30', 'd8_trip_approval', 'Maya approved your trip. Tom books your flight and hotel on the company card. Tell him what you need.', '마야가 출장을 승인했습니다. 톰이 법인 카드로 항공편과 호텔을 예약합니다. 필요한 것을 말하세요.', 0, 0, 920, 'travel,booking,week2'),
  ('d9_code_review', 'Trading code reviews', '코드 리뷰 주고받기', 'office_desk_team', 'derek', 9, 10, '13:00', '18:30', NULL, 'Ask Derek to review your pull request, take his feedback well, and give some feedback on his code.', '데릭에게 풀 리퀘스트 리뷰를 부탁하고, 피드백을 잘 받아들이고, 그의 코드에도 피드백을 주세요.', 0, 0, 930, 'office,code-review,feedback,week2'),
  ('d10_contract_terms', 'Negotiating the contract terms', '계약 조건 협상', 'office_meeting', 'priya', 10, 10, '10:00', '12:30', 'd9_scope', 'Greg pushes on price, payment terms and uptime. Hold your ground, find the middle, and don''t agree to what you can''t approve.', '그렉이 가격, 지급 조건, 가동률을 밀어붙입니다. 버틸 곳은 버티고, 중간을 찾되, 승인할 수 없는 것에는 동의하지 마세요.', 0, 0, 1010, 'client,negotiation,contract,video-call,week2'),
  ('d10_approval', 'Getting sign-off on the discount', '할인 승인 받기', 'office_manager', 'maya', 10, 10, '12:30', '17:30', 'd10_contract_terms', 'Greg asked for a lower price. Explain the situation to Maya and agree on how far you can go.', '그렉이 가격을 낮춰 달라고 했습니다. 마야에게 상황을 설명하고 어디까지 양보할지 정하세요.', 0, 0, 1020, 'negotiation,manager,approval,week2'),
  ('d10_handoff', 'Handing off before the trip', '출장 전 인수인계', 'office_desk_team', 'derek', 10, 10, '14:00', '19:00', 'd9_travel_booking', 'You will be out Thursday and Friday. Hand off your work to Derek so nothing falls through the cracks.', '목요일과 금요일에 자리를 비웁니다. 빠뜨리는 일이 없도록 데릭에게 인수인계하세요.', 0, 0, 1030, 'office,handoff,travel,week2');

/* part 1/9: d8_standup#1 d8_standup#2 d8_standup#3 d8_kickoff#1 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d8_standup', 1, 'derek', 'The team gathers by Derek''s desk for the Monday standup. It is your turn.', '팀이 월요일 스탠드업을 하러 데릭 자리 옆에 모였습니다. 당신 차례입니다.', 'Alright, you''re up. What did you get done last week, and what''s on your plate today?', 'Say you finished the login page, and today you are starting on the inventory API.', '지난주에 로그인 페이지를 끝냈고, 오늘은 재고 API를 시작한다고 말하세요.', '[{"all":["finished"],"any":["login","last week"]},{"all":["wrapped up"]},{"all":["done","login"]},{"all":["today"],"any":["starting","start on","work on","working on"]}]', 'Last week I finished the login page. Today I''m starting on the inventory API.', '["I''d like a table for two by the window, please.","Could you tell me where the nearest bus stop is?","I think it''s going to rain later this afternoon."]', '["Say what you finished and what you are starting today.","Key words: finished, today, starting"]', '["끝낸 일과 오늘 시작할 일을 말하세요.","핵심 단어: finished, today, starting"]', 'derek', 'Nice. The inventory API is a big one.', '좋아요. 재고 API는 큰 작업이죠.'),
  ('d8_standup', 2, 'derek', 'You can''t test the API because you still don''t have access to the staging database.', '스테이징 데이터베이스 접근 권한이 아직 없어서 API를 테스트할 수 없습니다.', 'Any blockers?', 'Say you are blocked: you still don''t have access to the staging database.', '막혀 있다고 말하세요. 스테이징 데이터베이스 접근 권한이 아직 없습니다.', '[{"all":["blocked"],"any":["access","database","staging"]},{"all":["access"],"any":["staging","database"]},{"all":["blocker"],"any":["access","database","staging"]}]', 'Yeah, I''m blocked on one thing. I still don''t have access to the staging database.', '["No blockers. Everything is going smoothly.","I''ll have the chicken sandwich, please.","My flight leaves at nine thirty on Thursday."]', '["Say what is blocking you.","Key words: blocked, access, staging database"]', '["무엇 때문에 막혀 있는지 말하세요.","핵심 단어: blocked, access, staging database"]', 'derek', 'Ugh, that''s on me. I''ll ping Sam in IT right after this.', '아, 그건 제 잘못이에요. 끝나자마자 IT의 샘에게 연락할게요.'),
  ('d8_standup', 3, 'derek', 'Before the standup ends, you remember the client call later this morning.', '스탠드업이 끝나기 전, 오늘 오전의 고객 통화가 떠오릅니다.', 'Anything else before we wrap up?', 'Remind everyone about the kickoff call with Summit Retail at eleven.', '11시에 서밋 리테일과 킥오프 콜이 있다고 모두에게 알려 주세요.', '[{"all":["kickoff"],"any":["eleven","11","call","summit"]},{"all":["kick off"]},{"all":["summit","call"]},{"all":["call"],"any":["eleven","11"]}]', 'Just a reminder that we have the kickoff call with Summit Retail at eleven.', '["Could I get a receipt for that, please?","I''d like an aisle seat if you have one.","Sorry, I think you have the wrong number."]', '["Remind the team about the client meeting.","Key words: kickoff call, Summit, eleven"]', '["고객 회의가 있다고 팀에 알려 주세요.","핵심 단어: kickoff call, Summit, eleven"]', 'derek', 'Good call. Priya''s running it, so bring your questions. Okay, that''s a wrap, everyone.', '좋아요. 프리야가 진행하니까 질문 준비해 와요. 자, 오늘은 여기까지!'),
  ('d8_kickoff', 1, 'priya', 'You join Priya in the meeting room. Greg from Summit Retail is on the video call.', '회의실에서 프리야와 함께합니다. 서밋 리테일의 그렉이 화상 통화에 들어와 있습니다.', 'Greg, this is our new developer. They''ll be building most of the dashboard. Want to say hi?', 'Greet Greg and say you are looking forward to working with him.', '그렉에게 인사하고 함께 일하게 되어 기대된다고 말하세요.', '[{"all":["looking forward"]},{"all":["nice","meet"]},{"all":["great","meet"]},{"all":["excited","work"]}]', 'Hi Greg, nice to meet you. I''m looking forward to working with you.', '["Hi, I''d like to check out of my room, please.","Sorry, I''m running late because of the traffic.","Could we split the check four ways?"]', '["Say hello and that you are happy to work together.","Key words: nice to meet you, looking forward"]', '["인사하고 함께 일하게 되어 기쁘다고 말하세요.","핵심 단어: nice to meet you, looking forward"]', 'greg', 'Likewise! We''ve got a lot riding on this project, so I''m glad you''re on board.', '저도요! 이 프로젝트에 걸린 게 많아서, 함께하게 되어 기뻐요.');

/* part 2/9: d8_kickoff#2 d8_kickoff#3 d8_kickoff#4 d8_kickoff#5 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d8_kickoff', 2, 'greg', 'Greg explains that his store managers can''t see stock levels in one place.', '그렉은 매장 관리자들이 재고를 한곳에서 볼 수 없다고 설명합니다.', 'Basically, our store managers are flying blind. We want one dashboard with live inventory for all forty stores.', 'Check that you understood. Start with "Just to make sure I understand" and restate what he wants.', '제대로 이해했는지 확인하세요. "Just to make sure I understand"로 시작해 그가 원하는 것을 다시 말하세요.', '[{"all":["make sure","understand"]},{"all":["if i understand"]},{"all":["so you want"],"any":["dashboard","inventory","stores"]},{"all":["understand","correctly"]}]', 'Just to make sure I understand, you want one dashboard that shows live inventory for all forty stores?', '["We can''t commit to that date.","Could you hold the elevator for me?","I''ll take the window seat, thanks."]', '["Repeat his request back to him to confirm it.","Key words: just to make sure I understand, dashboard"]', '["그의 요청을 다시 말해 확인하세요.","핵심 단어: just to make sure I understand, dashboard"]', 'greg', 'Exactly. And live means it updates within a few minutes, not overnight.', '바로 그거예요. 그리고 실시간이란 밤사이가 아니라 몇 분 안에 갱신된다는 뜻이에요.'),
  ('d8_kickoff', 3, 'greg', 'You don''t know how their stores record sales today.', '그들의 매장이 지금 판매 데이터를 어떻게 기록하는지 모릅니다.', 'Our point-of-sale system is kind of old, though. Is that going to be a problem?', 'Ask him to walk you through how their point-of-sale system sends data now.', '지금 POS 시스템이 데이터를 어떻게 보내는지 차근차근 설명해 달라고 하세요.', '[{"all":["walk","through"]},{"all":["how","data"],"any":["send","sends","export","work","works","get"]},{"all":["explain","how"]},{"all":["tell","more","system"]}]', 'It depends. Could you walk me through how your point-of-sale system sends data today?', '["It won''t be a problem at all, I promise.","Could you walk me to the gate, please?","How much is the late checkout fee?"]', '["Ask him to explain the current process step by step.","Key words: walk me through, how, data"]', '["현재 과정을 단계별로 설명해 달라고 하세요.","핵심 단어: walk me through, how, data"]', 'greg', 'Sure. Right now each store exports a file every night at midnight, and someone uploads it by hand.', '그럼요. 지금은 매장마다 매일 밤 자정에 파일을 내보내고, 누군가 그걸 손으로 올려요.'),
  ('d8_kickoff', 4, 'priya', 'A nightly file can''t give Greg live data. Priya looks at you to raise it.', '하루 한 번 올리는 파일로는 실시간 데이터가 나올 수 없습니다. 프리야가 말해 보라는 눈짓을 합니다.', 'Hmm. That could affect the timeline. Want to flag that for Greg?', 'Tell Greg politely that nightly files won''t be enough for live data, so you will need API access.', '매일 밤 파일로는 실시간 데이터에 부족해서 API 접근이 필요하다고 정중히 말하세요.', '[{"all":["api"],"any":["need","access","require"]},{"all":["nightly","enough"]},{"all":["real time"],"any":["need","api","access"]},{"all":["live","need"]}]', 'Nightly files won''t be enough for live data, so we''ll need API access to your point-of-sale system.', '["Nightly files are perfect, so we don''t need anything else.","The live music starts at eight tonight.","I''ll need a receipt for my expense report."]', '["Explain what you need instead of the nightly file.","Key words: not enough, API access, need"]', '["매일 밤 파일 대신 무엇이 필요한지 설명하세요.","핵심 단어: not enough, API access, need"]', 'greg', 'Got it. I''ll loop in our IT folks and get you what you need by Wednesday.', '알겠어요. 우리 IT 팀을 참여시켜서 수요일까지 필요한 걸 드릴게요.'),
  ('d8_kickoff', 5, 'priya', 'The call is almost over.', '통화가 거의 끝나 갑니다.', 'Great. Anything else before we let Greg go?', 'Say you will send a recap email with the next steps later today.', '오늘 중으로 다음 단계를 정리한 요약 메일을 보내겠다고 말하세요.', '[{"all":["recap"]},{"all":["summary"],"any":["send","email"]},{"all":["follow up"],"any":["email","today"]},{"all":["send","notes"]},{"all":["next steps"]}]', 'I''ll send a recap email with the next steps later today.', '["I''ll have the salmon with a side salad.","Can I get a late checkout tomorrow?","Let''s meet halfway on the price."]', '["Promise a written summary after the call.","Key words: recap email, next steps"]', '["통화 후 서면 요약을 약속하세요.","핵심 단어: recap email, next steps"]', 'greg', 'Perfect. Talk soon, everyone.', '좋아요. 다들 또 얘기해요.');

/* part 3/9: d8_trip_approval#1 d8_trip_approval#2 d8_trip_approval#3 d9_scope#1 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d8_trip_approval', 1, 'maya', 'After the call, Greg invited you to Ridgeport to go over the contract in person. You stop by Maya''s office.', '통화 후 그렉이 리지포트에서 직접 계약을 검토하자고 초대했습니다. 마야의 사무실에 들릅니다.', 'Hey, come on in. What''s up?', 'Ask if it would be okay for you to go to Ridgeport on Thursday and Friday.', '목요일과 금요일에 리지포트에 가도 괜찮을지 물어보세요.', '[{"all":["would it be okay"]},{"all":["would it be ok"]},{"all":["okay","if","go"]},{"all":["could","go","ridgeport"]},{"all":["permission"]},{"all":["approve","trip"]}]', 'Would it be okay if I went to Ridgeport on Thursday and Friday to meet the client?', '["I''m going to Ridgeport this weekend for a concert.","Can I take Friday off to see my family?","I already booked a first-class ticket, so I''m going."]', '["Ask politely for permission to travel.","Key words: would it be okay if, Ridgeport"]', '["출장 가도 되는지 정중히 허락을 구하세요.","핵심 단어: would it be okay if, Ridgeport"]', 'maya', 'Oh nice, Greg asked for you? Sure. It''s a good chance to meet them face to face.', '오, 그렉이 당신을 불렀어요? 좋아요. 직접 만날 좋은 기회예요.'),
  ('d8_trip_approval', 2, 'maya', 'Maya pulls up the travel policy on her screen.', '마야가 화면에 출장 규정을 띄웁니다.', 'Just stick to the travel policy. Economy flights, and hotels under two hundred a night.', 'Ask what the per diem is for meals.', '식비 일일 한도(per diem)가 얼마인지 물어보세요.', '[{"all":["per diem"]},{"all":["meals"],"any":["how much","budget","limit","allowance","cover"]},{"all":["food"],"any":["budget","limit","allowance"]}]', 'Got it. What''s the per diem for meals?', '["Can I upgrade to business class?","What time does the hotel pool close?","Is there a gym in the office?"]', '["Ask about the daily meal allowance.","Key words: per diem, meals"]', '["하루 식비 한도를 물어보세요.","핵심 단어: per diem, meals"]', 'maya', 'Sixty-five dollars a day. Keep your receipts, and client dinners go on the company card.', '하루 65달러예요. 영수증은 챙기고, 고객과의 저녁은 법인 카드로 해요.'),
  ('d8_trip_approval', 3, 'maya', 'You have never booked a business trip here before.', '이 회사에서 출장을 예약해 본 적이 없습니다.', 'Anything else you need from me?', 'Ask if you should book everything yourself or go through Tom.', '직접 다 예약해야 하는지, 톰을 통해야 하는지 물어보세요.', '[{"all":["book"],"any":["myself","tom","who"]},{"all":["go through","tom"]},{"all":["tom"],"any":["handle","booking","book"]}]', 'Should I book everything myself, or go through Tom?', '["Should I bring my own lunch tomorrow?","Could I get the check, please?","Should I take the bus or walk home?"]', '["Ask who handles the booking.","Key words: book, myself, go through Tom"]', '["예약을 누가 하는지 물어보세요.","핵심 단어: book, myself, go through Tom"]', 'maya', 'Go through Tom. He has the company card and knows the policy inside out. I''ll approve the trip in the system now.', '톰을 통해요. 법인 카드도 있고 규정을 훤히 알아요. 지금 시스템에서 출장을 승인할게요.'),
  ('d9_scope', 1, 'greg', 'Greg is back on the video call with Priya and you. He sounds rushed.', '그렉이 다시 화상 통화에 들어왔습니다. 급해 보입니다.', 'So, our board wants the dashboard and the mobile checkout app live by November first. Can you make that happen?', 'Say politely that you can''t commit to that date for both projects.', '두 프로젝트 모두 그 날짜까지는 약속할 수 없다고 정중히 말하세요.', '[{"all":["commit"]},{"all":["cannot","both"]},{"all":["not","realistic"]},{"all":["tight"],"any":["date","deadline","timeline"]}]', 'I understand the pressure, but we can''t commit to that date for both projects.', '["No problem, we can definitely do both by November first.","The flight is delayed until November first.","I''d love to try the local barbecue while I''m in town."]', '["Say no to the date, but politely.","Key words: can''t commit, that date"]', '["그 날짜는 안 된다고 정중히 말하세요.","핵심 단어: can''t commit, that date"]', 'greg', 'Hmm. I was afraid you''d say that. So what can you do?', '음. 그렇게 말할까 봐 걱정했어요. 그럼 뭘 할 수 있죠?');

/* part 4/9: d9_scope#2 d9_scope#3 d9_scope#4 d9_travel_booking#1 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d9_scope', 2, 'greg', 'The dashboard alone will take about eight weeks. The mobile app needs another eight.', '대시보드만 약 8주, 모바일 앱은 8주가 더 걸립니다.', 'What can you realistically deliver by November first?', 'Suggest phasing it: the dashboard by November first, the mobile app in January.', '단계를 나누자고 제안하세요. 11월 1일에 대시보드, 1월에 모바일 앱.', '[{"any":["phase","phased","phases","phasing"]},{"all":["dashboard"],"any":["january","later"]},{"all":["what if"],"any":["dashboard","january","split"]}]', 'What if we phased it? We deliver the dashboard by November first and the mobile app in January.', '["What if we met at the hotel lobby instead?","We could deliver both apps by next Friday.","Let''s push everything to next year."]', '["Offer to split the work into two stages.","Key words: what if we phased it, dashboard, January"]', '["일을 두 단계로 나누자고 제안하세요.","핵심 단어: what if we phased it, dashboard, January"]', 'greg', 'Phased… okay, I could sell that to the board. But what if we paid more?', '단계별이라… 좋아요, 그거면 이사회를 설득할 수 있겠어요. 그런데 돈을 더 내면요?'),
  ('d9_scope', 3, 'greg', 'Priya shakes her head slightly. Adding people late would not speed things up.', '프리야가 살짝 고개를 젓습니다. 늦게 사람을 더 넣는다고 빨라지지 않습니다.', 'Could you add more people and still do it all by November?', 'Explain the trade-off: more people won''t make it much faster, and quality would suffer.', '득실을 설명하세요. 사람을 더 넣어도 크게 빨라지지 않고 품질이 떨어집니다.', '[{"any":["trade off","tradeoff"]},{"all":["quality"],"any":["suffer","risk","drop","worse"]},{"all":["more people"],"any":["faster","slower","help"]},{"all":["adding","people"]}]', 'Honestly, adding people this late won''t make it much faster, and quality would suffer. That''s the trade-off.', '["Sure, send us ten more people and we''ll finish tomorrow.","I''d prefer a room on a higher floor, please.","Let''s talk about the weather instead."]', '["Explain why money and people won''t solve it.","Key words: adding people, quality, trade-off"]', '["돈과 사람으로 해결되지 않는 이유를 설명하세요.","핵심 단어: adding people, quality, trade-off"]', 'greg', 'Fair enough. I''d rather have it done right. Let''s go with the phased plan.', '그럴 만하네요. 제대로 하는 게 낫죠. 단계별 계획으로 갑시다.'),
  ('d9_scope', 4, 'priya', 'Priya is taking notes.', '프리야가 메모하고 있습니다.', 'Great. I''ll update the timeline. Can you confirm the plan with Greg before we hang up?', 'Confirm: phase one is the dashboard on November first, and you will send an updated timeline tomorrow.', '확인하세요. 1단계는 11월 1일의 대시보드이고, 내일 수정된 일정을 보냅니다.', '[{"all":["confirm"]},{"all":["send","timeline"]},{"all":["phase one"],"any":["november","first","dashboard"]},{"all":["updated","timeline"]}]', 'So to confirm, phase one is the dashboard on November first, and we''ll send an updated timeline tomorrow.', '["So we''ll deliver everything by November first, no matter what.","I''ll send you the hotel confirmation number.","Could you send me the menu, please?"]', '["Repeat the agreement and the next step.","Key words: to confirm, phase one, timeline"]', '["합의 내용과 다음 단계를 다시 말하세요.","핵심 단어: to confirm, phase one, timeline"]', 'greg', 'Sounds like a plan. Thanks for being straight with me.', '좋은 계획이네요. 솔직하게 말해 줘서 고마워요.'),
  ('d9_travel_booking', 1, 'tom', 'You go to the front desk to book your trip with Tom.', '출장 예약을 하러 프런트의 톰에게 갑니다.', 'Maya told me you''re heading to Ridgeport. What dates are we looking at?', 'Say you need to fly out Thursday morning and come back Friday afternoon.', '목요일 아침에 출발해서 금요일 오후에 돌아와야 한다고 말하세요.', '[{"all":["thursday","friday"]},{"all":["fly out"],"any":["thursday","morning"]},{"all":["leave","thursday"]}]', 'I need to fly out Thursday morning and come back Friday afternoon.', '["I need to fly out Saturday and come back next month.","I''d like to cancel my trip, please.","Could I get a refill on my coffee?"]', '["Give the departure and return days.","Key words: fly out Thursday, back Friday"]', '["출발일과 귀환일을 말하세요.","핵심 단어: fly out Thursday, back Friday"]', 'tom', 'Okay, there''s a nine-thirty on Thursday with Crestline Air. It''s a nonstop, about two hours.', '좋아요, 목요일 9시 30분 크레스트라인 항공편이 있어요. 직항이고 약 두 시간이에요.');

/* part 5/9: d9_travel_booking#2 d9_travel_booking#3 d9_travel_booking#4 d9_code_review#1 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d9_travel_booking', 2, 'tom', 'Tom is filling out the booking form.', '톰이 예약 양식을 채우고 있습니다.', 'Aisle or window? And do you have a frequent flyer number?', 'Tell him your seat preference, and say you don''t have a frequent flyer number yet.', '원하는 좌석을 말하고, 아직 마일리지 회원 번호가 없다고 하세요.', '[{"any":["aisle","window"]}]', 'Aisle, please. And I don''t have a frequent flyer number yet.', '["I''ll take the chicken, please.","No, I don''t need a hotel.","Could you put it on my personal credit card?"]', '["Choose a seat by the aisle or the window.","Key words: aisle or window"]', '["통로 쪽이나 창가 쪽을 고르세요.","핵심 단어: aisle 또는 window"]', 'tom', 'Aisle it is. I''ll sign you up for their program so you get the miles.', '통로석으로 할게요. 마일리지 받게 회원 가입도 해 둘게요.'),
  ('d9_travel_booking', 3, 'tom', 'Now the hotel. The policy cap is two hundred dollars a night.', '이제 호텔입니다. 규정상 한도는 1박 200달러입니다.', 'There''s the Pinecrest Hotel near Summit''s office, one eighty-nine a night. That''s under the cap.', 'Ask if it is within walking distance of the client''s office, and if breakfast is included.', '고객사까지 걸어갈 수 있는 거리인지, 아침 식사가 포함인지 물어보세요.', '[{"all":["walking distance"]},{"all":["breakfast"],"any":["included","include","includes","come with"]},{"all":["walk"],"any":["office","client"]},{"all":["how far"]}]', 'Is it within walking distance of their office? And is breakfast included?', '["Is it far from the beach?","Is lunch on the company today?","Can you book a table for dinner at seven?"]', '["Ask about the distance and the breakfast.","Key words: walking distance, breakfast included"]', '["거리와 아침 식사를 물어보세요.","핵심 단어: walking distance, breakfast included"]', 'tom', 'Five-minute walk, and yes, breakfast is included. I''ll put it all on the company card.', '걸어서 5분이고, 네, 조식 포함이에요. 전부 법인 카드로 할게요.'),
  ('d9_travel_booking', 4, 'tom', 'You will also need to get from the Ridgeport airport to the hotel.', '리지포트 공항에서 호텔까지도 가야 합니다.', 'Ground transportation is on you, but it''s reimbursable. Just keep the receipts.', 'Ask if it is okay to take a rideshare from the airport, or if you should take the shuttle.', '공항에서 차량 호출 서비스를 타도 되는지, 셔틀을 타야 하는지 물어보세요.', '[{"all":["rideshare"]},{"all":["ride share"]},{"all":["taxi"]},{"all":["cab"]},{"all":["shuttle"]}]', 'Is it okay to take a rideshare from the airport, or should I take the shuttle?', '["Can I rent a sports car for the weekend?","Should I bring my own towels?","Is it okay to bring my dog to work?"]', '["Ask how you should get to the hotel.","Key words: rideshare, taxi, shuttle"]', '["호텔까지 무엇을 타고 가야 하는지 물어보세요.","핵심 단어: rideshare, taxi, shuttle"]', 'tom', 'A rideshare is fine, up to fifty bucks each way. Here''s your itinerary. Have a good trip!', '차량 호출 괜찮아요, 편도 50달러까지요. 여기 여행 일정표예요. 잘 다녀와요!'),
  ('d9_code_review', 1, 'derek', 'Your inventory API pull request is ready. Derek is at his desk.', '재고 API 풀 리퀘스트가 준비됐습니다. 데릭이 자리에 있습니다.', 'Hey, what''s up?', 'Ask Derek if he has a few minutes to review your pull request.', '데릭에게 풀 리퀘스트를 리뷰할 시간이 있는지 물어보세요.', '[{"all":["review"],"any":["pull request","pr","code","changes"]},{"all":["take a look"]},{"all":["look at"],"any":["pr","code","pull request"]}]', 'Do you have a few minutes to review my pull request?', '["Do you have a few minutes to grab lunch?","Can you review the dinner menu with me?","Did you watch the game last night?"]', '["Ask for a code review.","Key words: review, pull request"]', '["코드 리뷰를 부탁하세요.","핵심 단어: review, pull request"]', 'derek', 'Sure, send me the link. Give me twenty minutes.', '그럼요, 링크 보내 줘요. 20분만 줘요.');

/* part 6/9: d9_code_review#2 d9_code_review#3 d9_code_review#4 d10_contract_terms#1 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d9_code_review', 2, 'derek', 'Derek left a comment: one function is too long and has no tests.', '데릭이 댓글을 남겼습니다. 함수 하나가 너무 길고 테스트가 없습니다.', 'Looks good overall. But this function is doing a lot. Mind splitting it up and adding a couple of tests?', 'Thank him for the feedback and say you will split it up and add tests.', '피드백에 감사하고, 함수를 나누고 테스트를 추가하겠다고 말하세요.', '[{"all":["thanks"],"any":["split","tests","test","feedback"]},{"all":["thank you"],"any":["split","tests","test","feedback"]},{"all":["good point"]},{"all":["split"],"any":["test","tests"]}]', 'Thanks for the feedback. Good point, I''ll split it up and add some tests.', '["I don''t think tests are necessary for this.","Thanks, but I''m already full.","Could you split the bill with me?"]', '["Accept the feedback gracefully.","Key words: thanks for the feedback, split, tests"]', '["피드백을 기분 좋게 받아들이세요.","핵심 단어: thanks for the feedback, split, tests"]', 'derek', 'Appreciate it. Oh, and I''ve got one for you too, if you have time.', '고마워요. 아, 나도 하나 부탁할 게 있는데, 시간 되면요.'),
  ('d9_code_review', 3, 'derek', 'You review Derek''s code. A variable named data2 is confusing.', '데릭의 코드를 리뷰합니다. data2라는 변수 이름이 헷갈립니다.', 'Be honest. Anything you''d change?', 'Give gentle feedback: suggest renaming data2 to something clearer.', '부드럽게 피드백하세요. data2를 더 분명한 이름으로 바꾸자고 제안하세요.', '[{"all":["rename"]},{"all":["name"],"any":["clearer","confusing","descriptive","better"]},{"all":["maybe","call","it"]}]', 'It looks great. One small thing: maybe rename data2 to something clearer, like storeInventory?', '["It''s terrible. You should rewrite all of it.","Can I put my name on the waitlist?","It''s perfect. I wouldn''t change a thing."]', '["Start with something positive, then make one small suggestion.","Key words: one small thing, rename, clearer"]', '["좋은 점을 먼저 말하고 작은 제안 하나를 하세요.","핵심 단어: one small thing, rename, clearer"]', 'derek', 'Ha, fair. data2 was a placeholder I forgot about. Nice catch. Coffee later?', '하, 맞아요. data2는 임시로 붙이고 잊어버린 거예요. 잘 찾았네요. 이따 커피 할래요?'),
  ('d9_code_review', 4, 'derek', 'Derek wants to grab coffee this afternoon.', '데릭이 오후에 커피 한잔하자고 합니다.', 'Want to grab coffee later? My treat for the review.', 'Accept and suggest going around three.', '좋다고 하고 3시쯤 가자고 제안하세요.', '[{"any":["three","3"]},{"all":["sounds good"]},{"all":["sure"]}]', 'Sure, how about around three?', '["Sorry, I''m allergic to peanuts.","I''ll be on a plane on Thursday.","The printer on our floor is out of paper."]', '["Say yes and name a time.","Key words: sure, around three"]', '["좋다고 하고 시간을 정하세요.","핵심 단어: sure, around three"]', 'derek', 'Three works. I''ll swing by your desk.', '3시 좋아요. 자리로 들를게요.'),
  ('d10_contract_terms', 1, 'greg', 'Priya shares the proposal on screen: $180,000 for phase one, payment Net 30.', '프리야가 제안서를 화면에 띄웁니다. 1단계 18만 달러, 지급 조건 Net 30.', 'Okay, I''ve looked at the numbers. Honestly, one eighty is a bit outside our budget. We were thinking closer to one fifty.', 'Show you understand his concern, and point out what the price includes: three months of support.', '그의 걱정을 이해한다고 하고, 가격에 3개월 지원이 포함되어 있음을 짚으세요.', '[{"any":["includes","include","included"]},{"all":["understand"],"any":["price","budget","support"]},{"all":["covers"]}]', 'I understand. Keep in mind the price includes three months of support after launch.', '["Okay, one fifty is fine. Let''s sign today.","I think the hotel is a bit outside my budget too.","Could you repeat that? The connection is bad."]', '["Explain the value before you talk about the number.","Key words: I understand, the price includes, support"]', '["숫자를 말하기 전에 가치를 설명하세요.","핵심 단어: I understand, the price includes, support"]', 'greg', 'That helps. But I still need to get the number down. Can you meet us halfway? Say, one sixty-five?', '도움이 되네요. 그래도 금액을 낮춰야 해요. 중간에서 만날 수 있을까요? 16만 5천 정도?');

/* part 7/9: d10_contract_terms#2 d10_contract_terms#3 d10_contract_terms#4 d10_contract_terms#5 d10_approval#1 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d10_contract_terms', 2, 'greg', 'You are not allowed to approve discounts on your own.', '당신은 혼자서 할인을 승인할 권한이 없습니다.', 'So, one sixty-five. Can we shake on that?', 'Say you can''t agree to that yourself. You will run it by your manager and get back to him.', '혼자서는 동의할 수 없고, 매니저에게 확인한 뒤 다시 연락하겠다고 말하세요.', '[{"all":["run it by"]},{"all":["manager"],"any":["check","ask","talk","run","discuss"]},{"all":["get back","you"]}]', 'I can''t approve that on my own, but let me run it by my manager and get back to you.', '["Sure, one sixty-five works for us. Deal!","My manager is on vacation in Hawaii.","Let me run to the restroom real quick."]', '["Don''t say yes or no. Buy time.","Key words: run it by my manager, get back to you"]', '["예나 아니요로 답하지 말고 시간을 버세요.","핵심 단어: run it by my manager, get back to you"]', 'greg', 'Fair enough. While you''re at it, let''s talk payment terms.', '그러죠. 그 김에 지급 조건도 얘기합시다.'),
  ('d10_contract_terms', 3, 'greg', 'Greg wants to pay 60 days after each invoice instead of 30.', '그렉은 송장마다 30일이 아니라 60일 뒤에 지급하길 원합니다.', 'Our standard is Net 60. Net 30 is tough for our finance team.', 'Propose a compromise in the middle: Net 45.', '중간에서 타협안을 내세요. Net 45.', '[{"any":["45","forty five","fortyfive"]}]', 'How about we meet in the middle at Net 45?', '["Net 60 is totally fine with us.","We need the payment by tomorrow morning.","Let''s meet in the hotel lobby at seven."]', '["Offer the number halfway between 30 and 60.","Key words: meet in the middle, Net 45"]', '["30과 60의 중간 숫자를 제안하세요.","핵심 단어: meet in the middle, Net 45"]', 'greg', 'Net 45… I can live with that.', 'Net 45라… 그 정도면 받아들일 수 있어요.'),
  ('d10_contract_terms', 4, 'greg', 'Next is the service level agreement, the SLA.', '다음은 서비스 수준 협약(SLA)입니다.', 'Last thing: uptime. We need a guarantee. What can you commit to?', 'Offer 99.9 percent uptime and a four-hour response time for critical issues.', '가동률 99.9%와 심각한 장애에 대해 4시간 내 대응을 제안하세요.', '[{"all":["99"]},{"all":["uptime"],"any":["percent","guarantee","commit"]},{"all":["four hour"]},{"all":["4 hour"]},{"all":["response time"]}]', 'We can commit to 99.9 percent uptime and a four-hour response time for critical issues.', '["We can''t promise anything about uptime.","Checkout is at eleven, and late checkout is extra.","Our office is closed on the weekends."]', '["Give a clear number for uptime and response time.","Key words: 99.9 percent uptime, four-hour response time"]', '["가동률과 대응 시간을 분명한 숫자로 말하세요.","핵심 단어: 99.9 percent uptime, four-hour response time"]', 'greg', 'That''s reasonable. Send me the revised terms and I''ll share them with legal.', '합리적이네요. 수정된 조건을 보내 주면 법무팀과 공유할게요.'),
  ('d10_contract_terms', 5, 'priya', 'Priya nods at you to close the call.', '프리야가 통화를 마무리하라고 고개를 끄덕입니다.', 'Nice job. Want to wrap up?', 'Summarize: you will check the price with your manager and send the revised terms by end of day.', '정리하세요. 가격은 매니저에게 확인하고, 수정된 조건을 오늘 중으로 보냅니다.', '[{"all":["end of day"]},{"all":["revised"],"any":["terms","contract","send"]},{"all":["get back"]},{"all":["eod"]}]', 'Great. I''ll check the price with my manager and send you the revised terms by end of day.', '["Great. Let''s sign the contract right now.","I''ll send you my dinner order by text.","See you at the airport tomorrow morning."]', '["List the next steps and a deadline.","Key words: revised terms, end of day"]', '["다음 단계와 기한을 말하세요.","핵심 단어: revised terms, end of day"]', 'greg', 'Sounds good. Talk soon.', '좋아요. 또 얘기해요.'),
  ('d10_approval', 1, 'maya', 'You need Maya''s sign-off before you answer Greg.', '그렉에게 답하기 전에 마야의 승인이 필요합니다.', 'How''d the call with Greg go?', 'Say it went well, but he asked for a discount, down to one sixty-five.', '잘 됐지만 그가 16만 5천으로 할인을 요청했다고 말하세요.', '[{"all":["discount"]},{"all":["165"]},{"all":["sixty five"]},{"all":["lower","price"]}]', 'It went well, but he asked for a discount. He wants to bring it down to one sixty-five.', '["It went great. He agreed to the full price.","He asked if we could meet for lunch.","He''s flying in next week for a visit."]', '["Report the client''s request.","Key words: discount, one sixty-five"]', '["고객의 요청을 보고하세요.","핵심 단어: discount, one sixty-five"]', 'maya', 'Figured. That''s about eight percent. What do you think we should do?', '그럴 줄 알았어요. 8% 정도네요. 어떻게 하면 좋겠어요?');

/* part 8/9: d10_approval#2 d10_approval#3 d10_handoff#1 d10_handoff#2 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d10_approval', 2, 'maya', 'You think a smaller discount could work if Summit commits to more.', '서밋이 더 약속한다면 작은 할인은 괜찮다고 생각합니다.', 'I want to hear your take first.', 'Suggest five percent off in exchange for a one-year support contract.', '1년 지원 계약을 조건으로 5% 할인을 제안하세요.', '[{"all":["support"],"any":["year","contract","commit"]},{"all":["in exchange"]},{"all":["if they"],"any":["sign","commit","agree"]}]', 'What if we offer five percent off in exchange for a one-year support contract?', '["We should give them whatever they want.","Let''s cancel the whole project.","What if we order pizza for the team?"]', '["Give something only if you get something back.","Key words: in exchange for, one-year support contract"]', '["무언가를 받는 조건으로만 양보하세요.","핵심 단어: in exchange for, one-year support contract"]', 'maya', 'I like that. It keeps the relationship going. Five percent is my limit, though.', '좋네요. 관계도 계속 이어지고요. 그래도 5%가 한계예요.'),
  ('d10_approval', 3, 'maya', 'Maya wants the final wording checked before anything is sent.', '마야는 무엇을 보내기 전에 최종 문구를 검토받길 원합니다.', 'And don''t put anything in writing until legal reviews it, okay?', 'Confirm you understand: five percent max, and nothing in writing until legal signs off.', '이해했다고 확인하세요. 최대 5%, 법무팀 승인 전에는 서면으로 아무것도 보내지 않습니다.', '[{"all":["five percent"]},{"all":["5"]},{"all":["legal"],"any":["review","reviews","signs off","sign off","writing","approves"]}]', 'Got it. Five percent max, and nothing in writing until legal signs off.', '["Got it. I''ll email Greg the contract right now.","Sure. I''ll take the rest of the day off.","Got it. Ten percent is our final offer."]', '["Repeat the limit and the condition.","Key words: five percent max, legal signs off"]', '["한도와 조건을 다시 말하세요.","핵심 단어: five percent max, legal signs off"]', 'maya', 'Perfect. You''re a natural at this. Go get ''em in Ridgeport.', '완벽해요. 이런 데 타고났네요. 리지포트에서 잘하고 와요.'),
  ('d10_handoff', 1, 'derek', 'Your flight is tomorrow morning. You stop by Derek''s desk.', '비행기는 내일 아침입니다. 데릭 자리에 들릅니다.', 'So you''re off to Ridgeport, huh? What do you need from me?', 'Ask if he can cover for you on the inventory API while you are away.', '출장 가 있는 동안 재고 API를 대신 봐 줄 수 있는지 물어보세요.', '[{"all":["cover"]},{"all":["keep an eye"]},{"all":["take over"]},{"all":["while"],"any":["away","gone","out"]}]', 'Could you cover for me on the inventory API while I''m away?', '["Could you water my plants this weekend?","Can you book my hotel room for me?","Would you like to come to Ridgeport with me?"]', '["Ask him to handle your work for two days.","Key words: cover for me, while I''m away"]', '["이틀 동안 일을 맡아 달라고 하세요.","핵심 단어: cover for me, while I''m away"]', 'derek', 'Sure thing. Where are things at right now?', '물론이죠. 지금 어디까지 됐어요?'),
  ('d10_handoff', 2, 'derek', 'The API is merged, but some store IDs come back empty.', 'API는 병합됐지만 일부 매장 ID가 빈 값으로 옵니다.', 'Where are things at?', 'Give a status update: the code is merged, but there is one open bug with store IDs.', '상황을 알려 주세요. 코드는 병합됐고 매장 ID 관련 버그가 하나 남아 있습니다.', '[{"all":["bug"]},{"all":["merged"]},{"all":["open","issue"]}]', 'The code is merged, but there''s one open bug. Some store IDs come back empty.', '["Everything is perfect. There''s nothing left to do.","The coffee machine on our floor is broken again.","The meeting room is booked all afternoon."]', '["Say what is done and what is still open.","Key words: merged, one open bug"]', '["끝난 것과 남은 것을 말하세요.","핵심 단어: merged, one open bug"]', 'derek', 'Okay, I''ll keep an eye on it. Did you write it up anywhere?', '알겠어요, 지켜볼게요. 어디 정리해 뒀어요?');

/* part 9/9: d10_handoff#3 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d10_handoff', 3, 'derek', 'You documented everything in the ticket.', '모든 걸 티켓에 적어 두었습니다.', 'Did you write it up anywhere?', 'Say the details are in the ticket, and you will be reachable on chat if anything comes up.', '자세한 건 티켓에 있고, 무슨 일이 생기면 채팅으로 연락이 된다고 말하세요.', '[{"all":["ticket"]},{"all":["reachable"]},{"all":["comes up"]},{"all":["chat"]},{"all":["message","me"]}]', 'Yeah, it''s all in the ticket. And I''ll be reachable on chat if anything comes up.', '["No, I didn''t write anything down, sorry.","I''ll be completely offline until Monday.","My boarding pass is on my phone."]', '["Say where the notes are and how to reach you.","Key words: in the ticket, reachable, if anything comes up"]', '["메모가 어디 있고 어떻게 연락할 수 있는지 말하세요.","핵심 단어: in the ticket, reachable, if anything comes up"]', 'derek', 'Perfect. Safe travels, and don''t let Greg push you around.', '완벽해요. 잘 다녀오고, 그렉한테 휘둘리지 마요.');

/* part 1/3: d8_standup.on_my_plate d8_standup.wrapped_up d8_standup.blocked_on d8_standup.thats_on_me d8_standup.ping d8_standup.thats_a_wrap d8_kickoff.make_sure d8_kickoff.walk_me_through d8_kickoff.flying_blind d8_kickoff.a_lot_riding d8_kickoff.loop_in d8_kickoff.flag d8_kickoff.recap_email d8_trip_approval.would_it_be_okay d8_trip_approval.face_to_face d8_trip_approval.stick_to_policy d8_trip_approval.per_diem d8_trip_approval.go_through d8_trip_approval.inside_out d9_scope.cant_commit ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d8_standup.on_my_plate', 'd8_standup', 'What''s on your plate today?', '오늘 할 일이 뭐예요?', 'On your plate means the work you have to do.', 'on your plate는 해야 할 일을 뜻합니다.', 'meeting'),
  ('d8_standup.wrapped_up', 'd8_standup', 'I wrapped up the login page.', '로그인 페이지를 마무리했어요.', 'Wrap up = finish.', 'wrap up은 끝내다라는 뜻입니다.', 'meeting'),
  ('d8_standup.blocked_on', 'd8_standup', 'I''m blocked on one thing.', '한 가지 때문에 막혀 있어요.', 'A blocker is anything that stops your progress. Standups always ask about them.', 'blocker는 진행을 막는 것입니다. 스탠드업에서 늘 묻습니다.', 'meeting'),
  ('d8_standup.thats_on_me', 'd8_standup', 'That''s on me.', '그건 제 잘못(책임)이에요.', 'A casual way to take responsibility.', '책임을 인정하는 가벼운 표현입니다.', 'office'),
  ('d8_standup.ping', 'd8_standup', 'I''ll ping Sam right after this.', '끝나자마자 샘에게 연락할게요.', 'Ping = send someone a quick message.', 'ping은 짧은 메시지를 보낸다는 뜻입니다.', 'office'),
  ('d8_standup.thats_a_wrap', 'd8_standup', 'That''s a wrap.', '이걸로 마칠게요.', 'Said to end a meeting or a job. It comes from film sets.', '회의나 일을 끝낼 때 씁니다. 영화 촬영장에서 온 말입니다.', 'meeting'),
  ('d8_kickoff.make_sure', 'd8_kickoff', 'Just to make sure I understand, …', '제가 제대로 이해했는지 확인하자면…', 'Restate the request in your own words. Clients love it because it prevents mistakes.', '요청을 자기 말로 다시 말하는 것입니다. 오해를 막아 줘서 고객들이 좋아합니다.', 'meeting'),
  ('d8_kickoff.walk_me_through', 'd8_kickoff', 'Could you walk me through how it works?', '어떻게 돌아가는지 차근차근 설명해 주시겠어요?', 'Walk someone through = explain step by step.', 'walk someone through는 단계별로 설명한다는 뜻입니다.', 'meeting'),
  ('d8_kickoff.flying_blind', 'd8_kickoff', 'We''re flying blind.', '정보 없이 감으로 하고 있어요.', 'Working without the information you need.', '필요한 정보 없이 일한다는 뜻입니다.', 'meeting'),
  ('d8_kickoff.a_lot_riding', 'd8_kickoff', 'We''ve got a lot riding on this.', '여기에 걸린 게 많아요.', 'Something important depends on the result.', '결과에 중요한 것이 달려 있다는 뜻입니다.', 'client'),
  ('d8_kickoff.loop_in', 'd8_kickoff', 'I''ll loop in our IT folks.', '우리 IT 담당자들을 참여시킬게요.', 'Loop someone in = add them to the conversation or email thread.', 'loop someone in은 대화나 메일에 누군가를 포함시킨다는 뜻입니다.', 'meeting'),
  ('d8_kickoff.flag', 'd8_kickoff', 'I want to flag something.', '짚고 넘어갈 게 있어요.', 'Flag = point out a possible problem early.', 'flag는 문제가 될 만한 것을 미리 알린다는 뜻입니다.', 'meeting'),
  ('d8_kickoff.recap_email', 'd8_kickoff', 'I''ll send a recap email.', '요약 메일을 보낼게요.', 'A short email after a meeting listing decisions and next steps.', '회의 후 결정 사항과 다음 단계를 정리한 짧은 메일입니다.', 'meeting'),
  ('d8_trip_approval.would_it_be_okay', 'd8_trip_approval', 'Would it be okay if I went to Ridgeport?', '리지포트에 가도 괜찮을까요?', 'A polite request. The past tense (went) makes it softer.', '정중한 부탁입니다. 과거형(went)을 쓰면 더 부드럽습니다.', 'request'),
  ('d8_trip_approval.face_to_face', 'd8_trip_approval', 'It''s a good chance to meet face to face.', '직접 만날 좋은 기회예요.', 'Face to face = in person, not on a call.', 'face to face는 통화가 아니라 직접 만난다는 뜻입니다.', 'travel'),
  ('d8_trip_approval.stick_to_policy', 'd8_trip_approval', 'Just stick to the travel policy.', '출장 규정만 지켜요.', 'Stick to = follow and not go beyond.', 'stick to는 벗어나지 않고 따른다는 뜻입니다.', 'travel'),
  ('d8_trip_approval.per_diem', 'd8_trip_approval', 'What''s the per diem for meals?', '식비 일일 한도가 얼마예요?', 'Per diem (Latin: per day) = a daily allowance for meals on a trip.', 'per diem(라틴어로 하루당)은 출장 중 하루 식비 한도입니다.', 'travel'),
  ('d8_trip_approval.go_through', 'd8_trip_approval', 'Go through Tom.', '톰을 통해서 처리하세요.', 'Go through someone = use them as the official route.', 'go through someone은 그 사람을 공식 창구로 삼는다는 뜻입니다.', 'office'),
  ('d8_trip_approval.inside_out', 'd8_trip_approval', 'He knows the policy inside out.', '그는 규정을 훤히 알아요.', 'Know something inside out = know it completely.', 'know something inside out은 완전히 안다는 뜻입니다.', 'office'),
  ('d9_scope.cant_commit', 'd9_scope', 'We can''t commit to that date.', '그 날짜는 약속드릴 수 없어요.', 'Firm but polite. Better than saying yes and missing the deadline.', '단호하지만 정중합니다. 약속하고 못 지키는 것보다 낫습니다.', 'negotiation');

/* part 2/3: d9_scope.realistically d9_scope.phased_it d9_scope.sell_to_board d9_scope.trade_off d9_scope.to_confirm d9_scope.straight_with_me d9_travel_booking.fly_out d9_travel_booking.nonstop d9_travel_booking.aisle_or_window d9_travel_booking.under_the_cap d9_travel_booking.walking_distance d9_travel_booking.on_you d9_travel_booking.reimbursable d9_travel_booking.itinerary d9_code_review.take_a_look d9_code_review.mind_splitting d9_code_review.good_point d9_code_review.one_small_thing d9_code_review.nice_catch d9_code_review.my_treat d9_code_review.swing_by d10_contract_terms.outside_budget ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d9_scope.realistically', 'd9_scope', 'What can you realistically deliver?', '현실적으로 무엇을 납품할 수 있나요?', 'Deliver = finish and hand over work.', 'deliver는 일을 끝내 넘겨준다는 뜻입니다.', 'negotiation'),
  ('d9_scope.phased_it', 'd9_scope', 'What if we phased it?', '단계별로 나누면 어떨까요?', 'What if we…? (past tense) is a soft way to propose an idea.', 'What if we…?(과거형)는 아이디어를 부드럽게 제안하는 방법입니다.', 'negotiation'),
  ('d9_scope.sell_to_board', 'd9_scope', 'I could sell that to the board.', '그거면 이사회를 설득할 수 있겠어요.', 'Sell an idea to someone = convince them.', 'sell an idea to someone은 설득한다는 뜻입니다.', 'negotiation'),
  ('d9_scope.trade_off', 'd9_scope', 'That''s the trade-off.', '그게 대가(득실)예요.', 'A trade-off: you get one thing by giving up another.', 'trade-off는 하나를 얻으려고 다른 것을 포기하는 것입니다.', 'negotiation'),
  ('d9_scope.to_confirm', 'd9_scope', 'So to confirm, …', '확인하자면…', 'Use it to close a discussion and make the agreement clear.', '논의를 마무리하며 합의를 분명히 할 때 씁니다.', 'meeting'),
  ('d9_scope.straight_with_me', 'd9_scope', 'Thanks for being straight with me.', '솔직하게 말해 줘서 고마워요.', 'Be straight with someone = be honest.', 'be straight with someone은 솔직하다는 뜻입니다.', 'negotiation'),
  ('d9_travel_booking.fly_out', 'd9_travel_booking', 'I need to fly out Thursday morning.', '목요일 아침에 출발해야 해요.', 'Fly out = leave by plane. Fly back / come back = return.', 'fly out은 비행기로 떠나다, fly back은 돌아오다입니다.', 'travel'),
  ('d9_travel_booking.nonstop', 'd9_travel_booking', 'It''s a nonstop flight.', '직항이에요.', 'Nonstop = no stops. A connecting flight means you change planes.', 'nonstop은 경유 없음, connecting flight는 갈아타는 비행편입니다.', 'travel'),
  ('d9_travel_booking.aisle_or_window', 'd9_travel_booking', 'Aisle or window?', '통로석이요, 창가석이요?', 'Aisle rhymes with mile. The s is silent.', 'aisle은 mile과 운이 맞고 s는 발음하지 않습니다.', 'travel'),
  ('d9_travel_booking.under_the_cap', 'd9_travel_booking', 'That''s under the cap.', '한도 이내예요.', 'Cap = the maximum amount allowed.', 'cap은 허용되는 최대 금액입니다.', 'travel'),
  ('d9_travel_booking.walking_distance', 'd9_travel_booking', 'Is it within walking distance?', '걸어갈 수 있는 거리예요?', 'A common question about hotels and restaurants.', '호텔이나 식당에 대해 흔히 묻는 질문입니다.', 'hotel'),
  ('d9_travel_booking.on_you', 'd9_travel_booking', 'Ground transportation is on you.', '현지 교통비는 본인이 먼저 내요.', 'Something is on you = you pay for it (here, and claim it back later).', 'something is on you는 당신이 낸다는 뜻입니다(여기서는 나중에 청구).', 'travel'),
  ('d9_travel_booking.reimbursable', 'd9_travel_booking', 'It''s reimbursable.', '나중에 돌려받을 수 있어요.', 'Reimburse = pay back money you spent for work.', 'reimburse는 업무로 쓴 돈을 돌려준다는 뜻입니다.', 'travel'),
  ('d9_travel_booking.itinerary', 'd9_travel_booking', 'Here''s your itinerary.', '여기 여행 일정표예요.', 'Itinerary = your flight, hotel and schedule in one document.', 'itinerary는 항공, 호텔, 일정을 담은 문서입니다.', 'travel'),
  ('d9_code_review.take_a_look', 'd9_code_review', 'Could you take a look at my pull request?', '제 풀 리퀘스트 좀 봐 줄래요?', 'Take a look = check or review something quickly.', 'take a look은 가볍게 확인하거나 검토한다는 뜻입니다.', 'office'),
  ('d9_code_review.mind_splitting', 'd9_code_review', 'Mind splitting it up?', '나눠 줄래요?', 'Mind + -ing? is a friendly request. Answer "Not at all" or "Sure".', 'Mind + -ing?는 친근한 부탁입니다. Not at all이나 Sure로 답합니다.', 'office'),
  ('d9_code_review.good_point', 'd9_code_review', 'Good point.', '좋은 지적이에요.', 'Accept feedback without getting defensive.', '방어적이지 않게 피드백을 받아들이는 말입니다.', 'office'),
  ('d9_code_review.one_small_thing', 'd9_code_review', 'One small thing: …', '사소한 거 하나만요.', 'Softens feedback so it doesn''t sound like criticism.', '피드백이 비판처럼 들리지 않게 부드럽게 합니다.', 'office'),
  ('d9_code_review.nice_catch', 'd9_code_review', 'Nice catch.', '잘 찾았네요.', 'Said when someone spots a mistake.', '누군가 실수를 찾아냈을 때 하는 말입니다.', 'office'),
  ('d9_code_review.my_treat', 'd9_code_review', 'My treat.', '제가 살게요.', 'I will pay for you.', '내가 계산하겠다는 뜻입니다.', 'small-talk'),
  ('d9_code_review.swing_by', 'd9_code_review', 'I''ll swing by your desk.', '자리로 들를게요.', 'Swing by = visit briefly.', 'swing by는 잠깐 들른다는 뜻입니다.', 'office'),
  ('d10_contract_terms.outside_budget', 'd10_contract_terms', 'That''s a bit outside our budget.', '예산을 조금 벗어나요.', 'A polite way to say the price is too high.', '가격이 너무 높다는 것을 정중하게 말하는 방법입니다.', 'negotiation');

/* part 3/3: d10_contract_terms.price_includes d10_contract_terms.meet_halfway d10_contract_terms.run_it_by d10_contract_terms.get_back d10_contract_terms.net_30 d10_contract_terms.can_live_with d10_contract_terms.sla d10_approval.sign_off d10_approval.bring_it_down d10_approval.your_take d10_approval.in_exchange d10_approval.my_limit d10_approval.in_writing d10_approval.a_natural d10_handoff.cover_for_me d10_handoff.where_things_are d10_handoff.keep_an_eye d10_handoff.write_it_up d10_handoff.if_anything_comes_up d10_handoff.safe_travels d10_handoff.fall_through_cracks ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d10_contract_terms.price_includes', 'd10_contract_terms', 'Keep in mind the price includes support.', '가격에 지원이 포함되어 있다는 걸 기억해 주세요.', 'Talk about value before you give a discount.', '할인하기 전에 가치를 먼저 말하세요.', 'negotiation'),
  ('d10_contract_terms.meet_halfway', 'd10_contract_terms', 'Can you meet us halfway?', '중간에서 합의할 수 있을까요?', 'Meet halfway / meet in the middle = both sides give up a little.', 'meet halfway, meet in the middle은 양쪽이 조금씩 양보한다는 뜻입니다.', 'negotiation'),
  ('d10_contract_terms.run_it_by', 'd10_contract_terms', 'Let me run it by my manager.', '매니저에게 확인해 볼게요.', 'Run something by someone = ask for their opinion or approval.', 'run something by someone은 의견이나 승인을 구한다는 뜻입니다.', 'negotiation'),
  ('d10_contract_terms.get_back', 'd10_contract_terms', 'I''ll get back to you.', '다시 연락드릴게요.', 'A promise to answer later.', '나중에 답하겠다는 약속입니다.', 'negotiation'),
  ('d10_contract_terms.net_30', 'd10_contract_terms', 'Net 30', '송장 발행 후 30일 이내 지급', 'Payment terms: the client pays within 30 days of the invoice. Net 45, Net 60 work the same way.', '지급 조건: 송장 후 30일 안에 지급. Net 45, Net 60도 같은 방식입니다.', 'contract'),
  ('d10_contract_terms.can_live_with', 'd10_contract_terms', 'I can live with that.', '그 정도면 받아들일 수 있어요.', 'Not perfect, but acceptable.', '완벽하진 않지만 받아들일 만하다는 뜻입니다.', 'negotiation'),
  ('d10_contract_terms.sla', 'd10_contract_terms', 'service level agreement (SLA)', '서비스 수준 협약', 'The part of a contract that promises uptime and response times.', '가동률과 대응 시간을 약속하는 계약 조항입니다.', 'contract'),
  ('d10_approval.sign_off', 'd10_approval', 'I need your sign-off.', '승인이 필요해요.', 'Sign-off (noun) = approval. Sign off on something (verb) = approve it.', 'sign-off(명사)는 승인, sign off on(동사)은 승인하다입니다.', 'negotiation'),
  ('d10_approval.bring_it_down', 'd10_approval', 'He wants to bring it down to one sixty-five.', '그는 16만 5천으로 낮추고 싶어 해요.', 'In business, people often drop the word thousand: one sixty-five = $165,000.', '비즈니스에서는 thousand를 자주 생략합니다. one sixty-five = 16만 5천 달러.', 'negotiation'),
  ('d10_approval.your_take', 'd10_approval', 'I want to hear your take.', '당신 생각을 듣고 싶어요.', 'Your take = your opinion.', 'your take는 당신의 의견입니다.', 'meeting'),
  ('d10_approval.in_exchange', 'd10_approval', 'Five percent off in exchange for a one-year contract.', '1년 계약을 조건으로 5% 할인.', 'Never give a discount for nothing. Ask for something back.', '공짜로 할인하지 말고 대가를 요구하세요.', 'negotiation'),
  ('d10_approval.my_limit', 'd10_approval', 'Five percent is my limit.', '5%가 제 한계예요.', 'The most someone can agree to.', '동의할 수 있는 최대치입니다.', 'negotiation'),
  ('d10_approval.in_writing', 'd10_approval', 'Don''t put anything in writing yet.', '아직 아무것도 서면으로 남기지 마세요.', 'Written offers can become binding. Check with legal first.', '서면 제안은 구속력이 생길 수 있어 먼저 법무팀에 확인합니다.', 'contract'),
  ('d10_approval.a_natural', 'd10_approval', 'You''re a natural.', '타고났네요.', 'A compliment: you are naturally good at it.', '원래 잘한다는 칭찬입니다.', 'office'),
  ('d10_handoff.cover_for_me', 'd10_handoff', 'Could you cover for me while I''m away?', '제가 없는 동안 제 일 좀 봐 줄래요?', 'Cover for someone = do their work while they are out.', 'cover for someone은 자리를 비운 사람의 일을 대신한다는 뜻입니다.', 'office'),
  ('d10_handoff.where_things_are', 'd10_handoff', 'Where are things at?', '진행 상황이 어때요?', 'A casual way to ask for a status update.', '진행 상황을 묻는 가벼운 표현입니다.', 'office'),
  ('d10_handoff.keep_an_eye', 'd10_handoff', 'I''ll keep an eye on it.', '지켜볼게요.', 'Watch something to make sure nothing goes wrong.', '문제가 없는지 지켜본다는 뜻입니다.', 'office'),
  ('d10_handoff.write_it_up', 'd10_handoff', 'Did you write it up?', '정리해 뒀어요?', 'Write up = document something.', 'write up은 문서로 정리한다는 뜻입니다.', 'office'),
  ('d10_handoff.if_anything_comes_up', 'd10_handoff', 'Call me if anything comes up.', '무슨 일 생기면 연락 주세요.', 'Come up = happen unexpectedly.', 'come up은 뜻밖에 생기다라는 뜻입니다.', 'office'),
  ('d10_handoff.safe_travels', 'd10_handoff', 'Safe travels!', '조심히 다녀와요!', 'A common goodbye to someone taking a trip.', '여행 떠나는 사람에게 하는 인사입니다.', 'travel'),
  ('d10_handoff.fall_through_cracks', 'd10_handoff', 'Nothing falls through the cracks.', '빠뜨리는 일이 없어요.', 'Fall through the cracks = get forgotten by accident.', 'fall through the cracks는 실수로 누락된다는 뜻입니다.', 'office');
