-- Sim Office seed (agent D): business trip to Ridgeport, days 11-12: airport, hotel, client visit, dinner, signing, flight home
-- Generated from structured data; push with: node tools/dolt.mjs push <this file>
-- Statements are split at a semicolon at the end of a line. Each statement is kept under ~11k URL-encoded characters (DoltHub limit).
/* part 1/1: d11_checkin d11_security d11_gate d11_hotel_checkin d11_client_visit d11_dinner d12_signing d12_checkout d12_flight_home ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO episodes (id, title, title_ko, place, npc, day_from, day_to, time_from, time_to, requires, summary, summary_ko, reward, energy, sort, tags) VALUES
  ('d11_checkin', 'Checking in for your flight', '탑승 수속', 'airport_checkin', 'amy', 11, 11, '06:30', '10:00', 'd9_travel_booking', 'Check in at the Crestline Air counter: show your ID, check a bag, and ask about the flight.', '크레스트라인 항공 카운터에서 탑승 수속을 합니다. 신분증을 보여 주고, 짐을 부치고, 항공편을 확인하세요.', 0, 0, 1110, 'travel,airport,trip'),
  ('d11_security', 'Going through security', '보안 검색대 통과', 'airport_security', 'lee', 11, 11, '06:30', '10:30', 'd11_checkin', 'Get through the TSA checkpoint: boarding pass, bins, shoes, and a forgotten water bottle.', 'TSA 보안 검색대를 통과하세요. 탑승권, 바구니, 신발, 그리고 깜빡한 물병.', 0, 0, 1120, 'travel,airport,security,trip'),
  ('d11_gate', 'A delay at the gate', '게이트에서 지연 안내', 'airport_gate', 'amy', 11, 11, '06:30', '11:00', 'd11_security', 'Your flight is delayed. Find out the new time, make sure you will make your meeting, and board.', '비행기가 지연됩니다. 새 출발 시각을 알아보고, 회의에 늦지 않을지 확인하고, 탑승하세요.', 0, 0, 1130, 'travel,airport,delay,trip'),
  ('d11_hotel_checkin', 'Checking in at the hotel', '호텔 체크인', 'hotel_desk', 'kelly', 11, 11, '09:00', '22:00', 'd11_gate', 'Check in at the Pinecrest Hotel in Ridgeport: early check-in, incidentals, breakfast and a late checkout.', '리지포트의 파인크레스트 호텔에 체크인합니다. 이른 체크인, 부대비용 보증금, 조식, 늦은 체크아웃.', 0, 0, 1140, 'travel,hotel,trip'),
  ('d11_client_visit', 'On-site at Summit Retail', '서밋 리테일 방문', 'client_meeting', 'greg', 11, 11, '11:00', '18:30', 'd11_hotel_checkin', 'Meet Greg in person and go through the contract draft. Push back on one clause and ask about code ownership.', '그렉을 직접 만나 계약서 초안을 검토합니다. 한 조항에 이의를 제기하고 코드 소유권을 물어보세요.', 0, 0, 1150, 'client,contract,negotiation,trip'),
  ('d11_dinner', 'Dinner with the client', '고객과 저녁 식사', 'hotel_restaurant', 'greg', 11, 11, '17:30', '22:30', 'd11_client_visit', 'Have dinner with Greg at the hotel restaurant: dietary needs, ordering, small talk, and picking up the check.', '호텔 레스토랑에서 그렉과 저녁을 먹습니다. 식이 제한, 주문, 가벼운 대화, 그리고 계산.', 0, 30, 1160, 'client,restaurant,small-talk,trip'),
  ('d12_signing', 'Signing the contract', '계약 서명', 'client_meeting', 'greg', 12, 12, '08:30', '13:00', 'd11_client_visit', 'Legal approved the final terms. Confirm the deal, sign it, and agree on the next steps. Lakeside Labs pays you a deal bonus.', '법무팀이 최종 조건을 승인했습니다. 합의를 확인하고 서명한 뒤 다음 단계를 정하세요. 레이크사이드 랩스가 계약 보너스를 줍니다.', 300, 0, 1210, 'client,contract,trip'),
  ('d12_checkout', 'Checking out of the hotel', '호텔 체크아웃', 'hotel_desk', 'kelly', 12, 12, '07:00', '14:00', 'd11_hotel_checkin', 'Check out, fix a wrong charge on the bill, get an itemized receipt, and find the airport shuttle.', '체크아웃하며 청구서의 잘못된 요금을 바로잡고, 항목별 영수증을 받고, 공항 셔틀을 찾으세요.', 0, 0, 1220, 'travel,hotel,trip'),
  ('d12_flight_home', 'An overbooked flight home', '초과 예약된 귀국편', 'airport_gate', 'amy', 12, 12, '11:00', '21:00', 'd12_checkout', 'Your flight home is overbooked. Volunteer for a later flight, but negotiate a better voucher first.', '귀국편이 초과 예약됐습니다. 나중 비행기로 양보하되, 먼저 더 좋은 바우처를 협상하세요.', 0, 0, 1230, 'travel,airport,negotiation,trip');

/* part 1/8: d11_checkin#1 d11_checkin#2 d11_checkin#3 d11_checkin#4 d11_security#1 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d11_checkin', 1, 'amy', 'You arrive at the Crestline Air counter with a backpack and a small suitcase.', '배낭과 작은 여행 가방을 들고 크레스트라인 항공 카운터에 도착합니다.', 'Good morning! Where are you flying today?', 'Say you are flying to Ridgeport on the nine-thirty flight.', '9시 30분 비행기로 리지포트에 간다고 말하세요.', '[{"all":["ridgeport"]},{"all":["nine thirty"]},{"all":["9 30"]},{"all":["930"]}]', 'Good morning. I''m flying to Ridgeport on the nine-thirty flight.', '["Good morning. I''d like a table for one, please.","I''m just here to pick up a friend.","Where is the nearest coffee shop?"]', '["Say where you are going and when.","Key words: flying to Ridgeport, nine-thirty"]', '["어디로, 몇 시에 가는지 말하세요.","핵심 단어: flying to Ridgeport, nine-thirty"]', 'amy', 'Great. Can I see a photo ID, please? And are you checking any bags today?', '좋아요. 사진 있는 신분증 보여 주시겠어요? 오늘 부칠 짐 있으세요?'),
  ('d11_checkin', 2, 'amy', 'Your suitcase is too big for the overhead bin. The backpack has your laptop.', '여행 가방은 기내 선반에 들어가기엔 큽니다. 배낭에는 노트북이 있습니다.', 'Photo ID, please. Any bags to check?', 'Hand over your ID and say you are checking one bag. The backpack is your carry-on.', '신분증을 건네고 가방 하나를 부친다고 하세요. 배낭은 기내 반입 가방입니다.', '[{"all":["one bag"]},{"all":["check","one"]},{"all":["checking","one"]},{"all":["one","suitcase"]},{"all":["carry on"]}]', 'Here''s my driver''s license. I''m checking one bag, and the backpack is my carry-on.', '["I''m not flying today, just looking around.","Could you see if my room is ready?","I don''t have any ID with me."]', '["Say how many bags you are checking.","Key words: checking one bag, carry-on"]', '["부칠 가방이 몇 개인지 말하세요.","핵심 단어: checking one bag, carry-on"]', 'amy', 'Perfect. The first checked bag is thirty-five dollars. How would you like to pay?', '좋아요. 첫 번째 위탁 수하물은 35달러예요. 어떻게 결제하시겠어요?'),
  ('d11_checkin', 3, 'amy', 'Tom said the bag fee is reimbursable.', '톰이 수하물 요금은 환급된다고 했습니다.', 'That''s thirty-five for the bag. Card or cash?', 'Say you will pay with your company card and ask for a receipt.', '법인 카드로 내겠다고 하고 영수증을 달라고 하세요.', '[{"all":["receipt"]},{"all":["company card"]},{"all":["corporate card"]}]', 'I''ll put it on my company card. Could I get a receipt, please?', '["Can I pay you back next week?","I''d like to upgrade to first class, please.","Could I get a window seat instead?"]', '["Pay, and remember your expense report.","Key words: company card, receipt"]', '["결제하고, 경비 정산을 기억하세요.","핵심 단어: company card, receipt"]', 'amy', 'Of course. The receipt will be in your email. You''re in seat 14C, on the aisle.', '그럼요. 영수증은 이메일로 갈 거예요. 좌석은 14C, 통로석이에요.'),
  ('d11_checkin', 4, 'amy', 'Amy prints your boarding pass.', '에이미가 탑승권을 출력합니다.', 'You''re in boarding group three. Boarding starts at eight-fifty at gate B12. Anything else?', 'Ask if the flight is on time.', '비행기가 제시간에 출발하는지 물어보세요.', '[{"all":["on time"]},{"all":["delayed"]},{"all":["delay"]},{"all":["on schedule"]}]', 'Thanks. Is the flight on time?', '["Thanks. Where can I buy a lottery ticket?","What time does the hotel breakfast end?","Can I bring my coffee on the plane?"]', '["Ask about delays.","Key words: on time"]', '["지연 여부를 물어보세요.","핵심 단어: on time"]', 'amy', 'As of now, yes. Keep an eye on the screens, though. Have a nice flight!', '현재로서는 네. 그래도 전광판을 잘 보세요. 즐거운 비행 되세요!'),
  ('d11_security', 1, 'lee', 'You reach the TSA checkpoint. Officer Lee holds out his hand.', 'TSA 검색대에 도착합니다. 리 요원이 손을 내밉니다.', 'Boarding pass and ID, please.', 'Hand them over and say "Here you go."', '건네면서 "Here you go."라고 말하세요.', '[{"any":["here you go","here you are","here it is","here they are","here are"]}]', 'Sure, here you go.', '["No thanks, I''m just browsing.","I left my ID at home.","Can I keep my coffee with me?"]', '["Say the phrase you use when you hand something over.","Key words: here you go"]', '["무언가를 건넬 때 쓰는 말을 하세요.","핵심 단어: here you go"]', 'lee', 'Thanks. Laptops out in a separate bin. Empty your pockets, please.', '감사합니다. 노트북은 따로 바구니에 꺼내 주세요. 주머니도 비워 주세요.');

/* part 2/8: d11_security#2 d11_security#3 d11_security#4 d11_gate#1 d11_gate#2 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d11_security', 2, 'lee', 'You put your laptop in a bin. You are not sure about your shoes.', '노트북을 바구니에 넣습니다. 신발은 어떻게 해야 할지 모르겠습니다.', 'Laptops out, pockets empty. Next!', 'Ask if you need to take your shoes off too.', '신발도 벗어야 하는지 물어보세요.', '[{"all":["shoes"]},{"all":["belt"]},{"all":["jacket"]}]', 'Do I need to take my shoes off too?', '["Do I need a coat in Ridgeport?","Can I bring my laptop to dinner?","Do I need to pay for the bin?"]', '["Ask about your shoes.","Key words: shoes off"]', '["신발에 대해 물어보세요.","핵심 단어: shoes off"]', 'lee', 'Yes, shoes off, unless you have TSA PreCheck. Then you''d use the other line.', '네, 신발 벗으세요. TSA 프리체크가 있으면 다른 줄로 가면 되고요.'),
  ('d11_security', 3, 'lee', 'The scanner beeps. You forgot a full water bottle in your bag.', '검색기가 삑 소리를 냅니다. 가방에 물이 가득 든 병을 깜빡했습니다.', 'Is this your bag? There''s a water bottle in here. It''s over the limit.', 'Apologize, say you forgot about it, and tell him he can throw it away.', '사과하고 깜빡했다고 말한 뒤 버려도 된다고 하세요.', '[{"all":["sorry"]},{"all":["forgot"]},{"all":["throw","away"]},{"all":["toss","it"]},{"all":["my bad"]}]', 'Oh, sorry, I totally forgot about it. You can throw it away.', '["That''s not mine. I''ve never seen that bag.","Could I get a refill on that?","It''s just water, so you should let me keep it."]', '["Apologize and let it go.","Key words: sorry, forgot, throw it away"]', '["사과하고 포기하세요.","핵심 단어: sorry, forgot, throw it away"]', 'lee', 'No problem. Next time, empty it before security and fill it up at the gate. You''re all set.', '괜찮아요. 다음엔 검색 전에 비우고 게이트에서 채우세요. 다 됐습니다.'),
  ('d11_security', 4, 'lee', 'You put your shoes back on and grab your laptop.', '신발을 다시 신고 노트북을 챙깁니다.', 'You''re all set. Have a good flight.', 'Ask how to get to gate B12.', 'B12 게이트로 어떻게 가는지 물어보세요.', '[{"all":["gate"]},{"all":["b12"]},{"all":["b 12"]}]', 'Thanks. Which way is gate B12?', '["Thanks. Which way is the hotel pool?","Where can I buy a return ticket?","Could you watch my bag for a minute?"]', '["Ask for directions to your gate.","Key words: which way, gate B12"]', '["게이트로 가는 길을 물어보세요.","핵심 단어: which way, gate B12"]', 'lee', 'Down the hall, on your left. About a five-minute walk.', '복도 따라 왼쪽이에요. 걸어서 5분쯤이요.'),
  ('d11_gate', 1, 'amy', 'At gate B12, the screen changes to DELAYED. Amy is now working the gate desk.', 'B12 게이트 전광판이 지연(DELAYED)으로 바뀝니다. 에이미가 이제 게이트 데스크를 맡고 있습니다.', 'Attention, passengers on flight 482 to Ridgeport. We have a thirty-minute delay due to a late incoming aircraft.', 'Go to the desk and ask what the new departure time is.', '데스크로 가서 새 출발 시각이 언제인지 물어보세요.', '[{"all":["new","time"]},{"all":["departure","time"]},{"all":["when"],"any":["leave","depart","departing","board","boarding","take off"]},{"all":["what time"]}]', 'Excuse me, what''s the new departure time?', '["Excuse me, where is baggage claim?","Excuse me, can I get a hotel voucher?","Excuse me, is this seat taken?"]', '["Ask when the plane will leave now.","Key words: new departure time"]', '["이제 언제 출발하는지 물어보세요.","핵심 단어: new departure time"]', 'amy', 'We''re now looking at ten o''clock, with boarding at nine-thirty.', '이제 10시 출발, 탑승은 9시 30분 예정이에요.'),
  ('d11_gate', 2, 'amy', 'Your meeting at Summit Retail is at two.', '서밋 리테일과의 회의는 2시입니다.', 'Do you have a connecting flight?', 'Say it is a nonstop, but you have a meeting at two. Ask if you will still make it.', '직항이지만 2시에 회의가 있다고 하고, 늦지 않을지 물어보세요.', '[{"all":["meeting"]},{"all":["make it"]},{"all":["still"],"any":["arrive","land","there"]}]', 'No, it''s nonstop. But I have a meeting at two. Will I still make it?', '["Yes, I''m connecting to Tokyo tonight.","No, I don''t want any snacks, thanks.","Can I switch to a flight next week?"]', '["Explain your plans and ask if the delay is a problem.","Key words: meeting at two, will I still make it"]', '["일정을 설명하고 지연이 문제가 될지 물어보세요.","핵심 단어: meeting at two, will I still make it"]', 'amy', 'You should land around twelve-fifteen, so you''ll have plenty of time.', '12시 15분쯤 도착하니까 시간은 충분할 거예요.');

/* part 3/8: d11_gate#3 d11_gate#4 d11_hotel_checkin#1 d11_hotel_checkin#2 d11_hotel_checkin#3 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d11_gate', 3, 'amy', 'The flight is full. Your laptop is in your backpack.', '비행기가 만석입니다. 노트북은 배낭에 있습니다.', 'The flight is full today, so we''re offering free gate checks for carry-on bags. Would you like to check yours?', 'Say no thanks. Your laptop is in there, so you would rather keep it with you.', '괜찮다고 하세요. 노트북이 들어 있어서 가지고 타는 게 낫습니다.', '[{"all":["no thanks"]},{"all":["no thank you"]},{"all":["rather","keep"]},{"all":["keep","with me"]}]', 'No thanks. My laptop is in there, so I''d rather keep it with me.', '["Sure, take my bag. I don''t need anything in it.","No, I''m not on this flight.","Yes, please upgrade me to first class."]', '["Decline politely and give a reason.","Key words: no thanks, I''d rather keep it with me"]', '["이유를 대며 정중히 거절하세요.","핵심 단어: no thanks, I''d rather keep it with me"]', 'amy', 'Totally understand. Thanks for your patience today.', '충분히 이해해요. 오늘 기다려 주셔서 감사해요.'),
  ('d11_gate', 4, 'amy', 'Boarding begins at last.', '드디어 탑승이 시작됩니다.', 'We''re now boarding group three. Group three, welcome aboard.', 'Hand her your boarding pass and thank her for keeping everyone updated.', '탑승권을 건네며 계속 안내해 줘서 고맙다고 말하세요.', '[{"any":["thank","thanks","appreciate"]}]', 'Here''s my boarding pass. Thanks for keeping us updated.', '["I''m in group one, so I should have boarded already.","Can you hold the plane while I get a coffee?","Sorry, which way is the exit?"]', '["Say thank you as you board.","Key words: thanks for keeping us updated"]', '["탑승하며 감사 인사를 하세요.","핵심 단어: thanks for keeping us updated"]', 'amy', 'My pleasure. Enjoy your flight!', '천만에요. 즐거운 비행 되세요!'),
  ('d11_hotel_checkin', 1, 'kelly', 'You arrive at the Pinecrest Hotel around lunchtime. Check-in is usually at three.', '점심때쯤 파인크레스트 호텔에 도착합니다. 체크인은 보통 3시입니다.', 'Welcome to the Pinecrest! Checking in?', 'Say you have a reservation under your name, and ask if early check-in is possible.', '당신 이름으로 예약했다고 하고, 일찍 체크인할 수 있는지 물어보세요.', '[{"all":["reservation"]},{"all":["early","check in"]},{"all":["early","checkin"]},{"all":["room","ready"]},{"all":["booking"]}]', 'Yes, I have a reservation under my name. Is early check-in possible?', '["No, I''m just here for the conference room.","I''d like to check out, please.","Can I get a table for two at seven?"]', '["Mention your reservation and ask about checking in early.","Key words: reservation under my name, early check-in"]', '["예약했다고 말하고 이른 체크인을 물어보세요.","핵심 단어: reservation under my name, early check-in"]', 'kelly', 'Let me see… You''re in luck. A room just opened up. One night, checking out Friday?', '잠시만요… 운이 좋으시네요. 방이 막 비었어요. 1박, 금요일 체크아웃 맞으시죠?'),
  ('d11_hotel_checkin', 2, 'kelly', 'The room is on the company card, but Kelly asks for another card.', '객실은 법인 카드로 결제됐는데, 켈리가 카드를 하나 더 달라고 합니다.', 'That''s right. I''ll just need a card for incidentals.', 'Ask what exactly the incidentals hold is for.', '부대비용 보증금(hold)이 정확히 무엇을 위한 것인지 물어보세요.', '[{"all":["incidentals"]},{"all":["incidental"]},{"all":["hold"],"any":["what","how much"]},{"all":["deposit"]}]', 'Sure. What exactly is the incidentals hold for?', '["Is there a gym in the hotel?","No, I''d rather pay in cash at the airport.","Can I get two extra towels?"]', '["Ask why she needs the card.","Key words: what is the hold for, incidentals"]', '["카드가 왜 필요한지 물어보세요.","핵심 단어: what is the hold for, incidentals"]', 'kelly', 'It''s fifty dollars a night for extras like room service or the minibar. It''s released when you check out.', '룸서비스나 미니바 같은 추가 비용용으로 1박에 50달러예요. 체크아웃하면 풀려요.'),
  ('d11_hotel_checkin', 3, 'kelly', 'Kelly hands you two key cards for room 612.', '켈리가 612호 키 카드 두 장을 건넵니다.', 'Here are your key cards. You''re in room 612.', 'Ask what time breakfast is served.', '아침 식사가 몇 시에 나오는지 물어보세요.', '[{"all":["breakfast"],"any":["time","when","hours","served","start","open"]}]', 'Thanks. What time is breakfast served?', '["Thanks. What time does the pool close?","Is dinner included in the price?","When is my flight home?"]', '["Ask about breakfast hours.","Key words: what time, breakfast served"]', '["조식 시간을 물어보세요.","핵심 단어: what time, breakfast served"]', 'kelly', 'Six-thirty to ten, in the restaurant off the lobby.', '6시 30분부터 10시까지, 로비 옆 레스토랑에서요.');

/* part 4/8: d11_hotel_checkin#4 d11_client_visit#1 d11_client_visit#2 d11_client_visit#3 d11_client_visit#4 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d11_hotel_checkin', 4, 'kelly', 'Your flight home on Friday is in the afternoon.', '금요일 귀국편은 오후입니다.', 'Anything else I can help you with?', 'Ask if you can get a late checkout on Friday.', '금요일에 늦게 체크아웃할 수 있는지 물어보세요.', '[{"all":["late checkout"]},{"all":["late check out"]},{"all":["check out","later"]},{"all":["checkout","later"]}]', 'Could I get a late checkout on Friday?', '["Could I get an early wake-up call on Friday?","Could you call me a taxi right now?","Could I check in on Friday instead?"]', '["Ask to leave the room later than usual.","Key words: late checkout"]', '["평소보다 늦게 방을 비워도 되는지 물어보세요.","핵심 단어: late checkout"]', 'kelly', 'I can do one p.m. at no charge. Enjoy your stay!', '오후 1시까지 무료로 해 드릴게요. 즐거운 시간 보내세요!'),
  ('d11_client_visit', 1, 'greg', 'You sign in as a visitor in Summit Retail''s lobby and get a guest badge. Greg meets you in the conference room.', '서밋 리테일 로비에서 방문자로 등록하고 방문증을 받습니다. 그렉이 회의실에서 맞이합니다.', 'Hey, you made it! Welcome to Ridgeport. How was the flight?', 'Say it was fine, apart from a short delay.', '짧은 지연 말고는 괜찮았다고 말하세요.', '[{"all":["delay"]},{"all":["delayed"]},{"all":["fine"]},{"all":["smooth"]},{"all":["not bad"]}]', 'Not bad, thanks! Just a short delay, but I made it.', '["Terrible. I''m never flying again.","I''d like to check in, please.","Thanks, I''ll take the aisle seat."]', '["Answer the small-talk question briefly.","Key words: not bad, short delay"]', '["가벼운 질문에 짧게 답하세요.","핵심 단어: not bad, short delay"]', 'greg', 'Glad to hear it. Can I get you anything before we dive in? Coffee, water?', '다행이네요. 본론 들어가기 전에 뭐 드릴까요? 커피, 물?'),
  ('d11_client_visit', 2, 'greg', 'There is a pot of coffee and some bottled water on the table.', '테이블에 커피 한 주전자와 생수가 있습니다.', 'Coffee, water?', 'Politely accept a glass of water or some coffee.', '물이나 커피를 정중히 받으세요.', '[{"any":["water","coffee"]}]', 'Water would be great, thanks.', '["I''ll have a steak, medium rare.","Can you split the check?","I''m fine. Let''s skip the meeting."]', '["Choose a drink and say thanks.","Key words: water would be great"]', '["음료를 고르고 고맙다고 하세요.","핵심 단어: water would be great"]', 'greg', 'Coming right up. Okay, let''s look at the contract draft.', '바로 드릴게요. 자, 계약서 초안을 봅시다.'),
  ('d11_client_visit', 3, 'greg', 'The draft says Summit can cancel with only seven days'' notice. That is too short for your team.', '초안에는 서밋이 7일 전 통보만으로 해지할 수 있다고 되어 있습니다. 팀에게는 너무 짧습니다.', 'Our legal team sent back a few redlines. Anything jump out at you?', 'Point out that seven days'' cancellation notice is too short, and suggest thirty days.', '7일 전 해지 통보는 너무 짧다고 지적하고 30일을 제안하세요.', '[{"any":["thirty","30"]},{"all":["cancellation"],"any":["short","longer"]},{"all":["notice"],"any":["short","longer"]}]', 'The seven-day cancellation notice is too short for us. Could we make it thirty days?', '["Everything looks perfect. No changes from us.","The coffee here is too strong for me.","Could we make the meeting shorter today?"]', '["Name the problem clause and offer a change.","Key words: cancellation notice, too short, thirty days"]', '["문제 조항을 짚고 수정안을 내세요.","핵심 단어: cancellation notice, too short, thirty days"]', 'greg', 'That''s fair. We can do thirty. Anything else on your side?', '타당하네요. 30일로 하죠. 그쪽에서 다른 건요?'),
  ('d11_client_visit', 4, 'greg', 'You want to know who owns the code after the project ends.', '프로젝트가 끝난 뒤 코드가 누구 소유인지 알고 싶습니다.', 'Anything else on your side?', 'Ask who owns the source code at the end of the project.', '프로젝트가 끝나면 소스 코드를 누가 소유하는지 물어보세요.', '[{"all":["own","code"]},{"all":["owns","code"]},{"all":["ownership"]},{"all":["intellectual property"]}]', 'Just one question: who owns the source code at the end of the project?', '["Just one question: who owns this building?","Where is the restroom?","Do you have Wi-Fi here?"]', '["Ask about ownership of the work.","Key words: who owns, source code"]', '["결과물의 소유권을 물어보세요.","핵심 단어: who owns, source code"]', 'greg', 'Summit does, once the final invoice is paid. It''s in section nine.', '최종 송장이 지급되면 서밋 소유예요. 9조에 있어요.');

/* part 5/8: d11_client_visit#5 d11_dinner#1 d11_dinner#2 d11_dinner#3 d11_dinner#4 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d11_client_visit', 5, 'greg', 'The meeting went well. Greg closes his laptop.', '회의가 잘 끝났습니다. 그렉이 노트북을 닫습니다.', 'I think we''re close. I''ll send the final version to legal tonight. Dinner at your hotel at seven?', 'Accept the dinner invitation.', '저녁 초대를 받아들이세요.', '[{"all":["sounds"]},{"all":["see you"]},{"all":["love to"]},{"all":["works"]},{"all":["great"]}]', 'Sounds great. See you at seven.', '["Sorry, I already have plans with friends.","Can we meet at the airport instead?","I don''t eat dinner, thanks."]', '["Say yes to dinner.","Key words: sounds great, see you at seven"]', '["저녁 초대에 응하세요.","핵심 단어: sounds great, see you at seven"]', 'greg', 'Great. I made a reservation at their restaurant. See you there.', '좋아요. 호텔 레스토랑에 예약해 뒀어요. 거기서 봐요.'),
  ('d11_dinner', 1, 'greg', 'You meet Greg at the hotel restaurant. The host seats you and hands you menus.', '호텔 레스토랑에서 그렉을 만납니다. 직원이 자리로 안내하고 메뉴를 건넵니다.', 'Before the server comes by, do you have any dietary restrictions? I want to make sure this place works for you.', 'Say you are allergic to peanuts, but other than that you eat everything.', '땅콩 알레르기가 있지만 그 외에는 다 먹는다고 말하세요.', '[{"all":["allergic"]},{"all":["allergy"]},{"all":["no","restrictions"]},{"all":["eat","everything"]},{"all":["vegetarian"]}]', 'Thanks for asking. I''m allergic to peanuts, but other than that I eat everything.', '["I''d like to check out tomorrow at noon.","Can I see the contract one more time?","I only eat at the hotel buffet."]', '["Mention any food you can''t eat.","Key words: allergic to, other than that"]', '["못 먹는 음식을 말하세요.","핵심 단어: allergic to, other than that"]', 'greg', 'Good to know. I''ll mention it to the server.', '알아 둘게요. 서버에게 말해 둘게요.'),
  ('d11_dinner', 2, 'greg', 'The server comes to take your order. Greg gestures for you to go first.', '서버가 주문을 받으러 옵니다. 그렉이 먼저 하라고 손짓합니다.', 'Go ahead, you first.', 'Order the grilled salmon with a side salad.', '연어 구이에 사이드 샐러드를 주문하세요.', '[{"any":["salmon","steak","fish","chicken","pasta"]}]', 'I''ll have the grilled salmon with a side salad, please.', '["I''ll have the check, please.","Could we get a table by the window?","Just the contract, please."]', '["Order a main dish and a side.","Key words: I''ll have the grilled salmon"]', '["메인 요리와 곁들임을 주문하세요.","핵심 단어: I''ll have the grilled salmon"]', 'greg', 'I''ll do the steak, medium rare. And let''s get the calamari to share.', '저는 스테이크, 미디엄 레어로요. 그리고 오징어 튀김 하나 나눠 먹죠.'),
  ('d11_dinner', 3, 'greg', 'Over dinner, the talk moves away from work.', '식사하며 대화가 일 얘기에서 벗어납니다.', 'So, enough about contracts. What do you like to do on the weekends?', 'Make small talk: say you like hiking and trying new restaurants.', '가볍게 이야기하세요. 하이킹과 새 식당 가 보는 걸 좋아한다고 하세요.', '[{"any":["hiking","hike","restaurants","cooking","reading","soccer","running","movies","games","music"]},{"any":["i like","i love","i enjoy"]}]', 'I like hiking, and I love trying new restaurants around town.', '["I prefer not to talk about my weekends.","Let''s go back to the payment terms.","I work every weekend, actually."]', '["Share a hobby or two.","Key words: I like, hiking, restaurants"]', '["취미 한두 개를 말하세요.","핵심 단어: I like, hiking, restaurants"]', 'greg', 'Oh, then you have to try the lake trail here. Great views.', '오, 그럼 여기 호수 산책로에 꼭 가 봐요. 경치가 끝내줘요.'),
  ('d11_dinner', 4, 'greg', 'The check arrives and Greg reaches for it. Maya said client dinners go on the company card.', '계산서가 오자 그렉이 손을 뻗습니다. 마야는 고객 식사는 법인 카드로 하라고 했습니다.', 'Here, let me get this.', 'Insist politely that you will get this one.', '이번엔 내가 내겠다고 정중히 고집하세요.', '[{"all":["get this one"]},{"all":["my treat"]},{"all":["i got this"]},{"all":["on us"]},{"all":["company card"]},{"all":["i will get"]},{"all":["let me get"]}]', 'Oh no, I''ll get this one. It''s on us.', '["Great, thanks for paying!","Let''s split it fifty-fifty.","Could we get the check, please?"]', '["Take the check yourself.","Key words: I''ll get this one, it''s on us"]', '["계산서를 직접 가져가세요.","핵심 단어: I''ll get this one, it''s on us"]', 'greg', 'Well, thank you. I''ll get the next one when you''re in town again.', '그럼 고마워요. 다음에 또 오면 제가 살게요.');

/* part 6/8: d11_dinner#5 d12_signing#1 d12_signing#2 d12_signing#3 d12_signing#4 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d11_dinner', 5, 'greg', 'The bill is $164 before tip. In the US, about 20 percent is normal for good service.', '팁 전 금액이 164달러입니다. 미국에서는 서비스가 좋으면 20% 정도가 보통입니다.', 'Service was great tonight, wasn''t it?', 'Agree, and say you will leave a twenty percent tip, about thirty-three dollars.', '동의하고, 20% 팁으로 33달러쯤 남기겠다고 말하세요.', '[{"any":["20","twenty","33","thirty three"]}]', 'It was. I''ll leave a twenty percent tip, so about thirty-three dollars.', '["It was okay, but my fish was a little cold.","I''ll leave five dollars. That''s enough.","Let''s ask for separate checks."]', '["Work out the tip: 20 percent of $164.","Key words: twenty percent, thirty-three dollars"]', '["164달러의 20%를 계산하세요.","핵심 단어: twenty percent, thirty-three dollars"]', 'greg', 'Very generous. Get some rest. Big day tomorrow!', '후하네요. 푹 쉬어요. 내일 중요한 날이잖아요!'),
  ('d12_signing', 1, 'greg', 'Legal approved the final version overnight. Greg has the contract up on the screen.', '밤사이 법무팀이 최종본을 승인했습니다. 그렉이 계약서를 화면에 띄워 둡니다.', 'Morning! Legal signed off. Thirty days'' notice, Net 45, five percent off with the support contract. Does that match your notes?', 'Confirm that everything matches, and say you think you are in agreement.', '모두 일치한다고 확인하고, 합의가 된 것 같다고 말하세요.', '[{"all":["in agreement"]},{"any":["matches","match"]},{"all":["agreed"]},{"all":["looks right"]},{"all":["looks good"]}]', 'Yes, that matches my notes. I think we''re in agreement.', '["Actually, we need to renegotiate everything.","Could you print a map to the airport?","Sorry, I didn''t bring any notes."]', '["Confirm the terms.","Key words: matches my notes, in agreement"]', '["조건을 확인하세요.","핵심 단어: matches my notes, in agreement"]', 'greg', 'Fantastic. I''ll send it out for e-signature now.', '좋아요. 지금 전자 서명 요청을 보낼게요.'),
  ('d12_signing', 2, 'greg', 'Maya signs from the office, then Greg signs.', '마야가 사무실에서 서명하고, 이어서 그렉이 서명합니다.', 'And… done! It''s official. Welcome to the Summit family.', 'Thank him for his trust and say you are excited to get started.', '믿어 줘서 고맙다고 하고, 시작하게 되어 기대된다고 말하세요.', '[{"all":["excited"]},{"all":["thank","trust"]},{"all":["looking forward"]},{"all":["thank"],"any":["partnership","opportunity"]}]', 'Thank you for your trust, Greg. We''re really excited to get started.', '["Great, now I can finally go home.","Do you validate parking here?","I hope it doesn''t rain on my flight."]', '["Show appreciation and enthusiasm.","Key words: thank you for your trust, excited to get started"]', '["감사와 기대를 표현하세요.","핵심 단어: thank you for your trust, excited to get started"]', 'greg', 'So are we. So, what happens next?', '저희도요. 그럼 다음은 뭐죠?'),
  ('d12_signing', 3, 'greg', 'Greg wants a clear plan for the next few weeks.', '그렉은 앞으로 몇 주의 분명한 계획을 원합니다.', 'What are the next steps?', 'Lay out the next steps: a kickoff with both teams next week, and a weekly status update every Friday.', '다음 단계를 말하세요. 다음 주 양 팀 킥오프, 매주 금요일 주간 현황 보고.', '[{"all":["weekly"]},{"all":["next week"]},{"all":["every friday"]},{"all":["status"],"any":["update","report","meeting"]}]', 'Next, we''ll set up a kickoff with both teams next week, and send a weekly status update every Friday.', '["There are no next steps. We''re done.","I''ll send you a postcard from the airport.","Let''s meet again next year."]', '["Describe what happens after signing.","Key words: kickoff next week, weekly status update"]', '["서명 후에 무엇을 하는지 말하세요.","핵심 단어: kickoff next week, weekly status update"]', 'greg', 'Perfect. And who''s my point of contact day to day?', '완벽해요. 평소에는 누구에게 연락하면 되죠?'),
  ('d12_signing', 4, 'greg', 'Priya manages the project. You handle the technical side.', '프로젝트는 프리야가 관리하고, 기술 쪽은 당신이 맡습니다.', 'Who should I reach out to day to day?', 'Say Priya is his main point of contact, and you will handle technical questions.', '주 담당자는 프리야이고, 기술적인 질문은 당신이 맡는다고 말하세요.', '[{"all":["point of contact"]},{"all":["priya"]},{"all":["technical"]}]', 'Priya will be your main point of contact, and I''ll handle any technical questions.', '["Just call the front desk at my hotel.","Nobody, really. We''ll figure it out.","You can email the airline if something comes up."]', '["Name the right people.","Key words: point of contact, Priya, technical questions"]', '["담당자를 정확히 말하세요.","핵심 단어: point of contact, Priya, technical questions"]', 'greg', 'Sounds good. Safe travels home, and thanks again. This was a great trip.', '좋아요. 조심히 돌아가고, 다시 한번 고마워요. 정말 좋은 출장이었어요.');

/* part 7/8: d12_checkout#1 d12_checkout#2 d12_checkout#3 d12_checkout#4 d12_flight_home#1 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d12_checkout', 1, 'kelly', 'You roll your suitcase to the front desk.', '여행 가방을 끌고 프런트로 갑니다.', 'Good morning! Checking out? How was your stay?', 'Say you would like to check out, and the stay was great.', '체크아웃하겠다고 하고 잘 지냈다고 말하세요.', '[{"all":["check out"]},{"all":["checkout"]},{"all":["checking out"]}]', 'Good morning. I''d like to check out, please. The stay was great.', '["I''d like to extend my stay for a week.","Could you send up more towels?","Is the restaurant open for dinner?"]', '["Say you are leaving today.","Key words: I''d like to check out"]', '["오늘 떠난다고 말하세요.","핵심 단어: I''d like to check out"]', 'kelly', 'Glad to hear it! Here''s your folio. Take a look and let me know if everything''s correct.', '다행이에요! 여기 청구서예요. 확인해 보시고 맞는지 알려 주세요.'),
  ('d12_checkout', 2, 'kelly', 'The bill shows a $14 minibar charge. You never opened the minibar.', '청구서에 미니바 14달러가 있습니다. 미니바는 열지도 않았습니다.', 'Does everything look okay?', 'Say there is a minibar charge you don''t recognize. You didn''t use it.', '모르는 미니바 요금이 있다고 하세요. 쓰지 않았습니다.', '[{"all":["minibar"]},{"all":["mini bar"]},{"all":["recognize"]},{"all":["charge"],"any":["wrong","mistake","error"]}]', 'Actually, there''s a minibar charge I don''t recognize. I didn''t use the minibar.', '["Everything looks perfect, thank you.","Can I add a bottle of wine to the bill?","I''d like to pay for the room in cash."]', '["Point out the wrong charge.","Key words: a charge I don''t recognize, minibar"]', '["잘못된 요금을 짚으세요.","핵심 단어: a charge I don''t recognize, minibar"]', 'kelly', 'I''m so sorry about that. I''ve taken it off. The room itself is on the company card.', '정말 죄송해요. 빼 드렸어요. 객실 요금은 법인 카드로 처리됐어요.'),
  ('d12_checkout', 3, 'kelly', 'You need the receipt for your expense report.', '경비 정산을 하려면 영수증이 필요합니다.', 'Would you like a copy of the receipt?', 'Ask her to email you an itemized receipt.', '항목별 영수증을 이메일로 보내 달라고 하세요.', '[{"all":["itemized"]},{"all":["email"],"any":["receipt","copy","it"]},{"all":["send","receipt"]}]', 'Yes, please. Could you email me an itemized receipt? I need it for my expense report.', '["No thanks, I don''t need anything.","Could you print my boarding pass?","Could you recommend a good steakhouse?"]', '["Ask for a detailed receipt by email.","Key words: email, itemized receipt"]', '["자세한 영수증을 이메일로 달라고 하세요.","핵심 단어: email, itemized receipt"]', 'kelly', 'Done. It should be in your inbox. Anything else?', '보냈어요. 메일함에 있을 거예요. 더 필요한 거 있으세요?'),
  ('d12_checkout', 4, 'kelly', 'Your flight home leaves this afternoon.', '귀국편은 오늘 오후에 출발합니다.', 'Anything else I can do for you?', 'Ask where you can catch the shuttle to the airport.', '공항 가는 셔틀을 어디서 타는지 물어보세요.', '[{"all":["shuttle"]},{"all":["airport"],"any":["get","how","ride"]}]', 'Yes, where can I catch the shuttle to the airport?', '["Where can I buy some souvenirs?","Could you recommend a good museum?","What time is breakfast tomorrow?"]', '["Ask how to get to the airport.","Key words: catch the shuttle, airport"]', '["공항 가는 방법을 물어보세요.","핵심 단어: catch the shuttle, airport"]', 'kelly', 'Right outside the main doors, every thirty minutes. Safe travels!', '정문 바로 밖에서 30분마다 있어요. 조심히 가세요!'),
  ('d12_flight_home', 1, 'amy', 'At the gate for your flight home, Amy makes an announcement.', '귀국편 게이트에서 에이미가 안내 방송을 합니다.', 'Folks, this flight is overbooked. We''re looking for one volunteer to take the next flight, three hours later, for a travel voucher.', 'Ask how much the voucher is worth.', '바우처가 얼마짜리인지 물어보세요.', '[{"all":["how much"]},{"all":["worth"]},{"all":["voucher"],"any":["value","amount","what"]}]', 'Excuse me, how much is the voucher worth?', '["Excuse me, where can I buy a sandwich?","Excuse me, can I sit in first class?","Excuse me, is my bag on this plane?"]', '["Find out the value first.","Key words: how much, voucher, worth"]', '["먼저 가치를 알아보세요.","핵심 단어: how much, voucher, worth"]', 'amy', 'Three hundred dollars toward any future flight.', '다음 항공권에 쓸 수 있는 300달러예요.');

/* part 8/8: d12_flight_home#2 d12_flight_home#3 d12_flight_home#4 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d12_flight_home', 2, 'amy', 'You are not in a hurry tonight, but three hundred feels a little low.', '오늘 밤 급하지는 않지만 300달러는 조금 적게 느껴집니다.', 'Would you be interested?', 'Say you might be. Ask if she would do four hundred if you take the later flight.', '그럴 수도 있다고 하세요. 나중 비행기를 타면 400달러로 해 줄 수 있는지 물어보세요.', '[{"any":["400","four hundred"]},{"all":["bump","up"]},{"all":["if"],"any":["more","higher"]}]', 'I might be. Would you do four hundred if I take the later flight?', '["No way. I need to get home right now.","Sure, I''ll do it for free.","Could you move me to an aisle seat?"]', '["Make a counteroffer with a higher number.","Key words: would you do four hundred"]', '["더 높은 금액으로 역제안하세요.","핵심 단어: would you do four hundred"]', 'amy', 'Let me check… Okay, I can do four hundred, plus a fifteen-dollar meal voucher.', '확인해 볼게요… 좋아요, 400달러에 15달러 식사 쿠폰도 드릴게요.'),
  ('d12_flight_home', 3, 'amy', 'You want to be sure you won''t get bumped again.', '다시 밀려나지 않을지 확실히 하고 싶습니다.', 'Four hundred plus a meal voucher. Deal?', 'Accept, and make sure you are guaranteed a seat on the later flight.', '받아들이고, 나중 비행기 좌석이 확실히 보장되는지 확인하세요.', '[{"all":["confirmed"]},{"all":["confirm"]},{"all":["guaranteed"]},{"all":["seat"],"any":["later","next","guarantee"]}]', 'Deal. Just to confirm, I''m guaranteed a seat on the later flight?', '["Deal. Can I have the window seat on this flight too?","Never mind, I''ll take this flight after all.","Deal. Can you mail the voucher to my house?"]', '["Say yes, but protect yourself.","Key words: deal, guaranteed a seat"]', '["수락하되 확실히 해 두세요.","핵심 단어: deal, guaranteed a seat"]', 'amy', 'Yes, you''re confirmed in seat 9A. Here are your vouchers. Thanks for helping us out!', '네, 9A 좌석으로 확정됐어요. 여기 바우처요. 도와주셔서 감사해요!'),
  ('d12_flight_home', 4, 'amy', 'You have three hours to kill at the airport.', '공항에서 세 시간을 보내야 합니다.', 'Is there anything else I can do for you?', 'Ask where you can use the meal voucher.', '식사 쿠폰을 어디서 쓸 수 있는지 물어보세요.', '[{"all":["where"],"any":["use","voucher","eat"]},{"all":["restaurant"]},{"all":["food court"]}]', 'Where can I use the meal voucher?', '["Where can I find a hotel for tonight?","Can I use it to pay my rent?","When do I get my luggage back?"]', '["Ask where the voucher works.","Key words: where, use, meal voucher"]', '["쿠폰을 어디서 쓸 수 있는지 물어보세요.","핵심 단어: where, use, meal voucher"]', 'amy', 'Any restaurant in this terminal. The burger place across the hall is pretty good.', '이 터미널의 식당 어디든요. 맞은편 버거집이 꽤 괜찮아요.');

/* part 1/4: d11_checkin.where_flying d11_checkin.photo_id d11_checkin.checking_bags d11_checkin.carry_on d11_checkin.boarding_group d11_checkin.on_time d11_checkin.as_of_now d11_security.here_you_go d11_security.laptops_out d11_security.empty_pockets d11_security.precheck d11_security.over_the_limit d11_security.all_set d11_security.which_way d11_gate.due_to d11_gate.new_departure d11_gate.connecting d11_gate.make_it d11_gate.gate_check d11_gate.id_rather d11_gate.your_patience -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d11_checkin.where_flying', 'd11_checkin', 'Where are you flying today?', '오늘 어디로 가세요?', 'The first question at an airline counter.', '항공사 카운터의 첫 질문입니다.', 'travel'),
  ('d11_checkin.photo_id', 'd11_checkin', 'Can I see a photo ID?', '사진 있는 신분증 보여 주시겠어요?', 'In the US a driver''s license or passport works for domestic flights.', '미국 국내선에서는 운전면허증이나 여권을 씁니다.', 'travel'),
  ('d11_checkin.checking_bags', 'd11_checkin', 'Are you checking any bags?', '부칠 짐 있으세요?', 'Check a bag = give it to the airline to put under the plane.', 'check a bag은 짐을 부친다는 뜻입니다.', 'travel'),
  ('d11_checkin.carry_on', 'd11_checkin', 'The backpack is my carry-on.', '배낭은 기내 반입 가방이에요.', 'Carry-on = a bag you take on the plane. Most US airlines charge for checked bags.', 'carry-on은 기내에 들고 타는 가방입니다. 미국 항공사는 대부분 위탁 수하물에 요금을 받습니다.', 'travel'),
  ('d11_checkin.boarding_group', 'd11_checkin', 'You''re in boarding group three.', '3번 그룹으로 탑승하세요.', 'US airlines board in numbered groups.', '미국 항공사는 번호 그룹 순서로 탑승합니다.', 'travel'),
  ('d11_checkin.on_time', 'd11_checkin', 'Is the flight on time?', '비행기가 제시간에 출발하나요?', 'On time = not delayed.', 'on time은 지연되지 않았다는 뜻입니다.', 'travel'),
  ('d11_checkin.as_of_now', 'd11_checkin', 'As of now, yes.', '현재로서는 그래요.', 'Things might change later.', '나중에 바뀔 수도 있다는 뜻을 담습니다.', 'travel'),
  ('d11_security.here_you_go', 'd11_security', 'Here you go.', '여기 있어요.', 'Say it when you hand something to someone.', '무언가를 건넬 때 하는 말입니다.', 'travel'),
  ('d11_security.laptops_out', 'd11_security', 'Laptops out in a separate bin.', '노트북은 따로 바구니에 꺼내 주세요.', 'Bin = the plastic tray at security.', 'bin은 보안 검색대의 플라스틱 바구니입니다.', 'travel'),
  ('d11_security.empty_pockets', 'd11_security', 'Empty your pockets, please.', '주머니를 비워 주세요.', 'Phones, keys and coins go in the bin.', '휴대폰, 열쇠, 동전은 바구니에 넣습니다.', 'travel'),
  ('d11_security.precheck', 'd11_security', 'TSA PreCheck', 'TSA 사전 심사 프로그램', 'A US program for pre-screened travelers: shorter line, shoes stay on.', '사전 심사를 받은 여행자용 미국 프로그램입니다. 줄이 짧고 신발을 벗지 않습니다.', 'travel'),
  ('d11_security.over_the_limit', 'd11_security', 'It''s over the limit.', '허용량을 넘었어요.', 'Liquids in carry-ons must be 3.4 ounces (100 ml) or less.', '기내 반입 액체는 3.4온스(100ml) 이하여야 합니다.', 'travel'),
  ('d11_security.all_set', 'd11_security', 'You''re all set.', '다 됐어요.', 'Everything is done. You can go.', '모든 게 끝났으니 가도 된다는 뜻입니다.', 'travel'),
  ('d11_security.which_way', 'd11_security', 'Which way is gate B12?', 'B12 게이트는 어느 쪽이에요?', 'A quick way to ask for directions.', '길을 묻는 간단한 표현입니다.', 'travel'),
  ('d11_gate.due_to', 'd11_gate', 'We have a delay due to a late incoming aircraft.', '앞 비행기가 늦게 도착해 지연됩니다.', 'Due to = because of. Very common in announcements.', 'due to는 because of와 같습니다. 안내 방송에서 자주 씁니다.', 'travel'),
  ('d11_gate.new_departure', 'd11_gate', 'What''s the new departure time?', '새 출발 시각이 언제예요?', 'Ask this whenever the screen says DELAYED.', '전광판에 DELAYED가 뜨면 물어보세요.', 'travel'),
  ('d11_gate.connecting', 'd11_gate', 'Do you have a connecting flight?', '연결편 있으세요?', 'A connecting flight means you change planes on the way.', '연결편은 가는 도중 비행기를 갈아탄다는 뜻입니다.', 'travel'),
  ('d11_gate.make_it', 'd11_gate', 'Will I still make it?', '그래도 제시간에 갈 수 있을까요?', 'Make it = arrive in time.', 'make it은 제시간에 도착한다는 뜻입니다.', 'travel'),
  ('d11_gate.gate_check', 'd11_gate', 'We''re offering free gate checks.', '게이트에서 무료로 짐을 부쳐 드려요.', 'On full flights, agents check carry-ons at the gate for free.', '만석일 때 게이트에서 기내 가방을 무료로 부쳐 줍니다.', 'travel'),
  ('d11_gate.id_rather', 'd11_gate', 'I''d rather keep it with me.', '제가 가지고 있는 게 나아요.', 'I would rather = I prefer to.', 'I would rather는 차라리 …하겠다는 뜻입니다.', 'travel'),
  ('d11_gate.your_patience', 'd11_gate', 'Thanks for your patience.', '기다려 주셔서 감사합니다.', 'Staff say this after delays or problems.', '지연이나 문제 뒤에 직원들이 하는 말입니다.', 'travel');

/* part 2/4: d11_hotel_checkin.under_my_name d11_hotel_checkin.early_checkin d11_hotel_checkin.in_luck d11_hotel_checkin.incidentals d11_hotel_checkin.key_cards d11_hotel_checkin.breakfast_served d11_hotel_checkin.late_checkout d11_hotel_checkin.enjoy_stay d11_client_visit.you_made_it d11_client_visit.dive_in d11_client_visit.redlines d11_client_visit.jump_out d11_client_visit.days_notice d11_client_visit.who_owns d11_client_visit.on_your_side d11_client_visit.were_close d11_dinner.dietary d11_dinner.allergic d11_dinner.ill_have d11_dinner.medium_rare d11_dinner.to_share ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d11_hotel_checkin.under_my_name', 'd11_hotel_checkin', 'I have a reservation under my name.', '제 이름으로 예약했어요.', 'Under = booked in the name of.', 'under는 … 이름으로 예약되었다는 뜻입니다.', 'hotel'),
  ('d11_hotel_checkin.early_checkin', 'd11_hotel_checkin', 'Is early check-in possible?', '일찍 체크인할 수 있나요?', 'US hotels usually check in at 3 p.m. and check out at 11 a.m. or noon.', '미국 호텔은 보통 오후 3시 체크인, 오전 11시나 정오 체크아웃입니다.', 'hotel'),
  ('d11_hotel_checkin.in_luck', 'd11_hotel_checkin', 'You''re in luck.', '운이 좋으시네요.', 'Good news: what you want is available.', '원하는 것이 된다는 좋은 소식입니다.', 'hotel'),
  ('d11_hotel_checkin.incidentals', 'd11_hotel_checkin', 'a hold for incidentals', '부대비용 보증금', 'The hotel blocks some money on your card for extras. It is released after checkout.', '추가 비용에 대비해 카드에 금액을 잡아 두고 체크아웃 후 풀어 줍니다.', 'hotel'),
  ('d11_hotel_checkin.key_cards', 'd11_hotel_checkin', 'Here are your key cards.', '여기 키 카드예요.', 'Most hotels give two cards per room.', '대부분 방마다 카드 두 장을 줍니다.', 'hotel'),
  ('d11_hotel_checkin.breakfast_served', 'd11_hotel_checkin', 'What time is breakfast served?', '아침은 몇 시에 나와요?', 'Served = offered to guests.', 'served는 손님에게 제공된다는 뜻입니다.', 'hotel'),
  ('d11_hotel_checkin.late_checkout', 'd11_hotel_checkin', 'Could I get a late checkout?', '늦게 체크아웃할 수 있을까요?', 'Often free if you ask nicely, especially midweek.', '정중히 부탁하면, 특히 주중에는 무료인 경우가 많습니다.', 'hotel'),
  ('d11_hotel_checkin.enjoy_stay', 'd11_hotel_checkin', 'Enjoy your stay!', '즐거운 시간 보내세요!', 'The usual goodbye at a hotel front desk.', '호텔 프런트의 흔한 인사입니다.', 'hotel'),
  ('d11_client_visit.you_made_it', 'd11_client_visit', 'You made it!', '잘 오셨어요!', 'A warm welcome to someone who traveled to see you.', '먼 길 온 사람을 반기는 말입니다.', 'small-talk'),
  ('d11_client_visit.dive_in', 'd11_client_visit', 'before we dive in', '본론에 들어가기 전에', 'Dive in = start the main work with energy.', 'dive in은 본격적으로 시작한다는 뜻입니다.', 'meeting'),
  ('d11_client_visit.redlines', 'd11_client_visit', 'Legal sent back a few redlines.', '법무팀이 수정 사항을 몇 개 보냈어요.', 'Redlines = changes marked on a contract draft.', 'redlines는 계약서 초안에 표시한 수정 사항입니다.', 'contract'),
  ('d11_client_visit.jump_out', 'd11_client_visit', 'Does anything jump out at you?', '눈에 띄는 게 있나요?', 'Jump out = be easy to notice.', 'jump out은 눈에 확 띈다는 뜻입니다.', 'meeting'),
  ('d11_client_visit.days_notice', 'd11_client_visit', 'thirty days'' notice', '30일 전 통보', 'Notice = a warning given in advance, usually before ending a contract.', 'notice는 계약 해지 등을 미리 알리는 것입니다.', 'contract'),
  ('d11_client_visit.who_owns', 'd11_client_visit', 'Who owns the source code?', '소스 코드는 누구 소유인가요?', 'Always check intellectual property (IP) in a software contract.', '소프트웨어 계약에서는 지식재산권(IP)을 꼭 확인하세요.', 'contract'),
  ('d11_client_visit.on_your_side', 'd11_client_visit', 'Anything else on your side?', '그쪽에서 다른 건요?', 'On your side = from your team or company.', 'on your side는 당신 쪽 팀이나 회사에서라는 뜻입니다.', 'meeting'),
  ('d11_client_visit.were_close', 'd11_client_visit', 'I think we''re close.', '거의 합의에 다 온 것 같아요.', 'Close = almost at an agreement.', 'close는 합의에 거의 다다랐다는 뜻입니다.', 'negotiation'),
  ('d11_dinner.dietary', 'd11_dinner', 'Do you have any dietary restrictions?', '가리는 음식 있어요?', 'A thoughtful question before a business meal.', '비즈니스 식사 전에 배려하는 질문입니다.', 'restaurant'),
  ('d11_dinner.allergic', 'd11_dinner', 'I''m allergic to peanuts.', '땅콩 알레르기가 있어요.', 'Other than that = except for that.', 'other than that은 그것 말고는이라는 뜻입니다.', 'restaurant'),
  ('d11_dinner.ill_have', 'd11_dinner', 'I''ll have the grilled salmon.', '연어 구이로 할게요.', 'The most natural way to order. Also: I''ll do the steak.', '가장 자연스러운 주문 표현입니다. I''ll do the steak도 씁니다.', 'restaurant'),
  ('d11_dinner.medium_rare', 'd11_dinner', 'The steak, medium rare.', '스테이크, 미디엄 레어로요.', 'Steak doneness: rare, medium rare, medium, medium well, well done.', '고기 굽기: rare, medium rare, medium, medium well, well done.', 'restaurant'),
  ('d11_dinner.to_share', 'd11_dinner', 'Let''s get the calamari to share.', '오징어 튀김 하나 나눠 먹죠.', 'Appetizers are often ordered to share.', '애피타이저는 나눠 먹으려고 자주 시킵니다.', 'restaurant');

/* part 3/4: d11_dinner.get_this_one d11_dinner.tip_percent d11_dinner.big_day d12_signing.legal_signed_off d12_signing.in_agreement d12_signing.e_signature d12_signing.its_official d12_signing.next_steps d12_signing.status_update d12_signing.point_of_contact d12_signing.reach_out d12_checkout.how_was_stay d12_checkout.folio d12_checkout.dont_recognize d12_checkout.taken_it_off d12_checkout.itemized d12_checkout.catch_shuttle d12_flight_home.overbooked d12_flight_home.volunteer d12_flight_home.voucher_worth d12_flight_home.would_you_do d12_flight_home.deal ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d11_dinner.get_this_one', 'd11_dinner', 'I''ll get this one.', '이번엔 제가 낼게요.', 'Offer to pay. When a company pays, add: It''s on us.', '계산하겠다는 말입니다. 회사가 낼 때는 It''s on us를 덧붙입니다.', 'restaurant'),
  ('d11_dinner.tip_percent', 'd11_dinner', 'I''ll leave a twenty percent tip.', '20% 팁을 남길게요.', 'US servers earn most of their pay from tips: 18 to 22 percent is normal.', '미국 서버는 수입 대부분이 팁입니다. 18~22%가 보통입니다.', 'restaurant'),
  ('d11_dinner.big_day', 'd11_dinner', 'Big day tomorrow!', '내일 중요한 날이잖아요!', 'Said the night before something important.', '중요한 일 전날 밤에 하는 말입니다.', 'small-talk'),
  ('d12_signing.legal_signed_off', 'd12_signing', 'Legal signed off.', '법무팀이 승인했어요.', 'Legal = the legal team. Sign off = approve.', 'legal은 법무팀, sign off는 승인하다입니다.', 'contract'),
  ('d12_signing.in_agreement', 'd12_signing', 'I think we''re in agreement.', '합의가 된 것 같네요.', 'A formal way to say you both agree.', '양쪽이 동의한다는 격식 있는 표현입니다.', 'contract'),
  ('d12_signing.e_signature', 'd12_signing', 'I''ll send it out for e-signature.', '전자 서명 요청을 보낼게요.', 'Most US contracts are signed online.', '미국 계약은 대부분 온라인으로 서명합니다.', 'contract'),
  ('d12_signing.its_official', 'd12_signing', 'It''s official.', '이제 공식이에요.', 'Said when something is signed or announced.', '서명이나 발표가 끝났을 때 하는 말입니다.', 'contract'),
  ('d12_signing.next_steps', 'd12_signing', 'What are the next steps?', '다음 단계는 뭐죠?', 'Every meeting should end with clear next steps.', '모든 회의는 분명한 다음 단계로 끝나야 합니다.', 'meeting'),
  ('d12_signing.status_update', 'd12_signing', 'a weekly status update', '주간 현황 보고', 'A short report on progress, sent on a fixed day.', '정해진 요일에 보내는 짧은 진행 보고입니다.', 'meeting'),
  ('d12_signing.point_of_contact', 'd12_signing', 'your main point of contact', '주 담당자', 'The person to call first.', '가장 먼저 연락할 사람입니다.', 'contract'),
  ('d12_signing.reach_out', 'd12_signing', 'Who should I reach out to?', '누구에게 연락하면 되죠?', 'Reach out = contact someone.', 'reach out은 연락한다는 뜻입니다.', 'office'),
  ('d12_checkout.how_was_stay', 'd12_checkout', 'How was your stay?', '지내시기 어떠셨어요?', 'The usual question at checkout.', '체크아웃 때 흔히 듣는 질문입니다.', 'hotel'),
  ('d12_checkout.folio', 'd12_checkout', 'Here''s your folio.', '여기 청구서예요.', 'Folio = the hotel''s bill for your stay.', 'folio는 숙박 청구서입니다.', 'hotel'),
  ('d12_checkout.dont_recognize', 'd12_checkout', 'There''s a charge I don''t recognize.', '모르는 요금이 있어요.', 'A polite, non-accusing way to question a bill.', '상대를 탓하지 않고 청구서에 의문을 제기하는 방법입니다.', 'hotel'),
  ('d12_checkout.taken_it_off', 'd12_checkout', 'I''ve taken it off.', '빼 드렸어요.', 'Take something off the bill = remove the charge.', 'take off the bill은 요금을 뺀다는 뜻입니다.', 'hotel'),
  ('d12_checkout.itemized', 'd12_checkout', 'Could you email me an itemized receipt?', '항목별 영수증을 이메일로 보내 주시겠어요?', 'Itemized = every charge listed separately. Expense reports need it.', 'itemized는 모든 요금이 따로 적혀 있다는 뜻입니다. 경비 정산에 필요합니다.', 'hotel'),
  ('d12_checkout.catch_shuttle', 'd12_checkout', 'Where can I catch the shuttle?', '셔틀은 어디서 타요?', 'Catch = get on a bus, train or shuttle.', 'catch는 버스, 기차, 셔틀을 탄다는 뜻입니다.', 'travel'),
  ('d12_flight_home.overbooked', 'd12_flight_home', 'This flight is overbooked.', '이 항공편은 초과 예약됐어요.', 'Airlines sell more seats than they have, then ask for volunteers.', '항공사는 좌석보다 많이 팔고 양보할 사람을 찾습니다.', 'travel'),
  ('d12_flight_home.volunteer', 'd12_flight_home', 'We''re looking for a volunteer.', '양보하실 분을 찾습니다.', 'Volunteering can earn you a voucher or cash.', '양보하면 바우처나 현금을 받을 수 있습니다.', 'travel'),
  ('d12_flight_home.voucher_worth', 'd12_flight_home', 'How much is the voucher worth?', '바우처는 얼마짜리예요?', 'Worth = value. Always ask before you accept.', 'worth는 가치입니다. 받기 전에 꼭 물어보세요.', 'travel'),
  ('d12_flight_home.would_you_do', 'd12_flight_home', 'Would you do four hundred?', '400으로 해 주실 수 있어요?', 'A casual counteroffer: Would you do + price?', 'Would you do + 가격?은 가벼운 역제안입니다.', 'negotiation'),
  ('d12_flight_home.deal', 'd12_flight_home', 'Deal.', '좋아요, 그렇게 하죠.', 'One word to accept an offer.', '제안을 받아들이는 한 단어입니다.', 'negotiation');

/* part 4/4: d12_flight_home.guaranteed_seat d12_flight_home.helping_out d12_flight_home.time_to_kill ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d12_flight_home.guaranteed_seat', 'd12_flight_home', 'I''m guaranteed a seat, right?', '좌석은 보장되는 거죠?', 'Make sure you won''t get bumped again.', '다시 밀려나지 않도록 확인하세요.', 'travel'),
  ('d12_flight_home.helping_out', 'd12_flight_home', 'Thanks for helping us out!', '도와주셔서 감사해요!', 'Help someone out = help them with a problem.', 'help someone out은 곤란한 사람을 돕는다는 뜻입니다.', 'travel'),
  ('d12_flight_home.time_to_kill', 'd12_flight_home', 'I have three hours to kill.', '세 시간이나 때워야 해요.', 'Time to kill = free time while you wait.', 'time to kill은 기다리며 보내야 하는 시간입니다.', 'small-talk');
