-- Sim Office seed (agent D): second weekend (days 13-14) and day 15: brunch, neighbor barbecue, trip report, expenses and payday, raise, sick call
-- Generated from structured data; push with: node tools/dolt.mjs push <this file>
-- Statements are split at a semicolon at the end of a line. Each statement is kept under ~11k URL-encoded characters (DoltHub limit).
/* part 1/1: w_brunch w_neighbor_bbq d15_trip_report d15_expenses d15_raise d15_sick_call ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO episodes (id, title, title_ko, place, npc, day_from, day_to, time_from, time_to, requires, summary, summary_ko, reward, energy, sort, tags) VALUES
  ('w_brunch', 'Weekend brunch at the diner', '다이너에서 주말 브런치', 'diner_counter', 'rosa', 13, 14, '08:00', '13:30', NULL, 'Treat yourself to brunch after the trip: order eggs the way you like them, get a refill, and pay with a tip. Brunch and tip come to $20.', '출장 후 브런치로 자신에게 상을 주세요. 원하는 방식으로 달걀을 주문하고, 리필을 받고, 팁을 얹어 계산합니다. 브런치와 팁은 20달러.', -20, 30, 1310, 'weekend,restaurant,life'),
  ('w_neighbor_bbq', 'Carl''s backyard barbecue', '칼의 뒷마당 바비큐', 'bus_stop', 'carl', 13, 14, '09:00', '18:00', NULL, 'Your neighbor Carl wants to hear about your trip, talks football, and invites you to a barbecue.', '이웃 칼이 출장 얘기를 궁금해하고, 풋볼 얘기를 하고, 바비큐에 초대합니다.', 0, 25, 1320, 'weekend,small-talk,neighbor,life'),
  ('d15_trip_report', 'Trip report at standup', '스탠드업에서 출장 보고', 'office_desk_team', 'derek', 15, 15, '09:00', '11:00', 'd12_signing', 'Back at the office, tell the team how the Ridgeport trip went and what it means for the sprint.', '사무실로 돌아와 리지포트 출장 결과와 이번 스프린트에 미칠 영향을 팀에 알리세요.', 0, 0, 1510, 'meeting,standup,week3'),
  ('d15_expenses', 'Expense report and your paycheck', '경비 정산과 급여 질문', 'office_hr', 'linda', 15, 15, '09:30', '17:30', 'd12_flight_home', 'Submit your trip expenses to Linda and ask about your paycheck: taxes, net pay and the 401(k) match. Your out-of-pocket costs ($118) are reimbursed.', '린다에게 출장 경비를 제출하고 급여에 대해 물어보세요. 세금, 실수령액, 401(k) 매칭. 개인 부담 비용 118달러가 환급됩니다.', 118, 0, 1520, 'hr,expenses,payday,money,week3'),
  ('d15_raise', 'Asking for a raise', '연봉 인상 요청', 'office_manager', 'maya', 15, 15, '13:00', '18:00', 'd12_signing', 'After the Summit deal, bring up your compensation with Maya, back it with data, and agree on a path to the next level.', '서밋 계약 성사 후 마야와 보상 문제를 꺼내고, 근거를 대고, 다음 단계로 가는 길을 합의하세요.', 0, 0, 1530, 'hr,negotiation,career,week3'),
  ('d15_sick_call', 'Calling in sick', '병가 전화', 'home_desk', 'maya', 15, 15, '19:00', '22:45', NULL, 'You come down with a fever on Monday night. Call Maya, take a sick day tomorrow, and arrange cover for your meeting.', '월요일 밤 열이 납니다. 마야에게 전화해 내일 병가를 내고, 회의를 대신할 사람을 정하세요.', 0, 0, 1540, 'hr,phone,sick,week3');

/* part 1/6: w_brunch#1 w_brunch#2 w_brunch#3 w_brunch#4 w_brunch#5 w_neighbor_bbq#1 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('w_brunch', 1, 'rosa', 'It is a weekend morning and the diner is busy. Rosa comes over with a coffee pot.', '주말 아침, 다이너가 붐빕니다. 로사가 커피 주전자를 들고 옵니다.', 'Morning, hon! Coffee to start?', 'Say yes, and ask for the brunch menu.', '네라고 하고 브런치 메뉴를 달라고 하세요.', '[{"all":["menu"]},{"all":["yes","please"]},{"all":["coffee","please"]}]', 'Yes, please. And could I see the brunch menu?', '["No, I''m just here to use the restroom.","Could I get the check right away?","I''d like to check in, please."]', '["Accept the coffee and ask for something to read.","Key words: yes please, brunch menu"]', '["커피를 받고 메뉴를 달라고 하세요.","핵심 단어: yes please, brunch menu"]', 'rosa', 'Here you go. The special today is the veggie omelet.', '여기요. 오늘의 스페셜은 채소 오믈렛이에요.'),
  ('w_brunch', 2, 'rosa', 'You know exactly what you want.', '먹고 싶은 게 분명합니다.', 'Ready to order?', 'Order two eggs over easy with bacon and wheat toast.', '달걀 두 개 오버 이지에 베이컨과 통밀 토스트를 주문하세요.', '[{"any":["over easy","scrambled","sunny side up","eggs","omelet","pancakes","waffles"]}]', 'Yes. Can I get two eggs over easy, with bacon and wheat toast?', '["I''ll have the steak and a glass of red wine.","Can I get a large popcorn, please?","I''m still deciding. Actually, never mind."]', '["Say how you want your eggs.","Key words: can I get, eggs over easy"]', '["달걀을 어떻게 해 달라고 할지 말하세요.","핵심 단어: can I get, eggs over easy"]', 'rosa', 'You got it. Hash browns or home fries with that?', '알겠어요. 해시 브라운이요, 홈 프라이요?'),
  ('w_brunch', 3, 'rosa', 'Both are fried potatoes, cut differently.', '둘 다 감자 요리인데 써는 방식이 다릅니다.', 'Hash browns or home fries?', 'Choose one.', '하나를 고르세요.', '[{"any":["hash browns","hash brown","home fries"]}]', 'Hash browns, please.', '["Neither, I''m allergic to eggs.","Can I pay by check?","Just water for the table, thanks."]', '["Pick a side.","Key words: hash browns or home fries"]', '["곁들임을 고르세요.","핵심 단어: hash browns 또는 home fries"]', 'rosa', 'Great choice. Coming right up.', '좋은 선택이에요. 금방 나와요.'),
  ('w_brunch', 4, 'rosa', 'You have finished eating. Your coffee cup is empty.', '다 먹었습니다. 커피 잔이 비었습니다.', 'How''s everything tasting?', 'Say it is great, and ask for a refill and the check.', '맛있다고 하고 리필과 계산서를 부탁하세요.', '[{"any":["refill","check","bill","top up"]}]', 'Everything''s great, thanks. Could I get a refill and the check, please?', '["It''s terrible. I want to speak to the manager.","Could I get another plate of pancakes?","Can I get a late checkout?"]', '["Ask for more coffee and the bill.","Key words: refill, the check"]', '["커피 한 잔 더와 계산서를 달라고 하세요.","핵심 단어: refill, the check"]', 'rosa', 'Sure thing. That''s fourteen fifty. No rush.', '그럼요. 14달러 50센트예요. 천천히 하세요.'),
  ('w_brunch', 5, 'rosa', 'The bill is $14.50. You pay with a twenty, and the rest is her tip.', '14달러 50센트입니다. 20달러를 내고 나머지는 팁으로 줍니다.', 'Do you need change?', 'Tell her to keep the change.', '잔돈은 가지라고 하세요.', '[{"all":["keep the change"]},{"all":["keep it"]},{"all":["no change"]},{"all":["all set"]}]', 'No, keep the change. Thanks, Rosa!', '["Yes, I need exact change for the bus.","Could you split it with the next table?","Can I pay you tomorrow?"]', '["Let her keep the rest as a tip.","Key words: keep the change"]', '["나머지를 팁으로 주세요.","핵심 단어: keep the change"]', 'rosa', 'Aw, thanks, hon. Have a good weekend!', '어머, 고마워요. 좋은 주말 보내요!'),
  ('w_neighbor_bbq', 1, 'carl', 'It is the weekend. Carl is out by the bus stop, walking his dog.', '주말입니다. 칼이 버스 정류장 근처에서 개를 산책시키고 있습니다.', 'Hey, stranger! Haven''t seen you around all week.', 'Explain that you were on a business trip to Ridgeport.', '리지포트로 출장을 갔었다고 설명하세요.', '[{"all":["trip"]},{"any":["traveling","travelling"]},{"all":["ridgeport"]},{"all":["out of town"]}]', 'Yeah, I was on a business trip to Ridgeport. I just got back last night.', '["Yeah, I''ve been sick in bed all week.","Sorry, do I know you?","I was at the office every night until midnight."]', '["Say where you were.","Key words: business trip, just got back"]', '["어디 있었는지 말하세요.","핵심 단어: business trip, just got back"]', 'carl', 'Ridgeport! How''d it go?', '리지포트! 어떻게 됐어요?');

/* part 2/6: w_neighbor_bbq#2 w_neighbor_bbq#3 w_neighbor_bbq#4 w_neighbor_bbq#5 d15_trip_report#1 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('w_neighbor_bbq', 2, 'carl', 'The contract was signed on Friday.', '금요일에 계약이 체결됐습니다.', 'How''d it go?', 'Say it went really well: you closed the deal.', '아주 잘 됐다고, 계약을 따냈다고 말하세요.', '[{"all":["closed"]},{"all":["signed"]},{"all":["went","well"]},{"all":["deal"]}]', 'It went really well. We closed the deal!', '["Not great. The client walked away.","It was raining the whole time.","I lost my luggage at the airport."]', '["Share the good news.","Key words: went really well, closed the deal"]', '["좋은 소식을 전하세요.","핵심 단어: went really well, closed the deal"]', 'carl', 'Well, look at you! Big shot. Hey, did you catch the game last night? What a finish!', '와, 대단한데요! 거물이네. 참, 어젯밤 경기 봤어요? 마무리 끝내줬는데!'),
  ('w_neighbor_bbq', 3, 'carl', 'You did not see the football game. You were busy traveling.', '풋볼 경기를 못 봤습니다. 이동하느라 바빴습니다.', 'Did you catch the game? What a finish!', 'Say you missed it, and ask who won.', '못 봤다고 하고 누가 이겼는지 물어보세요.', '[{"all":["who won"]},{"all":["missed"]},{"all":["final score"]},{"all":["did not see"]}]', 'No, I missed it. I was on a plane. Who won?', '["Yes, I scored the winning goal.","I don''t like sports, so please stop talking.","Can you recommend a good dentist?"]', '["Admit you didn''t watch it and ask about the result.","Key words: I missed it, who won"]', '["못 봤다고 하고 결과를 물어보세요.","핵심 단어: I missed it, who won"]', 'carl', 'We did, with a field goal in overtime! Hey, I''m grilling this afternoon. Want to come over?', '우리가 이겼죠, 연장전 필드골로! 참, 오늘 오후에 고기 굽는데 올래요?'),
  ('w_neighbor_bbq', 4, 'carl', 'Carl is inviting you to his backyard barbecue.', '칼이 뒷마당 바비큐에 초대합니다.', 'Nothing fancy. Burgers, hot dogs, a few neighbors. Four o''clock?', 'Accept, and ask what you can bring.', '좋다고 하고 무엇을 가져갈지 물어보세요.', '[{"all":["bring"]},{"all":["what can i"]}]', 'I''d love to! What can I bring?', '["Sorry, I don''t like meeting new people.","Four o''clock? I''ll be at work.","Can I invite my whole office?"]', '["Say yes and offer to bring something.","Key words: I''d love to, what can I bring"]', '["좋다고 하고 무언가 가져가겠다고 하세요.","핵심 단어: I''d love to, what can I bring"]', 'carl', 'Just yourself. Maybe some chips if you want. See you at four!', '몸만 와요. 원하면 칩 정도요. 4시에 봐요!'),
  ('w_neighbor_bbq', 5, 'carl', 'At four you show up in Carl''s backyard with a bag of chips. The grill is smoking.', '4시에 칩 한 봉지를 들고 칼의 뒷마당에 갑니다. 그릴에서 연기가 납니다.', 'There you are! How do you like your burger?', 'Say you would like it with cheese, well done.', '치즈를 넣어 바싹 익혀 달라고 하세요.', '[{"any":["cheese","cheeseburger","well done","medium","medium rare","no onions","plain"]}]', 'With cheese, please. Well done, if that''s okay.', '["I''ll get this one. It''s on the company.","Could I see the dessert menu?","No thanks, I already ate at the airport."]', '["Say how you want your burger cooked.","Key words: with cheese, well done"]', '["버거를 어떻게 해 줄지 말하세요.","핵심 단어: with cheese, well done"]', 'carl', 'Coming right up. Grab a drink from the cooler and make yourself at home.', '금방 돼요. 아이스박스에서 음료 꺼내고 편하게 있어요.'),
  ('d15_trip_report', 1, 'derek', 'It is the Monday standup. Everyone wants to hear about Ridgeport.', '월요일 스탠드업입니다. 모두 리지포트 이야기를 듣고 싶어 합니다.', 'Welcome back! So, how was the trip? Give us the highlights.', 'Report that the contract is signed, and phase one kicks off next week.', '계약이 체결됐고 1단계가 다음 주에 시작된다고 보고하세요.', '[{"all":["signed"]},{"all":["phase one"]},{"all":["closed"]},{"all":["contract"],"any":["done","signed","official"]}]', 'It went great. The contract is signed, and phase one kicks off next week.', '["It was fine. The hotel had a nice pool.","I didn''t really do anything there.","The flight was delayed, so I missed everything."]', '["Share the main result first.","Key words: contract is signed, phase one, next week"]', '["핵심 결과부터 말하세요.","핵심 단어: contract is signed, phase one, next week"]', 'derek', 'Awesome! What does that mean for our sprint?', '멋지다! 우리 스프린트엔 어떤 의미예요?');

/* part 3/6: d15_trip_report#2 d15_trip_report#3 d15_expenses#1 d15_expenses#2 d15_expenses#3 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d15_trip_report', 2, 'derek', 'The dashboard is due on November first.', '대시보드 마감은 11월 1일입니다.', 'What does that mean for our sprint?', 'Say the dashboard is the top priority now, and the deadline is November first.', '이제 대시보드가 최우선이고 마감은 11월 1일이라고 말하세요.', '[{"all":["priority"]},{"all":["november"]},{"all":["deadline"]},{"all":["dashboard"]}]', 'The dashboard is our top priority now. The deadline is November first.', '["Nothing changes. Let''s keep doing what we''re doing.","I think we should all take Friday off.","The mobile app is due tomorrow."]', '["Tell the team what comes first.","Key words: top priority, dashboard, deadline"]', '["무엇이 먼저인지 팀에 알리세요.","핵심 단어: top priority, dashboard, deadline"]', 'derek', 'Got it. Oh, and I fixed that store ID bug while you were out, by the way.', '알겠어요. 아, 그리고 당신 없는 동안 매장 ID 버그 고쳐 뒀어요.'),
  ('d15_trip_report', 3, 'derek', 'Derek covered for you while you were away.', '출장 중에 데릭이 당신 일을 맡아 주었습니다.', 'It was a quick fix. No big deal.', 'Thank him for covering for you.', '대신 맡아 줘서 고맙다고 말하세요.', '[{"any":["thank","thanks"]},{"all":["appreciate"]},{"all":["owe you"]}]', 'Thanks for covering for me. I owe you one.', '["Why did you touch my code?","Did you remember to water the plants?","I''ll send you the hotel bill."]', '["Show your appreciation.","Key words: thanks for covering, I owe you one"]', '["고마움을 표현하세요.","핵심 단어: thanks for covering, I owe you one"]', 'derek', 'Anytime. Alright, that''s standup. Let''s go build this thing.', '언제든지요. 자, 스탠드업 끝. 이제 만들러 갑시다.'),
  ('d15_expenses', 1, 'linda', 'You bring your trip receipts to Linda in HR.', '출장 영수증을 들고 인사팀 린다에게 갑니다.', 'Hi there! What can I do for you?', 'Say you would like to submit an expense report for your trip.', '출장 경비 보고서를 제출하고 싶다고 말하세요.', '[{"all":["expense report"]},{"all":["expenses"]},{"all":["receipts"]},{"any":["reimbursement","reimbursed"]}]', 'Hi Linda. I''d like to submit an expense report for my trip to Ridgeport.', '["Hi Linda. I''d like to book a vacation to Hawaii.","Hi, I lost my badge again.","Hi, where can I find the printer?"]', '["Say why you came.","Key words: submit an expense report"]', '["찾아온 이유를 말하세요.","핵심 단어: submit an expense report"]', 'linda', 'Sure! Did you keep all your receipts?', '그럼요! 영수증은 다 챙겼어요?'),
  ('d15_expenses', 2, 'linda', 'You have every receipt except one: the rideshare from the airport.', '영수증이 다 있는데 하나, 공항에서 탄 차량 호출 영수증이 없습니다.', 'Do you have receipts for everything?', 'Say you lost the receipt for the rideshare, and ask what to do.', '차량 호출 영수증을 잃어버렸다고 하고 어떻게 해야 하는지 물어보세요.', '[{"all":["lost"]},{"all":["missing"]},{"all":["cannot","find"]},{"all":["do not have","receipt"]}]', 'Almost. I lost the receipt for the rideshare from the airport. What should I do?', '["Yes, every single one is right here.","I didn''t take any taxis, so no.","Can I get cash back instead?"]', '["Admit the missing receipt and ask for help.","Key words: lost the receipt, what should I do"]', '["영수증이 없다고 말하고 방법을 물어보세요.","핵심 단어: lost the receipt, what should I do"]', 'linda', 'No problem. The ride app keeps a copy in your trip history. Just download it from there.', '괜찮아요. 앱의 이용 기록에 사본이 있어요. 거기서 내려받으면 돼요.'),
  ('d15_expenses', 3, 'linda', 'Your meals stayed under the $65 limit, and the client dinner went on the company card.', '식비는 65달러 한도 이내였고, 고객 저녁은 법인 카드로 냈습니다.', 'Did you go over the per diem on any day?', 'Say you stayed under the per diem, and the client dinner was on the company card.', '식비 한도를 넘지 않았고 고객 저녁은 법인 카드였다고 말하세요.', '[{"all":["under"]},{"all":["company card"]},{"all":["within"]}]', 'No, I stayed under the per diem. The client dinner was on the company card.', '["Yes, I spent three hundred dollars on lunch.","I don''t know what that means.","I put everything on my own credit card."]', '["Say you kept to the limit.","Key words: stayed under the per diem, company card"]', '["한도를 지켰다고 말하세요.","핵심 단어: stayed under the per diem, company card"]', 'linda', 'Perfect. You''ll be reimbursed by direct deposit. Anything else?', '완벽해요. 계좌로 환급될 거예요. 또 필요한 거 있어요?');

/* part 4/6: d15_expenses#4 d15_expenses#5 d15_raise#1 d15_raise#2 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d15_expenses', 4, 'linda', 'Your first paycheck came in two weeks ago, and it was much lower than the salary in your offer letter.', '2주 전에 첫 급여가 들어왔는데 제안서의 연봉보다 훨씬 적었습니다.', 'Anything else?', 'Ask why your paycheck is lower than you expected.', '급여가 예상보다 왜 적은지 물어보세요.', '[{"all":["paycheck"]},{"all":["lower"]},{"all":["less"]},{"all":["take home"]},{"all":["net pay"]}]', 'Yes, actually. My paycheck is lower than I expected. Why is that?', '["Can I get paid in cash from now on?","When is the next team lunch?","I think my salary is too high."]', '["Ask about the difference.","Key words: paycheck, lower than I expected"]', '["차이에 대해 물어보세요.","핵심 단어: paycheck, lower than I expected"]', 'linda', 'That''s gross versus net. Federal and state taxes, Social Security, Medicare and your 401(k) all come out before it hits your account.', '세전과 세후의 차이예요. 연방·주 소득세, 사회보장세, 메디케어, 401(k)가 계좌에 들어가기 전에 빠져요.'),
  ('d15_expenses', 5, 'linda', 'Linda checks your benefits page.', '린다가 복리후생 페이지를 확인합니다.', 'Right now you''re putting three percent into your 401(k). The company matches up to six.', 'Say you would like to raise your contribution to six percent to get the full match.', '회사 매칭을 전부 받도록 적립률을 6%로 올리고 싶다고 말하세요.', '[{"any":["six","6"]},{"all":["full match"]},{"all":["increase"]},{"all":["raise","contribution"]}]', 'Then I''d like to raise my contribution to six percent to get the full match.', '["Then I''d like to stop my contribution completely.","Can the company pay my rent instead?","Three percent is plenty. Leave it as it is."]', '["Don''t leave free money on the table.","Key words: raise my contribution, six percent, full match"]', '["공짜 돈을 놓치지 마세요.","핵심 단어: raise my contribution, six percent, full match"]', 'linda', 'Smart move. That''s free money. It''ll start with your next paycheck.', '현명해요. 공짜 돈이잖아요. 다음 급여부터 적용돼요.'),
  ('d15_raise', 1, 'maya', 'It is your check-in with Maya. After the Summit deal, you want to talk about your pay.', '마야와의 정기 면담입니다. 서밋 계약 후라 급여 이야기를 하고 싶습니다.', 'Great work on Summit. Greg emailed me to say you were a pleasure to work with. What''s on your mind?', 'Thank her, and say you would like to discuss your compensation.', '감사하다고 하고 보상(급여)에 대해 이야기하고 싶다고 말하세요.', '[{"any":["compensation","salary","raise","pay"]}]', 'Thanks, Maya. I''d like to discuss my compensation, if now is a good time.', '["I''d like to discuss my vacation plans.","I think Greg is a difficult client.","Could I get a bigger monitor?"]', '["Bring up the topic directly but politely.","Key words: discuss my compensation"]', '["주제를 정중하지만 분명히 꺼내세요.","핵심 단어: discuss my compensation"]', 'maya', 'Of course. Tell me what you''re thinking.', '물론이죠. 생각하는 걸 말해 봐요.'),
  ('d15_raise', 2, 'maya', 'You looked it up: developers with your skills in Fairview make about ten percent more.', '찾아보니 페어뷰에서 비슷한 역량의 개발자는 10%쯤 더 받습니다.', 'Tell me what you''re thinking.', 'Say that, based on your research, your salary is below the market rate.', '조사해 보니 당신 연봉이 시장 수준보다 낮다고 말하세요.', '[{"all":["market"]},{"all":["below"]},{"all":["research"]}]', 'I''ve done some research, and my salary is about ten percent below the market rate for my role.', '["I think I''m paid too much, honestly.","My neighbor got a new car last week.","I''d like to work fewer hours for the same pay."]', '["Use data, not feelings.","Key words: research, below the market rate"]', '["감정이 아니라 데이터를 쓰세요.","핵심 단어: research, below the market rate"]', 'maya', 'I appreciate you bringing data. I can''t change it mid-cycle, but I can make a case for you in the next review.', '데이터를 가져와 줘서 고마워요. 주기 중간에는 못 바꾸지만, 다음 평가 때 당신을 위해 근거를 마련할 수 있어요.');

/* part 5/6: d15_raise#3 d15_raise#4 d15_sick_call#1 d15_sick_call#2 d15_sick_call#3 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d15_raise', 3, 'maya', 'You want to know how to earn a bigger raise.', '더 큰 인상을 받으려면 어떻게 해야 하는지 알고 싶습니다.', 'I''ll make a case for you at the next review.', 'Ask what it would take to get to the next level.', '다음 단계로 올라가려면 무엇이 필요한지 물어보세요.', '[{"all":["what would it take"]},{"all":["next level"]},{"all":["promotion"]},{"all":["what","need","do"]}]', 'I understand. What would it take to get to the next level?', '["Then I''ll start looking for another job today.","Can we talk about it at the barbecue?","What time does the office close tonight?"]', '["Ask about the path forward.","Key words: what would it take, next level"]', '["앞으로의 방향을 물어보세요.","핵심 단어: what would it take, next level"]', 'maya', 'Keep owning projects like Summit, and start mentoring new hires. How about we write down three goals?', '서밋 같은 프로젝트를 계속 책임지고, 신입 멘토링도 시작해요. 목표 세 개를 적어 볼까요?'),
  ('d15_raise', 4, 'maya', 'Maya opens a document for your goals.', '마야가 목표를 적을 문서를 엽니다.', 'Let''s write down three goals and check in every month.', 'Agree, and ask if you could review your progress again in three months.', '동의하고, 3개월 뒤에 진행 상황을 다시 검토할 수 있는지 물어보세요.', '[{"any":["three months","3 months","quarter"]},{"all":["sounds good"]},{"all":["progress"]}]', 'That sounds good. Could we review my progress again in three months?', '["No thanks. I don''t like setting goals.","Could you give me the raise in cash?","Let''s talk again in five years."]', '["Agree and set a date to follow up.","Key words: sounds good, review my progress, three months"]', '["동의하고 다시 이야기할 시점을 정하세요.","핵심 단어: sounds good, review my progress, three months"]', 'maya', 'Deal. I''ll put it on the calendar. And seriously, great job this month.', '좋아요. 캘린더에 넣어 둘게요. 그리고 진심으로, 이번 달 정말 잘했어요.'),
  ('d15_sick_call', 1, 'maya', 'It is Monday night. You have a fever and a sore throat, so you call Maya from home.', '월요일 밤입니다. 열이 나고 목이 아파서 집에서 마야에게 전화합니다.', 'Hey, it''s Maya. Everything okay?', 'Say sorry for calling late, and that you are not feeling well.', '늦게 전화해서 미안하다고 하고 몸이 좋지 않다고 말하세요.', '[{"all":["not feeling"]},{"all":["sick"]},{"all":["fever"]},{"all":["under the weather"]},{"all":["sore throat"]}]', 'Hi Maya. Sorry to call so late. I''m not feeling well. I have a fever and a sore throat.', '["Hi Maya. I''m feeling great, thanks!","Hi Maya. I just wanted to say good night.","Hi Maya. Did you watch the game?"]', '["Explain how you feel.","Key words: not feeling well, fever"]', '["몸 상태를 설명하세요.","핵심 단어: not feeling well, fever"]', 'maya', 'Oh no, I''m sorry to hear that. Do you want to take tomorrow off?', '어머, 안됐네요. 내일 쉴래요?'),
  ('d15_sick_call', 2, 'maya', 'You need rest, not meetings.', '회의가 아니라 휴식이 필요합니다.', 'Do you want to take tomorrow off?', 'Say you are going to take a sick day tomorrow.', '내일 병가를 내겠다고 말하세요.', '[{"all":["sick day"]},{"all":["day off"]},{"all":["take","off"]},{"all":["stay home"]},{"all":["rest"]}]', 'Yes, I think I''m going to take a sick day tomorrow.', '["I''ll take the early bus tomorrow.","I''m going to the office party tomorrow night.","Can you send me the meeting notes tonight?"]', '["Say you won''t come in tomorrow.","Key words: take a sick day"]', '["내일 출근하지 않겠다고 말하세요.","핵심 단어: take a sick day"]', 'maya', 'Of course. Just rest. Is there anything that needs covering?', '그럼요. 푹 쉬어요. 대신 맡아야 할 일 있어요?'),
  ('d15_sick_call', 3, 'maya', 'You have the phase one planning meeting at ten tomorrow.', '내일 10시에 1단계 기획 회의가 있습니다.', 'Is there anything that needs covering?', 'Ask if Derek could cover the planning meeting, and say you will check email if anything is urgent.', '데릭이 기획 회의를 대신할 수 있는지 묻고, 급한 일이 있으면 메일을 보겠다고 말하세요.', '[{"all":["derek"]},{"all":["cover"]},{"all":["urgent"]}]', 'Could Derek cover the planning meeting at ten? I''ll check email if anything is urgent.', '["No, just cancel all my meetings forever.","Could you bring me some soup?","I''ll be at the gym, so don''t call."]', '["Suggest who can take your meeting.","Key words: Derek, cover, urgent"]', '["회의를 누가 대신할지 제안하세요.","핵심 단어: Derek, cover, urgent"]', 'maya', 'I''ll ask Derek. Don''t worry about work. Feel better, okay?', '데릭에게 부탁할게요. 일 걱정은 말고요. 얼른 나아요.');

/* part 6/6: d15_sick_call#4 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('d15_sick_call', 4, 'maya', 'Maya is about to hang up.', '마야가 전화를 끊으려 합니다.', 'Feel better, okay? Let me know how you''re doing.', 'Thank her and say you will keep her posted.', '고맙다고 하고 계속 소식 전하겠다고 말하세요.', '[{"all":["keep you posted"]},{"all":["let you know"]},{"any":["thank","thanks"]}]', 'Thanks, Maya. I''ll keep you posted.', '["Sorry, I can''t hear you. You''re breaking up.","See you at the office at nine!","Can I borrow your car tomorrow?"]', '["Say thanks and promise an update.","Key words: thanks, keep you posted"]', '["고맙다고 하고 소식을 전하겠다고 하세요.","핵심 단어: thanks, keep you posted"]', 'maya', 'Take care. Get some sleep.', '몸조심해요. 푹 자고요.');

/* part 1/3: w_brunch.to_start w_brunch.over_easy w_brunch.can_i_get w_brunch.hash_browns w_brunch.hows_everything w_brunch.refill w_brunch.keep_the_change w_brunch.no_rush w_neighbor_bbq.hey_stranger w_neighbor_bbq.just_got_back w_neighbor_bbq.closed_the_deal w_neighbor_bbq.catch_the_game w_neighbor_bbq.what_a_finish w_neighbor_bbq.come_over w_neighbor_bbq.what_can_i_bring w_neighbor_bbq.make_yourself_at_home d15_trip_report.welcome_back d15_trip_report.highlights d15_trip_report.kicks_off d15_trip_report.top_priority d15_trip_report.while_you_were_out d15_trip_report.owe_you_one d15_trip_report.anytime ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('w_brunch.to_start', 'w_brunch', 'Coffee to start?', '커피부터 드릴까요?', 'Diner servers often offer coffee right away.', '다이너 서버는 보통 커피부터 권합니다.', 'restaurant'),
  ('w_brunch.over_easy', 'w_brunch', 'Two eggs over easy, please.', '달걀 두 개, 오버 이지로요.', 'Egg styles: sunny side up, over easy, over medium, over hard, scrambled.', '달걀 방식: sunny side up, over easy, over medium, over hard, scrambled.', 'restaurant'),
  ('w_brunch.can_i_get', 'w_brunch', 'Can I get …?', '…주실래요?', 'The most common way to order in casual American restaurants.', '미국 캐주얼 식당에서 가장 흔한 주문 표현입니다.', 'restaurant'),
  ('w_brunch.hash_browns', 'w_brunch', 'Hash browns or home fries?', '해시 브라운이요, 홈 프라이요?', 'Hash browns are shredded potatoes. Home fries are cubes.', '해시 브라운은 채 썬 감자, 홈 프라이는 깍둑 썬 감자입니다.', 'restaurant'),
  ('w_brunch.hows_everything', 'w_brunch', 'How''s everything tasting?', '음식 맛은 괜찮으세요?', 'Servers check in during the meal. Great, thanks! is enough.', '식사 중 서버가 묻습니다. Great, thanks!면 충분합니다.', 'restaurant'),
  ('w_brunch.refill', 'w_brunch', 'Could I get a refill?', '리필해 주실래요?', 'Coffee and soft drinks are usually refilled for free.', '커피와 탄산음료는 보통 무료로 리필해 줍니다.', 'restaurant'),
  ('w_brunch.keep_the_change', 'w_brunch', 'Keep the change.', '잔돈은 가지세요.', 'The change becomes the tip.', '잔돈이 팁이 됩니다.', 'restaurant'),
  ('w_brunch.no_rush', 'w_brunch', 'No rush.', '천천히 하세요.', 'Take your time.', '서두르지 않아도 된다는 뜻입니다.', 'small-talk'),
  ('w_neighbor_bbq.hey_stranger', 'w_neighbor_bbq', 'Hey, stranger!', '오랜만이에요!', 'A friendly greeting for someone you haven''t seen in a while.', '한동안 못 본 사람에게 하는 친근한 인사입니다.', 'small-talk'),
  ('w_neighbor_bbq.just_got_back', 'w_neighbor_bbq', 'I just got back last night.', '어젯밤에 막 돌아왔어요.', 'Get back = return from a trip.', 'get back은 여행에서 돌아온다는 뜻입니다.', 'small-talk'),
  ('w_neighbor_bbq.closed_the_deal', 'w_neighbor_bbq', 'We closed the deal!', '계약을 따냈어요!', 'Close a deal = successfully finish a sale or agreement.', 'close a deal은 거래를 성사시킨다는 뜻입니다.', 'negotiation'),
  ('w_neighbor_bbq.catch_the_game', 'w_neighbor_bbq', 'Did you catch the game?', '경기 봤어요?', 'Catch = watch. In fall, the game usually means American football.', 'catch는 본다는 뜻입니다. 가을에 the game은 보통 미식축구입니다.', 'small-talk'),
  ('w_neighbor_bbq.what_a_finish', 'w_neighbor_bbq', 'What a finish!', '마무리 끝내줬죠!', 'An exciting end to a game.', '경기의 짜릿한 끝을 말합니다.', 'small-talk'),
  ('w_neighbor_bbq.come_over', 'w_neighbor_bbq', 'Want to come over?', '우리 집에 올래요?', 'Come over = visit someone''s home.', 'come over는 누군가의 집에 놀러 간다는 뜻입니다.', 'small-talk'),
  ('w_neighbor_bbq.what_can_i_bring', 'w_neighbor_bbq', 'What can I bring?', '뭐 가져갈까요?', 'Americans often bring chips, drinks or a side dish to a barbecue.', '미국인은 바비큐에 칩, 음료, 곁들임 음식을 자주 가져갑니다.', 'small-talk'),
  ('w_neighbor_bbq.make_yourself_at_home', 'w_neighbor_bbq', 'Make yourself at home.', '편하게 있어요.', 'Said by a host to a guest.', '집주인이 손님에게 하는 말입니다.', 'small-talk'),
  ('d15_trip_report.welcome_back', 'd15_trip_report', 'Welcome back!', '돌아온 걸 환영해요!', 'Said to someone returning from a trip or time off.', '출장이나 휴가에서 돌아온 사람에게 하는 말입니다.', 'office'),
  ('d15_trip_report.highlights', 'd15_trip_report', 'Give us the highlights.', '핵심만 말해 줘요.', 'Highlights = the most important or interesting parts.', 'highlights는 가장 중요하거나 흥미로운 부분입니다.', 'meeting'),
  ('d15_trip_report.kicks_off', 'd15_trip_report', 'Phase one kicks off next week.', '1단계가 다음 주에 시작돼요.', 'Kick off = start. Kickoff (noun) = a first meeting.', 'kick off는 시작하다, kickoff(명사)는 첫 회의입니다.', 'meeting'),
  ('d15_trip_report.top_priority', 'd15_trip_report', 'The dashboard is our top priority.', '대시보드가 최우선이에요.', 'Top priority = the most important task.', 'top priority는 가장 중요한 일입니다.', 'meeting'),
  ('d15_trip_report.while_you_were_out', 'd15_trip_report', 'while you were out', '당신이 없는 동안', 'Out = not in the office.', 'out은 사무실에 없다는 뜻입니다.', 'office'),
  ('d15_trip_report.owe_you_one', 'd15_trip_report', 'I owe you one.', '신세 졌어요.', 'You did me a favor, and I will return it.', '도움을 받았으니 갚겠다는 뜻입니다.', 'small-talk'),
  ('d15_trip_report.anytime', 'd15_trip_report', 'Anytime.', '언제든지요.', 'A friendly reply to thanks.', '감사 인사에 대한 친근한 대답입니다.', 'small-talk');

/* part 2/3: d15_expenses.submit_expenses d15_expenses.lost_receipt d15_expenses.under_per_diem d15_expenses.reimbursed d15_expenses.gross_net d15_expenses.take_home d15_expenses.full_match d15_expenses.free_money d15_raise.pleasure_to_work d15_raise.whats_on_your_mind d15_raise.discuss_compensation d15_raise.market_rate d15_raise.make_a_case d15_raise.mid_cycle d15_raise.what_would_it_take d15_sick_call.not_feeling_well d15_sick_call.under_the_weather d15_sick_call.sore_throat d15_sick_call.sick_day d15_sick_call.needs_covering d15_sick_call.keep_you_posted ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d15_expenses.submit_expenses', 'd15_expenses', 'I''d like to submit an expense report.', '경비 보고서를 제출하고 싶어요.', 'An expense report lists the work costs you paid yourself.', '경비 보고서는 업무로 직접 낸 비용을 정리한 것입니다.', 'hr'),
  ('d15_expenses.lost_receipt', 'd15_expenses', 'I lost the receipt.', '영수증을 잃어버렸어요.', 'Apps and cards usually keep a digital copy.', '앱이나 카드사에 보통 전자 사본이 있습니다.', 'hr'),
  ('d15_expenses.under_per_diem', 'd15_expenses', 'I stayed under the per diem.', '식비 한도를 넘지 않았어요.', 'Go over = spend more than allowed. Stay under = spend less.', 'go over는 초과, stay under는 이내라는 뜻입니다.', 'hr'),
  ('d15_expenses.reimbursed', 'd15_expenses', 'You''ll be reimbursed by direct deposit.', '계좌로 환급될 거예요.', 'Direct deposit = money sent straight to your bank account.', 'direct deposit은 은행 계좌로 바로 입금되는 것입니다.', 'hr'),
  ('d15_expenses.gross_net', 'd15_expenses', 'That''s gross versus net.', '세전과 세후의 차이예요.', 'Gross = before deductions. Net = what you take home.', 'gross는 공제 전, net은 실수령액입니다.', 'money'),
  ('d15_expenses.take_home', 'd15_expenses', 'take-home pay', '실수령액', 'The amount that actually reaches your bank account.', '실제로 계좌에 들어오는 금액입니다.', 'money'),
  ('d15_expenses.full_match', 'd15_expenses', 'to get the full match', '회사 매칭을 전부 받으려고', 'Many US companies add money to your 401(k) retirement account up to a limit.', '미국 회사는 401(k) 퇴직연금에 일정 한도까지 돈을 보태 줍니다.', 'money'),
  ('d15_expenses.free_money', 'd15_expenses', 'That''s free money.', '공짜 돈이잖아요.', 'Something you get without extra cost.', '추가 비용 없이 받는 돈입니다.', 'money'),
  ('d15_raise.pleasure_to_work', 'd15_raise', 'You were a pleasure to work with.', '함께 일해서 즐거웠어요.', 'A strong compliment from a client or colleague.', '고객이나 동료가 하는 큰 칭찬입니다.', 'office'),
  ('d15_raise.whats_on_your_mind', 'd15_raise', 'What''s on your mind?', '무슨 생각 해요? (하고 싶은 말이 뭐예요?)', 'An invitation to bring up a topic.', '하고 싶은 이야기를 꺼내라는 말입니다.', 'hr'),
  ('d15_raise.discuss_compensation', 'd15_raise', 'I''d like to discuss my compensation.', '제 보상에 대해 이야기하고 싶어요.', 'Compensation = salary plus bonus and benefits. More formal than pay.', 'compensation은 급여에 보너스와 복리후생을 더한 것으로, pay보다 격식 있습니다.', 'hr'),
  ('d15_raise.market_rate', 'd15_raise', 'My salary is below the market rate.', '제 연봉이 시장 수준보다 낮아요.', 'Market rate = what other companies pay for the same role.', 'market rate는 다른 회사가 같은 역할에 주는 금액입니다.', 'hr'),
  ('d15_raise.make_a_case', 'd15_raise', 'I''ll make a case for you.', '당신을 위해 근거를 마련할게요.', 'Make a case = argue for something with reasons.', 'make a case는 근거를 들어 주장한다는 뜻입니다.', 'hr'),
  ('d15_raise.mid_cycle', 'd15_raise', 'I can''t change it mid-cycle.', '평가 주기 중간에는 바꿀 수 없어요.', 'Many companies change salaries only once or twice a year.', '많은 회사가 1년에 한두 번만 연봉을 조정합니다.', 'hr'),
  ('d15_raise.what_would_it_take', 'd15_raise', 'What would it take to get to the next level?', '다음 단계로 가려면 무엇이 필요할까요?', 'A positive way to ask about promotion.', '승진에 대해 긍정적으로 묻는 방법입니다.', 'hr'),
  ('d15_sick_call.not_feeling_well', 'd15_sick_call', 'I''m not feeling well.', '몸이 좋지 않아요.', 'The simplest way to say you are sick.', '아프다는 것을 말하는 가장 간단한 방법입니다.', 'hr'),
  ('d15_sick_call.under_the_weather', 'd15_sick_call', 'I''m a bit under the weather.', '몸이 좀 안 좋아요.', 'A softer, casual way to say you are sick.', '아프다는 것을 부드럽고 가볍게 말하는 표현입니다.', 'hr'),
  ('d15_sick_call.sore_throat', 'd15_sick_call', 'I have a fever and a sore throat.', '열이 나고 목이 아파요.', 'Also: a cough, a headache, a stomachache.', '그 밖에 a cough, a headache, a stomachache.', 'hr'),
  ('d15_sick_call.sick_day', 'd15_sick_call', 'I''m going to take a sick day.', '병가를 낼게요.', 'US companies give a set number of paid sick days per year.', '미국 회사는 1년에 정해진 수의 유급 병가를 줍니다.', 'hr'),
  ('d15_sick_call.needs_covering', 'd15_sick_call', 'Is there anything that needs covering?', '대신 맡아야 할 일 있어요?', 'Cover = handle someone else''s work.', 'cover는 다른 사람의 일을 맡는다는 뜻입니다.', 'office'),
  ('d15_sick_call.keep_you_posted', 'd15_sick_call', 'I''ll keep you posted.', '계속 소식 전할게요.', 'Keep someone posted = give them updates.', 'keep someone posted는 계속 소식을 알린다는 뜻입니다.', 'office');

/* part 3/3: d15_sick_call.feel_better --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- */
REPLACE INTO phrases (id, episode, text, meaning_ko, note, note_ko, category) VALUES
  ('d15_sick_call.feel_better', 'd15_sick_call', 'Feel better!', '얼른 나아요!', 'What you say to someone who is sick.', '아픈 사람에게 하는 말입니다.', 'small-talk');
