-- Everyday realism: sales tax and tips, opening hours, where people are through the day, the weather, small talk
-- about it, and bills on autopay.
REPLACE INTO config (k, v, note) VALUES
  ('sales_tax', '0.0825', 'sales tax on meals, drinks and other goods (8.25%); groceries and fares are not taxed'),
  ('tip_options', '0,15,18,20', 'tip choices in percent where food or drinks are served'),
  ('tip_default', '18', 'the tip chosen at first where you are served at a table (diner, restaurant); 0 at a counter'),
  ('hours_diner', '06:30-21:30', 'Sunny Side Diner opening hours'),
  ('hours_market', '07:00-22:00', 'Fairview Market opening hours'),
  ('hours_coffee_cart', '06:30-15:00', 'the coffee cart on weekdays'),
  ('hours_coffee_cart_weekend', '08:00-14:00', 'the coffee cart on Saturday and Sunday');

-- Office people work Monday to Friday and take lunch in the kitchen at different times; nobody is in at the weekend.
REPLACE INTO schedule (npc, seq, days, time_from, time_to, place) VALUES
  ('tom', 1, 'weekday', '07:45', '17:30', 'office_lobby'),
  ('maya', 1, 'weekday', '08:15', '12:15', 'office_manager'),
  ('maya', 2, 'weekday', '12:15', '12:50', 'office_kitchen'),
  ('maya', 3, 'weekday', '12:50', '18:15', 'office_manager'),
  ('derek', 1, 'weekday', '08:50', '12:45', 'office_desk_team'),
  ('derek', 2, 'weekday', '12:45', '13:20', 'office_kitchen'),
  ('derek', 3, 'weekday', '13:20', '18:45', 'office_desk_team'),
  ('priya', 1, 'weekday', '09:00', '13:20', 'office_meeting'),
  ('priya', 2, 'weekday', '13:20', '13:50', 'office_kitchen'),
  ('priya', 3, 'weekday', '13:50', '17:45', 'office_meeting'),
  ('sam', 1, 'weekday', '08:30', '11:40', 'office_it'),
  ('sam', 2, 'weekday', '11:40', '12:15', 'office_kitchen'),
  ('sam', 3, 'weekday', '12:15', '17:30', 'office_it'),
  ('linda', 1, 'weekday', '08:30', '13:50', 'office_hr'),
  ('linda', 2, 'weekday', '13:50', '14:20', 'office_kitchen'),
  ('linda', 3, 'weekday', '14:20', '17:00', 'office_hr'),
  ('rosa', 1, 'all', '06:30', '21:30', 'diner_counter'),
  ('mike', 1, 'all', '07:00', '22:00', 'market_checkout'),
  ('nina', 1, 'weekday', '06:30', '15:00', 'coffee_cart'),
  ('nina', 2, 'weekend', '08:00', '14:00', 'coffee_cart'),
  ('carl', 1, 'weekday', '07:00', '09:30', 'bus_stop'),
  ('carl', 2, 'weekday', '15:00', '18:30', 'park_bench'),
  ('carl', 3, 'weekend', '08:00', '18:30', 'park_bench'),
  ('carl', 4, 'all', '18:30', '21:00', 'apartment_door');

REPLACE INTO weather (day, kind, high_f, low_f, forecast, forecast_ko) VALUES
  (1, 'clear', 74, 56, 'Sunny and mild. A great start to the week.', '맑고 온화합니다. 한 주를 시작하기 좋은 날이에요.'),
  (2, 'partly', 72, 55, 'Partly cloudy with a light breeze.', '구름이 조금 끼고 바람이 살짝 붑니다.'),
  (3, 'rain', 63, 52, 'Rain on and off all day. Bring an umbrella.', '하루 종일 비가 오락가락합니다. 우산을 챙기세요.'),
  (4, 'cloudy', 66, 53, 'Overcast and cool. The rain has moved out.', '흐리고 선선합니다. 비는 지나갔어요.'),
  (5, 'clear', 73, 54, 'Clear skies for Friday. Perfect patio weather.', '금요일은 맑은 하늘. 야외 자리에 앉기 딱 좋은 날씨예요.'),
  (6, 'clear', 76, 57, 'Sunny and warm. A beautiful Saturday.', '맑고 따뜻합니다. 아름다운 토요일이에요.'),
  (7, 'clear', 75, 58, 'Mostly sunny, with a few clouds late in the day.', '대체로 맑고 늦게 구름이 조금 낍니다.'),
  (8, 'fog', 68, 51, 'Foggy this morning, clearing up by noon.', '아침에 안개가 끼고 정오쯤 갭니다.'),
  (9, 'rain', 61, 50, 'A rainy day. Expect a wet commute.', '비 오는 날. 출퇴근길이 젖겠어요.'),
  (10, 'cloudy', 64, 49, 'Cloudy and chilly. You might want a jacket.', '흐리고 쌀쌀합니다. 재킷을 입는 게 좋겠어요.'),
  (11, 'clear', 70, 50, 'Clear and calm. Good flying weather.', '맑고 바람이 없습니다. 비행하기 좋은 날씨예요.'),
  (12, 'partly', 71, 52, 'Partly sunny. No delays expected.', '구름 사이로 해가 납니다. 지연은 없을 거예요.'),
  (13, 'clear', 77, 56, 'Sunny and warm. Great weather for a barbecue.', '맑고 따뜻합니다. 바비큐 하기 좋은 날씨예요.'),
  (14, 'rain', 62, 51, 'Showers through the afternoon. A good day to stay in.', '오후까지 소나기. 집에 있기 좋은 날이에요.'),
  (15, 'cloudy', 65, 50, 'Gray skies, but dry.', '하늘은 흐리지만 비는 오지 않아요.'),
  (16, 'clear', 69, 49, 'Crisp and sunny. It feels like fall.', '상쾌하고 맑습니다. 가을 느낌이 나요.'),
  (17, 'partly', 68, 50, 'A mix of sun and clouds.', '해와 구름이 번갈아 나옵니다.'),
  (18, 'rain', 59, 48, 'Steady rain and a cool breeze. Bundle up.', '비가 계속 오고 바람이 찹니다. 따뜻하게 입으세요.'),
  (19, 'clear', 67, 47, 'Sunny for payday Friday.', '월급날 금요일은 맑습니다.'),
  (20, 'clear', 70, 49, 'Blue skies all day.', '하루 종일 파란 하늘이에요.'),
  (21, 'fog', 66, 48, 'Morning fog, then some sun.', '아침 안개 뒤에 해가 조금 납니다.');

REPLACE INTO smalltalk (topic, seq, line, line_ko) VALUES
  ('weather:clear', 1, 'Beautiful day, isn''t it?', '날씨 정말 좋죠?'),
  ('weather:clear', 2, 'Can you believe this weather? Not a cloud in the sky.', '이 날씨 믿어져요? 구름 한 점 없어요.'),
  ('weather:clear', 3, 'It''s too nice out to be stuck inside.', '안에만 있기엔 날씨가 너무 좋아요.'),
  ('weather:partly', 1, 'Nice out today. Not too hot, not too cold.', '오늘 날씨 좋네요. 덥지도 춥지도 않고요.'),
  ('weather:partly', 2, 'I heard it might cloud over later.', '이따가 구름이 낄 수도 있대요.'),
  ('weather:cloudy', 1, 'Kind of a gloomy day, huh?', '좀 우중충한 날이죠?'),
  ('weather:cloudy', 2, 'It looks like it could rain any minute.', '금방이라도 비가 올 것 같아요.'),
  ('weather:cloudy', 3, 'It got chilly all of a sudden.', '갑자기 쌀쌀해졌어요.'),
  ('weather:rain', 1, 'It''s really coming down out there.', '밖에 비가 정말 많이 와요.'),
  ('weather:rain', 2, 'Did you get caught in the rain?', '비 맞았어요?'),
  ('weather:rain', 3, 'I forgot my umbrella. Of course.', '우산을 깜빡했어요. 꼭 이런다니까요.'),
  ('weather:rain', 4, 'Stay dry out there!', '비 맞지 말고 다녀요!'),
  ('weather:fog', 1, 'I could barely see the road this morning.', '오늘 아침엔 길이 거의 안 보였어요.'),
  ('weather:fog', 2, 'It''s so foggy out. Drive safe.', '안개가 많이 꼈어요. 운전 조심해요.'),
  ('day:monday', 1, 'How was your weekend?', '주말 어땠어요?'),
  ('day:monday', 2, 'Mondays, am I right?', '월요일이 다 그렇죠, 안 그래요?'),
  ('day:friday', 1, 'Happy Friday!', '즐거운 금요일!'),
  ('day:friday', 2, 'Any plans for the weekend?', '주말에 무슨 계획 있어요?'),
  ('day:friday', 3, 'We made it. It''s finally Friday.', '해냈네요. 드디어 금요일이에요.'),
  ('day:weekend', 1, 'Enjoying your weekend?', '주말 잘 보내고 있어요?'),
  ('day:weekend', 2, 'Taking it easy today?', '오늘은 쉬엄쉬엄 보내요?'),
  ('time:morning', 1, 'Good morning! You''re here early.', '좋은 아침! 일찍 왔네요.'),
  ('time:morning', 2, 'Morning! I''m not awake until my second coffee.', '좋은 아침! 커피 두 잔은 마셔야 잠이 깨요.'),
  ('time:lunch', 1, 'Have you had lunch yet?', '점심 먹었어요?'),
  ('time:lunch', 2, 'I''m starving. Is it lunchtime yet?', '배고파 죽겠어요. 아직 점심시간 안 됐어요?'),
  ('time:evening', 1, 'Long day, huh? Get some rest.', '긴 하루였죠? 좀 쉬어요.'),
  ('time:evening', 2, 'Heading home? Have a good one!', '집에 가요? 좋은 저녁 보내요!');

REPLACE INTO bills (id, name, name_ko, amount, day, every, note) VALUES
  ('renters_insurance', 'Renters insurance', '세입자 보험', 14.00, 3, 30, 'autopay from your checking account'),
  ('phone', 'Phone plan', '휴대전화 요금', 45.00, 8, 30, 'unlimited talk and text, autopay discount'),
  ('streaming', 'Streaming subscription', '스트리밍 구독', 15.49, 10, 30, 'renews every month until you cancel'),
  ('utilities', 'Electric and gas bill', '전기·가스 요금', 68.40, 12, 30, 'Fairview Power, autopay'),
  ('internet', 'Home internet', '인터넷 요금', 55.00, 16, 30, '300 Mbps, no contract');
