-- Replying to messages, calling back a voicemail, and the mailbox at home.
-- Push the CREATE TABLE replies and CREATE TABLE mail statements of db/schema.sql first.
REPLACE INTO config (k, v, note) VALUES
  ('mail_time', '13:00', 'the mail comes to the mailbox after this (not on Sundays and federal holidays)');

REPLACE INTO messages (id, hero, day, time, kind, sender, subject, body, body_ko) VALUES
  ('m09_linda_vm', 'all', 9, '15:15', 'voicemail', 'linda', NULL, 'Hi {name}, it''s Linda from HR. I need your signature on one more form for your benefits enrollment. Could you stop by my office when you have a minute? Thanks!', '안녕하세요, 인사팀 린다예요. 복리후생 가입 서류에 서명이 하나 더 필요해요. 시간 될 때 제 사무실에 들러 주실래요? 고마워요! (stop by: 잠깐 들르다)'),
  ('m10_pharmacy', 'all', 10, '15:40', 'voicemail', 'Fairview Pharmacy', NULL, 'Hello, this is Fairview Pharmacy calling for {name}. Your prescription is ready for pickup. We are open until 7 PM today. Please bring your ID.', '안녕하세요, 페어뷰 약국입니다. 처방약이 준비되었습니다. 오늘은 오후 7시까지 엽니다. 신분증을 가져오세요. (prescription: 처방약, pickup: 찾아가기)'),
  ('m12_dental_vm', 'all', 12, '10:20', 'voicemail', 'Fairview Dental', NULL, 'Hi {name}, this is Amy at Fairview Dental. I''m calling about your cleaning on the 20th. We need to move it to 10:30 AM. Please give us a call back at your convenience. Thanks!', '안녕하세요, 페어뷰 치과의 에이미예요. 20일 스케일링을 오전 10시 30분으로 옮겨야 해요. 편하실 때 다시 전화 주세요. 고맙습니다! (call back: 회신 전화하다, at your convenience: 편하실 때)');

REPLACE INTO replies (id, msg, sort, label, label_ko, tone, tip_ko, answer, answer_ko, answer_from, delay) VALUES
  ('m01_tom_a', 'm01_tom', 1, 'Hi Tom, count me in for the 29th. Thanks for organizing!', '톰, 29일에 참석할게요. 준비해 줘서 고마워요!', 'good', '"Count me in"은 참석하겠다는 자연스러운 말이에요.', 'Great, you are on the list! See you there.', '좋아요, 명단에 넣었어요! 그날 봐요.', NULL, 30),
  ('m01_tom_b', 'm01_tom', 2, 'I come to lunch. Yes.', '점심에 가요. 네.', 'ok', '뜻은 통하지만 어색해요. "I''ll be there." 또는 "Count me in."이 좋아요.', 'Got it, thanks.', '알겠어요, 고마워요.', NULL, 30),
  ('m01_tom_c', 'm01_tom', 3, 'Thanks for the invite, Tom, but I can''t make it that day. Save me a slice!', '초대 고맙지만 그날은 못 가요, 톰. 피자 한 조각 남겨 줘요!', 'good', '"I can''t make it"은 정중하게 거절할 때 써요.', 'No problem! I will save you a slice.', '괜찮아요! 한 조각 남겨 둘게요.', NULL, 30),
  ('m01_carl_a', 'm01_carl', 1, 'Thanks, Carl! Good to know. I will put them out Wednesday night.', '고마워요, 칼! 덕분에 알았어요. 수요일 밤에 내놓을게요.', 'good', '고마움을 표하고 할 일을 덧붙이면 더 친절해요.', 'You are welcome! Welcome to the building.', '별말씀을요! 이 건물에 오신 걸 환영해요.', NULL, 8),
  ('m01_carl_b', 'm01_carl', 2, 'Ok thank you.', '네 고마워요.', 'ok', '공손하지만 짧아요. 이웃이라면 한마디 더 붙이면 좋아요.', 'Anytime.', '언제든지요.', NULL, 8),
  ('m01_carl_c', 'm01_carl', 3, 'Why are you telling me this?', '왜 저한테 이걸 알려 주세요?', 'poor', '도와주려던 이웃에게 퉁명스럽게 들려요.', 'Oh, sorry. I just thought it might help. Never mind!', '아, 미안해요. 도움이 될까 해서요. 신경 쓰지 마세요!', NULL, 8),
  ('m02_dental_a', 'm02_dental', 1, 'C', 'C', 'good', '자동 문자는 안내한 글자 그대로 답해야 알아들어요.', 'Thanks! Your cleaning is confirmed for Oct 20 at 8:30 AM. See you then.', '감사합니다! 10월 20일 오전 8시 30분 스케일링이 확정되었습니다.', NULL, 1),
  ('m02_dental_b', 'm02_dental', 2, 'Thanks! I need to reschedule. Can I call you tomorrow?', '고마워요! 일정을 바꿔야 해요. 내일 전화해도 될까요?', 'ok', '자동 문자는 이런 문장을 못 알아들어요. 일정 변경은 전화로 해요.', 'Sorry, we did not understand your reply. Reply C to confirm, or call us to reschedule.', '죄송합니다, 답장을 이해하지 못했어요. 확정은 C, 변경은 전화 주세요.', NULL, 1),
  ('m04_mom_jun_a', 'm04_mom_jun', 1, 'Work is going well, Mom! I am eating fine. I will call on Sunday. Love you!', '일은 잘 되고 있어요, 엄마! 밥도 잘 먹어요. 일요일에 전화할게요. 사랑해요!', 'good', '안부 질문마다 하나씩 답하면 걱정을 덜어 드려요.', 'So proud of you! Love you too.', '정말 자랑스럽구나! 나도 사랑해.', NULL, 5),
  ('m04_mom_jun_b', 'm04_mom_jun', 2, 'Fine.', '괜찮아요.', 'poor', '"Fine."만 보내면 퉁명스럽게 들려요.', 'Just fine? Please call us on Sunday. 😊', '그냥 괜찮다고? 일요일에 꼭 전화하렴.', NULL, 5),
  ('m04_mom_jun_c', 'm04_mom_jun', 3, 'Busy, but good. Can we talk Sunday evening?', '바쁘지만 좋아요. 일요일 저녁에 통화할까요?', 'good', '시간을 제안하면 약속이 분명해져요.', 'Of course! Sunday evening works. Dad will be happy.', '물론이지! 일요일 저녁 좋아. 아빠가 좋아하시겠다.', NULL, 5);

REPLACE INTO replies (id, msg, sort, label, label_ko, tone, tip_ko, answer, answer_ko, answer_from, delay) VALUES
  ('m04_sis_derek_a', 'm04_sis_derek', 1, 'Yes, I will be there! Save me a seat, and tell Mom I will bring dessert.', '응, 갈게! 자리 맡아 주고, 엄마께 디저트는 내가 가져간다고 전해 줘.', 'good', '"Save me a seat"는 자리를 맡아 달라는 말이에요.', 'Yay! Mom will be thrilled. Pecan pie?', '야호! 엄마가 좋아하시겠다. 피칸 파이?', NULL, 6),
  ('m04_sis_derek_b', 'm04_sis_derek', 2, 'I am still checking my schedule. Can I let you know next week?', '아직 일정을 보는 중이야. 다음 주에 알려 줘도 될까?', 'good', '"Let you know"는 나중에 알려 주겠다는 뜻이에요.', 'Sure, but do not wait too long. Mom needs a headcount!', '그래, 하지만 너무 미루지 마. 엄마가 인원수를 알아야 해!', NULL, 6),
  ('m04_sis_derek_c', 'm04_sis_derek', 3, 'Maybe.', '아마도.', 'poor', '"Maybe."만 보내면 성의 없이 들려요. 언제 알려 줄지 덧붙이세요.', 'Maybe? Come on, give me a real answer soon!', '아마도? 얼른 확실히 답해 줘!', NULL, 6),
  ('m04_dad_priya_a', 'm04_dad_priya', 1, 'Yes! I would love to see the garden. I will video call you Saturday morning.', '네! 텃밭 보고 싶어요. 토요일 아침에 영상 통화할게요.', 'good', '"I would love to"는 정말 하고 싶다는 따뜻한 표현이에요.', 'Wonderful! I will hold the phone up to the tomatoes.', '좋구나! 토마토에 전화기를 갖다 대 줄게.', NULL, 7),
  ('m04_dad_priya_b', 'm04_dad_priya', 2, 'Ok, Dad.', '네, 아빠.', 'ok', '짧아도 괜찮지만 반가움을 한마디 더하면 좋아요.', 'Talk this weekend then! Love you.', '그럼 주말에 얘기하자! 사랑한다.', NULL, 7),
  ('m04_dad_priya_c', 'm04_dad_priya', 3, 'Tomatoes already? Send me a photo now, Dad!', '벌써 토마토가요? 지금 사진 보내 주세요, 아빠!', 'good', '놀라움을 표현하며 대화를 이어 가는 답장이에요.', 'Here it comes. Are they not beautiful?', '자, 보낸다. 예쁘지 않니?', NULL, 7),
  ('m05_derek_a', 'm05_derek', 1, 'Thanks for the heads up, Derek. Have a great weekend!', '미리 알려 줘서 고마워요, 데릭. 좋은 주말 보내요!', 'good', '"Thanks for the heads up"은 미리 알려 준 사람에게 하는 인사예요.', 'You too!', '당신도요!', NULL, 4),
  ('m05_derek_b', 'm05_derek', 2, 'Great news. Do you need anyone on standby, just in case?', '좋은 소식이네요. 혹시 모르니 대기할 사람이 필요한가요?', 'good', '"Just in case"는 혹시 몰라서라는 뜻이에요.', 'Nope, all good. Enjoy your weekend.', '아뇨, 괜찮아요. 주말 잘 보내요.', NULL, 4),
  ('m09_scam_a', 'm09_scam', 1, 'Delete the text and block the number.', '문자를 지우고 번호를 차단한다.', 'good', '모르는 번호의 링크는 누르지 말고 지우세요. 택배사는 링크로 주소를 확인하라고 하지 않아요.', NULL, NULL, NULL, 0),
  ('m09_scam_b', 'm09_scam', 2, 'Tap the link to confirm your address.', '링크를 눌러 주소를 확인한다.', 'poor', '피싱 문자예요. 링크를 누르면 개인 정보를 빼 가려고 해요.', 'Fraud alert: we blocked a charge of $499.00 on your debit card. If this was not you, no action is needed.', '사기 알림: 체크카드에서 499달러 결제 시도를 막았습니다. 본인이 아니라면 따로 하실 일은 없습니다.', 'Fairview Credit Union', 12),
  ('m09_scam_c', 'm09_scam', 3, 'STOP', 'STOP', 'poor', '스팸에 답하면 이 번호가 살아 있다고 알려 주는 셈이에요.', 'Thanks for replying! Your number is now verified.', '답장 고마워요! 이제 번호가 확인되었습니다.', '+1 (555) 0142', 5),
  ('m02_spam_a', 'm02_spam', 1, 'Delete the voicemail.', '음성 메시지를 지운다.', 'good', '자동차 보증 전화는 미국에서 가장 흔한 스팸이에요. 무시하세요.', NULL, NULL, NULL, 0),
  ('m02_spam_b', 'm02_spam', 2, 'Call the number back.', '그 번호로 다시 전화한다.', 'poor', '스팸 번호는 대개 없는 번호거나 또 다른 스팸으로 이어져요.', 'The number you have reached is not in service. Please check the number and try again.', '연결하신 번호는 사용되지 않는 번호입니다. 번호를 확인하고 다시 걸어 주세요.', 'Recording', 0),
  ('m09_linda_vm_a', 'm09_linda_vm', 1, 'Hi Linda, it is {name}. I got your message. I will stop by tomorrow morning around nine. Does that work?', '린다, 저 {name}이에요. 메시지 받았어요. 내일 아침 아홉 시쯤 들를게요. 괜찮으세요?', 'good', '회신 전화의 흐름: 누구인지, 왜 걸었는지, 제안을 차례로 말했어요.', 'That works. I will have the form ready. Thanks, {name}!', '좋아요. 서류를 준비해 둘게요. 고마워요, {name}!', 'linda', 0),
  ('m09_linda_vm_b', 'm09_linda_vm', 2, 'Hi Linda, {name} here. Sorry I missed your call. Is now a good time to swing by?', '린다, {name}이에요. 전화를 못 받아 미안해요. 지금 들러도 될까요?', 'good', '"Swing by"는 가볍게 들르다예요. "Is now a good time?"으로 상대 사정을 물어요.', 'Sure, come on by! I am at my desk.', '그럼요, 오세요! 저 자리에 있어요.', 'linda', 0),
  ('m09_linda_vm_c', 'm09_linda_vm', 3, 'What form? I already did everything.', '무슨 서류요? 다 했는데요.', 'poor', '틀린 말은 아니지만 퉁명스러워요. "Which form is it?"이 부드러워요.', 'Oh, it is a small one. The insurance company needs a second signature. It will not take long.', '아, 작은 거예요. 보험사가 서명을 하나 더 원해요. 오래 안 걸려요.', 'linda', 0);

REPLACE INTO replies (id, msg, sort, label, label_ko, tone, tip_ko, answer, answer_ko, answer_from, delay) VALUES
  ('m10_pharmacy_a', 'm10_pharmacy', 1, 'Hi, I am returning your call. I will pick up my prescription after work. Are you open until seven?', '회신 전화드려요. 퇴근 후에 처방약을 찾으러 갈게요. 7시까지 여나요?', 'good', '"Returning your call"은 걸려 온 전화에 회신할 때 쓰는 말이에요.', 'Yes, we are open until seven. Just bring your ID and your insurance card.', '네, 7시까지 엽니다. 신분증과 보험 카드를 가져오세요.', 'Fairview Pharmacy', 0),
  ('m10_pharmacy_b', 'm10_pharmacy', 2, 'Hi, this is {name}. Could you hold the prescription until tomorrow?', '{name}입니다. 처방약을 내일까지 보관해 주실 수 있나요?', 'good', '"Hold"는 맡아 두다예요. "Could you...?"는 정중한 부탁이에요.', 'Sure, we can hold it for seven days. Just come by when you can.', '그럼요, 7일 동안 보관해 드려요. 편할 때 오세요.', 'Fairview Pharmacy', 0),
  ('m12_dental_vm_a', 'm12_dental_vm', 1, 'Hi, this is {name}, returning Amy''s call. Ten thirty works for me.', '{name}인데 에이미 전화에 회신해요. 10시 30분 좋아요.', 'good', '이름, 용건, 답을 한 번에 말하면 통화가 빨리 끝나요.', 'Perfect, thank you! I have moved you to 10:30 AM on the 20th. See you then.', '좋아요, 감사합니다! 20일 오전 10시 30분으로 옮겼어요. 그때 봬요.', 'Fairview Dental', 0),
  ('m12_dental_vm_b', 'm12_dental_vm', 2, 'Hi, this is {name}. Ten thirty is tough because I am at work. Do you have anything after five?', '{name}입니다. 10시 30분은 일하는 시간이라 어려워요. 5시 이후에 자리가 있나요?', 'good', '"Do you have anything after five?"는 다른 시간을 묻는 자연스러운 표현이에요.', 'Let me check. Yes, we have 5:15 that day. Would you like it?', '확인해 볼게요. 그날 5시 15분이 있어요. 그 시간으로 할까요?', 'Fairview Dental', 0),
  ('m12_dental_vm_c', 'm12_dental_vm', 3, 'I get your call. Time is bad.', '전화 받았어요. 시간은 나빠요.', 'poor', '뜻이 분명하지 않아요. "That time doesn''t work for me."라고 말하세요.', 'I am sorry, could you say that again? Do you want to keep 10:30?', '죄송하지만 다시 말씀해 주실래요? 10시 30분으로 할까요?', 'Fairview Dental', 0);

REPLACE INTO mail (id, hero, day, kind, sender, subject, body, body_ko) VALUES
  ('mail01_preapproved', 'all', 1, 'junk', 'Current Resident', 'You may already be pre-approved!', 'Congratulations! You may already be pre-approved for a low-rate credit card. Call now. No obligation. This offer expires soon.', '축하합니다! 낮은 금리의 신용카드에 이미 사전 승인되었을 수 있습니다. 지금 전화하세요. (광고 우편입니다. 버려도 됩니다. pre-approved: 사전 승인된)'),
  ('mail01_card', 'all', 1, 'letter', 'Fairview Credit Union', 'Your new debit card', 'Your new debit card is enclosed. To activate it, call the number on the sticker. Keep your PIN private, and never write it on the card.', '새 체크카드가 들어 있습니다. 사용하려면 스티커에 적힌 번호로 전화해 활성화하세요. 비밀번호(PIN)는 남에게 알리지 말고 카드에 적지 마세요. (activate: 활성화하다)'),
  ('mail02_pizza', 'all', 2, 'junk', 'Pizza Palace', 'Two large pizzas, $19.99', 'Two large one-topping pizzas for $19.99. Carry-out or delivery. Expires Oct 31. One coupon per order.', '토핑 하나 라지 피자 두 판에 19.99달러. 포장 또는 배달. 10월 31일까지. 주문 한 건에 쿠폰 한 장. (carry-out: 포장, expires: 만료되다)'),
  ('mail02_power', 'all', 2, 'bill', 'Fairview Power & Light', 'Your bill is ready', 'Statement date: Oct 6. Your bill is ready to view online. Your autopay is set up, so you do not need to do anything. Thank you for being a customer.', '명세서 날짜: 10월 6일. 요금 고지서를 온라인에서 볼 수 있습니다. 자동이체가 설정되어 있어 따로 하실 일은 없습니다. (statement: 명세서, autopay: 자동이체)'),
  ('mail03_missed', 'all', 3, 'notice', 'Fairview Post Office', 'Sorry we missed you', 'We tried to deliver a package that needed a signature. Pick it up at the post office within 15 days. Bring a photo ID.', '서명이 필요한 소포를 배달하려 했지만 만나지 못했습니다. 15일 안에 우체국에서 찾아가세요. 사진이 붙은 신분증을 가져오세요. (a photo ID: 사진이 붙은 신분증)'),
  ('mail03_hardware', 'all', 3, 'junk', 'Fairview Hardware', 'Fall sale: up to 30% off', 'Rakes, gloves and leaf bags are up to 30% off through Sunday. Bring this flyer to the register.', '갈퀴, 장갑, 낙엽 봉투가 일요일까지 최대 30% 할인입니다. 계산대에 이 전단지를 가져오세요. (flyer: 전단지, register: 계산대)'),
  ('mail04_jun', 'jun', 4, 'card', 'Grandma', 'Congratulations on the new job!', 'Congratulations on your new job! I am so proud of you. Have a nice lunch on me. Love, Grandma', '새 직장을 축하한다! 정말 자랑스럽구나. 맛있는 점심을 먹으렴. 사랑한다, 할머니가. (have ... on me: 내가 살게)'),
  ('mail04_derek', 'derek', 4, 'card', 'Aunt Rosa', 'Thinking of you', 'Just a little note to say hello. Come by for dinner when you have a free Sunday. We miss you. Love, Aunt Rosa', '안부를 전하려고 몇 자 적어요. 일요일에 시간 나면 저녁 먹으러 와요. 보고 싶어요. 로사 이모가. (come by: 들르다)'),
  ('mail04_priya', 'priya', 4, 'card', 'Aunt Meera', 'Congratulations, Priya!', 'We heard about your promotion. Congratulations! Your mother tells everyone. Come visit soon. Love, Aunt Meera', '승진 소식 들었다. 축하해! 네 엄마가 만나는 사람마다 자랑한단다. 조만간 놀러 오렴. 미라 이모가. (promotion: 승진)'),
  ('mail05_eob', 'all', 5, 'letter', 'Fairview Health Plan', 'Explanation of Benefits', 'This is not a bill. It shows what your plan paid for your recent visit. Keep it for your records.', '청구서가 아닙니다. 최근 진료에서 보험이 무엇을 부담했는지 보여 줍니다. 기록으로 보관하세요. (EOB: 보험금 지급 내역서, records: 기록)'),
  ('mail06_ad', 'all', 6, 'junk', 'Fairview Market', 'Weekly ad', 'Fresh salmon $9.99 a pound. Apples 3 for $2. Fall pumpkins are here! Prices good through Friday.', '신선한 연어 파운드당 9.99달러. 사과 세 개에 2달러. 가을 호박이 나왔어요! 금요일까지 행사 가격입니다. (a pound: 1파운드에)');

REPLACE INTO mail (id, hero, day, kind, sender, subject, body, body_ko) VALUES
  ('mail09_vote', 'all', 9, 'notice', 'City of Fairview', 'Election Day is November 3', 'Election Day is Nov 3. Register to vote by Oct 13, or check your registration online. Polls are open from 7 AM to 8 PM.', '선거일은 11월 3일입니다. 10월 13일까지 유권자 등록을 하거나 등록 상태를 온라인에서 확인하세요. 투표소는 오전 7시부터 오후 8시까지 엽니다. (register to vote: 유권자 등록, polls: 투표소)'),
  ('mail09_fiber', 'all', 9, 'junk', 'Fairview Fiber', 'Switch and save', 'Internet 300 Mbps for $39.99 a month for 12 months, then the regular price applies. Taxes and fees extra.', '인터넷 300Mbps를 12개월 동안 월 39.99달러에 드립니다. 이후에는 정상 요금이 적용됩니다. 세금과 수수료는 별도입니다. (then the regular price applies: 그 뒤에는 정가)'),
  ('mail10_statement', 'all', 10, 'letter', 'Fairview Credit Union', 'Your statement is ready', 'Your monthly statement for checking ···4821 is ready. View it online or in the app. Report any error within 60 days.', '입출금 계좌 ···4821의 월 명세서가 나왔습니다. 온라인이나 앱에서 확인하세요. 오류가 있으면 60일 안에 알려 주세요. (statement: 거래 명세서)'),
  ('mail11_jury', 'all', 11, 'notice', 'Fairview County Court', 'Jury service questionnaire', 'You may be selected for jury service. Complete the questionnaire online within 10 days. Failure to respond may result in a fine.', '배심원으로 선정될 수 있습니다. 10일 안에 온라인으로 설문지를 작성하세요. 답하지 않으면 벌금이 나올 수 있습니다. (jury: 배심원단, fine: 벌금)'),
  ('mail11_lawn', 'all', 11, 'junk', 'Green Thumb Landscaping', 'Fall cleanup special', 'Leaves raked and gutters cleaned, from $99. Free estimates. Call today!', '낙엽 치우기와 배수로 청소가 99달러부터. 견적은 무료입니다. 오늘 전화하세요! (estimate: 견적)'),
  ('mail12_coupon', 'all', 12, 'junk', 'Fairview Market', '$5 off $30', 'Save $5 when you spend $30 or more. Valid Oct 12 to 18. Not valid with other offers.', '30달러 이상 사면 5달러를 깎아 드립니다. 10월 12일부터 18일까지 유효. 다른 할인과 중복 불가입니다. (valid: 유효한)'),
  ('mail12_vision', 'all', 12, 'junk', 'Fairview Vision', 'Your eyes matter', 'It has been over a year since your last eye exam. Book one this month and get 20% off frames.', '마지막 시력 검사를 받은 지 1년이 넘었습니다. 이달에 예약하면 안경테를 20% 깎아 드립니다. (frames: 안경테)'),
  ('mail13_jun', 'jun', 13, 'notice', 'Cedar Court Apartments', 'Notice of entry', 'Maintenance will enter your unit on Tuesday between 9 AM and noon to check the smoke detectors. You do not need to be home.', '화요일 오전 9시부터 정오 사이에 화재 감지기를 점검하러 관리인이 들어갑니다. 집에 계실 필요는 없습니다. (smoke detector: 화재 감지기)'),
  ('mail13_derek', 'derek', 13, 'notice', 'Fairview Waste Services', 'New recycling rules', 'Starting Nov 1, greasy pizza boxes go in the trash, not the recycling. Please rinse cans and bottles.', '11월 1일부터 기름이 밴 피자 상자는 재활용이 아니라 일반 쓰레기로 버립니다. 캔과 병은 헹궈 주세요. (rinse: 헹구다)'),
  ('mail13_priya', 'priya', 13, 'notice', 'Cedar Street Lofts', 'Parking permit renewal', 'Resident parking permits expire Oct 31. Renew at the leasing office with your license and registration.', '입주민 주차 허가증이 10월 31일에 만료됩니다. 운전면허증과 차량 등록증을 가지고 관리사무소에서 갱신하세요. (permit: 허가증, renew: 갱신하다)');
