-- Realism: texts, emails and letters that keep coming after the missions (until now the last text came on day 14 and the
-- last letter on day 13). A row with `every` comes back every that many days (30 or more: the same date every month),
-- until `last_day`: the market's weekly email and paper ad (four of each, in turn), family on Sunday evenings, the
-- team's texts, the fridge cleanout and Patch Tuesday, spam calls and scam texts, the bank statement, credit card
-- offers and other junk mail. Some come once with the season: Halloween candy, the Thanksgiving turkey, a holiday
-- catalog, holiday cards from family, the W-2 and the 1099-INT. The engine adds the weather service's alerts (rain,
-- fog, a freeze) and an email from each company on autopay (bills.company) five days before the bill.
-- The ALTER TABLE lines were run on DoltHub once (2026-10-02); to push this file again, leave them out.
ALTER TABLE messages ADD COLUMN every int;
ALTER TABLE messages ADD COLUMN last_day int;
ALTER TABLE mail ADD COLUMN every int;
ALTER TABLE mail ADD COLUMN last_day int;
ALTER TABLE bills ADD COLUMN company varchar(60);

REPLACE INTO bills (id, name, name_ko, amount, day, every, note, note_ko, company) VALUES
  ('internet', 'Home internet', '인터넷 요금', 55, 16, 30, '300 Mbps, no contract', '300Mbps, 약정 없음', 'Bayline Internet'),
  ('phone', 'Phone plan', '휴대전화 요금', 45, 8, 30, 'unlimited talk and text, autopay discount', '통화·문자 무제한, 자동이체 할인', 'Pacific Wireless'),
  ('renters_insurance', 'Renters insurance', '세입자 보험', 14, 3, 30, 'autopay from your checking account', '입출금 계좌에서 자동이체', 'Harbor Mutual Insurance'),
  ('streaming', 'Streaming subscription', '스트리밍 구독', 15.49, 10, 30, 'renews every month until you cancel', '해지할 때까지 매달 갱신', 'StreamBox'),
  ('utilities', 'Electric and gas bill', '전기·가스 요금', 68.4, 12, 30, 'Fairview Power, autopay', '페어뷰 전력, 자동이체', 'Fairview Power & Light');

REPLACE INTO messages (id, hero, day, time, kind, sender, subject, subject_ko, body, body_ko, every, last_day) VALUES
  ('r_market_1', 'all', 18, '09:00', 'email', 'Fairview Market', 'This week''s deals', '이번 주 할인 상품', 'Apples are 3 for $2, fresh salmon is $9.99 a pound, and bakery bread is buy one, get one half off. Prices are good through Sunday.', '사과 세 개에 2달러, 생연어 파운드당 9.99달러, 빵집 빵은 하나 사면 하나 반값입니다. 행사 가격은 일요일까지입니다. (buy one, get one half off: 하나 사면 하나 반값)', 28, NULL),
  ('r_market_2', 'all', 25, '09:00', 'email', 'Fairview Market', 'This week''s deals', '이번 주 할인 상품', 'Chicken thighs are $1.99 a pound, eggs are $2.99 a dozen, and all soups are 20% off. Prices are good through Sunday.', '닭 넓적다리살 파운드당 1.99달러, 달걀 한 판(12개) 2.99달러, 수프는 전부 20% 할인입니다. 행사 가격은 일요일까지입니다. (a dozen: 12개)', 28, NULL),
  ('r_market_3', 'all', 32, '09:00', 'email', 'Fairview Market', 'This week''s deals', '이번 주 할인 상품', 'Oranges are 79 cents a pound, pasta is 2 for $3, and coffee beans are $2 off. Prices are good through Sunday.', '오렌지 파운드당 79센트, 파스타 두 봉지에 3달러, 원두는 2달러 할인입니다. 행사 가격은 일요일까지입니다.', 28, NULL),
  ('r_market_4', 'all', 39, '09:00', 'email', 'Fairview Market', 'This week''s deals', '이번 주 할인 상품', 'Ground beef is $4.49 a pound, frozen vegetables are 4 for $5, and laundry detergent is $3 off. Prices are good through Sunday.', '다진 소고기 파운드당 4.49달러, 냉동 채소 네 봉지에 5달러, 세탁 세제는 3달러 할인입니다. 행사 가격은 일요일까지입니다. (ground beef: 다진 소고기)', 28, NULL),
  ('r_market_halloween', 'all', 22, '09:00', 'email', 'Fairview Market', 'Get ready for trick-or-treaters', '사탕 받으러 올 아이들을 맞을 준비', 'Halloween is Saturday! Big bags of candy are $8.99, and carving pumpkins are $4.99 each while they last.', '핼러윈이 토요일이에요! 큰 사탕 봉지가 8.99달러, 조각용 호박은 남아 있는 동안 개당 4.99달러입니다. (while they last: 재고가 있는 동안)', NULL, NULL),
  ('r_market_thanksgiving', 'all', 43, '09:00', 'email', 'Fairview Market', 'Thanksgiving is next week', '추수감사절이 다음 주예요', 'Fresh turkeys are $1.29 a pound. Order yours at the deli counter by Sunday. We have holiday hours on Thanksgiving Day, so check the sign on the door.', '생칠면조가 파운드당 1.29달러입니다. 일요일까지 델리 카운터에서 주문하세요. 추수감사절 당일에는 휴일 영업시간이 적용되니 문에 붙은 안내를 확인하세요. (deli counter: 조리 식품 코너)', NULL, NULL),
  ('r_market_baking', 'all', 71, '09:00', 'email', 'Fairview Market', 'Bake something sweet', '달콤한 걸 구워 보세요', 'Holiday baking sale: butter, flour and sugar are 25% off, and gift cards are at every register.', '연말 베이킹 세일: 버터, 밀가루, 설탕이 25% 할인이고, 상품권은 모든 계산대에 있습니다. (gift card: 상품권)', NULL, NULL),
  ('r_market_newyear', 'all', 85, '09:00', 'email', 'Fairview Market', 'Happy New Year from Fairview Market', '페어뷰 마켓의 새해 인사', 'Ring in the new year: sparkling cider is 2 for $6 and party platters are 10% off. We close early on New Year''s Eve.', '새해맞이: 탄산 사과주스 두 병에 6달러, 파티용 모둠 접시는 10% 할인입니다. 12월 31일에는 일찍 문을 닫습니다. (ring in the new year: 새해를 맞이하다)', NULL, NULL),
  ('r_fam_jun_1', 'jun', 21, '18:30', 'text', 'Mom', NULL, NULL, 'Did you eat dinner? The weather app says it is getting cold there. Wear a warm jacket.', '저녁은 먹었니? 날씨 앱을 보니 거기 추워진다더라. 따뜻한 겉옷 입고 다녀.', 28, NULL),
  ('r_fam_jun_2', 'jun', 28, '18:30', 'text', 'Dad', NULL, NULL, 'Your mom told me about your job. I am proud of you. Don''t work too late.', '엄마한테 회사 얘기 들었다. 자랑스럽다. 너무 늦게까지 일하지 마라.', 28, NULL),
  ('r_fam_jun_3', 'jun', 35, '18:30', 'text', 'Mom', NULL, NULL, 'Your aunt asked if you have a nice apartment. Send us a photo of your place sometime!', '이모가 집은 괜찮냐고 묻더라. 언제 집 사진 좀 보내 줘!', 28, NULL),
  ('r_fam_jun_4', 'jun', 42, '18:30', 'text', 'Mom', NULL, NULL, 'Are you saving a little every month? Even a little helps. Love you.', '매달 조금씩 저축은 하니? 조금이라도 도움이 돼. 사랑해.', 28, NULL),
  ('r_fam_dk_1', 'derek', 21, '18:30', 'text', 'Elena (sister)', NULL, NULL, 'Mom wants to know if you still like pecan pie or if that was a phase. I said phase.', '엄마가 너 아직도 피칸 파이 좋아하는지, 아니면 한때였는지 물어봐. 난 한때였다고 했어.', 28, NULL),
  ('r_fam_dk_2', 'derek', 28, '18:30', 'text', 'Mom', NULL, NULL, 'Hi honey. Remember to change the furnace filter before it gets cold. Love, Mom', '얘야, 추워지기 전에 난방기 필터 갈아 끼우는 거 잊지 마. 엄마가.', 28, 70),
  ('r_fam_dk_3', 'derek', 35, '18:30', 'text', 'Elena (sister)', NULL, NULL, 'The kids drew you a picture. I''ll mail it if I can find a stamp. Who even has stamps anymore?', '애들이 너 그림 그렸어. 우표 찾으면 부칠게. 요즘 누가 우표를 갖고 있어?', 28, NULL),
  ('r_fam_dk_4', 'derek', 42, '18:30', 'text', 'Mom', NULL, NULL, 'Your father finally fixed the garage door. It only took him two years. Call when you can.', '아빠가 드디어 차고 문을 고쳤어. 2년밖에 안 걸렸네. 시간 될 때 전화해.', 28, NULL),
  ('r_fam_pr_1', 'priya', 21, '18:30', 'text', 'Dad', NULL, NULL, 'The last tomatoes are in. Your mother made chutney. Are you eating your vegetables?', '마지막 토마토를 땄단다. 엄마가 처트니를 만들었어. 채소는 잘 먹고 있니?', 28, 60),
  ('r_fam_pr_2', 'priya', 28, '18:30', 'text', 'Mom', NULL, NULL, 'Your cousin got engaged! I will send you the details. Don''t tell anyone yet.', '사촌이 약혼했어! 자세한 건 보내 줄게. 아직 아무한테도 말하지 마.', 28, NULL);

REPLACE INTO messages (id, hero, day, time, kind, sender, subject, subject_ko, body, body_ko, every, last_day) VALUES
  ('r_fam_pr_3', 'priya', 35, '18:30', 'text', 'Dad', NULL, NULL, 'Did you get your flu shot? Most pharmacies give them for free.', '독감 예방 주사는 맞았니? 약국 대부분에서 무료로 놔 준단다.', 28, NULL),
  ('r_fam_pr_4', 'priya', 42, '18:30', 'text', 'Mom', NULL, NULL, 'Work is work, but take a walk this week. Sunshine is good for you.', '일은 일이고, 이번 주엔 산책 좀 해. 햇볕 쬐는 게 몸에 좋아.', 28, NULL),
  ('r_team_1', 'all', 17, '16:30', 'text', 'priya', NULL, NULL, 'FYI, the coffee cart has pumpkin bread today. Not saying you need it. But it''s good.', '참고로 오늘 커피 카트에 호박빵 있어요. 꼭 먹으라는 건 아닌데, 맛있어요.', 28, 60),
  ('r_team_2', 'all', 24, '16:30', 'text', 'derek', NULL, NULL, 'Staging is back up. Thanks for your patience, everyone.', '스테이징 다시 살아났어요. 다들 기다려 줘서 고마워요.', 28, NULL),
  ('r_team_3', 'all', 31, '16:30', 'text', 'maya', NULL, NULL, 'Quick reminder: please update your tickets on the board before Friday. Thanks, team!', '잠깐 알림: 금요일 전에 보드에서 맡은 티켓 상태를 업데이트해 주세요. 고마워요, 여러분!', 28, NULL),
  ('r_team_4', 'all', 38, '16:30', 'text', 'jun', NULL, NULL, 'Does anyone know if the 8 o''clock bus runs on holidays? Asking for a friend. The friend is me.', '혹시 8시 버스가 공휴일에도 다니는지 아는 분? 친구가 궁금해해서요. 그 친구가 저예요.', 28, NULL),
  ('r_tom_fridge', 'all', 25, '08:45', 'email', 'tom', 'Fridge cleanout tomorrow', '내일 냉장고 정리', 'The fridge gets cleaned out tomorrow at 4 PM. Anything without a name and a date goes. Thanks!', '내일 오후 4시에 냉장고를 정리합니다. 이름과 날짜가 없는 건 모두 버려요. 고맙습니다!', 14, NULL),
  ('r_sam_patch', 'all', 23, '10:00', 'email', 'sam', 'Restart your laptop tonight', '오늘 밤 노트북 다시 켜기', 'Patch Tuesday: security updates go out tonight. Please save your work and restart your laptop before you leave.', '패치 화요일: 오늘 밤 보안 업데이트가 배포됩니다. 퇴근 전에 작업을 저장하고 노트북을 다시 켜 주세요. (Patch Tuesday: 매달 둘째 화요일 보안 업데이트 날)', 28, NULL),
  ('r_linda_w2', 'all', 116, '10:00', 'email', 'linda', 'Your W-2 is ready', 'W-2가 준비되었습니다', 'Your 2026 Form W-2 is now in the HR portal, and a paper copy is in the mail. You will need it to file your taxes by April 15.', '2026년 W-2 양식(연간 급여·세금 명세)을 HR 포털에 올렸고, 종이 사본은 우편으로 보냈습니다. 4월 15일까지 세금 신고할 때 필요합니다. (W-2: 연말정산용 급여 명세서)', NULL, NULL),
  ('r_spam_warranty', 'all', 20, '11:40', 'voicemail', 'Unknown caller', NULL, NULL, 'This is a final courtesy call about your vehicle''s extended warranty. Press 1 now to speak to a specialist.', '차량 보증 연장에 관한 마지막 안내 전화입니다. 상담원과 통화하려면 지금 1번을 누르세요. (흔한 스팸 전화예요. 지우면 돼요.)', 23, NULL),
  ('r_scam_toll', 'all', 27, '13:05', 'text', '+1 (555) 0187', NULL, NULL, 'Fairview Toll Services: you have an unpaid toll of $4.15. Pay within 24 hours to avoid a $50 late fee: fvw-toll-pay.info', '페어뷰 통행료 서비스: 미납 통행료 4.15달러가 있습니다. 50달러 연체료를 피하려면 24시간 안에 내세요: fvw-toll-pay.info (피싱 문자예요. 링크를 누르지 말고 지우세요.)', 38, NULL),
  ('r_scam_bank', 'all', 46, '20:15', 'text', '+1 (555) 0199', NULL, NULL, 'Fairview Credit Union ALERT: your account has been locked. Verify your identity at the link to unlock it: fcu-secure-verify.com', '페어뷰 신용조합 알림: 계좌가 잠겼습니다. 링크에서 본인 확인을 하면 풀립니다: fcu-secure-verify.com (진짜 은행은 문자 링크로 본인 확인을 하지 않아요. 피싱이에요.)', 38, NULL);

REPLACE INTO mail (id, hero, day, kind, sender, subject, subject_ko, body, body_ko, every, last_day) VALUES
  ('r_ad_1', 'all', 20, 'junk', 'Fairview Market', 'Weekly ad', '주간 전단 광고', 'Russet potatoes, 5 pounds for $2.99. Rotisserie chicken $6.99. Prices good through Friday.', '러셋 감자 5파운드 2.99달러. 통닭구이 6.99달러. 금요일까지 행사 가격입니다. (rotisserie chicken: 통째로 돌려 구운 닭)', 28, NULL),
  ('r_ad_2', 'all', 27, 'junk', 'Fairview Market', 'Weekly ad', '주간 전단 광고', 'Bananas 59 cents a pound. Greek yogurt 4 for $5. Fresh flowers $7.99 a bunch. Prices good through Friday.', '바나나 파운드당 59센트. 그릭 요구르트 네 개에 5달러. 생화 한 다발 7.99달러. 금요일까지 행사 가격입니다. (a bunch: 한 다발)', 28, NULL),
  ('r_ad_3', 'all', 34, 'junk', 'Fairview Market', 'Weekly ad', '주간 전단 광고', 'Pork chops $3.49 a pound. Cereal 2 for $6. Paper towels 6 rolls for $7.99. Prices good through Friday.', '돼지 목살 파운드당 3.49달러. 시리얼 두 상자에 6달러. 키친타월 6롤 7.99달러. 금요일까지 행사 가격입니다.', 28, NULL),
  ('r_ad_4', 'all', 41, 'junk', 'Fairview Market', 'Weekly ad', '주간 전단 광고', 'Avocados 2 for $3. Shredded cheese 2 for $5. Rice, 10 pounds for $8.99. Prices good through Friday.', '아보카도 두 개에 3달러. 슬라이스 치즈 두 봉지에 5달러. 쌀 10파운드 8.99달러. 금요일까지 행사 가격입니다.', 28, NULL),
  ('r_statement', 'all', 41, 'letter', 'Fairview Credit Union', 'Your statement is ready', '거래 명세서가 나왔습니다', 'Your monthly statement for checking ···4821 is ready. View it online or in the app. Report any error within 60 days.', '입출금 계좌 ···4821의 월 명세서가 나왔습니다. 온라인이나 앱에서 확인하세요. 오류가 있으면 60일 안에 알려 주세요.', 30, NULL),
  ('r_preapproved_1', 'all', 22, 'junk', 'Current Resident', 'You''re pre-approved!', '사전 승인되셨습니다!', '0% intro APR for 15 months on purchases and balance transfers. Respond by the date on the enclosed form.', '구매와 잔액 이전에 15개월 동안 0% 우대 금리. 동봉한 양식에 적힌 날짜까지 답하세요. (APR: 연이율, intro: 처음 일정 기간의)', 42, NULL),
  ('r_preapproved_2', 'all', 43, 'junk', 'Current Resident', 'You''ve been pre-selected', '선정되셨습니다', 'Earn 3% cash back at grocery stores and 1% on everything else. No annual fee the first year.', '식료품점에서 3%, 나머지는 1% 캐시백. 첫해 연회비 없음. (cash back: 쓴 금액의 일부를 돌려받음)', 42, NULL),
  ('r_pizza', 'all', 23, 'junk', 'Pizza Palace', 'Large two-topping pizza, $12.99', '토핑 두 개 라지 피자 12.99달러', 'Large two-topping pizza for $12.99, carry-out only. Show this coupon at the counter.', '토핑 두 개 라지 피자 12.99달러, 포장만 됩니다. 계산대에서 이 쿠폰을 보여 주세요. (carry-out only: 포장만)', 35, NULL),
  ('r_fiber', 'all', 30, 'junk', 'Fairview Fiber', 'Still paying too much for internet?', '아직도 인터넷 요금을 많이 내세요?', '500 Mbps for $45 a month for 12 months. Free installation. Taxes and fees extra.', '500Mbps를 12개월 동안 월 45달러에. 설치비 무료. 세금과 수수료는 별도입니다.', 42, NULL),
  ('r_hardware_winter', 'all', 50, 'junk', 'Fairview Hardware', 'Get your home ready for winter', '집을 겨울 채비하세요', 'Space heaters, weather stripping and door sweeps are up to 25% off through Sunday.', '전기난로, 문풍지, 문 밑 바람막이가 일요일까지 최대 25% 할인입니다. (weather stripping: 문풍지)', 35, 120),
  ('r_catalog', 'all', 48, 'junk', 'Northwind Outfitters', 'Our holiday catalog is here', '연말 카탈로그가 나왔습니다', 'Warm jackets, flannel shirts and gifts for everyone on your list. Order by December 18 for delivery before Christmas.', '따뜻한 재킷, 플란넬 셔츠, 선물 목록 속 모두를 위한 선물. 12월 18일까지 주문하면 크리스마스 전에 배달됩니다.', NULL, NULL),
  ('r_card_jun', 'jun', 76, 'card', 'Grandma', 'Merry Christmas!', '메리 크리스마스!', 'Merry Christmas and Happy New Year, Jun! I am so proud of you. Stay warm and eat well. Love, Grandma', '준아, 메리 크리스마스, 새해 복 많이 받아라! 정말 자랑스럽구나. 따뜻하게 지내고 잘 챙겨 먹으렴. 할머니가.', NULL, NULL),
  ('r_card_derek', 'derek', 76, 'card', 'Aunt Rosa', 'Happy holidays!', '즐거운 연말 보내!', 'Happy holidays, Derek! I hope the house is warm and cozy. Love from all of us. Aunt Rosa', '데릭, 즐거운 연말 보내! 집이 따뜻하고 아늑하길 바란다. 우리 모두의 사랑을 담아. 로사 이모가.', NULL, NULL),
  ('r_card_priya', 'priya', 76, 'card', 'Aunt Meera', 'Season''s greetings', '연말 인사', 'Season''s greetings, Priya! Wishing you a bright and happy new year. With love, Aunt Meera', '프리야, 즐거운 연말 보내렴! 밝고 행복한 새해가 되길. 사랑을 담아, 미라 이모가.', NULL, NULL),
  ('r_w2', 'all', 118, 'letter', 'Seaside Labs Payroll', 'Form W-2: Wage and Tax Statement', 'W-2 양식: 급여 및 세금 명세서', 'Your 2026 Form W-2 is enclosed. It shows your wages and the taxes withheld last year. Keep it for your tax return, due April 15.', '2026년 W-2 양식을 동봉합니다. 지난해 급여와 원천징수된 세금이 적혀 있습니다. 4월 15일까지 내는 세금 신고에 쓰도록 보관하세요. (withheld: 원천징수된)', NULL, NULL),
  ('r_1099', 'all', 118, 'letter', 'Fairview Credit Union', 'Form 1099-INT', '1099-INT 양식', 'Form 1099-INT: interest paid to you in 2026 on checking ···4821. Keep this form for your tax return.', '1099-INT 양식: 2026년에 입출금 계좌 ···4821에서 받은 이자 내역입니다. 세금 신고에 쓰도록 보관하세요. (interest: 이자)', NULL, NULL);
