-- The review (eighth round): early January, three months after Jun started. Jun has his 90-day review (the end of
-- probation); Derek and Priya, who have been at Seaside Labs longer, have their year-end review. A conversation with
-- Maya in her office on Monday, January 4 (game day 92) at 3:30 PM, open until Friday; when it is over the engine scores
-- the time since day 1 (attendance, team meetings, weeks at the desk, what came up, the missions) and gives a raise,
-- a bonus or an extended probation. Maya sends a heads-up on December 28 (day 85).
REPLACE INTO config (k, v, note) VALUES
  ('raise_meets', '3', 'raise in percent for a review that meets expectations'),
  ('raise_exceeds', '5', 'raise in percent for a review that exceeds expectations'),
  ('review_bonus', '1500', 'bonus for exceeding expectations at a year-end review (not at the end of probation)'),
  ('probation_extend_days', '30', 'a new hire whose review needs improvement: probation goes on this many days, then is looked at again');

REPLACE INTO episodes (id, title, title_ko, place, npc, day_from, day_to, time_from, time_to, requires, summary, summary_ko, reward, energy, sort, tags, hero) VALUES
  ('rv_jun', '90-day review', '90일 평가', 'office_manager', 'maya', 92, 96, '15:15', '17:30', NULL, 'Your 90-day review with Maya. Give a balanced view of your first three months, take feedback well, set a goal, and ask what comes next. Then see your results.', '마야와 하는 90일 평가입니다. 첫 석 달을 균형 있게 돌아보고, 피드백을 잘 받아들이고, 목표를 정하고, 다음 단계를 물어보세요. 그다음 결과를 확인하세요.', 0, 0, 3000, 'meeting,manager,review', 'jun'),
  ('rv_derek', 'Year-end review', '연말 평가', 'office_manager', 'maya', 92, 96, '15:15', '17:30', NULL, 'Your year-end review with Maya. Look back on the year, take the team''s feedback, set a goal for next year, and ask about growing into a lead. Then see your results.', '마야와 하는 연말 평가입니다. 한 해를 돌아보고, 팀의 피드백을 받아들이고, 내년 목표를 정하고, 리드로 성장하는 길을 물어보세요. 그다음 결과를 확인하세요.', 0, 0, 3000, 'meeting,manager,review', 'derek'),
  ('rv_priya', 'Year-end review', '연말 평가', 'office_manager', 'maya', 92, 96, '15:15', '17:30', NULL, 'Your year-end review with Maya. Look back on the pilot year, take the engineers'' feedback, set a goal for next year, and ask about the product''s future. Then see your results.', '마야와 하는 연말 평가입니다. 시범 운영의 한 해를 돌아보고, 개발자들의 피드백을 받아들이고, 내년 목표를 정하고, 제품의 앞날을 물어보세요. 그다음 결과를 확인하세요.', 0, 0, 3000, 'meeting,manager,review', 'priya');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rv_jun', 1, NULL, 'Monday, January 4. Your 90-day review in Maya''s office. Linda from HR sent the form, and Maya has it open on her laptop.', '1월 4일 월요일. 마야의 방에서 90일 평가를 합니다. 인사팀 린다가 양식을 보냈고, 마야가 노트북에 띄워 두었습니다.', 'Happy New Year, Jun! Three months already. Before I share my notes, how do you think it''s gone?', '새해 복 많이 받아요, 준! 벌써 석 달이네요. 내 메모를 보여 주기 전에, 준은 어땠다고 생각해요?', 'Give an honest, balanced view: something that went well and something you still want to improve.', '잘된 점 하나와 아직 나아지고 싶은 점 하나로, 솔직하고 균형 있게 말하세요.', '[]', 'I think it''s gone well overall. I''ve shipped real work, but I''d like to get faster at code reviews.', '전체적으로 잘 지낸 것 같아요. 실제로 쓰이는 걸 만들었고, 코드 리뷰는 더 빨라지고 싶어요.', '["Honestly, it''s been perfect. I''ve shipped everything on time and I can''t think of anything I''d change.", "Not great, to be honest. I feel like I''ve been behind since day one and still haven''t caught up.", "It''s been fine, I think. But I''d rather hear first what the team has been saying about me."]', '["솔직히 완벽했어요. 다 제때 냈고, 바꾸고 싶은 게 하나도 떠오르지 않아요.", "솔직히 별로예요. 첫날부터 뒤처진 느낌이고 아직도 못 따라잡았어요.", "괜찮았던 것 같아요. 그런데 팀에서 저에 대해 뭐라고 하는지 먼저 듣고 싶어요."]', '["Nobody''s perfect after three months, Jun. Let''s find something to grow on.", "That''s harsher than what I''ve seen. Let''s look at the facts.", "We''ll get there. First I want to hear your view."]', '["석 달 만에 완벽한 사람은 없어요, 준. 성장할 점을 하나 찾아봐요.", "내가 본 것보다 훨씬 박하네요. 사실을 같이 봐요.", "그건 곧 얘기할게요. 먼저 준의 생각을 듣고 싶어요."]', NULL, 'That matches a lot of what I wrote. Let''s go through it.', '내가 적은 것과 많이 같네요. 하나씩 봐요.'),
  ('rv_jun', 2, NULL, NULL, NULL, 'One thing from the team: your pull requests are solid, but people sometimes hear about problems late. What could help?', '팀에서 나온 얘기 하나: 풀 리퀘스트는 탄탄한데, 문제를 늦게 알게 될 때가 있대요. 뭐가 도움이 될까요?', 'Take the feedback without getting defensive, and suggest something concrete.', '방어하지 말고 피드백을 받아들인 뒤, 구체적인 방법을 제안하세요.', '[]', 'That''s fair. I''ll bring up blockers at standup the same day instead of waiting until I''ve tried everything.', '맞는 말이에요. 다 해 볼 때까지 기다리지 않고, 막히면 그날 스탠드업에서 바로 말할게요.', '["Who said that, exactly? I''d like to know so I can go and talk to them about it myself.", "I only wait because I don''t want to bother anyone with half-finished problems. That''s being polite.", "Okay, that''s fair. I''ll just try to do better at everything from now on and see how it goes."]', '["정확히 누가 그랬어요? 제가 직접 가서 얘기해 보게 알고 싶어요.", "반쯤 풀린 문제로 누굴 귀찮게 하기 싫어서 기다리는 거예요. 그게 예의잖아요.", "네, 맞는 말이에요. 앞으로 모든 걸 더 잘해 보고 어떻게 되는지 볼게요."]', '["It came from the team, not one person. Let''s focus on what you can change.", "I get that, but here it''s more polite to speak up early.", "That''s a bit general. What would you actually do differently?"]', '["한 사람이 아니라 팀에서 나온 얘기예요. 바꿀 수 있는 것에 집중해요.", "이해해요. 그런데 여기서는 일찍 말하는 게 더 예의예요.", "좀 막연하네요. 실제로 뭘 다르게 할 거예요?"]', NULL, 'Perfect. Small and specific is how it sticks.', '좋아요. 작고 구체적이어야 몸에 붙어요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rv_jun', 3, NULL, NULL, NULL, 'Let''s set a goal for the next quarter. What would you like to own?', '다음 분기 목표를 정해 봐요. 뭘 맡아 보고 싶어요?', 'Name one goal that''s specific and stretches you a little.', '구체적이고 조금 버거운 목표 하나를 말하세요.', '[]', 'I''d like to own the store alerts feature from design to launch, with Derek reviewing.', '매장 알림 기능을 설계부터 출시까지 맡고 싶어요. 리뷰는 데릭이 봐 주고요.', '["I''d like to be promoted to senior engineer by the summer, if that''s possible here.", "Honestly, whatever you think is best for the team. I''m happy to work on anything.", "Maybe learn more about the codebase in general and read more of the docs."]', '["가능하다면 여름까지 시니어 개발자로 승진하고 싶어요.", "솔직히 팀에 제일 좋은 거면 뭐든요. 어떤 일이든 좋아요.", "전반적으로 코드베이스를 더 익히고 문서를 더 읽어 볼까 해요."]', '["Ambitious! Let''s pick something you can finish this quarter first.", "I want to hear what you want, though. That''s the point of a goal.", "Can we make it more concrete? What would you build?"]', '["야심 차네요! 먼저 이번 분기 안에 끝낼 수 있는 걸 골라요.", "그래도 준이 원하는 걸 듣고 싶어요. 목표는 그러라고 있는 거예요.", "좀 더 구체적으로 해 볼까요? 뭘 만들 거예요?"]', NULL, 'Great. I''ll write that down, and we''ll check in on it in our 1:1s.', '좋아요. 적어 두고 1:1 때마다 점검해요.'),
  ('rv_jun', 4, NULL, NULL, NULL, 'Before we wrap up, any questions for me?', '마무리하기 전에, 나한테 물어볼 거 있어요?', 'Ask a useful question about what comes next, not only about money.', '돈 얘기만 말고, 앞으로에 대해 쓸모 있는 질문을 하세요.', '[]', 'Yes. What would you need to see from me to take on bigger projects next year?', '네. 내년에 더 큰 프로젝트를 맡으려면 제가 뭘 보여 드려야 할까요?', '["Yes. How much is my raise going to be, and when does it show up in my paycheck?", "No, I think I''m good. You''ve covered everything, so can I head back to my desk?", "Is it true that people sometimes get let go right after their 90-day review?"]', '["네. 연봉은 얼마나 오르고, 급여에는 언제부터 반영돼요?", "아니요, 괜찮아요. 다 말씀해 주셨으니 자리로 돌아가도 될까요?", "90일 평가 직후에 잘리는 사람도 가끔 있다는 게 사실이에요?"]', '["We''ll get to pay in a second, I promise. Anything else on your mind?", "Sure, but this is your time too. Nothing at all?", "Only in rare cases, and that''s not what this is. Anything else?"]', '["급여 얘기는 곧 할게요, 약속해요. 다른 궁금한 건요?", "그래도 되지만, 이건 준의 시간이기도 해요. 정말 없어요?", "아주 드문 경우고, 지금이 그런 자리는 아니에요. 다른 건요?"]', NULL, 'Good question. Keep doing what you''re doing, and say yes to the alerts project. Now, let me show you the numbers.', '좋은 질문이에요. 지금처럼 하면서 알림 프로젝트를 맡아 봐요. 자, 이제 숫자를 보여 줄게요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rv_derek', 1, NULL, 'Monday, January 4. Your year-end review in Maya''s office. Your fourth year at Seaside Labs, and the year you became Jun''s onboarding buddy.', '1월 4일 월요일. 마야의 방에서 연말 평가를 합니다. 시사이드 랩스에서의 네 번째 해이고, 준의 온보딩 버디가 된 해예요.', 'Happy New Year, Derek. Big year for you. How do you see it?', '새해 복 많이 받아요, 데릭. 큰 한 해였죠. 데릭은 어떻게 봐요?', 'Sum up the year honestly, with something you want to change.', '한 해를 솔직하게 정리하고, 바꾸고 싶은 점도 말하세요.', '[]', 'A good year. The dashboard launched and onboarding Jun went well. Next year I''d like to hand off more.', '좋은 한 해였어요. 대시보드가 나왔고 준 온보딩도 잘됐고요. 내년에는 일을 더 넘겨 주고 싶어요.', '["Same as every year, really. I closed my tickets, fixed what broke, and kept things running.", "Honestly, I carried the team this year. Without me the dashboard wouldn''t have launched.", "Tiring, to be honest. Onboarding Jun took a lot of time I needed for my own work."]', '["매년 똑같았죠. 티켓 닫고, 고장 난 거 고치고, 시스템 돌아가게 했어요.", "솔직히 올해는 제가 팀을 끌고 갔죠. 제가 없었으면 대시보드는 못 나왔어요.", "솔직히 피곤했어요. 준 온보딩에 제 일에 써야 할 시간을 많이 뺏겼어요."]', '["You did more than tickets, and I''d like you to see that.", "You did a lot, but the launch was a team effort.", "I hear you. Was any of it worth it?"]', '["티켓보다 훨씬 많은 걸 했어요. 그걸 데릭도 알았으면 해요.", "많이 한 건 맞지만, 출시는 팀이 함께 한 거예요.", "그랬겠네요. 그래도 보람은 있었어요?"]', NULL, 'Agreed on all of it.', '전부 동의해요.'),
  ('rv_derek', 2, NULL, NULL, NULL, 'From the team: you''re the go-to person, which is great, but sometimes you fix things yourself instead of teaching. Thoughts?', '팀에서 나온 얘기: 다들 데릭을 찾는 건 좋은데, 가르치는 대신 직접 고쳐 버릴 때가 있대요. 어떻게 생각해요?', 'Take the feedback and say what you''ll do about it.', '피드백을 받아들이고 어떻게 할지 말하세요.', '[]', 'That''s true. When Jun gets stuck, I''ll pair with him instead of just pushing the fix.', '맞아요. 준이 막히면 고친 걸 그냥 올리지 않고 같이 붙어서 볼게요.', '["It''s just faster if I do it myself. We have deadlines, and teaching takes time.", "Who complained about that? Was it Jun? I thought we were getting along fine.", "Fine. If that''s how it looks, I''ll stop jumping in to help people, then."]', '["제가 하는 게 그냥 빨라요. 마감이 있고, 가르치는 건 시간이 들잖아요.", "누가 그런 불평을 했어요? 준이에요? 사이좋게 지내는 줄 알았는데요.", "알겠어요. 그렇게 보인다면, 이제 사람들 돕는 데 끼어들지 않을게요."]', '["Faster this week, slower next year. Think about it.", "Nobody complained. It''s a pattern I noticed.", "That''s not what I meant, Derek."]', '["이번 주엔 빠르지만 내년엔 느려져요. 생각해 봐요.", "아무도 불평 안 했어요. 내가 본 패턴이에요.", "그런 뜻이 아니에요, 데릭."]', NULL, 'That''s exactly it.', '바로 그거예요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rv_derek', 3, NULL, NULL, NULL, 'What''s your goal for next year?', '내년 목표는 뭐예요?', 'Name a goal that''s specific and moves your career forward.', '구체적이고 경력에 도움이 되는 목표를 말하세요.', '[]', 'I''d like to lead the offline-mode project and grow toward a tech lead role.', '오프라인 모드 프로젝트를 이끌면서 테크 리드 역할로 성장하고 싶어요.', '["Honestly, keep doing what I''m doing. It''s working, so why change it?", "A promotion, plain and simple. That''s my goal for next year.", "Fewer meetings, so I have more time to actually write code."]', '["솔직히 지금 하는 걸 계속하는 거요. 잘되고 있으니 바꿀 이유가 있나요?", "승진이요, 간단해요. 그게 내년 목표예요.", "회의를 줄여서 실제로 코드 짤 시간을 늘리는 거요."]', '["You could, but I think you want more than that.", "Let''s talk about what would get you there.", "Ha, me too. But a real goal?"]', '["그래도 되지만, 데릭은 그 이상을 원하는 것 같은데요.", "거기까지 가려면 뭐가 필요한지 얘기해 봐요.", "하하, 나도요. 그래도 진짜 목표는요?"]', NULL, 'I''d love that. Let''s make a plan.', '좋아요. 계획을 세워 봐요.'),
  ('rv_derek', 4, NULL, NULL, NULL, 'Any questions for me?', '나한테 물어볼 거 있어요?', 'Ask about how to reach your goal.', '목표에 다가가는 방법을 물어보세요.', '[]', 'What would a tech lead role look like here, and how would we know I''m ready?', '여기서 테크 리드는 어떤 역할이고, 제가 준비됐는지 어떻게 알 수 있을까요?', '["Yes, is there a bonus this year? And will it come with the next paycheck?", "No, not really. I think we covered it all. Thanks for your time, Maya.", "Is something going on? Are you leaving the company? You can tell me."]', '["네, 올해 보너스 있어요? 다음 급여 때 같이 들어와요?", "아니요, 딱히요. 다 얘기한 것 같아요. 시간 내 줘서 고마워요, 마야.", "무슨 일 있어요? 혹시 회사 그만두세요? 말해도 돼요."]', '["We''ll get to that in a second. Anything about the work?", "Nothing at all? This is your time.", "No! Why would you think that?"]', '["그건 곧 얘기할게요. 일에 관해서는요?", "하나도 없어요? 데릭의 시간인데요.", "아니요! 왜 그렇게 생각했어요?"]', NULL, 'Let''s write that down together at our next 1:1. Now, the numbers.', '다음 1:1에서 같이 정리해 봐요. 자, 이제 숫자를 볼게요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rv_priya', 1, NULL, 'Monday, January 4. Your year-end review with Maya. This year you launched the store dashboard with Summit Retail and ran the team''s planning.', '1월 4일 월요일. 마야와 연말 평가를 합니다. 올해 서밋 리테일과 매장 대시보드를 출시했고, 팀의 계획 회의를 이끌었어요.', 'Happy New Year, Priya. How do you think the year went?', '새해 복 많이 받아요, 프리야. 한 해가 어땠다고 생각해요?', 'Sum up the year honestly, with something you want to do better.', '한 해를 솔직하게 정리하고, 더 잘하고 싶은 점도 말하세요.', '[]', 'Strong overall. The pilot launched on time and Greg is happy. I want to push back on scope creep earlier.', '전체적으로 좋았어요. 시범 운영이 제때 시작됐고 그레그도 만족해요. 요구가 불어날 때 더 일찍 선을 긋고 싶어요.', '["Great, mostly because I kept pushing the engineers to hit every date we promised.", "Messy, honestly. Greg kept changing his mind, and we spent months chasing him.", "I''m honestly not sure how it went. I''d rather hear your view first, Maya."]', '["좋았어요. 대부분 제가 약속한 날짜를 다 맞추라고 개발자들을 밀어붙인 덕분이죠.", "솔직히 엉망이었어요. 그레그가 계속 말을 바꿔서 몇 달을 쫓아다녔어요.", "어땠는지 솔직히 잘 모르겠어요. 마야 생각을 먼저 듣고 싶어요."]', '["The engineers pushed too. It was a team result.", "He did, and you handled it. What would you do differently?", "I want your view first."]', '["개발자들도 애썼어요. 팀이 함께 낸 결과예요.", "그랬죠. 그리고 프리야가 잘 대처했어요. 뭘 다르게 하고 싶어요?", "먼저 프리야의 생각을 듣고 싶어요."]', NULL, 'That''s what I saw too.', '나도 그렇게 봤어요.'),
  ('rv_priya', 2, NULL, NULL, NULL, 'From the engineers: they love your clear specs, but sometimes they hear about promises to the client late. Thoughts?', '개발자들 얘기: 명세가 명확해서 좋은데, 고객에게 한 약속을 늦게 알게 될 때가 있대요. 어떻게 생각해요?', 'Take the feedback and say what you''ll change.', '피드백을 받아들이고 무엇을 바꿀지 말하세요.', '[]', 'Fair point. I''ll bring the team in before I promise dates to Greg.', '맞는 말이에요. 그레그에게 날짜를 약속하기 전에 팀과 먼저 얘기할게요.', '["The client pays us, so sometimes I have to promise before I can ask.", "Engineers always say that about PMs. It comes with the job, I think.", "Then I just won''t talk to Greg at all unless an engineer is there."]', '["돈은 고객이 내니까, 가끔은 물어보기 전에 약속해야 해요.", "개발자들은 PM한테 늘 그렇게 말해요. 이 일의 숙명 같아요.", "그럼 개발자가 없으면 그레그랑은 아예 얘기 안 할게요."]', '["True, but a promise the team can''t keep costs us more.", "Maybe, but it''s worth taking seriously.", "That goes too far. Just loop them in."]', '["맞아요. 그런데 팀이 못 지키는 약속은 더 비싸게 먹혀요.", "그럴지도 모르지만, 진지하게 받아들일 만해요.", "그건 너무 나갔어요. 그냥 미리 알려 주면 돼요."]', NULL, 'Exactly.', '바로 그거예요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rv_priya', 3, NULL, NULL, NULL, 'What''s your goal for next year?', '내년 목표는 뭐예요?', 'Name a goal for the product that the team can share.', '팀이 함께 가질 수 있는 제품 목표를 말하세요.', '[]', 'Grow the pilot to all of Summit Retail''s stores, with a rollout plan the team agrees on.', '팀이 동의하는 확대 계획으로 시범 운영을 서밋 리테일 전 매장으로 넓히는 거예요.', '["Bring in a second client, so we don''t depend so much on Summit Retail.", "Become a director of product, with a team of my own to manage.", "Honestly, spend less time on email and more time with the stores."]', '["두 번째 고객사를 데려와서 서밋 리테일 의존을 줄이는 거요.", "제 팀을 둔 프로덕트 디렉터가 되는 거요.", "솔직히 이메일은 덜 쓰고 매장에서 시간을 더 보내는 거요."]', '["Sales handles that. What about our product?", "Let''s talk about the steps toward that.", "Same! But a work goal?"]', '["그건 영업팀 일이에요. 우리 제품은요?", "거기까지 가는 단계를 얘기해 봐요.", "나도요! 그래도 일 목표는요?"]', NULL, 'Good. Let''s make that the team''s goal, too.', '좋아요. 그걸 팀 목표로도 삼아요.'),
  ('rv_priya', 4, NULL, NULL, NULL, 'Any questions for me?', '나한테 물어볼 거 있어요?', 'Ask a question that helps you do the job better.', '일을 더 잘하는 데 도움이 되는 질문을 하세요.', '[]', 'Yes. Where do you see the product in a year, and how can I help get it there?', '네. 1년 뒤 제품이 어디쯤 있을 거라고 보세요? 거기까지 가는 데 제가 뭘 도우면 될까요?', '["Yes, how big is my raise this year, and when does it start?", "Nope, I think we''re all good. Thanks for making the time today.", "Why didn''t I get a promotion this year, after the pilot went so well?"]', '["네, 올해 연봉은 얼마나 오르고, 언제부터 적용돼요?", "아니요, 다 괜찮은 것 같아요. 오늘 시간 내 줘서 고마워요.", "시범 운영이 그렇게 잘됐는데 저는 왜 올해 승진을 못 했어요?"]', '["Coming up, I promise. Anything about the work?", "Nothing? This is your time.", "Let''s talk about what a promotion would take, not why it didn''t happen."]', '["곧 얘기할게요, 약속해요. 일에 관해서는요?", "없어요? 프리야의 시간인데요.", "왜 안 됐는지보다 승진하려면 뭐가 필요한지 얘기해요."]', NULL, 'Great question. Now let me show you the numbers.', '좋은 질문이에요. 자, 이제 숫자를 보여 줄게요.');

REPLACE INTO calendar (hero, day, time, title, title_ko, place, episode) VALUES
  ('jun', 92, '15:30', '90-day review with Maya', '마야와 90일 평가', 'office_manager', 'rv_jun'),
  ('derek', 92, '15:30', 'Year-end review with Maya', '마야와 연말 평가', 'office_manager', 'rv_derek'),
  ('priya', 92, '15:30', 'Year-end review with Maya', '마야와 연말 평가', 'office_manager', 'rv_priya');

REPLACE INTO messages (id, hero, day, time, kind, sender, subject, subject_ko, body, body_ko) VALUES
  ('r_review_jun', 'jun', 85, '10:00', 'email', 'maya', 'Your 90-day review', '90일 평가 안내', 'Hi Jun, let''s do your 90-day review on Monday, January 4 at 3:30 in my office. I''ll go over your attendance, the team meetings, the work at your desk and how you handled what came up. Nothing to prepare, but bring your questions. Enjoy the holidays!', '준, 90일 평가를 1월 4일 월요일 오후 3시 30분에 내 방에서 해요. 근태, 팀 회의, 자리에서 한 일, 중간에 생긴 일을 어떻게 처리했는지 볼 거예요. 준비할 건 없고, 궁금한 걸 가져와요. 연휴 잘 보내요!'),
  ('r_review_derek', 'derek', 85, '10:00', 'email', 'maya', 'Year-end review', '연말 평가 안내', 'Hi Derek, your year-end review is Monday, January 4 at 3:30 in my office. We''ll look at the year: attendance, meetings, your work and how you handled what came up, plus goals for next year. Enjoy the holidays!', '데릭, 연말 평가는 1월 4일 월요일 오후 3시 30분, 내 방에서 해요. 근태, 회의, 한 일, 중간에 생긴 일을 어떻게 처리했는지 돌아보고 내년 목표도 정해요. 연휴 잘 보내요!'),
  ('r_review_priya', 'priya', 85, '10:00', 'email', 'maya', 'Year-end review', '연말 평가 안내', 'Hi Priya, your year-end review is Monday, January 4 at 3:30 in my office. We''ll look at the year: attendance, meetings, your work and how you handled what came up, plus goals for next year. Enjoy the holidays!', '프리야, 연말 평가는 1월 4일 월요일 오후 3시 30분, 내 방에서 해요. 근태, 회의, 한 일, 중간에 생긴 일을 어떻게 처리했는지 돌아보고 내년 목표도 정해요. 연휴 잘 보내요!');
