-- Benefits enrollment (seed 86): open enrollment in the HR portal, October 12 to 23 (game days 8 to 19), as Linda's
-- emails say. Pick a medical plan (Basic HMO, Choice PPO, Saver HSA), dental and vision; the new plans start November 1
-- (day 28), and their premiums come out of every paycheck after, before tax. Not submitting gets the Basic HMO with no
-- dental or vision. The 401(k) can change any time (from the next paycheck): the company matches all of it up to 4% of
-- pay, as Linda tells Jun on day 4. The pay stub (gross, taxes, premiums, 401(k), net) is worked out by the engine;
-- heroes.salary_net stays the paycheck with each hero's plans before November (config benefits_now).
-- Also: Linda's email of day 5 and her line in passing no longer say the plan carries over or "thirty days", and
-- Jun's day 15 talk with Linda (d15_expenses turn 5) is about the open enrollment deadline instead of a 6% match
-- (it said three percent and a match up to six, against day 4 and the day 5 pay stub: four percent, a match up to four).
-- The plans table is in db/schema.sql (this CREATE TABLE is the same).
CREATE TABLE IF NOT EXISTS plans (id varchar(16) PRIMARY KEY, kind varchar(8) NOT NULL, name varchar(60) NOT NULL, name_ko varchar(60), premium decimal(8,2) NOT NULL DEFAULT 0, deductible int NOT NULL DEFAULT 0, oop_max int NOT NULL DEFAULT 0, copays json NOT NULL, hsa decimal(8,2) NOT NULL DEFAULT 0, note varchar(255), note_ko varchar(255), sort int NOT NULL DEFAULT 0);

REPLACE INTO config (k, v, note) VALUES
  ('benefits_open', '2026-10-12', 'open enrollment in the HR portal opens on this day (phone or Work record): medical, dental and vision from the plans table'),
  ('benefits_close', '2026-10-23', 'open enrollment closes at the end of this day; submitting again before then replaces the choices'),
  ('benefits_start', '2026-11-01', 'the plans picked in open enrollment start on this day: every paycheck after it has their premiums'),
  ('benefits_default', 'med_hmo+den_none+vis_none', 'the plans you get from benefits_start if you do not submit in open enrollment (plans ids)'),
  ('benefits_now', 'jun:med_ppo+den_ppo+vis_plan+4@d4_benefits,derek:med_ppo+den_ppo+vis_plan+8,priya:med_hsa+den_ppo+vis_plan+6', 'each hero: plans and 401(k) % until benefits_start (@episode: once it is done; before, the default and k401_auto). heroes.salary_net is the paycheck with these'),
  ('k401_auto', '3', '401(k) percent of pay a new hire is enrolled at automatically'),
  ('k401_match', '100', 'the company adds this percent of what you put into your 401(k), up to k401_match_up_to'),
  ('k401_match_up_to', '4', 'the company match counts your 401(k) up to this percent of pay'),
  ('k401_max', '15', 'the highest 401(k) percent the HR portal takes'),
  ('tax_state', '5.5', 'state income tax, percent of pay after the premiums and the 401(k) (an effective rate; federal is each hero''s own, from benefits_now and salary_net)'),
  ('tax_ss', '6.2', 'Social Security, percent of pay after the premiums (the 401(k) does not lower it)'),
  ('tax_medicare', '1.45', 'Medicare, percent of pay after the premiums');

REPLACE INTO plans (id, kind, name, name_ko, premium, deductible, oop_max, copays, hsa, note, note_ko, sort) VALUES
  ('med_hmo', 'medical', 'Fairview Health Basic HMO', '페어뷰 헬스 베이식 HMO', 41.5, 1500, 4500, '{"doctor":30,"specialist":60,"urgent":75,"er":350,"rx":15}', 0, 'You pick a primary care doctor in the network, and you need a referral from them to see a specialist. The plan you get if you don''t choose.', '네트워크 안에서 주치의를 정하고, 전문의를 보려면 주치의의 의뢰서가 필요해요. 아무것도 고르지 않으면 이 플랜이에요.', 10),
  ('med_ppo', 'medical', 'Fairview Health Choice PPO', '페어뷰 헬스 초이스 PPO', 86.0, 500, 3000, '{"doctor":25,"specialist":40,"urgent":50,"er":250,"rx":10}', 0, 'See any doctor or specialist without a referral. Doctors outside the network cost more.', '의뢰서 없이 어느 의사든 전문의든 볼 수 있어요. 네트워크 밖의 의사는 더 비싸요.', 20),
  ('med_hsa', 'medical', 'Fairview Health Saver HSA', '페어뷰 헬스 세이버 HSA', 12.0, 3300, 6000, '{"doctor":160,"specialist":250,"urgent":200,"er":1400,"rx":22}', 40, 'A high-deductible plan: you pay the full price of visits and drugs until you reach the deductible. The company puts $40 a paycheck into your health savings account (HSA), and it stays yours.', '공제액이 높은 플랜이에요. 공제액을 채울 때까지 진료비와 약값을 전부 내요. 회사가 급여마다 건강 저축 계좌(HSA)에 40달러를 넣어 주고, 그 돈은 계속 내 것이에요.', 30),
  ('den_ppo', 'dental', 'Coastline Dental PPO', '코스트라인 치과 PPO', 7.5, 50, 0, '{"cleaning":0,"filling":45}', 0, 'Two cleanings a year at no cost; fillings are mostly covered.', '스케일링은 1년에 두 번 무료이고, 충치 치료는 대부분 보험이 내요.', 40),
  ('den_none', 'dental', 'No dental coverage', '치과 보험 없음', 0, 0, 0, '{"cleaning":125,"filling":220}', 0, 'You pay the dentist''s full price.', '치과 비용을 전부 직접 내요.', 50),
  ('vis_plan', 'vision', 'Coastline Vision', '코스트라인 안과', 2.4, 0, 0, '{"eye_exam":10,"glasses":25}', 0, 'An eye exam a year for $10, and $150 toward glasses or contacts.', '1년에 한 번 시력 검사가 10달러이고, 안경이나 렌즈에 150달러까지 지원돼요.', 60),
  ('vis_none', 'vision', 'No vision coverage', '안과 보험 없음', 0, 0, 0, '{"eye_exam":110,"glasses":220}', 0, 'You pay the full price of eye exams and glasses.', '시력 검사와 안경 값을 전부 직접 내요.', 70);

REPLACE INTO messages (id, hero, day, time, kind, sender, subject, subject_ko, body, body_ko, every, last_day) VALUES
  ('m05_linda', 'all', 5, '10:00', 'email', 'linda', 'Open enrollment starts Monday', '월요일부터 보험 정기 가입 기간', 'Open enrollment for health, dental and vision runs October 12 through 23 in the HR portal. Our plans change on November 1, so nothing carries over this year: if you do nothing, you will get the Basic HMO with no dental or vision. Questions? My door is always open.', '건강·치과·안과 보험의 정기 가입 기간은 10월 12일부터 23일까지이고, HR 포털에서 합니다. 11월 1일에 플랜이 바뀌어서 올해는 지금 보험이 이어지지 않습니다. 아무것도 하지 않으면 치과·안과 보험 없이 베이식 HMO에 가입됩니다. 궁금한 점이 있으면 언제든 찾아오세요. (open enrollment: 보험 정기 가입 기간, carry over: 이어지다)', NULL, NULL),
  ('m08_enroll', 'all', 8, '08:30', 'email', 'linda', 'Open enrollment is open', '복리후생 정기 가입 시작', 'Open enrollment is open in the HR portal until Friday, October 23. Pick a medical plan (Basic HMO, Choice PPO or Saver HSA), and dental and vision if you want them. The new plans start November 1, and the premiums come out of your paycheck before tax. If you don''t submit anything, you''ll get the Basic HMO with no dental or vision. You can open the portal from your phone or your work record.', 'HR 포털에서 10월 23일 금요일까지 복리후생 정기 가입을 받습니다. 의료 보험(베이식 HMO, 초이스 PPO, 세이버 HSA 중 하나)을 고르고, 원하면 치과·안과 보험도 고르세요. 새 플랜은 11월 1일에 시작하고, 보험료는 급여에서 세전으로 빠집니다. 아무것도 제출하지 않으면 치과·안과 보험 없이 베이식 HMO에 가입됩니다. 포털은 휴대전화나 근무 기록에서 열 수 있어요. (premium: 보험료)', NULL, NULL);

REPLACE INTO calendar (day, time, title, title_ko, place, episode, hero) VALUES
  (19, '17:00', 'Open enrollment closes today (HR portal)', '복리후생 정기 가입 마감 (HR 포털)', NULL, NULL, 'jun'),
  (19, '17:00', 'Open enrollment closes today (HR portal)', '복리후생 정기 가입 마감 (HR 포털)', NULL, NULL, 'derek'),
  (19, '17:00', 'Open enrollment closes today (HR portal)', '복리후생 정기 가입 마감 (HR 포털)', NULL, NULL, 'priya');

REPLACE INTO chatter (npc, seq, line, line_ko) VALUES
  ('linda', 2, 'Questions about your benefits? It''s all in the HR portal.', '복리후생이 궁금하면 HR 포털에 다 있어요.');

REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, prompt, prompt_ko, answers, model, distractors, hints, hints_ko, reply_speaker, reply_line, reply_ko, line_ko, model_ko, distractors_ko, reactions, reactions_ko) VALUES
  ('d4_benefits', 3, 'linda', 'You look at the monthly costs.', '월 비용을 살펴봅니다.', 'A lot of people your age go with the HMO. But if you see doctors a lot, the PPO is worth it. Which one would you like?', 'Pick the plan where you don''t need anyone''s permission to see a specialist, and say why.', '전문의를 볼 때 누구 허락도 필요 없는 플랜을 고르고 이유를 말하세요.', '[{"any":["ppo","hmo"]}]', 'I''ll go with the PPO. I''d like to choose my own doctors.', '["I''ll go with the HMO. I''d like to choose my own doctors.","I''ll take the PPO. I''ll see doctors less, so it''s worth it.","Can I sign up for both of them, just to be safe?"]', '["Choose with \\"I''ll go with …\\".","Key words: I''ll go with, PPO or HMO"]', '["\\"I''ll go with …\\"로 고르세요.","핵심 단어: I''ll go with, PPO 또는 HMO"]', 'linda', 'Good choice. And you can still change your mind at open enrollment, October twelfth to the twenty-third.', '좋은 선택이에요. 마음이 바뀌면 10월 12일부터 23일까지 정기 가입 기간에 바꿀 수 있어요.', '또래분들은 HMO를 많이 골라요. 근데 병원을 자주 가면 PPO가 값을 해요. 어느 걸로 할래요?', 'PPO로 할게요. 의사를 제가 직접 고르고 싶어요.', '["HMO로 할게요. 의사를 제가 직접 고르고 싶어요.","PPO로 할게요. 병원은 별로 안 가니까 그게 낫겠어요.","혹시 모르니까 둘 다 가입하면 안 돼요?"]', '["With the HMO, you''d need a referral first, though.","Hmm, the PPO pays off if you go a lot, though.","Ha, no. Just one plan per person."]', '["HMO는 먼저 의뢰서가 필요한데요.","음, PPO는 병원을 자주 가야 이득인데요.","하하, 안 돼요. 한 사람당 하나예요."]'),
  ('d15_expenses', 5, 'linda', 'Linda checks your benefits page. Open enrollment for the plans that start in November closes this Friday.', '린다가 복리후생 페이지를 확인합니다. 11월에 시작하는 플랜의 정기 가입이 이번 주 금요일에 끝납니다.', 'Your four percent gets you the full 401(k) match, so that part''s fine. But don''t forget open enrollment. It closes on Friday.', 'Find out what happens if you miss the deadline.', '마감을 놓치면 어떻게 되는지 알아보세요.', '[{"any":["miss","deadline"]},{"all":["do nothing"]},{"all":["don''t","pick"]}]', 'Good to know. What happens if I miss the deadline?', '["Good to know. My plan just carries over if I do nothing, right?","Good to know. Could you pick a plan for me, then?","Good to know. Can I switch plans any time after that?"]', '["Ask what happens if you don''t make it in time.","Key words: what happens, miss the deadline"]', '["제때 못 하면 어떻게 되는지 물어보세요.","핵심 단어: what happens, miss the deadline"]', 'linda', 'You''d get the Basic HMO, just you, with no dental or vision, until next fall. So log in to the HR portal before Friday!', '치과·안과 보험 없이 본인만 베이식 HMO에 가입되고, 내년 가을까지 그대로예요. 그러니 금요일 전에 HR 포털에 들어가 봐요!', '4%를 넣고 있으니 401(k) 매칭은 다 받고 있어요. 그건 됐고요. 그런데 정기 가입 잊지 마요. 금요일에 끝나요.', '알아 둘게요. 마감을 놓치면 어떻게 돼요?', '["알아 둘게요. 아무것도 안 하면 지금 플랜이 그대로 이어지는 거죠?","알아 둘게요. 그럼 플랜을 대신 골라 주실 수 있어요?","알아 둘게요. 그 뒤에도 아무 때나 플랜을 바꿀 수 있죠?"]', '["Not this year. The plans change on November first, so everyone picks again.","I wish I could! It has to be your choice. It only takes ten minutes.","Only at the next open enrollment, or after a life event, like getting married."]', '["올해는 아니에요. 11월 1일에 플랜이 바뀌어서 다들 다시 골라야 해요.","그러고 싶지만 안 돼요! 본인이 골라야 해요. 10분이면 돼요.","다음 정기 가입 때나, 결혼 같은 생활의 변화가 있을 때만 돼요."]');
