-- Hybrid work: from Monday, November 9 (game day 36, three weeks after the missions) Seaside Labs is in the office
-- Tuesday to Thursday, and Mondays and Fridays are worked from home. Linda sends the policy on October 26 (two weeks
-- ahead), Maya texts, the all-hands day ends with a reminder, and Sam sends a checklist for working from home. On a
-- remote day you log in at your desk at home (heroes.home_desk) by late_after instead of walking into the office:
-- logging in late is late, never logging in is a missed day, logging off (or walking out of home) before early_before
-- and not coming back is leaving early. The team (config remote_people) stays home; Tom and Sam are at the office every
-- day. The standup is a video call from home with its own conversations (routines.remote_episodes, three for each
-- hero), and sprint planning and the retro move to office days (routines.hybrid_days: Tuesday, Thursday); some of their
-- lines named Monday or Friday, so they are made day-neutral here. Maya's review on Monday, January 4 stays in person.
-- The ALTER TABLE lines are run on DoltHub once; to push this file again, leave them out.
ALTER TABLE routines ADD COLUMN hybrid_days varchar(40);
ALTER TABLE routines ADD COLUMN remote_episodes varchar(1000);

REPLACE INTO config (k, v, note) VALUES
  ('hybrid_from', '2026-11-09', 'hybrid work starts this date (after the missions): config remote_days are worked from home'),
  ('remote_days', 'mon,fri', 'hybrid work: the days worked from home (log in at the desk at home); the other weekdays are office days'),
  ('remote_people', 'maya,derek,priya,jun,linda', 'hybrid work: who stays away from the office on a remote day (the front desk and IT still come in)');

UPDATE routines SET hybrid_days = 'tue' WHERE id = 'planning';
UPDATE routines SET hybrid_days = 'thu' WHERE id = 'retro';
UPDATE routines SET remote_episodes = 'rt_video_jun_1,rt_video_jun_2,rt_video_jun_3,rt_video_dk_1,rt_video_dk_2,rt_video_dk_3,rt_video_pr_1,rt_video_pr_2,rt_video_pr_3' WHERE id = 'standup';

UPDATE turns SET situation = 'Sprint planning. Priya shares the board on the big screen. First story: store managers want to export the weekly sales table as a CSV file. You built that table last sprint, so the work is small: one button and a download.', situation_ko = '스프린트 계획 회의입니다. 프리야가 큰 화면에 보드를 띄웁니다. 첫 스토리는 매장 매니저들이 주간 매출 표를 CSV 파일로 내려받고 싶어 한다는 것입니다. 그 표는 지난 스프린트에 당신이 만들었으니 일은 작습니다. 버튼 하나와 다운로드뿐이에요.' WHERE episode = 'rt_planning_dev_1' AND seq = 1;
UPDATE turns SET situation = 'Sprint planning. The team is in the meeting room, and the board is on the screen. Summit Retail''s store managers keep saying the same thing: the dashboard is slow to load in the mornings. Every other request can wait.', situation_ko = '스프린트 계획 회의입니다. 팀이 회의실에 모였고 화면에 보드가 떠 있습니다. 서밋 리테일 매장 매니저들은 같은 말을 계속합니다. 아침마다 대시보드가 느리게 뜬다고요. 다른 요청은 다 기다릴 수 있습니다.' WHERE episode = 'rt_planning_pr_1' AND seq = 1;
UPDATE turns SET situation = 'Sprint retro. Maya has drawn three columns on the whiteboard: Went well, To improve, Action items. This sprint''s release went out with zero bugs, thanks to a new release checklist the team tried.', situation_ko = '스프린트 회고입니다. 마야가 화이트보드에 세 칸을 그렸습니다. 잘된 것, 개선할 것, 실행 항목. 이번 스프린트 배포는 팀이 새로 써 본 배포 체크리스트 덕분에 버그 없이 나갔습니다.' WHERE episode = 'rt_retro_1' AND seq = 1;
UPDATE turns SET situation = 'Sprint retro. Maya always opens with shout-outs. This sprint, Sam from IT stayed late on Tuesday to fix the build server, so the team could release on time. Sam has joined the retro today.', situation_ko = '스프린트 회고입니다. 마야는 늘 감사 인사로 시작합니다. 이번 스프린트에 IT의 샘이 화요일에 늦게까지 남아 빌드 서버를 고쳐서, 팀이 제때 배포할 수 있었습니다. 오늘은 샘도 회고에 왔습니다.' WHERE episode = 'rt_retro_2' AND seq = 1;
UPDATE turns SET reply_line = 'Thanks. That''s everything. Good sprint, everyone.', reply_ko = '고마워요. 이걸로 끝이에요. 다들 수고했어요.' WHERE episode = 'rt_retro_2' AND seq = 3;
UPDATE episodes SET summary = 'Every other week, Priya plans the next two weeks with the team. Estimate a story, speak up when the sprint gets too full, and flag a risk before you commit.', summary_ko = '2주마다 프리야가 팀과 다음 2주를 계획합니다. 스토리를 추정하고, 스프린트가 너무 차면 말하고, 약속하기 전에 위험 요소를 알리세요.' WHERE id = 'rt_planning_dev_1';
UPDATE episodes SET summary = 'Every other week, Maya runs the sprint retro. Name what went well, raise a problem without blaming anyone, and turn it into an action item you own.', summary_ko = '2주마다 마야가 스프린트 회고를 진행합니다. 잘된 것을 말하고, 누구도 탓하지 않고 문제를 꺼내고, 그것을 당신이 맡는 실행 항목으로 바꾸세요.' WHERE id = 'rt_retro_1';

-- the video standups (the routine standup on a remote day): three for each hero, opened by the engine at the desk where you work
REPLACE INTO episodes (id, title, title_ko, place, npc, day_from, day_to, time_from, time_to, requires, summary, summary_ko, reward, energy, sort, tags, hero) VALUES
  ('rt_video_jun_1', 'Video standup: on mute', '화상 스탠드업: 음소거', 'home_desk', 'priya', 16, NULL, '09:45', '10:30', NULL, 'The standup is a video call today. Get your update across after a muted start, ask the right person for what you need, and own up when you miss something on a noisy call.', '오늘 스탠드업은 화상 회의입니다. 음소거로 시작이 꼬여도 소식을 전하고, 필요한 것은 맞는 사람에게 부탁하고, 시끄러워서 놓친 말은 솔직하게 다시 물으세요.', 0, 0, 2051, 'meeting,standup,routine,video', 'jun'),
  ('rt_video_jun_2', 'Video standup: the VPN', '화상 스탠드업: VPN', 'home_desk', 'priya', 16, NULL, '09:45', '10:30', NULL, 'Your VPN dropped this morning. Give your update honestly, report the problem the right way, and turn your camera on when the team asks.', '오늘 아침 VPN이 끊겼습니다. 소식을 솔직하게 전하고, 문제는 맞는 방법으로 알리고, 팀이 부탁하면 카메라를 켜세요.', 0, 0, 2052, 'meeting,standup,routine,video', 'jun'),
  ('rt_video_jun_3', 'Video standup: the lag', '화상 스탠드업: 지연', 'home_desk', 'priya', 16, NULL, '09:45', '10:30', NULL, 'The call lags, and people talk over each other. Give the floor politely, keep your update specific, and take a side question offline.', '통화가 지연되어 서로 말이 겹칩니다. 정중하게 순서를 양보하고, 소식은 구체적으로 전하고, 곁가지 질문은 회의 뒤로 미루세요.', 0, 0, 2053, 'meeting,standup,routine,video', 'jun'),
  ('rt_video_dk_1', 'Video standup: the doorbell', '화상 스탠드업: 초인종', 'derek_desk', 'priya', 16, NULL, '09:45', '10:30', NULL, 'The doorbell rings just as it''s your turn. Keep your update calm and short, tell Jun where his data is, and let the team know when you''ll be away this week.', '당신 차례가 되자마자 초인종이 울립니다. 침착하고 짧게 소식을 전하고, 준에게 데이터가 어디 있는지 알려 주고, 이번 주에 자리를 비우는 때를 팀에 알리세요.', 0, 0, 2061, 'meeting,standup,routine,video', 'derek'),
  ('rt_video_dk_2', 'Video standup: a frozen screen', '화상 스탠드업: 멈춘 화면', 'derek_desk', 'priya', 16, NULL, '09:45', '10:30', NULL, 'Jun''s connection breaks up in the middle of his update. Help him get it across, point him to a bug you know, and tell the team when you''ll be offline.', '준의 연결이 소식 도중에 끊깁니다. 그가 말을 전하도록 돕고, 아는 버그를 알려 주고, 언제 오프라인인지 팀에 알리세요.', 0, 0, 2062, 'meeting,standup,routine,video', 'derek'),
  ('rt_video_dk_3', 'Video standup: the wrong window', '화상 스탠드업: 엉뚱한 창', 'derek_desk', 'priya', 16, NULL, '09:45', '10:30', NULL, 'You share the wrong window on a video call. Fix it quickly, explain a slow query in plain words, and set up a call so Jun can learn from you.', '화상 회의에서 엉뚱한 창을 공유했습니다. 얼른 바로잡고, 느린 쿼리를 쉬운 말로 설명하고, 준이 배울 수 있게 통화 약속을 잡으세요.', 0, 0, 2063, 'meeting,standup,routine,video', 'derek'),
  ('rt_video_pr_1', 'Video standup: starting on time', '화상 스탠드업: 제시간에 시작하기', 'priya_desk', 'derek', 16, NULL, '09:45', '10:30', NULL, 'You run the standup on video. Start on time without Maya, share what the stores asked for, and keep a long update from taking over.', '화상 스탠드업을 진행합니다. 마야 없이도 제시간에 시작하고, 매장의 요청을 전하고, 긴 발언이 회의를 잡아먹지 않게 하세요.', 0, 0, 2071, 'meeting,standup,routine,video', 'priya'),
  ('rt_video_pr_2', 'Video standup: news from IT', '화상 스탠드업: IT 공지', 'priya_desk', 'derek', 16, NULL, '09:45', '10:30', NULL, 'Pass on a notice from IT, look out for a teammate who had a rough night, and say when the notes go out.', 'IT의 공지를 전하고, 힘든 밤을 보낸 동료를 챙기고, 회의 메모를 언제 올릴지 말하세요.', 0, 0, 2072, 'meeting,standup,routine,video', 'priya'),
  ('rt_video_pr_3', 'Video standup: drilling next door', '화상 스탠드업: 옆집 공사', 'priya_desk', 'derek', 16, NULL, '09:45', '10:30', NULL, 'Construction noise starts next door while you run the call. Handle it, share the client''s decision and what it means, and unblock Jun right away.', '통화를 진행하는데 옆집 공사 소음이 들립니다. 소음을 처리하고, 고객의 결정과 그 의미를 전하고, 막힌 준을 바로 풀어 주세요.', 0, 0, 2073, 'meeting,standup,routine,video', 'priya');

-- rt_video_jun_1
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_jun_1', 1, NULL, 'Ten o''clock standup on video: five faces in little squares. Yesterday you finished the store picker; today you''re writing its tests. You start talking, and the chat fills up: you''re on mute.', '화상으로 하는 10시 스탠드업입니다. 작은 네모 안에 얼굴 다섯이 보입니다. 어제는 매장 선택 기능을 끝냈고, 오늘은 그 테스트를 씁니다. 말을 시작하자 채팅창에 메시지가 쏟아집니다. 음소거 상태라고요.', 'Jun, I think you''re on mute. ... There you go. Go ahead.', '준, 음소거된 것 같아요. ... 이제 들려요. 시작해요.', 'Brush off the mute in a few words, then give your update.', '음소거는 짧게 넘기고, 오늘 소식을 전하세요.', '[]', 'Sorry, I was muted. Yesterday I finished the store picker, and today I''m writing its tests.', '죄송해요, 음소거였네요. 어제 매장 선택 기능을 끝냈고, 오늘은 그 테스트를 써요.', '["Sorry, I was muted. Yesterday I started the store picker, and today I''m finishing it.", "Sorry, my laptop''s mic never works properly. Honestly, IT should replace this thing.", "Can everyone hear me now? Maybe we should all turn our cameras off to save bandwidth."]', '["죄송해요, 음소거였네요. 어제 매장 선택 기능을 시작했고, 오늘 끝낼 거예요.", "죄송해요, 노트북 마이크가 늘 말썽이에요. 솔직히 IT에서 이거 바꿔 줘야 해요.", "이제 다들 들려요? 대역폭 아끼게 다 같이 카메라를 끄는 게 어때요?"]', '["Started? I thought it was done.", "Let''s take that up with Sam after standup.", "Cameras are fine. Just your update, please."]', '["시작했다고요? 끝난 줄 알았는데요.", "그건 스탠드업 끝나고 샘이랑 얘기해요.", "카메라는 괜찮아요. 소식만 말해 줘요."]', NULL, 'Got it, thanks.', '알겠어요, 고마워요.'),
  ('rt_video_jun_1', 2, NULL, 'You need test data for two pilot stores. Only Derek has access to the sales export, and you haven''t asked him yet.', '시범 매장 두 곳의 테스트 데이터가 필요합니다. 매출 내보내기 권한은 데릭에게만 있고, 아직 부탁하지 않았습니다.', 'Anything blocking you?', '막힌 건 없어요?', 'Ask for what you need, from the person who can give it.', '필요한 것을, 그걸 해 줄 수 있는 사람에게 부탁하세요.', '[]', 'One thing: I need test data for two stores. Derek, could you pull an export for me today?', '하나 있어요. 매장 두 곳 테스트 데이터가 필요해요. 데릭, 오늘 내보내기 좀 해 줄 수 있어요?', '["One thing: I need test data for two stores. Sam, could you pull an export for me today?", "Nope. If I can''t get real data, I''ll just make up some numbers for the tests.", "Yes, I''m stuck until Derek sends me data. I can''t do anything else today."]', '["하나 있어요. 매장 두 곳 테스트 데이터가 필요해요. 샘, 오늘 내보내기 좀 해 줄 수 있어요?", "없어요. 진짜 데이터를 못 구하면 테스트용 숫자는 그냥 지어낼게요.", "네, 데릭이 데이터를 보내 줄 때까지 꼼짝 못 해요. 오늘은 다른 걸 못 해요."]', '["Sam? I think only Derek has that access.", "Made-up numbers can hide real bugs. Ask for the real thing.", "Nothing else at all? You could start with the simple tests."]', '["샘이요? 그 권한은 데릭만 있는 것 같은데요.", "지어낸 숫자는 진짜 버그를 가릴 수 있어요. 진짜 데이터를 부탁해요.", "다른 건 하나도요? 간단한 테스트부터 시작해도 되잖아요."]', 'derek', 'Sure. I''ll send it over after lunch.', '그래요. 점심 먹고 보내 줄게요.'),
  ('rt_video_jun_1', 3, NULL, 'A leaf blower starts up right outside your window. Priya is talking about the release, and you miss the day she says.', '창문 바로 밖에서 낙엽 청소기가 돌기 시작합니다. 프리야가 배포 얘기를 하는데, 무슨 요일이라고 했는지 놓쳤습니다.', '...so that''s the plan for the release. Jun, did you catch that?', '...배포는 그렇게 하기로 해요. 준, 들었어요?', 'Admit the noise made you miss it, and ask her to repeat the key part.', '소음 때문에 놓쳤다고 솔직히 말하고, 중요한 부분을 다시 말해 달라고 하세요.', '[]', 'Sorry, a leaf blower just started outside. Could you repeat the release day?', '죄송해요, 밖에서 낙엽 청소기가 돌기 시작해서요. 배포 날짜를 다시 말해 줄래요?', '["Yes, got it. The release is Tuesday, right? Sounds good to me.", "Sorry, it''s way too loud here. Can we just do standups by email from now on?", "Sorry, a leaf blower just started outside. Could you repeat the part about the budget?"]', '["네, 들었어요. 배포는 화요일 맞죠? 좋아요.", "죄송해요, 여기 너무 시끄러워요. 앞으로 스탠드업은 그냥 이메일로 하면 안 돼요?", "죄송해요, 밖에서 낙엽 청소기가 돌기 시작해서요. 예산 얘기를 다시 해 줄래요?"]', '["Thursday, actually. Good thing I asked.", "It''s one noisy morning, Jun. I''ll just repeat it.", "Budget? I was talking about the release."]', '["사실은 목요일이에요. 물어보길 잘했네요.", "시끄러운 건 오늘 아침뿐이잖아요, 준. 다시 말해 줄게요.", "예산이요? 배포 얘기였는데요."]', NULL, 'No problem. It''s Thursday, so please have your tests merged by Wednesday.', '괜찮아요. 목요일이니까 테스트는 수요일까지 병합해 줘요.');

-- rt_video_jun_2
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_jun_2', 1, NULL, 'Ten o''clock standup on video. The VPN dropped twice this morning, and you lost about an hour. Yesterday you fixed the date filter bug; today you''re on the export button.', '화상으로 하는 10시 스탠드업입니다. 오늘 아침 VPN이 두 번 끊겨서 한 시간쯤 날렸습니다. 어제는 날짜 필터 버그를 고쳤고, 오늘은 내보내기 버튼을 만듭니다.', 'Morning, Jun. How''s it going?', '좋은 아침이에요, 준. 어때요?', 'Give your update, and mention the connection trouble briefly.', '오늘 소식을 전하고, 접속 문제도 짧게 말하세요.', '[]', 'Yesterday I fixed the date filter. Today it''s the export button. The VPN dropped twice this morning, though.', '어제는 날짜 필터를 고쳤고, 오늘은 내보내기 버튼을 해요. 그런데 아침에 VPN이 두 번 끊겼어요.', '["Yesterday I fixed the export button. Today it''s the date filter. The VPN dropped twice this morning, though.", "Not great, honestly. The VPN keeps dropping, so working from home just doesn''t work for me.", "Yesterday I fixed the date filter. Today it''s the export button. Everything''s running perfectly."]', '["어제는 내보내기 버튼을 고쳤고, 오늘은 날짜 필터를 해요. 그런데 아침에 VPN이 두 번 끊겼어요.", "솔직히 별로예요. VPN이 자꾸 끊겨서 재택근무는 저랑 안 맞아요.", "어제는 날짜 필터를 고쳤고, 오늘은 내보내기 버튼을 해요. 다 완벽하게 돌아가요."]', '["Wait, I thought the export was today''s job.", "Let''s fix the VPN before we give up on home days.", "Really? Your status said offline for an hour."]', '["잠깐, 내보내기가 오늘 할 일인 줄 알았는데요.", "재택을 포기하기 전에 VPN부터 고쳐 봐요.", "정말요? 한 시간 동안 오프라인으로 떠 있던데요."]', NULL, 'Ugh, sorry. That''s no fun.', '아이고, 저런. 힘들었겠네요.'),
  ('rt_video_jun_2', 2, NULL, 'Sam from IT fixes VPN problems through the help desk. You haven''t filed a ticket yet.', 'IT의 샘이 헬프데스크로 VPN 문제를 처리합니다. 아직 티켓을 올리지 않았습니다.', 'Have you told Sam?', '샘한테 말했어요?', 'Say what you''ll do about it, through the proper channel.', '어떻게 할지, 정해진 방법으로 처리하겠다고 말하세요.', '[]', 'Not yet. I''ll file a help desk ticket right after standup, with the times it dropped.', '아직요. 스탠드업 끝나면 바로 끊긴 시각을 적어서 헬프데스크 티켓을 올릴게요.', '["Not yet. I''ll call Sam on his cell tonight and ask him to take a look.", "No. It''s probably just my home Wi-Fi, so there''s nothing IT can do.", "Not yet. I''ll file a help desk ticket next week, when I''m back at the office."]', '["아직요. 오늘 밤에 샘 휴대전화로 전화해서 봐 달라고 할게요.", "아뇨. 아마 집 와이파이 문제라서 IT가 해 줄 게 없을 거예요.", "아직요. 다음 주에 사무실 나가면 헬프데스크 티켓을 올릴게요."]', '["Tonight? Please use the help desk instead.", "Maybe, but let IT check first.", "Next week? You''ll lose more hours before then."]', '["오늘 밤이요? 헬프데스크로 해 줘요.", "그럴 수도 있지만 IT가 먼저 확인하게 해요.", "다음 주요? 그 전에 시간을 더 날릴 거예요."]', NULL, 'Good. The times will help him a lot.', '좋아요. 시각을 적어 주면 샘한테 큰 도움이 돼요.'),
  ('rt_video_jun_2', 3, 'maya', 'Maya joins a few minutes late. Your camera is off because your room is a mess.', '마야가 몇 분 늦게 들어옵니다. 방이 어질러져 있어서 당신은 카메라를 꺼 두었습니다.', 'Quick ask, everyone: cameras on for standup, if you can. Jun, could you turn yours on?', '다들 부탁 하나 할게요. 스탠드업 때는 되도록 카메라를 켜 줘요. 준, 켜 줄 수 있어요?', 'Agree politely and turn it on, with a light word about your room.', '기분 좋게 알겠다고 하고 카메라를 켜면서, 방 얘기를 가볍게 덧붙이세요.', '[]', 'Sure, one sec. Please ignore the laundry behind me!', '그럼요, 잠깐만요. 뒤에 빨래는 못 본 걸로 해 주세요!', '["I''d rather not. Nobody needs to see my apartment.", "Sure, one sec. Though cameras on is a bit much for a ten-minute call.", "Sure. I''ll have it on for the next standup."]', '["안 켜고 싶어요. 제 집을 볼 필요는 없잖아요.", "네, 잠깐만요. 근데 10분짜리 통화에 카메라까지 켜는 건 좀 과한 것 같아요.", "네. 다음 스탠드업 때는 켤게요."]', '["It''s only for ten minutes, but okay. We can talk later.", "I hear you, but it helps us feel like a team.", "Now would be great, actually."]', '["10분만인데요. 알겠어요, 나중에 얘기해요.", "무슨 말인지 알지만, 얼굴을 보면 팀처럼 느껴져요.", "사실 지금 켜 주면 좋겠어요."]', NULL, 'Ha, we''ve all got laundry. Good to see you!', '하하, 빨래는 다들 있죠. 얼굴 보니 좋네요!');

-- rt_video_jun_3
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_jun_3', 1, 'derek', 'Ten o''clock standup on video. The call lags a little. You and Derek both start talking at the same moment, then both stop.', '화상으로 하는 10시 스탠드업입니다. 통화가 조금 지연됩니다. 당신과 데릭이 동시에 말을 시작했다가 둘 다 멈춥니다.', 'Oh, sorry. Go ahead.', '아, 미안해요. 먼저 해요.', 'Let him go first, politely.', '정중하게 데릭에게 먼저 하라고 양보하세요.', '[]', 'No, you go ahead, Derek. I''ll go after you.', '아니에요, 데릭 먼저 해요. 전 다음에 할게요.', '["No, you go ahead, Priya. I''ll go after you.", "Okay, thanks. Could you mute, though? There''s an echo from your side.", "Thanks. I''ll be fast, since my update is more important today."]', '["아니에요, 프리야 먼저 해요. 전 다음에 할게요.", "네, 고마워요. 근데 음소거 좀 해 줄래요? 그쪽에서 울려요.", "고마워요. 오늘은 제 소식이 더 중요하니까 빨리 할게요."]', '["Priya''s running it. I meant you.", "I''m on headphones, Jun. No echo here.", "More important? Okay..."]', '["진행은 프리야가 해요. 당신한테 한 말이에요.", "저 헤드폰 쓰고 있어요, 준. 안 울려요.", "더 중요하다고요? 음..."]', NULL, 'Thanks. I''ll keep it short.', '고마워요. 짧게 할게요.'),
  ('rt_video_jun_3', 2, NULL, 'Your turn. Yesterday you reviewed Derek''s pull request and left three comments. At two today you''re pairing with Derek on the inventory chart.', '당신 차례입니다. 어제 데릭의 풀 리퀘스트를 리뷰하고 의견 세 개를 남겼습니다. 오늘 2시에는 데릭과 재고 차트를 같이 작업합니다.', 'Jun, your turn.', '준, 당신 차례예요.', 'Give a short, specific update.', '짧고 구체적으로 소식을 전하세요.', '[]', 'Yesterday I reviewed Derek''s pull request and left a few comments. At two, Derek and I are pairing on the inventory chart.', '어제 데릭의 풀 리퀘스트를 리뷰하고 의견을 몇 개 남겼어요. 2시에는 데릭과 재고 차트를 같이 해요.', '["Yesterday I reviewed Derek''s pull request and approved it as is. At two, Derek and I are pairing on the inventory chart.", "Yesterday I reviewed Derek''s pull request and left a few comments. At two, Derek and I are pairing on the sales chart.", "Same as usual, really. Some coding, some reviews, some meetings. Nothing special."]', '["어제 데릭의 풀 리퀘스트를 리뷰하고 그대로 승인했어요. 2시에는 데릭과 재고 차트를 같이 해요.", "어제 데릭의 풀 리퀘스트를 리뷰하고 의견을 몇 개 남겼어요. 2시에는 데릭과 매출 차트를 같이 해요.", "늘 하던 거예요. 코딩 조금, 리뷰 조금, 회의 조금. 특별한 건 없어요."]', '["Approved? I thought you had a few comments.", "The sales chart? I have inventory on the board.", "Could you be a little more specific?"]', '["승인했다고요? 의견을 남긴 줄 알았는데요.", "매출 차트요? 보드에는 재고로 되어 있는데요.", "조금만 더 구체적으로 말해 줄래요?"]', NULL, 'Great, thanks.', '좋아요, 고마워요.'),
  ('rt_video_jun_3', 3, NULL, 'The call is almost over. You have a quick question for Derek about the chart library, but it only matters to the two of you.', '통화가 거의 끝나 갑니다. 차트 라이브러리에 대해 데릭에게 물어볼 게 있지만, 두 사람에게만 해당하는 얘기입니다.', 'Anything else before we drop off?', '끊기 전에 더 할 말 있어요?', 'Keep the call short: take your question offline.', '통화를 짧게 끝내도록, 질문은 회의 뒤로 미루세요.', '[]', 'Just one for Derek, but I''ll message him after this.', '데릭한테 하나 있는데, 끝나고 메시지 보낼게요.', '["Yes. Derek, which version of the chart library are we on? Is it the old one or the new one?", "Just one for Derek, but let''s all stay on so everyone can hear it.", "Just one for Sam, but I''ll message him after this."]', '["네. 데릭, 우리 차트 라이브러리 몇 버전 써요? 예전 거예요, 새 거예요?", "데릭한테 하나 있는데, 다들 들을 수 있게 다 같이 남아 있어요.", "샘한테 하나 있는데, 끝나고 메시지 보낼게요."]', '["Can that wait until after standup?", "Only if it matters to everyone.", "Sam? I thought it was about the chart."]', '["그건 스탠드업 끝나고 해도 되지 않아요?", "다들 알아야 하는 거라면요.", "샘이요? 차트 얘기인 줄 알았는데요."]', 'derek', 'Sounds good. Ping me.', '좋아요. 메시지 줘요.');

-- rt_video_dk_1
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_dk_1', 1, NULL, 'Ten o''clock standup on video. The doorbell rings just as Priya calls your name: a delivery. Yesterday you finished the store ID cleanup; today you''re testing it on staging.', '화상으로 하는 10시 스탠드업입니다. 프리야가 당신 이름을 부르는 순간 초인종이 울립니다. 택배입니다. 어제는 매장 ID 정리를 끝냈고, 오늘은 스테이징에서 테스트합니다.', 'Derek? Oh, sounds like someone''s at your door.', '데릭? 아, 누가 문 앞에 왔나 봐요.', 'Excuse the interruption in a few words, then give your update.', '끊긴 건 짧게 사과하고, 오늘 소식을 전하세요.', '[]', 'Sorry, just a delivery. Yesterday I finished the store ID cleanup. Today I''m testing it on staging.', '미안해요, 택배예요. 어제 매장 ID 정리를 끝냈고, 오늘은 스테이징에서 테스트해요.', '["Sorry, just a delivery. Yesterday I finished the store ID cleanup. Today it goes straight to production.", "Sorry, just a delivery. Yesterday I started the store ID cleanup. Today I''m finishing it.", "Sorry, it''s chaos here today. Can someone else go first while I deal with it?"]', '["미안해요, 택배예요. 어제 매장 ID 정리를 끝냈고, 오늘 바로 운영에 올려요.", "미안해요, 택배예요. 어제 매장 ID 정리를 시작했고, 오늘 끝낼 거예요.", "미안해요, 오늘 여기 정신없네요. 제가 처리하는 동안 다른 사람이 먼저 해 줄래요?"]', '["Production? Didn''t you want staging first?", "Started? I thought it was done.", "Sure, but it''s only a delivery. Can you do it quickly?"]', '["운영에요? 스테이징부터 하려던 거 아니었어요?", "시작했다고요? 끝난 줄 알았는데요.", "그래도 되지만, 택배일 뿐이잖아요. 빨리 할 수 있어요?"]', NULL, 'Thanks, Derek.', '고마워요, 데릭.'),
  ('rt_video_dk_1', 2, 'jun', 'Jun asked you for test data for two stores. You pulled it this morning and put it in the team folder.', '준이 매장 두 곳의 테스트 데이터를 부탁했습니다. 오늘 아침에 뽑아서 팀 폴더에 넣어 두었습니다.', 'Derek, did you get a chance to pull that test data?', '데릭, 그 테스트 데이터 뽑아 볼 시간 있었어요?', 'Tell him it''s done and where to find it.', '다 했다고, 어디서 찾으면 되는지 알려 주세요.', '[]', 'Yes, I pulled it this morning. It''s in the team folder, under Test Data.', '네, 오늘 아침에 뽑았어요. 팀 폴더의 Test Data 안에 있어요.', '["Not yet, sorry. I''ll get to it this afternoon.", "Yes, I emailed it to Sam this morning. He can forward it to you.", "Yes, but you should really learn to pull your own data by now."]', '["아직요, 미안해요. 오후에 할게요.", "네, 오늘 아침에 샘한테 메일로 보냈어요. 샘이 전달해 줄 거예요.", "네, 근데 이제는 데이터 정도는 직접 뽑을 줄 알아야죠."]', '["Oh. Sam said you did it this morning.", "To Sam? I don''t think he has it.", "Okay... could you show me how sometime?"]', '["아. 샘은 오늘 아침에 했다고 하던데요.", "샘한테요? 샘한테는 없는 것 같은데요.", "네... 언제 방법 좀 알려 줄 수 있어요?"]', NULL, 'Found it. Thanks!', '찾았어요. 고마워요!'),
  ('rt_video_dk_1', 3, NULL, 'Your on-call week starts tonight. You''ll be home with your laptop all week, but you have a dentist appointment at two on Wednesday.', '오늘 밤부터 온콜 주간입니다. 일주일 내내 노트북을 끼고 집에 있겠지만, 수요일 2시에 치과 예약이 있습니다.', 'Anything the team should know this week?', '이번 주에 팀이 알아야 할 게 있어요?', 'Mention the on-call week and the hour you''ll be away.', '온콜 주간이라는 것과 자리를 비우는 한 시간을 알리세요.', '[]', 'I''m on call from tonight. And Wednesday at two, I''m at the dentist for an hour.', '오늘 밤부터 온콜이에요. 그리고 수요일 2시에 한 시간 동안 치과에 가요.', '["I''m on call from tonight. And Thursday at two, I''m at the dentist for an hour.", "I''m on call this week, so please don''t put any meetings on my calendar.", "Nothing much. Oh, and I''ll be out all day Wednesday for the dentist."]', '["오늘 밤부터 온콜이에요. 그리고 목요일 2시에 한 시간 동안 치과에 가요.", "이번 주는 온콜이니까 제 일정에는 회의를 넣지 말아 주세요.", "별거 없어요. 아, 수요일은 치과 때문에 하루 종일 없어요."]', '["Thursday? Your calendar says Wednesday.", "On call doesn''t mean no meetings, Derek.", "All day? For the dentist?"]', '["목요일이요? 달력에는 수요일로 되어 있는데요.", "온콜이라고 회의가 없는 건 아니에요, 데릭.", "하루 종일이요? 치과 때문에요?"]', NULL, 'Thanks. I''ll put it on the team calendar.', '고마워요. 팀 달력에 넣어 둘게요.');

-- rt_video_dk_2
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_dk_2', 1, NULL, 'Ten o''clock standup on video. Jun is reporting a bug, but his picture froze a minute ago and his voice keeps cutting out.', '화상으로 하는 10시 스탠드업입니다. 준이 버그를 보고하고 있는데, 1분 전부터 화면이 멈췄고 목소리가 자꾸 끊깁니다.', 'Jun? I think we lost you.', '준? 연결이 끊긴 것 같아요.', 'Help out: tell Jun he''s breaking up, and suggest a way around it.', '도와주세요. 준에게 끊긴다고 알려 주고, 다른 방법을 제안하세요.', '[]', 'Jun, you''re breaking up. Could you type it in the chat?', '준, 소리가 끊겨요. 채팅에 적어 줄래요?', '["Jun, you''re frozen. Let''s just skip you today.", "Jun, we can hear you fine. Keep going.", "Jun, you''re breaking up. Could you email it to us next week?"]', '["준, 화면이 멈췄어요. 오늘은 그냥 건너뛰죠.", "준, 잘 들려요. 계속해요.", "준, 소리가 끊겨요. 다음 주에 메일로 보내 줄래요?"]', '["Let''s not skip him. He has a bug to report.", "Really? It''s all choppy on my end.", "Next week? It sounded urgent."]', '["건너뛰진 말아요. 버그를 보고하던 중이에요.", "정말요? 제 쪽에서는 계속 끊기는데요.", "다음 주요? 급한 얘기 같던데요."]', NULL, 'Good idea. ...Okay, it''s in the chat: the weekly totals are off by a few cents.', '좋은 생각이에요. ...채팅에 올라왔네요. 주간 합계가 몇 센트씩 안 맞는대요.'),
  ('rt_video_dk_2', 2, NULL, 'You know this bug: it''s the same rounding problem you fixed in the daily totals last month.', '이 버그는 압니다. 지난달 당신이 일간 합계에서 고친 반올림 문제와 같습니다.', 'Derek, does that ring a bell?', '데릭, 짚이는 거 있어요?', 'Say what you know, and offer to help Jun without taking over.', '아는 것을 말하고, 일을 가져가지 말고 준을 돕겠다고 하세요.', '[]', 'Yes, it looks like the rounding bug from the daily totals. I can pair with Jun on it after lunch.', '네, 일간 합계의 반올림 버그 같아요. 점심 먹고 준이랑 같이 볼게요.', '["Yes, it''s the rounding bug. I''ll just fix it myself tonight. It''s faster that way.", "No idea, sorry. That''s Jun''s code, so it''s really his problem.", "Yes, it looks like the time zone bug from the daily totals. I can pair with Jun on it after lunch."]', '["네, 반올림 버그예요. 오늘 밤에 제가 그냥 고칠게요. 그게 빨라요.", "모르겠어요, 미안해요. 준의 코드니까 준이 알아서 할 문제예요.", "네, 일간 합계의 시간대 버그 같아요. 점심 먹고 준이랑 같이 볼게요."]', '["Let Jun learn this one. Maybe pair with him instead?", "We''re one team, Derek.", "Time zone? He said it''s off by cents."]', '["이번 건 준이 배우게 해 줘요. 같이 보는 건 어때요?", "우린 한 팀이에요, 데릭.", "시간대요? 몇 센트 차이라고 했는데요."]', NULL, 'Perfect. Jun says after lunch works.', '좋아요. 준도 점심 뒤가 괜찮대요.'),
  ('rt_video_dk_2', 3, NULL, 'Today you log off at four to pick up your sister Elena at the airport. Maya already said that was fine.', '오늘은 엘레나를 데리러 공항에 가려고 4시에 로그아웃합니다. 마야는 이미 괜찮다고 했습니다.', 'Anything else before we go?', '끝내기 전에 더 있어요?', 'Tell the team when you''ll be offline today, and how to reach you.', '오늘 언제 오프라인인지, 급하면 어떻게 연락하면 되는지 팀에 알리세요.', '[]', 'I''m logging off at four today. If anything breaks, text me.', '오늘은 4시에 로그아웃해요. 뭐가 고장 나면 문자 주세요.', '["I''m logging off at two today. If anything breaks, text me.", "I''m off at four, and I won''t look at my phone after that, so don''t bother texting.", "Nope, nothing from me. Have a good one, everyone."]', '["오늘은 2시에 로그아웃해요. 뭐가 고장 나면 문자 주세요.", "4시에 끝나고 그 뒤로는 휴대전화를 안 볼 테니까 문자해도 소용없어요.", "아뇨, 저는 없어요. 다들 수고해요."]', '["Two? I thought Maya said four.", "Okay, but who do we call if it''s urgent?", "Didn''t you say you''re leaving early today?"]', '["2시요? 마야는 4시라고 했던 것 같은데요.", "알겠어요. 그럼 급하면 누구한테 연락해요?", "오늘 일찍 간다고 하지 않았어요?"]', NULL, 'Thanks for the heads-up. Safe drive!', '미리 알려 줘서 고마워요. 운전 조심해요!');

-- rt_video_dk_3
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_dk_3', 1, NULL, 'Ten o''clock standup on video. You share your screen to show the slow sales query, but your personal email is open on top.', '화상으로 하는 10시 스탠드업입니다. 느린 매출 쿼리를 보여 주려고 화면을 공유했는데, 개인 메일 창이 맨 위에 떠 있습니다.', 'Derek, I think we''re looking at your inbox...', '데릭, 지금 메일함이 보이는 것 같은데요...', 'Apologize quickly and share only the right window.', '얼른 사과하고, 맞는 창만 공유하세요.', '[]', 'Oops, sorry about that. Let me share just the browser window.', '앗, 미안해요. 브라우저 창만 공유할게요.', '["Oops, sorry about that. Let me share my whole screen instead.", "Ha, well, now you all know my weekend plans. Anyway, the query...", "Sorry, I''ll stop sharing. You can look at the query on your own later."]', '["앗, 미안해요. 대신 화면 전체를 공유할게요.", "하하, 이제 다들 제 주말 계획을 알게 됐네요. 아무튼, 쿼리는...", "미안해요, 공유를 끌게요. 쿼리는 나중에 각자 봐요."]', '["Your whole screen is what we''re seeing now.", "Ha. Could you switch windows first, though?", "It would really help to see it now."]', '["지금 보이는 게 화면 전체예요.", "하하. 그래도 창부터 바꿔 줄래요?", "지금 보는 게 정말 도움이 될 텐데요."]', NULL, 'There it is. Thanks.', '이제 보여요. 고마워요.'),
  ('rt_video_dk_3', 2, NULL, 'On screen: the weekly sales query reads the whole sales table every time. You plan to add an index today and test it on staging first.', '화면에는 주간 매출 쿼리가 매번 매출 테이블 전체를 읽는 모습이 보입니다. 오늘 인덱스를 추가하고 먼저 스테이징에서 테스트할 계획입니다.', 'So what''s the plan?', '그래서 계획은요?', 'Explain the plan in plain words.', '쉬운 말로 계획을 설명하세요.', '[]', 'The query reads the whole table every time. I''ll add an index today and test it on staging.', '쿼리가 매번 테이블 전체를 읽어요. 오늘 인덱스를 추가하고 스테이징에서 테스트할게요.', '["The query reads the whole table every time. I''ll add an index today and put it straight into production.", "It''s a full scan on the sales fact table. I''ll add a composite B-tree index on two columns.", "The query is just slow sometimes. I''ll keep an eye on it and see if it gets worse."]', '["쿼리가 매번 테이블 전체를 읽어요. 오늘 인덱스를 추가해서 바로 운영에 넣을게요.", "매출 팩트 테이블 풀 스캔이에요. 두 컬럼에 복합 B-트리 인덱스를 걸게요.", "쿼리가 가끔 느릴 뿐이에요. 지켜보다가 더 나빠지면 볼게요."]', '["Straight into production? Staging first, please.", "Um... in plain words?", "The stores are already complaining, though."]', '["바로 운영에요? 스테이징부터 해 줘요.", "음... 쉬운 말로 해 줄래요?", "매장들은 벌써 불평하고 있는데요."]', NULL, 'Clear. Thanks, Derek.', '알겠어요. 고마워요, 데릭.'),
  ('rt_video_dk_3', 3, 'jun', 'In the chat, Jun asks if he can watch you add the index. You plan to do it at one.', '준이 채팅으로 인덱스 추가하는 걸 지켜봐도 되냐고 묻습니다. 당신은 1시에 할 계획입니다.', 'Derek, could I watch when you add the index?', '데릭, 인덱스 추가할 때 옆에서 봐도 돼요?', 'Say yes, and set it up for a day when you both work from home.', '좋다고 하고, 둘 다 집에서 일하는 날에 맞게 약속을 잡으세요.', '[]', 'Sure. I''ll send you a call link at one.', '그럼요. 1시에 통화 링크 보낼게요.', '["Sure. I''ll send you a call link at three.", "Sure. Just come by my desk at one.", "Maybe another time. It''s a bit too advanced for you."]', '["그럼요. 3시에 통화 링크 보낼게요.", "그럼요. 1시에 제 자리로 와요.", "다음에 해요. 아직 당신한텐 좀 어려워요."]', '["Three? I have a meeting then.", "Your desk? We''re both at home today.", "Oh. Okay..."]', '["3시요? 그때는 회의가 있는데요.", "자리요? 오늘은 둘 다 집인데요.", "아. 네..."]', NULL, 'Thanks! See you at one.', '고마워요! 1시에 봐요.');

-- rt_video_pr_1
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_pr_1', 1, NULL, 'Ten o''clock. You run the standup on video. Derek and Jun are on the call, but Maya hasn''t joined yet. It''s 10:01.', '10시입니다. 화상 스탠드업은 당신이 진행합니다. 데릭과 준은 들어와 있는데 마야는 아직입니다. 지금 10시 1분입니다.', 'Should we wait for Maya?', '마야를 기다릴까요?', 'Start on time, and say how Maya can catch up.', '제시간에 시작하고, 마야가 내용을 어떻게 따라잡을지 말하세요.', '[]', 'Let''s start. I''ll post notes in the chat for Maya.', '시작하죠. 마야를 위해 채팅에 메모를 올릴게요.', '["Let''s give her five more minutes. She''s the manager, after all.", "Let''s start. Maya doesn''t really need to be here anyway.", "Let''s just cancel today. It''s not worth it without Maya."]', '["5분만 더 기다려요. 그래도 매니저잖아요.", "시작하죠. 어차피 마야는 꼭 있어야 하는 건 아니에요.", "오늘은 그냥 취소해요. 마야 없으면 할 의미가 없어요."]', '["Five minutes times four people adds up.", "Careful, she might join any second.", "Cancel? I have things to share."]', '["5분씩 네 명이면 꽤 되는데요.", "조심해요, 마야가 곧 들어올지도 몰라요.", "취소요? 전 할 얘기가 있는데요."]', NULL, 'Works for me.', '좋아요.'),
  ('rt_video_pr_1', 2, NULL, 'Your update: yesterday you talked to two pilot store managers. Both asked for low-stock alerts by email. You haven''t written the story yet.', '당신 소식: 어제 시범 매장 관리자 두 명과 얘기했습니다. 둘 다 재고 부족 알림을 이메일로 받고 싶어 합니다. 스토리는 아직 쓰지 않았습니다.', 'Your update, Priya?', '프리야 소식은요?', 'Share what you learned and what you''ll do next.', '알게 된 것과 다음에 할 일을 말하세요.', '[]', 'Two store managers asked for low-stock alerts by email. I''ll write the story today.', '매장 관리자 두 명이 재고 부족 알림을 이메일로 받고 싶대요. 오늘 스토리를 쓸게요.', '["Two store managers asked for low-stock alerts by text. I''ll write the story today.", "Two store managers asked for low-stock alerts by email. Derek, can you start building it today?", "The store managers want a bunch of things. I''ll tell you more when I know more."]', '["매장 관리자 두 명이 재고 부족 알림을 문자로 받고 싶대요. 오늘 스토리를 쓸게요.", "매장 관리자 두 명이 재고 부족 알림을 이메일로 받고 싶대요. 데릭, 오늘 만들기 시작할 수 있어요?", "매장 관리자들이 이것저것 원해요. 더 알게 되면 말할게요."]', '["By text? I thought the stores used email for everything.", "Today? It''s not even a story yet.", "Could you be a bit more specific?"]', '["문자요? 매장들은 다 이메일로 하는 줄 알았는데요.", "오늘이요? 아직 스토리도 없잖아요.", "조금 더 구체적으로 말해 줄래요?"]', NULL, 'Nice. Send it over when it''s ready.', '좋네요. 다 쓰면 보내 줘요.'),
  ('rt_video_pr_1', 3, 'jun', 'Jun''s update runs long: he''s deep into the details of a layout bug. Derek is still waiting to talk, and there are three minutes left.', '준의 발언이 길어집니다. 레이아웃 버그를 아주 자세히 설명하고 있습니다. 데릭이 아직 말을 기다리고 있고, 3분 남았습니다.', '...and then the grid wraps, so everything shifts by two pixels, and...', '...그래서 그리드가 줄바꿈되면서 전부 2픽셀씩 밀리고...', 'Politely move the meeting on, and give him a place to finish.', '정중하게 회의를 다음으로 넘기고, 나머지는 따로 하도록 자리를 마련하세요.', '[]', 'Sorry to jump in, Jun. Let''s go over the details after standup. Derek, you''re next.', '끼어들어서 미안해요, 준. 자세한 건 스탠드업 끝나고 봐요. 데릭, 다음이요.', '["Jun, nobody needs this much detail. Derek, you''re next.", "Sorry to jump in, Jun. Let''s go over the details after standup. Maya, you''re next.", "Interesting, Jun. Keep going. We can run a little over today."]', '["준, 그렇게까지 자세히 들을 필요는 없어요. 데릭, 다음이요.", "끼어들어서 미안해요, 준. 자세한 건 스탠드업 끝나고 봐요. 마야, 다음이요.", "흥미롭네요, 준. 계속해요. 오늘은 좀 넘겨도 돼요."]', '["Oh. Sorry...", "Maya''s not on the call, though.", "Okay! So, the second problem is..."]', '["아. 죄송해요...", "마야는 통화에 없는데요.", "좋아요! 그럼 두 번째 문제는요..."]', NULL, 'Sure. Sorry, I got carried away.', '네. 죄송해요, 너무 빠져들었네요.');

-- rt_video_pr_2
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_pr_2', 1, NULL, 'Ten o''clock standup on video. Before the call, Sam from IT posted in the team chat: the build server will be down from one to two this afternoon for an update. Nobody else has seen it.', '화상으로 하는 10시 스탠드업입니다. 통화 전에 IT의 샘이 팀 채팅에 올렸습니다. 오늘 오후 1시부터 2시까지 업데이트 때문에 빌드 서버가 멈춘다고요. 아직 아무도 보지 못했습니다.', 'Morning. Anything new?', '좋은 아침이에요. 새 소식 있어요?', 'Pass on Sam''s notice clearly.', '샘의 공지를 분명하게 전하세요.', '[]', 'Sam says the build server is down from one to two today for an update.', '샘이 그러는데, 오늘 1시부터 2시까지 업데이트로 빌드 서버가 멈춘대요.', '["Sam says the build server is down from two to three today for an update.", "Sam posted something about the build server. Check the chat, I guess.", "Sam says the build server is down all afternoon today for an update."]', '["샘이 그러는데, 오늘 2시부터 3시까지 업데이트로 빌드 서버가 멈춘대요.", "샘이 빌드 서버에 대해 뭘 올렸어요. 채팅 확인해 보세요.", "샘이 그러는데, 오늘 오후 내내 업데이트로 빌드 서버가 멈춘대요."]', '["Two to three? The chat says one.", "Could you just tell us what it says?", "All afternoon? That would wreck my plan."]', '["2시부터 3시요? 채팅에는 1시라고 되어 있는데요.", "그냥 뭐라고 했는지 말해 줄래요?", "오후 내내요? 그럼 제 계획이 다 틀어지는데요."]', NULL, 'Thanks. I''ll merge before one, then.', '고마워요. 그럼 1시 전에 병합할게요.'),
  ('rt_video_pr_2', 2, NULL, 'Derek''s camera is off, and he sounds tired. He was paged twice last night for the data import. He also has a call with Greg from Summit Retail at two.', '데릭은 카메라를 껐고 목소리가 피곤합니다. 어젯밤 데이터 가져오기 때문에 두 번 호출을 받았습니다. 2시에는 서밋 리테일의 그렉과 통화도 있습니다.', 'Sorry, I''m a little slow today. I got paged twice last night.', '미안해요, 오늘 좀 멍해요. 어젯밤에 호출을 두 번 받았어요.', 'Show you care, and offer to take something off his plate.', '걱정해 주고, 그의 일을 하나 덜어 주겠다고 하세요.', '[]', 'Oh no. Want me to move your call with Greg to tomorrow?', '저런. 그렉과의 통화를 내일로 옮겨 줄까요?', '["Oh no. Want me to move your call with Greg to next month?", "That''s on-call life, I guess. Anyway, Jun, you''re up.", "Oh no. Maybe turn your camera on? It might help you wake up."]', '["저런. 그렉과의 통화를 다음 달로 옮겨 줄까요?", "온콜이 원래 그렇죠, 뭐. 아무튼 준, 다음이요.", "저런. 카메라를 켜 보는 건요? 잠이 좀 깰 수도 있잖아요."]', '["Next month? Tomorrow would be fine.", "Thanks a lot...", "I''d rather keep it off today."]', '["다음 달이요? 내일이면 충분해요.", "참 고맙네요...", "오늘은 그냥 끄고 있을게요."]', NULL, 'That would really help. Thanks, Priya.', '그러면 정말 도움이 돼요. 고마워요, 프리야.'),
  ('rt_video_pr_2', 3, 'jun', 'Maya is out today. She asked you to post the standup notes in the team chat afterward.', '마야는 오늘 자리를 비웁니다. 스탠드업이 끝나면 메모를 팀 채팅에 올려 달라고 당신에게 부탁했습니다.', 'Priya, will there be notes for Maya?', '프리야, 마야한테 줄 메모 있어요?', 'Confirm, and say when.', '그렇다고 하고, 언제 올릴지 말하세요.', '[]', 'Yes, I''ll post the notes in the team chat right after this.', '네, 끝나자마자 팀 채팅에 메모를 올릴게요.', '["Yes, I''ll email Maya the notes at the end of the week.", "Maya''s out, so let''s skip the notes today.", "Yes. Jun, could you take the notes and post them?"]', '["네, 이번 주 끝날 때쯤 마야한테 메모를 메일로 보낼게요.", "마야가 없으니까 오늘은 메모 생략해요.", "네. 준, 메모 좀 해서 올려 줄래요?"]', '["The end of the week? She''ll want them today.", "But she asked for them, didn''t she?", "Me? I thought she asked you."]', '["주 끝날 때요? 오늘 필요할 텐데요.", "그래도 마야가 부탁한 거 아니에요?", "저요? 프리야한테 부탁한 줄 알았는데요."]', NULL, 'Great, thanks.', '좋아요, 고마워요.');

-- rt_video_pr_3
REPLACE INTO turns (episode, seq, speaker, situation, situation_ko, line, line_ko, prompt, prompt_ko, answers, model, model_ko, distractors, distractors_ko, reactions, reactions_ko, reply_speaker, reply_line, reply_ko) VALUES
  ('rt_video_pr_3', 1, NULL, 'Ten o''clock standup on video, from your loft. Construction next door just started drilling, and you''re the one running the call.', '로프트에서 화상으로 하는 10시 스탠드업입니다. 옆집 공사에서 막 드릴 소리가 나기 시작했고, 통화는 당신이 진행합니다.', 'Whoa, what''s that noise?', '와, 무슨 소리예요?', 'Explain in a few words, and deal with it so the meeting can go on.', '짧게 설명하고, 회의가 계속될 수 있게 처리하세요.', '[]', 'Construction next door, sorry! I''ll stay muted when I''m not talking.', '옆집 공사예요, 미안해요! 말할 때 말고는 음소거할게요.', '["Construction next door. Just ignore it. It should stop in an hour or so.", "My neighbor''s dog, sorry! I''ll stay muted when I''m not talking.", "Construction next door, sorry! Derek, could you just run standup today?"]', '["옆집 공사예요. 그냥 신경 쓰지 마요. 한 시간쯤이면 끝날 거예요.", "이웃집 개예요, 미안해요! 말할 때 말고는 음소거할게요.", "옆집 공사예요, 미안해요! 데릭, 오늘 스탠드업은 대신 진행해 줄래요?"]', '["An hour? We can barely hear anyone.", "That doesn''t sound like a dog.", "Me? You''re fine, just mute between turns."]', '["한 시간이요? 지금 다들 잘 안 들려요.", "개 소리 같지는 않은데요.", "제가요? 괜찮아요, 차례 사이에만 음소거해요."]', NULL, 'Ha, good luck with that.', '하하, 힘내요.'),
  ('rt_video_pr_3', 2, NULL, 'Your update: Greg from Summit Retail approved the store comparison design yesterday. The engineers can start building it next sprint.', '당신 소식: 어제 서밋 리테일의 그렉이 매장 비교 디자인을 승인했습니다. 개발자들은 다음 스프린트에 만들기 시작할 수 있습니다.', 'Any news from Summit?', '서밋에서 소식 있어요?', 'Share the news and what it means for the team.', '소식과 그게 팀에 어떤 의미인지 전하세요.', '[]', 'Greg approved the comparison design, so we can start building it next sprint.', '그렉이 비교 디자인을 승인해서, 다음 스프린트에 만들기 시작할 수 있어요.', '["Greg approved the comparison design, so we can start building it today.", "Greg turned down the comparison design, so we''re back to square one.", "Greg liked something, I think. I''ll find out more and let you know."]', '["그렉이 비교 디자인을 승인해서, 오늘부터 만들기 시작할 수 있어요.", "그렉이 비교 디자인을 거절해서, 원점으로 돌아갔어요.", "그렉이 뭔가 마음에 들어 한 것 같아요. 더 알아보고 알려 줄게요."]', '["Today? It isn''t in this sprint.", "Turned down? I heard he liked it.", "Liked something? What exactly?"]', '["오늘이요? 이번 스프린트에는 없잖아요.", "거절이요? 마음에 들어 했다고 들었는데요.", "뭔가요? 정확히 뭘요?"]', NULL, 'Great news. I''ll look at the design this afternoon.', '좋은 소식이네요. 오후에 디자인 볼게요.'),
  ('rt_video_pr_3', 3, 'jun', 'The drilling stops. Jun says he''s blocked: he can''t open the design file. You own the file, and sharing it takes a minute.', '드릴 소리가 멈춥니다. 준이 막혔다고 합니다. 디자인 파일이 안 열린대요. 그 파일은 당신 것이고, 공유하는 데 1분이면 됩니다.', 'I can''t open the design file. It says I need access.', '디자인 파일이 안 열려요. 권한이 필요하대요.', 'Fix it for him right away, and tell him.', '바로 해결해 주고, 그렇다고 말하세요.', '[]', 'That''s on me. I''m sharing it with you right now.', '제 탓이에요. 지금 바로 공유할게요.', '["That''s an IT thing. File a ticket with Sam.", "That''s on me. I''ll share it with you next sprint.", "Ask Derek. He can probably send you a screenshot."]', '["그건 IT 일이에요. 샘한테 티켓 올려요.", "제 탓이에요. 다음 스프린트에 공유할게요.", "데릭한테 물어봐요. 스크린숏은 보내 줄 수 있을 거예요."]', '["Sam? I think it''s your file.", "Next sprint? I need it today.", "A screenshot? I need the real file."]', '["샘이요? 프리야 파일인 것 같은데요.", "다음 스프린트요? 오늘 필요해요.", "스크린숏이요? 진짜 파일이 필요해요."]', NULL, 'Got it! Thanks, Priya.', '열렸어요! 고마워요, 프리야.');

REPLACE INTO messages (id, hero, day, time, kind, sender, subject, subject_ko, body, body_ko) VALUES
  ('hy_announce', 'all', 22, '09:30', 'email', 'linda', 'Hybrid work starts November 9', '11월 9일부터 하이브리드 근무', 'Hi everyone, starting Monday, November 9, Seaside Labs goes hybrid. Tuesday to Thursday are office days. On Mondays and Fridays you work from home: log in at your desk at home by 9:15, the same as badging in, and stay online until at least 4. Standups on those days are video calls. Sprint planning moves to Tuesdays and the retro to Thursdays, so we can do them in person. The office stays open every day, and Tom and Sam are on site if you would rather come in. Questions? Ask me or your manager. Linda, HR', '안녕하세요, 11월 9일 월요일부터 시사이드 랩스는 하이브리드 근무를 시작합니다. 화요일부터 목요일까지는 사무실에 나옵니다. 월요일과 금요일은 집에서 일합니다. 출입증을 찍을 때처럼 9시 15분까지 집 책상에서 로그인하고, 적어도 4시까지는 접속해 있어 주세요. 그날 스탠드업은 화상으로 합니다. 스프린트 계획은 화요일, 회고는 목요일로 옮겨 직접 만나서 합니다. 사무실은 매일 열려 있고, 나오고 싶으면 톰과 샘이 자리에 있습니다. 궁금한 점은 저나 매니저에게 물어보세요. 인사팀 린다'),
  ('hy_maya', 'all', 22, '11:40', 'text', 'maya', NULL, NULL, 'Hi {name}, did you see Linda''s email? Hybrid starts November 9. I''m excited about it. Just treat 9:15 on home days like you would at the office, and keep your camera on for standup.', '{name}, 린다 메일 봤어요? 11월 9일부터 하이브리드예요. 기대돼요. 집에서 일하는 날에도 9시 15분은 사무실처럼 지켜 주고, 스탠드업 때는 카메라를 켜 줘요.'),
  ('hy_allhands', 'all', 32, '17:00', 'text', 'maya', NULL, NULL, 'Thanks for coming to the all-hands today. Reminder: Monday is our first remote day. Log in from home by 9:15, and see you on video at ten.', '오늘 전사 회의에 와 줘서 고마워요. 잊지 말아요: 월요일이 첫 재택근무 날이에요. 9시 15분까지 집에서 로그인하고, 10시에 화상으로 봐요.'),
  ('hy_sam', 'all', 33, '11:00', 'email', 'sam', 'Working from home: a quick checklist', '재택근무 체크리스트', 'Before Monday, please: 1) connect to the VPN once from home and make sure it works, 2) test your camera and mic, 3) use your home Wi-Fi, not a coffee shop''s, and 4) lock your laptop whenever you step away. If something breaks, file a help desk ticket and I''ll call you back. Sam, IT', '월요일 전에 꼭 해 주세요. 1) 집에서 VPN에 한 번 접속해 잘 되는지 확인하기, 2) 카메라와 마이크 테스트하기, 3) 카페 와이파이가 아니라 집 와이파이 쓰기, 4) 자리를 비울 때마다 노트북 잠그기. 문제가 생기면 헬프데스크 티켓을 올려 주세요. 제가 전화드릴게요. IT 샘'),
  ('hy_first', 'all', 36, '07:40', 'text', 'maya', NULL, NULL, 'Morning! First remote day. Log in by 9:15, and see you at standup at ten.', '좋은 아침이에요! 첫 재택근무 날이에요. 9시 15분까지 로그인하고, 10시 스탠드업에서 봐요.'),
  ('hy_review', 'all', 91, '18:30', 'text', 'maya', NULL, NULL, 'Quick note about tomorrow, {name}: I know Monday is a remote day, but let''s do your review in person. Work from home in the morning and come by my office at 3:30.', '{name}, 내일 얘기 잠깐 할게요. 월요일이 재택하는 날인 건 알지만 평가는 직접 만나서 해요. 오전엔 집에서 일하고 3시 30분에 내 방으로 와 줘요.');

REPLACE INTO calendar (hero, day, time, title, title_ko, place, episode) VALUES
  ('jun', 36, '09:15', 'First remote day: log in from home', '첫 재택근무: 집에서 로그인', 'home_desk', NULL),
  ('derek', 36, '09:15', 'First remote day: log in from home', '첫 재택근무: 집에서 로그인', 'derek_desk', NULL),
  ('priya', 36, '09:15', 'First remote day: log in from home', '첫 재택근무: 집에서 로그인', 'priya_desk', NULL);

REPLACE INTO smalltalk (topic, seq, line, line_ko) VALUES
  ('hybrid:office', 1, 'Nice to have everyone in the office today.', '오늘은 다들 사무실에 있으니 좋네요.'),
  ('hybrid:office', 2, 'I like the office days. Quick questions are so much easier.', '사무실 나오는 날이 좋아요. 금방 물어볼 수 있잖아요.'),
  ('hybrid:office', 3, 'How''s working from home going for you?', '재택근무는 어때요?'),
  ('hybrid:office', 4, 'Three days a week, the commute almost feels short.', '일주일에 사흘만 출근하니까 출퇴근길이 짧게 느껴져요.'),
  ('hybrid:remote', 1, 'Quiet in here today. Everybody''s working from home.', '오늘은 조용하네요. 다들 재택근무 중이에요.'),
  ('hybrid:remote', 2, 'You came in today? You''ve got the whole floor to yourself.', '오늘 나왔어요? 층 전체를 혼자 쓰겠네요.'),
  ('hybrid:remote', 3, 'Some people like the quiet days at the office. I get it.', '조용한 날 일부러 나오는 사람도 있어요. 이해가 가요.');
