"""Build the 3D models of the Little Prince game (this repository).

    blender -b --python tools/game-models.py                     # every model
    blender -b --python tools/game-models.py -- prince fox       # only these
    blender -b --python tools/game-models.py -- --list           # names and builder files
    blender -b --python tools/game-models.py -- fox --keep-glb /tmp/glb   # also keep the .glb (to inspect)

Builders live in tools/game_models/<file>.py, each with MODELS = {'name': build}; shared tools are in
tools/game_models/kit.py. Each model becomes models/<name>.js: the .glb as base64, so
the game runs from file://, where neither fetch() nor loading a .glb file works.
The people share the skeleton and animations of Kenney's Mini Characters (CC0, kenney/mini-character.glb);
their bodies are new meshes drawn after reference/characters/ and bound rigidly to its bones.
"""
import base64
import importlib
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from game_models import kit  # noqa: E402

argv = sys.argv[sys.argv.index('--') + 1:] if '--' in sys.argv else []
keep = None
if '--keep-glb' in argv:
    i = argv.index('--keep-glb')
    keep = argv[i + 1]
    del argv[i:i + 2]
listing = '--list' in argv
wanted = [a for a in argv if not a.startswith('--')]

registry = {}
pkg = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'game_models')
for fn in sorted(os.listdir(pkg)):
    if not fn.endswith('.py') or fn in ('__init__.py', 'kit.py'):
        continue
    mod = importlib.import_module('game_models.' + fn[:-3])
    for name, build in getattr(mod, 'MODELS', {}).items():
        if name in registry:
            raise SystemExit(f'model {name} defined twice ({registry[name][1]} and {fn})')
        registry[name] = (build, fn)

if listing:
    for name, (_, fn) in sorted(registry.items()):
        print(f'{name:20} {fn}')
    raise SystemExit(0)
missing = [w for w in wanted if w not in registry]
if missing:
    raise SystemExit('unknown model(s): ' + ', '.join(missing))

out_dir = os.path.join(kit.GAME, 'models')
os.makedirs(out_dir, exist_ok=True)
tmp = keep or tempfile.mkdtemp()
os.makedirs(tmp, exist_ok=True)
for name in (wanted or sorted(registry)):
    build, fn = registry[name]
    kit.reset()
    objs = build()
    path = os.path.join(tmp, name + '.glb')
    kit.export(path, objs)
    with open(path, 'rb') as fh:
        b64 = base64.b64encode(fh.read()).decode('ascii')
    with open(os.path.join(out_dir, name + '.js'), 'w') as fh:
        fh.write(f'/* Generated by tools/game-models.py from tools/game_models/{fn}. Do not edit. */\n'
                 f"(window.LP_GAME_MODELS = window.LP_GAME_MODELS || {{}})['{name}'] = '{b64}';\n")
    print(f'{name}: {os.path.getsize(path) // 1024} KB  ({fn})')
