// The people you can play: home, desk, money and pay. Their conversations are in db/scenarios/<hero>/.

export const heroes = [
  {
    id: 'derek',
    name: 'Derek',
    full_name: 'Derek Alvarez',
    name_ko: '데릭',
    full_name_ko: '데릭 알바레스',
    role: 'Senior developer, onboarding buddy',
    role_ko: '시니어 개발자, 온보딩 버디',
    model: 'man-hoodie',
    bio: 'Six years at Seaside Labs. Reviews the code, is on call when things break, and shows the new hire the ropes.',
    bio_ko: '시사이드 랩스 6년 차. 코드를 리뷰하고, 장애가 나면 호출을 받고, 신입에게 일을 가르칩니다.',
    home_zone: 'home_derek',
    home_name: 'House on River Road',
    home_name_ko: '리버 로드의 단독 주택',
    home_bed: 'derek_bed',
    home_kitchen: 'derek_kitchen',
    home_desk: 'derek_desk',
    home_door: 'derek_door',
    desk: 'office_desk_team',
    start_money: 5400,
    salary_net: 3900,
    salary_gross: 5770,
    housing: 2150,
    housing_name: 'Mortgage',
    housing_name_ko: '주택담보대출 상환금',
    level: 'Mentoring, code review, pushing back',
    level_ko: '멘토링·코드 리뷰·반대 의견 말하기',
    sort: 2
  },
  {
    id: 'jun',
    name: 'Jun',
    full_name: 'Jun Kim',
    name_ko: '준',
    full_name_ko: '준 김',
    role: 'Software developer, new hire',
    role_ko: '신입 소프트웨어 개발자',
    model: 'man-casual-3',
    bio: 'Just moved to Fairview for a first job in the US. Everything is new: the badge, the standup, the tipping.',
    bio_ko: '미국 첫 직장 때문에 페어뷰로 막 이사 왔습니다. 출입증도, 스탠드업도, 팁도 모두 처음입니다.',
    home_zone: 'home',
    home_name: 'Studio at Maple Street Apartments',
    home_name_ko: '메이플 스트리트 아파트의 원룸',
    home_bed: 'home_bed',
    home_kitchen: 'home_kitchen',
    home_desk: 'home_desk',
    home_door: 'apartment_door',
    desk: 'office_desk',
    start_money: 1200,
    salary_net: 2600,
    salary_gross: 3654,
    housing: 1450,
    housing_name_ko: '월세',
    level: 'Everyday and first-week English',
    level_ko: '일상·입사 첫 주 영어',
    sort: 1
  },
  {
    id: 'priya',
    name: 'Priya',
    full_name: 'Priya Nair',
    name_ko: '프리야',
    full_name_ko: '프리야 네어',
    role: 'Product manager',
    role_ko: '프로덕트 매니저',
    model: 'woman-casual-2',
    bio: 'Runs the standup, owns the roadmap and talks to the client. Every meeting ends on time.',
    bio_ko: '스탠드업을 진행하고, 로드맵을 책임지고, 고객과 이야기합니다. 회의는 늘 제시간에 끝납니다.',
    home_zone: 'home_priya',
    home_name: 'Loft at Cedar Street Lofts',
    home_name_ko: '시더 스트리트 로프트',
    home_bed: 'priya_bed',
    home_kitchen: 'priya_kitchen',
    home_desk: 'priya_desk',
    home_door: 'priya_door',
    desk: 'office_desk_priya',
    start_money: 3800,
    salary_net: 3500,
    salary_gross: 5000,
    housing: 1900,
    housing_name_ko: '월세',
    level: 'Running meetings, negotiating, stakeholders',
    level_ko: '회의 진행·협상·이해관계자 소통',
    sort: 3
  }
];
