// What money buys (items), what you can cook at home (recipes) and what you can order from your phone (catalog).

export const items = [
  {
    id: 'apple',
    name: 'Apple',
    name_ko: '사과',
    kind: 'grocery',
    price: 0.89,
    model: 'apple',
    energy: 8,
    place: 'market_shelves',
    note: 'sold by the piece',
    note_ko: '낱개 판매',
    shelf_days: 10
  },
  {
    id: 'avocado',
    name: 'Avocado',
    name_ko: '아보카도',
    kind: 'grocery',
    price: 1.5,
    model: 'avocado',
    energy: 10,
    place: 'market_shelves',
    shelf_days: 4
  },
  {
    id: 'bacon',
    name: 'Bacon (12 oz)',
    name_ko: '베이컨(12온스)',
    kind: 'grocery',
    price: 6.99,
    model: 'bacon',
    energy: 15,
    place: 'market_shelves',
    shelf_days: 7,
    uses: 3,
    cook_only: 1
  },
  {
    id: 'baguette',
    name: 'French baguette',
    name_ko: '바게트',
    kind: 'grocery',
    price: 2.99,
    model: 'loaf-baguette',
    energy: 12,
    place: 'market_shelves',
    shelf_days: 2,
    uses: 3
  },
  {
    id: 'bananas',
    name: 'Bananas (bunch of 5)',
    name_ko: '바나나(5개 한 송이)',
    kind: 'grocery',
    price: 1.45,
    model: 'banana',
    energy: 10,
    place: 'market_shelves',
    shelf_days: 5,
    uses: 5
  },
  {
    id: 'bread',
    name: 'Sandwich bread (loaf)',
    name_ko: '식빵(한 봉지)',
    kind: 'grocery',
    price: 3.49,
    model: 'loaf',
    energy: 12,
    place: 'market_shelves',
    shelf_days: 6,
    uses: 8
  },
  {
    id: 'broccoli',
    name: 'Broccoli crown',
    name_ko: '브로콜리',
    kind: 'grocery',
    price: 2.29,
    model: 'broccoli',
    energy: 6,
    place: 'market_shelves',
    shelf_days: 6,
    uses: 2,
    cook_only: 1
  },
  {
    id: 'bus_day_pass',
    name: 'Bus day pass',
    name_ko: '버스 1일권',
    kind: 'fare',
    price: 5,
    place: 'bus_stop',
    note: 'unlimited rides until midnight',
    note_ko: '자정까지 무제한 탑승'
  },
  {
    id: 'bus_ride',
    name: 'Bus fare',
    name_ko: '버스 요금',
    kind: 'fare',
    price: 2.5,
    place: 'bus_stop',
    note: 'one ride, tap a card or pay exact change',
    note_ko: '1회 탑승, 카드를 찍거나 잔돈 없이 정확히 내기'
  },
  {
    id: 'candy_bar',
    name: 'Candy bar',
    name_ko: '초코바',
    kind: 'grocery',
    price: 1.79,
    model: 'candy-bar',
    energy: 10,
    place: 'market_shelves'
  },
  {
    id: 'canned_soup',
    name: 'Canned chicken noodle soup',
    name_ko: '치킨 누들 수프 통조림',
    kind: 'grocery',
    price: 2.19,
    model: 'can',
    energy: 30,
    place: 'market_shelves',
    note: 'a quick meal',
    note_ko: '간단한 한 끼'
  },
  {
    id: 'carrots',
    name: 'Baby carrots (1 lb bag)',
    name_ko: '베이비 당근(1파운드 봉지)',
    kind: 'grocery',
    price: 1.79,
    model: 'carrot',
    energy: 8,
    place: 'market_shelves',
    shelf_days: 14,
    uses: 4
  },
  {
    id: 'cereal',
    name: 'Box of cereal',
    name_ko: '시리얼 한 상자',
    kind: 'grocery',
    price: 4.99,
    model: 'bowl-cereal',
    energy: 15,
    place: 'market_shelves',
    uses: 6
  },
  {
    id: 'cheese',
    name: 'Cheddar cheese (8 oz)',
    name_ko: '체다 치즈(8온스)',
    kind: 'grocery',
    price: 4.49,
    model: 'cheese',
    energy: 12,
    place: 'market_shelves',
    shelf_days: 21,
    uses: 4
  },
  {
    id: 'chips',
    name: 'Potato chips (family size)',
    name_ko: '감자칩(대용량)',
    kind: 'grocery',
    price: 4.29,
    model: 'bag',
    energy: 12,
    place: 'market_shelves',
    uses: 3
  },
  {
    id: 'coffee',
    name: 'Drip coffee, medium',
    name_ko: '드립 커피(미디엄)',
    kind: 'drink',
    price: 2.75,
    model: 'cup-coffee',
    energy: 8,
    place: 'coffee_cart',
    note: 'house blend',
    note_ko: '하우스 블렌드'
  },
  {
    id: 'cold_brew',
    name: 'Cold brew',
    name_ko: '콜드브루',
    kind: 'drink',
    price: 4.5,
    model: 'frappe',
    energy: 10,
    place: 'coffee_cart',
    note: 'extra strong',
    note_ko: '아주 진함'
  },
  {
    id: 'cold_relief',
    name: 'Cold & flu relief, store brand (24 caplets)',
    name_ko: '종합 감기약, 매장 자체 브랜드(24정)',
    kind: 'gear',
    price: 7.99,
    place: 'pharmacy',
    note: 'a day of doses each morning while you are sick; the same active ingredients as the name brand',
    note_ko: '아픈 동안 아침마다 하루치를 먹어요. 유명 브랜드와 유효 성분이 같아요',
    uses: 6
  },
  {
    id: 'cold_relief_brand',
    name: 'ColdAway cold & flu (24 caplets)',
    name_ko: '콜드어웨이 종합 감기약(24정)',
    kind: 'gear',
    price: 12.99,
    place: 'pharmacy',
    note: 'the name brand: a day of doses each morning while you are sick',
    note_ko: '유명 브랜드예요. 아픈 동안 아침마다 하루치를 먹어요',
    uses: 6
  },
  {
    id: 'cookies',
    name: 'Chocolate chip cookies',
    name_ko: '초콜릿 칩 쿠키',
    kind: 'grocery',
    price: 3.99,
    model: 'cookie',
    energy: 11,
    place: 'market_shelves',
    uses: 4
  },
  {
    id: 'croissant',
    name: 'Butter croissant',
    name_ko: '버터 크루아상',
    kind: 'meal',
    price: 3.5,
    model: 'croissant',
    energy: 12,
    place: 'coffee_cart',
    note: 'a snack',
    note_ko: '간식'
  },
  {
    id: 'deli_turkey',
    name: 'Sliced deli turkey (8 oz)',
    name_ko: '칠면조 슬라이스(8온스)',
    kind: 'grocery',
    price: 5.49,
    model: 'turkey',
    energy: 14,
    place: 'market_shelves',
    shelf_days: 5,
    uses: 4
  },
  {
    id: 'detergent',
    name: 'Laundry detergent pods (16 loads)',
    name_ko: '세탁 세제 캡슐(16회분)',
    kind: 'gear',
    price: 11.99,
    place: 'market_shelves',
    note: 'one pod a load',
    note_ko: '한 번 빨래에 캡슐 하나',
    uses: 16
  },
  {
    id: 'diner_cheeseburger',
    name: 'Cheeseburger with fries',
    name_ko: '치즈버거와 감자튀김',
    kind: 'meal',
    price: 13.95,
    model: 'burger-cheese',
    energy: 42,
    place: 'diner_counter',
    note: 'comes with fries or a side salad',
    note_ko: '감자튀김이나 사이드 샐러드 포함'
  },
  {
    id: 'diner_club',
    name: 'Club sandwich',
    name_ko: '클럽 샌드위치',
    kind: 'meal',
    price: 12.5,
    model: 'sandwich',
    energy: 38,
    place: 'diner_counter',
    note: 'turkey, bacon, lettuce and tomato',
    note_ko: '칠면조, 베이컨, 양상추, 토마토'
  },
  {
    id: 'diner_coffee',
    name: 'Diner coffee (free refills)',
    name_ko: '다이너 커피(리필 무료)',
    kind: 'drink',
    price: 2.25,
    model: 'mug',
    energy: 7,
    place: 'diner_counter',
    note: 'bottomless',
    note_ko: '무한 리필'
  },
  {
    id: 'diner_fries',
    name: 'Side of fries',
    name_ko: '감자튀김(사이드)',
    kind: 'meal',
    price: 4.5,
    model: 'fries',
    energy: 12,
    place: 'diner_counter',
    note: 'a snack',
    note_ko: '간식'
  },
  {
    id: 'diner_pancakes',
    name: 'Short stack of pancakes',
    name_ko: '팬케이크(세 장)',
    kind: 'meal',
    price: 10.95,
    model: 'pancakes',
    energy: 35,
    place: 'diner_counter',
    note: 'breakfast served all day',
    note_ko: '아침 메뉴 종일 제공'
  },
  {
    id: 'diner_pie',
    name: 'Slice of apple pie',
    name_ko: '사과 파이 한 조각',
    kind: 'meal',
    price: 5.25,
    model: 'cake-slicer',
    energy: 14,
    place: 'diner_counter',
    note: 'a la mode for $1.50 more',
    note_ko: '아이스크림 추가 시 1.50달러'
  },
  {
    id: 'diner_salad',
    name: 'Garden salad',
    name_ko: '가든 샐러드',
    kind: 'meal',
    price: 9.5,
    model: 'salad',
    energy: 30,
    place: 'diner_counter',
    note: 'ranch, Italian or balsamic',
    note_ko: '랜치, 이탈리안, 발사믹 드레싱'
  },
  {
    id: 'diner_soup',
    name: 'Soup of the day',
    name_ko: '오늘의 수프',
    kind: 'meal',
    price: 6.95,
    model: 'bowl-soup',
    energy: 30,
    place: 'diner_counter',
    note: 'with crackers',
    note_ko: '크래커 포함'
  },
  {
    id: 'eggs',
    name: 'Eggs (dozen)',
    name_ko: '달걀(12개)',
    kind: 'grocery',
    price: 3.79,
    model: 'egg',
    energy: 15,
    place: 'market_shelves',
    note: 'large, grade A',
    note_ko: '대란, A등급',
    shelf_days: 21,
    uses: 6,
    cook_only: 1
  },
  {
    id: 'farm_apples',
    name: 'Honeycrisp apples (2 lb)',
    name_ko: '허니크리스프 사과(2파운드)',
    kind: 'grocery',
    price: 6,
    model: 'apple',
    energy: 8,
    place: 'farm_stand',
    shelf_days: 21,
    uses: 4
  },
  {
    id: 'farm_cider',
    name: 'Apple cider (half gallon)',
    name_ko: '애플 사이더(반 갤런)',
    kind: 'grocery',
    price: 6,
    model: 'carton',
    energy: 6,
    place: 'farm_stand',
    note: 'fresh, unfiltered apple juice',
    note_ko: '거르지 않은 생사과 주스',
    shelf_days: 10,
    uses: 6
  },
  {
    id: 'farm_cinnamon_rolls',
    name: 'Cinnamon rolls (2)',
    name_ko: '시나몬 롤(2개)',
    kind: 'grocery',
    price: 6,
    model: 'muffin',
    energy: 14,
    place: 'bakery_stand',
    shelf_days: 3,
    uses: 2
  },
  {
    id: 'farm_honey',
    name: 'Wildflower honey (12 oz jar)',
    name_ko: '야생화 꿀(12온스 병)',
    kind: 'grocery',
    price: 9,
    model: 'honey',
    energy: 6,
    place: 'farm_stand',
    note: 'from hives in the hills',
    note_ko: '언덕의 벌통에서 딴 꿀',
    uses: 12
  },
  {
    id: 'farm_kettle_corn',
    name: 'Kettle corn (big bag)',
    name_ko: '케틀콘(큰 봉지)',
    kind: 'grocery',
    price: 5,
    model: 'bag',
    energy: 9,
    place: 'bakery_stand',
    note: 'sweet and salty popcorn',
    note_ko: '달고 짭짤한 팝콘',
    uses: 4
  },
  {
    id: 'farm_peaches',
    name: 'Peaches (3 lb)',
    name_ko: '복숭아(3파운드)',
    kind: 'grocery',
    price: 10,
    energy: 9,
    place: 'farm_stand',
    note: 'three pounds for ten',
    note_ko: '3파운드에 10달러',
    shelf_days: 5,
    uses: 6
  },
  {
    id: 'farm_sourdough',
    name: 'Sourdough loaf',
    name_ko: '사워도우 빵',
    kind: 'grocery',
    price: 7,
    model: 'loaf',
    energy: 12,
    place: 'bakery_stand',
    note: 'baked this morning',
    note_ko: '오늘 아침에 구움',
    shelf_days: 4,
    uses: 6
  },
  {
    id: 'farm_tomatoes',
    name: 'Heirloom tomatoes (1 lb)',
    name_ko: '에어룸 토마토(1파운드)',
    kind: 'grocery',
    price: 5,
    model: 'tomato',
    energy: 5,
    place: 'farm_stand',
    note: 'picked yesterday',
    note_ko: '어제 딴 것',
    shelf_days: 5,
    uses: 3
  },
  {
    id: 'frozen_pizza',
    name: 'Frozen pepperoni pizza',
    name_ko: '냉동 페퍼로니 피자',
    kind: 'grocery',
    price: 6.49,
    model: 'pizza-box',
    energy: 40,
    place: 'market_shelves',
    note: 'a meal',
    note_ko: '한 끼',
    shelf_days: 60,
    uses: 2,
    cook_only: 1
  },
  {
    id: 'grapes',
    name: 'Red grapes (2 lb)',
    name_ko: '적포도(2파운드)',
    kind: 'grocery',
    price: 4.98,
    model: 'grapes',
    energy: 10,
    place: 'market_shelves',
    shelf_days: 7,
    uses: 4
  },
  {
    id: 'ground_beef',
    name: 'Ground beef (1 lb)',
    name_ko: '다진 소고기(1파운드)',
    kind: 'grocery',
    price: 5.99,
    model: 'meat-patty',
    energy: 15,
    place: 'market_shelves',
    note: 'for burgers at home',
    note_ko: '집에서 햄버거 만들기용',
    shelf_days: 2,
    uses: 2,
    cook_only: 1
  },
  {
    id: 'hot_tea',
    name: 'Hot tea',
    name_ko: '따뜻한 차',
    kind: 'drink',
    price: 2.5,
    model: 'cup-tea',
    energy: 5,
    place: 'coffee_cart'
  },
  {
    id: 'ice_cream',
    name: 'Ice cream (pint)',
    name_ko: '아이스크림(파인트)',
    kind: 'grocery',
    price: 5.49,
    model: 'ice-cream',
    energy: 12,
    place: 'market_shelves',
    shelf_days: 60,
    uses: 3
  },
  {
    id: 'latte',
    name: 'Latte, medium',
    name_ko: '라테(미디엄)',
    kind: 'drink',
    price: 4.75,
    model: 'cup-coffee',
    energy: 9,
    place: 'coffee_cart',
    note: 'whole, skim, oat or almond milk',
    note_ko: '일반 우유, 무지방, 오트, 아몬드 우유'
  },
  {
    id: 'laundry_load',
    name: 'Laundry room, wash and dry',
    name_ko: '세탁실 세탁·건조 1회',
    kind: 'other',
    price: 5,
    note: 'washer $2.50, dryer $2.50, paid with the laundry app',
    note_ko: '세탁기 2.50달러, 건조기 2.50달러, 세탁 앱으로 결제'
  },
  {
    id: 'milk',
    name: 'Milk (half gallon carton)',
    name_ko: '우유(반 갤런 팩)',
    kind: 'grocery',
    price: 3.29,
    model: 'carton',
    energy: 8,
    place: 'market_shelves',
    note: '2%',
    note_ko: '저지방 2%',
    shelf_days: 7,
    uses: 4
  },
  {
    id: 'muffin',
    name: 'Blueberry muffin',
    name_ko: '블루베리 머핀',
    kind: 'meal',
    price: 3.25,
    model: 'muffin',
    energy: 12,
    place: 'coffee_cart',
    note: 'a snack',
    note_ko: '간식'
  },
  {
    id: 'np_cold_brew',
    name: 'Canned cold brew (4-pack)',
    name_ko: '캔 콜드브루(4캔 묶음)',
    kind: 'grocery',
    price: 9.99,
    model: 'soda-can',
    energy: 6,
    uses: 4
  },
  { id: 'np_desk_lamp', name: 'LED desk lamp', name_ko: 'LED 책상 스탠드', kind: 'other', price: 24.99 },
  { id: 'np_first_aid', name: 'First aid kit', name_ko: '구급상자', kind: 'other', price: 18.99 },
  {
    id: 'np_granola',
    name: 'Granola bars (box of 12)',
    name_ko: '그래놀라 바(12개 한 상자)',
    kind: 'grocery',
    price: 7.99,
    model: 'candy-bar',
    energy: 8,
    uses: 12
  },
  {
    id: 'np_headphones',
    name: 'Noise-canceling headphones',
    name_ko: '노이즈 캔슬링 헤드폰',
    kind: 'other',
    price: 119.99,
    note: 'for the open office',
    note_ko: '개방형 사무실에서'
  },
  { id: 'np_paper_towels', name: 'Paper towels (6 rolls)', name_ko: '키친타월(6롤)', kind: 'other', price: 11.49 },
  {
    id: 'np_ramen',
    name: 'Instant ramen (12-pack)',
    name_ko: '인스턴트 라면(12개 묶음)',
    kind: 'grocery',
    price: 8.99,
    model: 'bowl-soup',
    energy: 20,
    note: 'just add hot water',
    note_ko: '뜨거운 물만 부으면 됨',
    uses: 12
  },
  {
    id: 'np_space_heater',
    name: 'Small space heater',
    name_ko: '소형 전기 히터',
    kind: 'other',
    price: 39.99,
    note: 'for chilly winter nights',
    note_ko: '쌀쌀한 겨울밤에'
  },
  { id: 'np_toilet_paper', name: 'Toilet paper (12 rolls)', name_ko: '화장지(12롤)', kind: 'other', price: 13.99 },
  {
    id: 'np_trail_mix',
    name: 'Trail mix (2 lb bag)',
    name_ko: '트레일 믹스(2파운드 봉지)',
    kind: 'grocery',
    price: 12.99,
    model: 'bag',
    energy: 10,
    note: 'nuts, raisins and chocolate',
    note_ko: '견과류, 건포도, 초콜릿',
    uses: 10
  },
  { id: 'np_vacuum', name: 'Cordless stick vacuum', name_ko: '무선 스틱 청소기', kind: 'other', price: 149.99 },
  {
    id: 'onion',
    name: 'Yellow onion',
    name_ko: '양파',
    kind: 'grocery',
    price: 0.99,
    model: 'onion',
    energy: 3,
    place: 'market_shelves',
    note: 'for cooking',
    note_ko: '요리용',
    shelf_days: 30,
    uses: 2,
    cook_only: 1
  },
  {
    id: 'oranges',
    name: 'Navel oranges (3)',
    name_ko: '네이블 오렌지(3개)',
    kind: 'grocery',
    price: 2.99,
    model: 'orange',
    energy: 9,
    place: 'market_shelves',
    shelf_days: 14,
    uses: 3
  },
  {
    id: 'pain_reliever',
    name: 'Pain and fever reliever (50 tablets)',
    name_ko: '해열진통제(50정)',
    kind: 'gear',
    price: 6.49,
    place: 'pharmacy',
    note: 'for a fever and aches: a day of doses each morning while you are sick',
    note_ko: '열과 몸살에. 아픈 동안 아침마다 하루치를 먹어요',
    uses: 10
  },
  {
    id: 'parking_day',
    name: 'Parking, all day',
    name_ko: '주차(종일)',
    kind: 'fare',
    price: 18,
    place: 'parking',
    note: 'downtown lot',
    note_ko: '시내 주차장'
  },
  {
    id: 'peanut_butter',
    name: 'Peanut butter (jar)',
    name_ko: '땅콩버터(병)',
    kind: 'grocery',
    price: 3.49,
    model: 'peanut-butter',
    energy: 12,
    place: 'market_shelves',
    uses: 8
  },
  {
    id: 'soda_12pk',
    name: 'Soda (12-pack of cans)',
    name_ko: '탄산음료(12캔 묶음)',
    kind: 'grocery',
    price: 7.99,
    model: 'soda-can',
    energy: 7,
    place: 'market_shelves',
    uses: 12
  },
  {
    id: 'soda_bottle',
    name: 'Soda (2-liter bottle)',
    name_ko: '탄산음료(2리터 병)',
    kind: 'grocery',
    price: 2.29,
    model: 'soda-bottle',
    energy: 6,
    place: 'market_shelves',
    uses: 4
  },
  {
    id: 'strawberries',
    name: 'Strawberries (1 lb box)',
    name_ko: '딸기(1파운드 상자)',
    kind: 'grocery',
    price: 3.99,
    model: 'strawberry',
    energy: 9,
    place: 'market_shelves',
    note: 'buy one, get one free this week',
    note_ko: '이번 주 하나 사면 하나 더',
    shelf_days: 4,
    uses: 3
  },
  {
    id: 'tomatoes',
    name: 'Tomatoes (1 lb)',
    name_ko: '토마토(1파운드)',
    kind: 'grocery',
    price: 2.49,
    model: 'tomato',
    energy: 5,
    place: 'market_shelves',
    shelf_days: 6,
    uses: 3
  },
  {
    id: 'trip_airport_burger',
    name: 'Cheeseburger and fries',
    name_ko: '치즈버거와 감자튀김',
    kind: 'meal',
    price: 17.5,
    model: 'burger-cheese',
    energy: 40,
    place: 'airport_gate'
  },
  {
    id: 'trip_airport_shuttle',
    name: 'Airport shuttle bus, one way',
    name_ko: '공항 셔틀버스(편도)',
    kind: 'fare',
    price: 12,
    place: 'airport_shuttle',
    note: 'Maple Street to the airport, reimbursable',
    note_ko: '메이플 스트리트에서 공항까지, 경비 청구 가능'
  },
  {
    id: 'trip_breakfast_sandwich',
    name: 'Breakfast sandwich',
    name_ko: '아침 샌드위치',
    kind: 'meal',
    price: 9.49,
    model: 'sandwich',
    energy: 25,
    place: 'airport_gate'
  },
  {
    id: 'trip_candy',
    name: 'Candy bar',
    name_ko: '초코바',
    kind: 'meal',
    price: 3.29,
    model: 'candy-bar',
    energy: 8,
    place: 'airport_gate'
  },
  {
    id: 'trip_charger',
    name: 'Phone charger',
    name_ko: '휴대폰 충전기',
    kind: 'other',
    price: 29.99,
    place: 'airport_gate'
  },
  {
    id: 'trip_checked_bag',
    name: 'First checked bag',
    name_ko: '첫 번째 위탁 수하물',
    kind: 'fare',
    price: 35,
    place: 'airport_checkin',
    note: 'reimbursable',
    note_ko: '경비 청구 가능'
  },
  {
    id: 'trip_client_dinner',
    name: 'Client dinner for two, with tip',
    name_ko: '고객 저녁 2인(팁 포함)',
    kind: 'meal',
    price: 197,
    model: 'plate-dinner',
    note: 'company card: $164 plus a 20% tip',
    note_ko: '법인카드: 164달러에 팁 20%'
  },
  {
    id: 'trip_club_sandwich',
    name: 'Club sandwich',
    name_ko: '클럽 샌드위치',
    kind: 'meal',
    price: 16,
    model: 'sandwich',
    energy: 30,
    place: 'hotel_restaurant'
  },
  {
    id: 'trip_flight',
    name: 'Round-trip flight, Fairview to Ridgeport (main cabin)',
    name_ko: '페어뷰–리지포트 왕복 항공권(일반석)',
    kind: 'ticket',
    price: 386,
    note: 'booked by Tom on the company card, not sold in a shop',
    note_ko: '톰이 법인카드로 예약, 가게에서는 안 팖'
  },
  {
    id: 'trip_hotel_breakfast',
    name: 'Hotel breakfast buffet',
    name_ko: '호텔 조식 뷔페',
    kind: 'meal',
    price: 0,
    model: 'pancakes',
    energy: 35,
    place: 'hotel_restaurant',
    note: 'included with the room, 6:30 to 10:00',
    note_ko: '객실 요금에 포함, 6:30~10:00'
  },
  {
    id: 'trip_hotel_night',
    name: 'Pinecrest Hotel, one night',
    name_ko: '파인크레스트 호텔 1박',
    kind: 'other',
    price: 189,
    note: 'company card, under the $200 policy cap',
    note_ko: '법인카드, 규정 상한 200달러 이내'
  },
  {
    id: 'trip_latte',
    name: 'Airport latte, large',
    name_ko: '공항 라테(큰 것)',
    kind: 'drink',
    price: 6.25,
    model: 'cup-coffee',
    energy: 12,
    place: 'airport_gate'
  },
  {
    id: 'trip_lobby_snack',
    name: 'Trail mix from the lobby shop',
    name_ko: '로비 매점 견과류 믹스',
    kind: 'meal',
    price: 5.49,
    model: 'bag',
    energy: 10,
    place: 'hotel_desk'
  },
  {
    id: 'trip_neck_pillow',
    name: 'Travel neck pillow',
    name_ko: '여행용 목베개',
    kind: 'other',
    price: 24.99,
    place: 'airport_gate'
  },
  {
    id: 'trip_rideshare',
    name: 'Rideshare, airport to hotel',
    name_ko: '차량 호출, 공항에서 호텔까지',
    kind: 'fare',
    price: 38.6,
    place: 'airport_arrive',
    note: 'reimbursable up to $50 each way',
    note_ko: '편도 50달러까지 경비 청구 가능'
  },
  {
    id: 'trip_salmon',
    name: 'Grilled salmon dinner',
    name_ko: '연어 구이 저녁',
    kind: 'meal',
    price: 29,
    model: 'plate-dinner',
    energy: 40,
    place: 'hotel_restaurant'
  },
  {
    id: 'trip_steak',
    name: 'Steak dinner',
    name_ko: '스테이크 저녁',
    kind: 'meal',
    price: 38,
    model: 'plate-dinner',
    energy: 45,
    place: 'hotel_restaurant'
  },
  {
    id: 'trip_water',
    name: 'Bottled water',
    name_ko: '생수',
    kind: 'drink',
    price: 4.29,
    model: 'soda-bottle',
    energy: 5,
    place: 'airport_gate',
    note: 'airport prices',
    note_ko: '공항 가격'
  },
  {
    id: 'umbrella',
    name: 'Compact umbrella',
    name_ko: '접이식 우산',
    kind: 'gear',
    price: 12.99,
    place: 'market_shelves',
    note: 'keeps you dry on rainy days',
    note_ko: '비 오는 날 젖지 않게'
  }
];

export const recipes = [
  {
    id: 'avocado_toast',
    name: 'Avocado toast with a fried egg',
    name_ko: '달걀 프라이를 올린 아보카도 토스트',
    minutes: 12,
    energy: 38,
    ingredients: 'avocado,bread,eggs',
    tool: 'stovetop',
    steps: 'Cut the avocado in half, take out the pit and scoop it into a bowl. | Mash it with a fork and season with salt and pepper. | Spread it on toast. | Top it with a fried egg.',
    steps_ko: '아보카도를 반으로 갈라 씨를 빼고 그릇에 퍼 담습니다. | 포크로 으깨고 소금과 후추로 간을 합니다. | 토스트에 바릅니다. | 달걀 프라이를 올립니다. (pit: 씨, mash: 으깨다, season: 간을 하다)',
    sort: 7
  },
  {
    id: 'bacon_eggs',
    name: 'Bacon, eggs and toast',
    name_ko: '베이컨, 달걀, 토스트',
    energy: 48,
    ingredients: 'bacon,eggs,bread',
    tool: 'stovetop',
    steps: 'Lay the bacon in a cold pan and cook it over medium heat until crisp. | Drain the bacon on a paper towel. | Fry two eggs in the same pan, sunny-side up or over easy. | Serve with buttered toast.',
    steps_ko: '차가운 팬에 베이컨을 깔고 중불에서 바삭해질 때까지 굽습니다. | 키친타월에 올려 기름을 뺍니다. | 같은 팬에 달걀 두 개를 부칩니다. 한쪽만 익히거나(sunny-side up) 살짝 뒤집습니다(over easy). | 버터 바른 토스트와 함께 냅니다.',
    sort: 2
  },
  {
    id: 'baked_pizza',
    name: 'Frozen pizza, baked',
    name_ko: '오븐에 구운 냉동 피자',
    minutes: 20,
    energy: 40,
    ingredients: 'frozen_pizza',
    tool: 'oven',
    steps: 'Preheat the oven to 425 degrees. | Take the pizza out of the box and remove the plastic wrap. | Bake it on the middle rack for 15 minutes. | Let it cool for a minute and cut it into slices.',
    steps_ko: '오븐을 화씨 425도(섭씨 약 220도)로 예열합니다. | 피자를 상자에서 꺼내고 비닐을 벗깁니다. | 가운데 칸에서 15분 굽습니다. | 1분 식힌 뒤 조각으로 자릅니다. (preheat: 예열하다, rack: 오븐 선반)',
    sort: 11
  },
  {
    id: 'beef_skillet',
    name: 'Beef and vegetable skillet',
    name_ko: '소고기 채소 볶음',
    minutes: 30,
    energy: 58,
    ingredients: 'ground_beef,onion,carrots,broccoli,tomatoes',
    tool: 'stovetop',
    steps: 'Brown the ground beef in a large skillet and drain the fat. | Add the chopped onion and carrots and cook for five minutes. | Stir in the broccoli and the diced tomatoes. | Cover and simmer for ten minutes.',
    steps_ko: '큰 프라이팬에 다진 소고기를 갈색이 나게 볶고 기름을 따라 냅니다. | 썬 양파와 당근을 넣고 5분 익힙니다. | 브로콜리와 깍둑썬 토마토를 넣고 섞습니다. | 뚜껑을 덮고 10분 동안 약불에 끓입니다. (brown: 갈색이 나게 익히다, simmer: 약불에 끓이다)',
    sort: 10
  },
  {
    id: 'cereal_bowl',
    name: 'Bowl of cereal',
    name_ko: '시리얼 한 그릇',
    minutes: 5,
    energy: 24,
    ingredients: 'cereal,milk',
    tool: 'no cooking',
    steps: 'Pour the cereal into a bowl. | Add cold milk. | Eat it before it gets soggy.',
    steps_ko: '그릇에 시리얼을 붓습니다. | 차가운 우유를 넣습니다. | 눅눅해지기 전에 먹습니다. (soggy: 눅눅한)',
    sort: 6
  },
  {
    id: 'cheeseburger',
    name: 'Homemade cheeseburger',
    name_ko: '집에서 만든 치즈버거',
    minutes: 25,
    energy: 55,
    ingredients: 'ground_beef,bread,cheese,onion,tomatoes',
    tool: 'stovetop',
    steps: 'Shape the ground beef into a patty and season both sides. | Cook it for four minutes on each side. | Put a slice of cheese on top and let it melt. | Build the burger with sliced onion and tomato.',
    steps_ko: '다진 소고기를 패티 모양으로 빚고 양면에 간을 합니다. | 한 면에 4분씩 굽습니다. | 치즈 한 장을 올려 녹입니다. | 썬 양파와 토마토를 넣어 버거를 만듭니다. (shape: 모양을 빚다, melt: 녹다)',
    sort: 9
  },
  {
    id: 'fruit_salad',
    name: 'Fruit salad',
    name_ko: '과일 샐러드',
    minutes: 10,
    ingredients: 'strawberries,grapes,bananas,oranges',
    tool: 'no cooking',
    steps: 'Rinse the strawberries and the grapes. | Peel the orange and the banana. | Cut everything into bite-size pieces. | Toss the fruit together in a bowl.',
    steps_ko: '딸기와 포도를 헹굽니다. | 오렌지와 바나나의 껍질을 벗깁니다. | 모두 한입 크기로 자릅니다. | 그릇에 담아 가볍게 섞습니다. (rinse: 헹구다, bite-size: 한입 크기, toss: 가볍게 섞다)',
    sort: 12
  },
  {
    id: 'grilled_cheese',
    name: 'Grilled cheese sandwich',
    name_ko: '그릴드 치즈 샌드위치',
    minutes: 10,
    energy: 32,
    ingredients: 'bread,cheese',
    tool: 'stovetop',
    steps: 'Butter one side of each slice of bread. | Put the cheese between the slices, buttered sides out. | Cook over medium-low heat until golden brown, then flip. | Cut it in half and eat it while it is hot.',
    steps_ko: '빵 한쪽 면에 버터를 바릅니다. | 버터 바른 면이 바깥으로 가게 하고 사이에 치즈를 넣습니다. | 중약불에서 노릇해질 때까지 굽고 뒤집습니다. | 반으로 잘라 뜨거울 때 먹습니다. (flip: 뒤집다)',
    sort: 3
  },
  {
    id: 'peanut_butter_toast',
    name: 'Peanut butter and banana toast',
    name_ko: '땅콩버터 바나나 토스트',
    minutes: 5,
    ingredients: 'bread,peanut_butter,bananas',
    tool: 'toaster',
    steps: 'Toast two slices of bread. | Spread peanut butter on the toast. | Peel a banana, slice it and put the slices on top.',
    steps_ko: '빵 두 쪽을 굽습니다. | 토스트에 땅콩버터를 바릅니다. | 바나나 껍질을 벗기고 썰어서 위에 올립니다. (peel: 껍질을 벗기다)',
    sort: 5
  },
  {
    id: 'scrambled_eggs',
    name: 'Scrambled eggs and toast',
    name_ko: '스크램블드에그와 토스트',
    minutes: 10,
    energy: 35,
    ingredients: 'eggs,bread',
    tool: 'stovetop',
    steps: 'Crack two eggs into a bowl and whisk them with a pinch of salt. | Melt a little butter in a pan over medium heat. | Pour in the eggs and stir gently until they are just set. | Toast two slices of bread and serve.',
    steps_ko: '달걀 두 개를 그릇에 깨 넣고 소금을 조금 넣어 젓습니다. | 중불에서 팬에 버터를 조금 녹입니다. | 달걀을 붓고 막 익을 때까지 살살 젓습니다. | 빵 두 쪽을 구워 함께 냅니다. (crack: 깨다, whisk: 휘젓다, set: 굳다)',
    sort: 1
  },
  {
    id: 'turkey_sandwich',
    name: 'Turkey and cheese sandwich',
    name_ko: '칠면조 치즈 샌드위치',
    minutes: 8,
    energy: 40,
    ingredients: 'bread,deli_turkey,cheese,tomatoes',
    tool: 'no cooking',
    steps: 'Slice a tomato. | Spread mayo or mustard on two slices of bread. | Layer the turkey, the cheese and the tomato. | Cut the sandwich diagonally.',
    steps_ko: '토마토를 얇게 썹니다. | 빵 두 쪽에 마요네즈나 머스터드를 바릅니다. | 칠면조, 치즈, 토마토를 차례로 올립니다. | 샌드위치를 대각선으로 자릅니다. (spread: 바르다, layer: 겹겹이 올리다)',
    sort: 4
  },
  {
    id: 'veggie_omelet',
    name: 'Veggie omelet',
    name_ko: '채소 오믈렛',
    energy: 42,
    ingredients: 'eggs,cheese,onion,broccoli',
    tool: 'stovetop',
    steps: 'Chop the onion and the broccoli into small pieces. | Saute them for a few minutes until soft. | Pour in the beaten eggs and let them set. | Sprinkle the cheese on top and fold the omelet in half.',
    steps_ko: '양파와 브로콜리를 잘게 썹니다. | 부드러워질 때까지 몇 분 볶습니다. | 풀어 둔 달걀을 붓고 익힙니다. | 치즈를 뿌리고 오믈렛을 반으로 접습니다. (chop: 썰다, saute: 볶다, sprinkle: 뿌리다, fold: 접다)',
    sort: 8
  }
];

export const catalog = [
  { id: 'c_cereal', item: 'cereal', qty: 3, name: 'Cereal (3 boxes)', name_ko: '시리얼(3상자)', price: 12.49, sort: 5 },
  {
    id: 'c_cold_brew',
    item: 'np_cold_brew',
    name: 'Canned cold brew (4-pack)',
    name_ko: '캔 콜드브루(4캔 묶음)',
    price: 9.99,
    sort: 10
  },
  { id: 'c_desk_lamp', item: 'np_desk_lamp', name: 'LED desk lamp', name_ko: 'LED 책상 스탠드', price: 24.99, sort: 13 },
  {
    id: 'c_detergent',
    item: 'detergent',
    qty: 3,
    name: 'Laundry pods, 3 packs (48 loads)',
    name_ko: '세탁 세제 캡슐 3팩(48회분)',
    price: 29.99,
    note: 'less than three packs at the store',
    note_ko: '매장에서 세 팩 사는 것보다 저렴',
    sort: 1
  },
  { id: 'c_first_aid', item: 'np_first_aid', name: 'First aid kit', name_ko: '구급상자', price: 18.99, sort: 12 },
  {
    id: 'c_granola',
    item: 'np_granola',
    name: 'Granola bars (box of 12)',
    name_ko: '그래놀라 바(12개 한 상자)',
    price: 7.99,
    sort: 8
  },
  {
    id: 'c_headphones',
    item: 'np_headphones',
    name: 'Noise-canceling headphones',
    name_ko: '노이즈 캔슬링 헤드폰',
    price: 119.99,
    signature: 1,
    note: 'for the open office',
    note_ko: '개방형 사무실에서',
    sort: 15
  },
  {
    id: 'c_paper_towels',
    item: 'np_paper_towels',
    name: 'Paper towels (6 rolls)',
    name_ko: '키친타월(6롤)',
    price: 11.49,
    sort: 2
  },
  {
    id: 'c_peanut_butter',
    item: 'peanut_butter',
    qty: 2,
    name: 'Peanut butter (2 jars)',
    name_ko: '땅콩버터(2병)',
    price: 6.49,
    sort: 6
  },
  {
    id: 'c_ramen',
    item: 'np_ramen',
    name: 'Instant ramen (12-pack)',
    name_ko: '인스턴트 라면(12개 묶음)',
    price: 8.99,
    note: 'just add hot water',
    note_ko: '뜨거운 물만 부으면 됨',
    sort: 7
  },
  {
    id: 'c_soup',
    item: 'canned_soup',
    qty: 6,
    name: 'Chicken noodle soup (6 cans)',
    name_ko: '치킨 누들 수프(6캔)',
    price: 10.99,
    sort: 4
  },
  {
    id: 'c_space_heater',
    item: 'np_space_heater',
    name: 'Small space heater',
    name_ko: '소형 전기 히터',
    price: 39.99,
    note: 'for chilly winter nights',
    note_ko: '쌀쌀한 겨울밤에',
    sort: 14
  },
  {
    id: 'c_toilet_paper',
    item: 'np_toilet_paper',
    name: 'Toilet paper (12 rolls)',
    name_ko: '화장지(12롤)',
    price: 13.99,
    sort: 3
  },
  {
    id: 'c_trail_mix',
    item: 'np_trail_mix',
    name: 'Trail mix (2 lb bag)',
    name_ko: '트레일 믹스(2파운드 봉지)',
    price: 12.99,
    note: 'nuts, raisins and chocolate',
    note_ko: '견과류, 건포도, 초콜릿',
    sort: 9
  },
  {
    id: 'c_umbrella',
    item: 'umbrella',
    name: 'Compact umbrella',
    name_ko: '접이식 우산',
    price: 11.99,
    note: 'keeps you dry on rainy days',
    note_ko: '비 오는 날 젖지 않게',
    sort: 11
  },
  {
    id: 'c_vacuum',
    item: 'np_vacuum',
    name: 'Cordless stick vacuum',
    name_ko: '무선 스틱 청소기',
    price: 149.99,
    signature: 1,
    sort: 16
  }
];
